package balticporter.core

import java.nio.file.Path

/** Provenance stamped into every generated file's header, plus upstream NOTICE files the port
  * ships beside its output. Attribution is a licence obligation. // CLAUDE.md §4.57 */
final case class Provenance(
    upstreamName: String,
    upstreamCommit: String,
    originalLicense: String,
    /** path prefix shown in headers before the unit's sourcePath, e.g. "liqp/src/main/java". */
    sourcePathPrefix: String,
    /** Absolute root the Java sources were parsed from. The emitter relativises each unit's origin
      * against this; left empty it falls back to locating `sourcePathPrefix` inside the path. */
    sourceRoot: String = "",
    /** Upstream files (LICENSE, NOTICE) copied beside emitted code. Empty = no-op (§1(b) default).
      * A missing declared file is FATAL. // CLAUDE.md §4.57 */
    notices: List[Path] = Nil,
)

/** M0 subset of a port configuration (DESIGN.md §3.3): one module, explicit file list. */
final case class UnitPlan(
    sourceRoot: Path,
    files: List[String],
    classpath: List[Path],
    outDir: Path,
    provenance: Provenance,
    /** source roots participating in resolution but not converted (see FrontendConfig). */
    resolutionRoots: List[Path] = Nil,
)

/** Engine coordinates, taken from build-generated `BuildVersion`. */
object EngineInfo:
  val organization: String = BuildVersion.organization
  val version: String      = BuildVersion.version
  /** Bumped whenever any pass/printer behavior changes; part of the header + cache key. */
  val fingerprint = s"balticporter/$version"

/** Engine version a generated project was produced by, recorded as a properties file beside `src/`.
  * A declaration, not a lock file; [[check]] compares it against the running engine. */
final case class EnginePin(
    engineVersion: String,
    engineFingerprint: String,
    runtimeArtifact: String,
    runtimeVersion: String,
    runtimeMode: String,
):
  def render: String =
    s"""# Generated by Baltic Porter — DO NOT EDIT; regenerate instead.
       |# The engine version this project was produced by. `EnginePin.check` compares it against
       |# the engine now on the classpath; a mismatch means the emitted sources are stale.
       |engine.organization=${EngineInfo.organization}
       |engine.version=$engineVersion
       |engine.fingerprint=$engineFingerprint
       |runtime.artifact=$runtimeArtifact
       |runtime.version=$runtimeVersion
       |runtime.mode=$runtimeMode
       |""".stripMargin

object EnginePin:
  val fileName = "balticporter-engine.properties"

  /** the pin describing the engine RUNNING NOW, delivering `plan`. */
  def current(plan: RuntimePlan): EnginePin =
    EnginePin(
      engineVersion = EngineInfo.version,
      engineFingerprint = EngineInfo.fingerprint,
      runtimeArtifact = RuntimeArtifact.artifact,
      runtimeVersion = if plan.isEmpty then "" else RuntimeArtifact.version,
      runtimeMode = if plan.isEmpty then "none" else plan.mode.toString.toLowerCase,
    )

  def parse(text: String): Option[EnginePin] =
    val kv = text.linesIterator
      .map(_.trim)
      .filter(l => l.nonEmpty && !l.startsWith("#") && l.contains('='))
      .map { l => val i = l.indexOf('='); l.substring(0, i) -> l.substring(i + 1) }
      .toMap
    for v <- kv.get("engine.version"); f <- kv.get("engine.fingerprint")
    yield EnginePin(v, f, kv.getOrElse("runtime.artifact", ""), kv.getOrElse("runtime.version", ""),
      kv.getOrElse("runtime.mode", "none"))

  def write(root: Path, pin: EnginePin): Unit =
    java.nio.file.Files.writeString(root.resolve(fileName), pin.render)

  def read(root: Path): Option[EnginePin] =
    val p = root.resolve(fileName)
    if java.nio.file.Files.exists(p) then parse(java.nio.file.Files.readString(p)) else None

  /** Compare a port's declared engine against the one on the classpath. `Left` names the mismatch. */
  def check(root: Path): Either[String, Option[EnginePin]] =
    read(root) match
      case None => Right(None)
      case Some(pin) if pin.engineVersion == EngineInfo.version => Right(Some(pin))
      case Some(pin) =>
        Left(
          s"$fileName pins engine ${pin.engineVersion}, but ${EngineInfo.version} is on the classpath. " +
            s"Either depend on ${EngineInfo.organization}:balticporter-engine:${pin.engineVersion} to " +
            s"regenerate byte-identical output, or regenerate with ${EngineInfo.version} and update the pin."
        )
