/*
 * Generated by Baltic Porter 0.1.0-SNAPSHOT — DO NOT EDIT; regenerate instead.
 *
 * Ported from: vis-ui/ui/src/main/java/com/kotcrab/vis/ui/widget/PopupMenu.java
 * Original license: Apache-2.0 (see VisUI upstream)
 * upstream-commit: vis-ui@820300c86a1bd907404217195a9987e5c66d2220 (last change to ui/src/main/java; origin https://github.com/kotcrab/vis-ui.git)
 */
/*
 * Copyright 2014-2017 See AUTHORS file.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* porter: renamed-package reason=configured phase=package-rename key="com.kotcrab.vis.ui -> sge.visui" from=com.kotcrab.vis.ui.widget.PopupMenu to=sge.visui.widget.PopupMenu */
package sge.visui.widget

/**
 * Standard popup menu that can be displayed anywhere on stage. Menu is automatically removed when user clicked outside menu,
 * or clicked menu item. For proper behaviour menu should be displayed in touchUp event. If you want to display
 * menu from touchDown you have to call event.stop() otherwise menu will by immediately closed.
 * <p>
 * If you want to add right click menu to actor you can use getDefaultInputListener() to get premade default listener.
 * <p>
 * Since 1.0.2 arrow keys can be used to navigate menu hierarchy.
 * @author Kotcrab
 */
class PopupMenu(using sge.Sge) extends sge.scenes.scene2d.ui.Table {
  /* porter: dropped-member reason=universal rule=ctor-funnel/nilary-dropped(C11) arguments=1 member=<init>() owner=sge.visui.widget.PopupMenu
     — java ran this nilary constructor's delegation and scala's implicit nilary primary runs nothing; `def this()` beside that primary is `E120`, so there is nowhere to put it. `new PopupMenu()` therefore builds an object java could not build. Emitting, promoting and marker-disambiguating it were each measured and each emits a WRONG answer in place of a missing one (ENGINE-LIMITS.md C11); a port that needs the behaviour writes the constructor by hand (§1.5's `inject`) */
  /* porter: forced-class-init reason=universal rule=class-init-trigger(§4.4) forces=sge.visui.widget.PopupMenu trigger=instantiation
     — java runs this class's initialiser — its `static { }` blocks and its static field initialisers, one sequence, JLS 12.4.2 step 9 — at class initialisation, and a scala companion initialises on first access to the OBJECT, which `new` is not */
  val _ = sge.visui.widget.PopupMenu
  /* porter: widened-visibility reason=universal rule=ctor-replay-widening cause=ctor-replay-widening from=private scope=dependent-modules to=public
     — a paramful constructor of this class writes this member, and a SUBCLASS IN ANOTHER MODULE can only express its `super(args)` as a replay one level down (scala lets only the primary reach super) — where `private` does not reach and where nothing but this run can widen it (ENGINE-LIMITS.md C15); widening can only remove access errors */
  var sizes: sge.visui.Sizes = scala.compiletime.uninitialized
  /* porter: widened-visibility reason=universal rule=ctor-replay-widening cause=ctor-replay-widening from=private scope=dependent-modules to=public
     — a paramful constructor of this class writes this member, and a SUBCLASS IN ANOTHER MODULE can only express its `super(args)` as a replay one level down (scala lets only the primary reach super) — where `private` does not reach and where nothing but this run can widen it (ENGINE-LIMITS.md C15); widening can only remove access errors */
  var style: sge.visui.widget.PopupMenu.PopupMenuStyle = scala.compiletime.uninitialized
  /* porter: renamed-member reason=universal rule=member-rename(§4.55) clash=field-vs-method from=listener owner=sge.visui.widget.PopupMenu to=listener$field
     — java keeps fields and methods in SEPARATE namespaces, so a field may share a name with a method of this class or of a SUBCLASS; scala has one namespace and forbids it */
  /* porter: widened-visibility reason=universal rule=member-rename(§4.55) cause=member-rename clash=field-vs-method from=private to=public
     — java lets this name be reused where scala cannot, so the field is renamed (§4.55) — and a renamed field must stay reachable from every place java read it, which scala's own access rules do not grant at the new name; widening can only remove access errors, never introduce one, and never changes behaviour */
  var listener$field: sge.visui.widget.PopupMenu.PopupMenuListener = scala.compiletime.uninitialized
  private var stageListener: sge.scenes.scene2d.InputListener = scala.compiletime.uninitialized
  private var sharedMenuItemInputListener: sge.scenes.scene2d.InputListener = scala.compiletime.uninitialized
  private var sharedMenuItemChangeListener: sge.scenes.scene2d.utils.ChangeListener = scala.compiletime.uninitialized
  /* porter: renamed-member reason=universal rule=member-rename(§4.55) clash=field-vs-method from=defaultInputListener owner=sge.visui.widget.PopupMenu to=defaultInputListener$field
     — java keeps fields and methods in SEPARATE namespaces, so a field may share a name with a method of this class or of a SUBCLASS; scala has one namespace and forbids it */
  /* porter: widened-visibility reason=universal rule=member-rename(§4.55) cause=member-rename clash=field-vs-method from=private to=public
     — java lets this name be reused where scala cannot, so the field is renamed (§4.55) — and a renamed field must stay reachable from every place java read it, which scala's own access rules do not grant at the new name; widening can only remove access errors, never introduce one, and never changes behaviour */
  var defaultInputListener$field: sge.scenes.scene2d.InputListener = scala.compiletime.uninitialized
  /** The parent sub-menu, that this popup menu belongs to or null if this sub menu is root */
  private var parentSubMenu: PopupMenu = scala.compiletime.uninitialized
  /** The current sub-menu, set by MenuItem */
  /* porter: renamed-member reason=universal rule=member-rename(§4.55) clash=field-vs-method from=activeSubMenu owner=sge.visui.widget.PopupMenu to=activeSubMenu$field
     — java keeps fields and methods in SEPARATE namespaces, so a field may share a name with a method of this class or of a SUBCLASS; scala has one namespace and forbids it */
  /* porter: widened-visibility reason=universal rule=member-rename(§4.55) cause=member-rename clash=field-vs-method from=private to=public
     — java lets this name be reused where scala cannot, so the field is renamed (§4.55) — and a renamed field must stay reachable from every place java read it, which scala's own access rules do not grant at the new name; widening can only remove access errors, never introduce one, and never changes behaviour */
  var activeSubMenu$field: PopupMenu = scala.compiletime.uninitialized
  /* porter: renamed-member reason=universal rule=member-rename(§4.55) clash=field-vs-method from=activeItem owner=sge.visui.widget.PopupMenu to=activeItem$field
     — java keeps fields and methods in SEPARATE namespaces, so a field may share a name with a method of this class or of a SUBCLASS; scala has one namespace and forbids it */
  /* porter: widened-visibility reason=universal rule=member-rename(§4.55) cause=member-rename clash=field-vs-method from=private to=public
     — java lets this name be reused where scala cannot, so the field is renamed (§4.55) — and a renamed field must stay reachable from every place java read it, which scala's own access rules do not grant at the new name; widening can only remove access errors, never introduce one, and never changes behaviour */
  var activeItem$field: sge.visui.widget.MenuItem = scala.compiletime.uninitialized
  def this(sizes: sge.visui.Sizes, style: sge.visui.widget.PopupMenu.PopupMenuStyle)(using sge.Sge) = {
    this()
    this.sizes = sizes
    this.style = style
    this.setTouchable(sge.scenes.scene2d.Touchable.enabled)
    this.pad(0.toFloat)
    this.setBackground(lowlevel.Nullable(style.background))
    this.createListeners()
  }
  def this(style: sge.visui.widget.PopupMenu.PopupMenuStyle)(using sge.Sge) = {
    this(sge.visui.VisUI.getSizes(), style)
  }
  def this(styleName: java.lang.String)(using sge.Sge) = {
    this(sge.visui.VisUI.getSkin().get(styleName, classOf[sge.visui.widget.PopupMenu.PopupMenuStyle]))
  }
  private def createListeners(): scala.Unit = {
    this.stageListener = new sge.scenes.scene2d.InputListener() {
      @java.lang.Override
      override def touchDown(event: sge.scenes.scene2d.InputEvent, x: scala.Float, y: scala.Float, pointer: scala.Int, button: scala.Int): scala.Boolean = {
        if (PopupMenu.this.rootMenu.subMenuStructureContains(x, y) == false) {
          PopupMenu.this.remove()
        } else ()
        return true
      }
      @java.lang.Override
      override def keyDown(event: sge.scenes.scene2d.InputEvent, keycode: scala.Int): scala.Boolean = {
        val children: lowlevel.util.DynamicArray[sge.scenes.scene2d.Actor] = PopupMenu.this.children
        if ((children.size == 0) || (PopupMenu.this.activeSubMenu$field != null)) {
          return false
        } else ()
        if (keycode == sge.Input.Keys.DOWN) {
          PopupMenu.this.selectNextItem()
          return true
        } else ()
        if (keycode == sge.Input.Keys.UP) {
          PopupMenu.this.selectPreviousItem()
          return true
        } else ()
        if (PopupMenu.this.activeItem$field == null) {
          return false
        } else ()
        if ((keycode == sge.Input.Keys.LEFT) && (PopupMenu.this.activeItem$field.containerMenu.parentSubMenu != null)) {
          PopupMenu.this.activeItem$field.containerMenu.parentSubMenu.activeSubMenu = null
          return true
        } else ()
        if ((keycode == sge.Input.Keys.RIGHT) && (PopupMenu.this.activeItem$field.subMenu != null)) {
          PopupMenu.this.activeItem$field.showSubMenu()
          PopupMenu.this.activeSubMenu$field.selectNextItem()
          return true
        } else ()
        if (keycode == sge.Input.Keys.ENTER) {
          PopupMenu.this.activeItem$field.fireChangeEvent()
          return true
        } else ()
        return false
      }
    }
    this.sharedMenuItemInputListener = new sge.scenes.scene2d.InputListener() {
      @java.lang.Override
      override def enter(event: sge.scenes.scene2d.InputEvent, x: scala.Float, y: scala.Float, pointer: scala.Int, fromActor: lowlevel.Nullable[sge.scenes.scene2d.Actor]): scala.Unit = {
        if ((pointer == (-1)) && event.listenerActor.isInstanceOf[sge.visui.widget.MenuItem]) {
          val item: sge.visui.widget.MenuItem = event.listenerActor.asInstanceOf[sge.visui.widget.MenuItem]
          if (item.disabled == false) {
            PopupMenu.this.setActiveItem(item, false)
          } else ()
        } else ()
      }
      @java.lang.Override
      override def exit(event: sge.scenes.scene2d.InputEvent, x: scala.Float, y: scala.Float, pointer: scala.Int, toActor: lowlevel.Nullable[sge.scenes.scene2d.Actor]): scala.Unit = {
        if ((pointer == (-1)) && event.listenerActor.isInstanceOf[sge.visui.widget.MenuItem]) {
          if (PopupMenu.this.activeSubMenu$field != null) {
            return
          } else ()
          val item: sge.visui.widget.MenuItem = event.listenerActor.asInstanceOf[sge.visui.widget.MenuItem]
          if (item eq PopupMenu.this.activeItem$field) {
            PopupMenu.this.setActiveItem(null, false)
          } else ()
        } else ()
      }
    }
    this.sharedMenuItemChangeListener = new sge.scenes.scene2d.utils.ChangeListener() {
      @java.lang.Override
      override def changed(event: sge.scenes.scene2d.utils.ChangeListener.ChangeEvent, actor: sge.scenes.scene2d.Actor): scala.Unit = {
        if (event.stopped == false) {
          PopupMenu.this.removeHierarchy()
        } else ()
      }
    }
  }
  /* porter: renamed-member reason=universal rule=bean-detect component=1 from=getRootMenu owner=com.kotcrab.vis.ui.widget.PopupMenu to=rootMenu
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  /* porter: renamed-member reason=universal rule=bean-detect accessors=getRootMenu property=rootMenu source=auto-detect */
  private def rootMenu: PopupMenu = {
    if (this.parentSubMenu != null) {
      return this.parentSubMenu.rootMenu
    } else ()
    return this
  }
  private def subMenuStructureContains(x: scala.Float, y: scala.Float): scala.Boolean = {
    if (this.contains(x, y)) {
      return true
    } else ()
    if (this.activeSubMenu$field != null) {
      return this.activeSubMenu$field.subMenuStructureContains(x, y)
    } else ()
    return false
  }
  private def removeHierarchy(): scala.Unit = {
    if (((this.activeItem$field != null) && (this.activeItem$field.containerMenu != null)) && (this.activeItem$field.containerMenu.parentSubMenu != null)) {
      this.activeItem$field.containerMenu.parentSubMenu.removeHierarchy()
    } else ()
    this.remove()
  }
  private def selectNextItem(): scala.Unit = {
    val children: lowlevel.util.DynamicArray[sge.scenes.scene2d.Actor] = this.children
    if (!this.hasSelectableMenuItems) {
      return
    } else ()
    val startIndex: scala.Int = if (this.activeItem$field == null) 0 else children.indexOfByRef(this.activeItem$field) + 1
    scala.util.boundary { { var i: scala.Int = startIndex; while (true) { {
      if (i >= children.size) {
        i = 0
      } else ()
      val actor: sge.scenes.scene2d.Actor = children.apply(i)
      if (actor.isInstanceOf[sge.visui.widget.MenuItem] && (actor.asInstanceOf[sge.visui.widget.MenuItem].disabled == false)) {
        this.setActiveItem(actor.asInstanceOf[sge.visui.widget.MenuItem], true)
        scala.util.boundary.break(())
      } else ()
    }; i = i + 1 } } }
  }
  private def selectPreviousItem(): scala.Unit = {
    val children: lowlevel.util.DynamicArray[sge.scenes.scene2d.Actor] = this.children
    if (!this.hasSelectableMenuItems) {
      return
    } else ()
    val startIndex: scala.Int = if (this.activeItem$field == null) children.size - 1 else children.indexOfByRef(this.activeItem$field) - 1
    scala.util.boundary { { var i: scala.Int = startIndex; while (true) { {
      if (i <= (-1)) {
        i = children.size - 1
      } else ()
      val actor: sge.scenes.scene2d.Actor = children.apply(i)
      if (actor.isInstanceOf[sge.visui.widget.MenuItem] && (actor.asInstanceOf[sge.visui.widget.MenuItem].disabled == false)) {
        this.setActiveItem(actor.asInstanceOf[sge.visui.widget.MenuItem], true)
        scala.util.boundary.break(())
      } else ()
    }; i = i - 1 } } }
  }
  /* porter: parenless-conversion reason=universal rule=nullary-arity from=hasSelectableMenuItems() to=hasSelectableMenuItems */
  private def hasSelectableMenuItems: scala.Boolean = {
    val children: lowlevel.util.DynamicArray[sge.scenes.scene2d.Actor] = this.children;
    { val actor$it = children.iterator; while (actor$it.hasNext) { val actor: sge.scenes.scene2d.Actor = actor$it.next(); {
      if (actor.isInstanceOf[sge.visui.widget.MenuItem] && (actor.asInstanceOf[sge.visui.widget.MenuItem].disabled == false)) {
        return true
      } else ()
    } } }
    return false
  }
  /* porter: suppressed-warning reason=universal rule=suppressed-warning(orNull) annotation=@nowarn("msg=deprecated")
     — this member's body calls `.orNull` (the null-preserving unwrap at a slot that accepts null); lls deprecates `orNull` as a lint so every usage needs `@nowarn` — the same pattern sge uses at every Java interop boundary */
  @java.lang.Override
  @scala.annotation.nowarn("msg=deprecated")
  override def add[T <: sge.scenes.scene2d.Actor](actor: T): sge.scenes.scene2d.ui.Cell[T] = {
    if (actor.isInstanceOf[sge.visui.widget.MenuItem]) {
      throw new java.lang.IllegalArgumentException("MenuItems can be only added to PopupMenu by using addItem(MenuItem) method")
    } else ()
    return super.add(actor)
  }
  def addItem(item: sge.visui.widget.MenuItem): scala.Unit = {
    super.add(item).fillX().expandX().row()
    this.pack()
    item.addListener(this.sharedMenuItemChangeListener)
    item.addListener(this.sharedMenuItemInputListener)
  }
  def addSeparator(): scala.Unit = {
    this.add(new sge.visui.widget.Separator("menu")).padTop(2.toFloat).padBottom(2.toFloat).fill().expand().row()
  }
  /**
   * Returns input listener that can be added to scene2d actor. When right mouse button is pressed on that actor,
   * menu will be displayed
   */
  /* porter: renamed-member reason=universal rule=bean-detect accessors=getDefaultInputListener property=defaultInputListener source=auto-detect */
  /* porter: renamed-member reason=universal rule=bean-detect component=1 from=getDefaultInputListener owner=com.kotcrab.vis.ui.widget.PopupMenu to=defaultInputListener
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  def defaultInputListener: sge.scenes.scene2d.InputListener = {
    return this.getDefaultInputListener(sge.Input.Buttons.RIGHT)
  }
  /**
   * Returns input listener that can be added to scene2d actor. When mouse button is pressed on that actor,
   * menu will be displayed
   * @param mouseButton from {@link Buttons}
   */
  def getDefaultInputListener(mouseButton: scala.Int): sge.scenes.scene2d.InputListener = {
    if (this.defaultInputListener$field == null) {
      this.defaultInputListener$field = new sge.scenes.scene2d.InputListener() {
        @java.lang.Override
        override def touchDown(event: sge.scenes.scene2d.InputEvent, x: scala.Float, y: scala.Float, pointer: scala.Int, button: scala.Int): scala.Boolean = {
          return true
        }
        @java.lang.Override
        override def touchUp(event: sge.scenes.scene2d.InputEvent, x: scala.Float, y: scala.Float, pointer: scala.Int, button: scala.Int): scala.Unit = {
          if (event.button == mouseButton) {
            PopupMenu.this.showMenu(event.stage, event.stageX, event.stageY)
          } else ()
        }
      }
    } else ()
    return this.defaultInputListener$field
  }
  @java.lang.Override
  override def draw(batch: sge.graphics.g2d.Batch, parentAlpha: scala.Float): scala.Unit = {
    super.draw(batch, parentAlpha)
    if (this.style.border != null) {
      this.style.border.draw(batch, this.x, this.y, this.getWidth, this.getHeight)
    } else ()
  }
  /**
   * Shows menu as given stage coordinates
   * @param stage stage instance that this menu is being added to
   * @param x stage x position
   * @param y stage y position
   */
  def showMenu(stage: sge.scenes.scene2d.Stage, x: scala.Float, y: scala.Float): scala.Unit = {
    this.setPosition(x, y - this.getHeight)
    if ((stage.height - this.y) > stage.height) {
      this.y = this.y + this.getHeight
    } else ()
    sge.visui.util.ActorUtils.keepWithinStage(stage, this)
    stage.addActor(this)
  }
  /**
   * Shows menu below (or above if not enough space) given actor.
   * @param stage stage instance that this menu is being added to
   * @param actor used to get calculate menu position in stage, menu will be displayed above or below it
   */
  def showMenu(stage: sge.scenes.scene2d.Stage, actor: sge.scenes.scene2d.Actor): scala.Unit = {
    val pos: sge.math.Vector2 = actor.localToStageCoordinates(PopupMenu.tmpVector.setZero())
    var menuY: scala.Float = 0.0f
    if ((pos.y - this.getHeight) <= 0) {
      menuY = ((pos.y + actor.getHeight) + this.getHeight) - this.sizes.borderSize
    } else {
      menuY = pos.y + this.sizes.borderSize
    }
    this.showMenu(stage, pos.x, menuY)
  }
  def contains(x: scala.Float, y: scala.Float): scala.Boolean = {
    return (((this.x < x) && ((this.x + this.getWidth) > x)) && (this.y < y)) && ((this.y + this.getHeight) > y)
  }
  /** Called by framework, when PopupMenu is added to MenuItem as submenu */
  /* porter: renamed-member reason=universal rule=bean-detect component=1 from=setActiveSubMenu owner=com.kotcrab.vis.ui.widget.PopupMenu to=activeSubMenu_=
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  private[widget] def activeSubMenu_=(newSubMenu: PopupMenu): scala.Unit = {
    if (this.activeSubMenu$field eq newSubMenu) {
      return
    } else ()
    if (this.activeSubMenu$field != null) {
      this.activeSubMenu$field.remove()
    } else ()
    this.activeSubMenu$field = newSubMenu
    if (newSubMenu != null) {
      newSubMenu.setParentMenu(this)
    } else ()
  }
  /* porter: renamed-member reason=universal rule=bean-detect accessors=getActiveSubMenu/setActiveSubMenu property=activeSubMenu source=auto-detect */
  /* porter: renamed-member reason=universal rule=bean-detect component=1 from=getActiveSubMenu owner=com.kotcrab.vis.ui.widget.PopupMenu to=activeSubMenu
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  def activeSubMenu: PopupMenu = {
    return this.activeSubMenu$field
  }
  /* porter: renamed-member reason=universal rule=bean-detect component=12 from=setStage owner=com.kotcrab.vis.ui.widget.PopupMenu to=stage_=
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  /* porter: widened-visibility reason=universal rule=visibility(§8.7) cause=x-pkg-protected-override from=protected to=protected[sge]
     — this overrides a protected member declared in another package tree; a scala override may not have weaker access privileges and no enclosing package covers both, so it ships public */
  @java.lang.Override
  protected[sge] override def stage_=(stage: lowlevel.Nullable[sge.scenes.scene2d.Stage]): scala.Unit = {
    super.stage = stage
    if (!stage.isEmpty) {
      stage.get.addListener(this.stageListener)
    } else ()
  }
  @java.lang.Override
  override def remove(): scala.Boolean = {
    if (!this.stage.isEmpty) {
      this.stage.get.removeListener(this.stageListener)
    } else ()
    if (this.activeSubMenu$field != null) {
      this.activeSubMenu$field.remove()
    } else ()
    this.setActiveItem(null, false)
    this.parentSubMenu = null
    this.activeSubMenu$field = null
    return super.remove()
  }
  private[widget] def setActiveItem(newItem: sge.visui.widget.MenuItem, keyboardChange: scala.Boolean): scala.Unit = {
    this.activeItem$field = newItem
    if (this.listener$field != null) {
      this.listener$field.activeItemChanged(newItem, keyboardChange)
    } else ()
  }
  /* porter: renamed-member reason=universal rule=bean-detect accessors=getActiveItem property=activeItem source=auto-detect */
  /* porter: renamed-member reason=universal rule=bean-detect component=1 from=getActiveItem owner=com.kotcrab.vis.ui.widget.PopupMenu to=activeItem
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  def activeItem: sge.visui.widget.MenuItem = {
    return this.activeItem$field
  }
  private[widget] def setParentMenu(parentSubMenu: PopupMenu): scala.Unit = {
    this.parentSubMenu = parentSubMenu
  }
  /* porter: renamed-member reason=universal rule=bean-detect component=1 from=getListener owner=com.kotcrab.vis.ui.widget.PopupMenu to=listener
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  /* porter: renamed-member reason=universal rule=bean-detect accessors=getListener/setListener property=listener source=auto-detect */
  def listener: sge.visui.widget.PopupMenu.PopupMenuListener = {
    return this.listener$field
  }
  /* porter: renamed-member reason=universal rule=bean-detect component=1 from=setListener owner=com.kotcrab.vis.ui.widget.PopupMenu to=listener_=
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  def listener_=(listener: sge.visui.widget.PopupMenu.PopupMenuListener): scala.Unit = {
    this.listener$field = listener
  }
}
object PopupMenu {
  /* porter: forced-class-init reason=universal rule=class-init-trigger(§4.4) forces=sge.scenes.scene2d.ui.Table trigger=subclass-init
     — initialising this type initialises `sge.scenes.scene2d.ui.Table` first (JLS 12.4.1 item 7), which runs that type's class initialiser; a scala object's initialisation reaches no other object */
  val _ = sge.scenes.scene2d.ui.Table
  export sge.scenes.scene2d.ui.Table.{PopupMenuListener => _, PopupMenuStyle => _, cellPool => _, cellPool$set => _, cellPool$value => _, columnWeightedWidth => _, removeEveryMenu => _, rowWeightedHeight => _, tmp => _, tmpVector => _, *}
  private final val tmpVector: sge.math.Vector2 = new sge.math.Vector2()
  /**
   * Removes every instance of {@link PopupMenu} form {@link Stage} actors.
   * <p>
   * Generally called from {@link ApplicationListener#resize(int, int)} to remove menus on resize event.
   */
  def removeEveryMenu(stage: sge.scenes.scene2d.Stage): scala.Unit = {
    for (actor <- stage.actors) {
      if (actor.isInstanceOf[PopupMenu]) {
        val menu: PopupMenu = actor.asInstanceOf[PopupMenu]
        menu.removeHierarchy()
      } else ()
    }
  }
  /**
   * Listener used to get events from {@link PopupMenu}.
   * @since 1.0.2
   */
  trait PopupMenuListener {
    /**
     * Called when active menu item (the highlighted one) has changed. This can't be used to listen when
     * {@link MenuItem} was pressed, add {@link ChangeListener} to {@link MenuItem} directly to achieve this.
     * @param newActiveItem new item that is now active. May be null.
     * @param changedByKeyboard whether the change occurred by keyboard (arrows keys) or by mouse.
     */
    def activeItemChanged(newActiveItem: sge.visui.widget.MenuItem, changedByKeyboard: scala.Boolean): scala.Unit
  }
  /* porter: funnelled-ctor reason=universal rule=ctor-funnel constructors=3 disambiguator=marker escapes=0 notSlot=background=order,border=order primary=() primaryVis=protected shape=synthesised-primary slots=- superArgs=0
     — java lets every constructor pick its own `super(...)` and scala lets only the PRIMARY reach super; no java constructor here can be that primary, so a protected one taking the PARENT constructor's own parameters is synthesised and every java constructor becomes a `def this` computing its arguments */
  class PopupMenuStyle protected (ctor$: sge.visui.widget.PopupMenu.PopupMenuStyle.Funnel) {
    var background: sge.scenes.scene2d.utils.Drawable = scala.compiletime.uninitialized
    var border: sge.scenes.scene2d.utils.Drawable = scala.compiletime.uninitialized
    def this() = {
      this((null: sge.visui.widget.PopupMenu.PopupMenuStyle.Funnel))
    }
    def this(background: sge.scenes.scene2d.utils.Drawable, border: sge.scenes.scene2d.utils.Drawable) = {
      this((null: sge.visui.widget.PopupMenu.PopupMenuStyle.Funnel))
      this.background = background
      this.border = border
    }
    def this(style: sge.visui.widget.PopupMenu.PopupMenuStyle) = {
      this((null: sge.visui.widget.PopupMenu.PopupMenuStyle.Funnel))
      this.background = style.background
      this.border = style.border
    }
  }
  object PopupMenuStyle {
    protected final class Funnel
  }
}