/*
 * Generated by Baltic Porter 0.1.0-SNAPSHOT — DO NOT EDIT; regenerate instead.
 *
 * Ported from: vis-ui/ui/src/main/java/com/kotcrab/vis/ui/widget/VisTextButton.java
 * Original license: Apache-2.0 (see VisUI upstream)
 * upstream-commit: vis-ui@820300c86a1bd907404217195a9987e5c66d2220 (last change to ui/src/main/java; origin https://github.com/kotcrab/vis-ui.git)
 */
/*
 * Copyright 2014-2017 See AUTHORS file.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* porter: funnelled-ctor reason=universal rule=ctor-funnel constructors=5 disambiguator=none escapes=0 notSlot=- primary="(sup$0: lowlevel.Nullable[java.lang.String], sup$1: sge.scenes.scene2d.ui.TextButton$TextButtonStyle)" primaryVis=protected shape=synthesised-primary slots=sup$0,sup$1 superArgs=2
   — java lets every constructor pick its own `super(...)` and scala lets only the PRIMARY reach super; no java constructor here can be that primary, so a protected one taking the PARENT constructor's own parameters is synthesised and every java constructor becomes a `def this` computing its arguments */
/* porter: renamed-package reason=configured phase=package-rename key="com.kotcrab.vis.ui -> sge.visui" from=com.kotcrab.vis.ui.widget.VisTextButton to=sge.visui.widget.VisTextButton */
package sge.visui.widget

/**
 * Extends functionality of standard {@link TextButton}, supports focus border. Compatible with standard {@link TextButton}.
 * <p>
 * When listening for button press {@link ChangeListener} should be always preferred (instead of {@link ClickListener}).
 * {@link ClickListener} does not support disabling button and will still report button presses.
 * @author Kotcrab
 * @see TextButton
 */
class VisTextButton protected (sup$0: lowlevel.Nullable[java.lang.String], sup$1: sge.scenes.scene2d.ui.TextButton.TextButtonStyle)(using sge.Sge) extends sge.scenes.scene2d.ui.TextButton(sup$0, sup$1) with sge.visui.Focusable with sge.visui.util.BorderOwner {
  private var visStyle$field: sge.visui.widget.VisTextButton.VisTextButtonStyle = scala.compiletime.uninitialized
  private var drawBorder: scala.Boolean = false
  /* porter: renamed-member reason=universal rule=member-rename(§4.55) clash=field-vs-method from=focusBorderEnabled owner=sge.visui.widget.VisTextButton to=focusBorderEnabled$field
     — java keeps fields and methods in SEPARATE namespaces, so a field may share a name with a method of this class or of a SUBCLASS; scala has one namespace and forbids it */
  /* porter: widened-visibility reason=universal rule=member-rename(§4.55) cause=member-rename clash=field-vs-method from=private to=public
     — java lets this name be reused where scala cannot, so the field is renamed (§4.55) — and a renamed field must stay reachable from every place java read it, which scala's own access rules do not grant at the new name; widening can only remove access errors, never introduce one, and never changes behaviour */
  var focusBorderEnabled$field: scala.Boolean = true
  def this(text: java.lang.String, styleName: java.lang.String)(using sge.Sge) = {
    this(lowlevel.Nullable(text), sge.visui.VisUI.getSkin().get(styleName, classOf[sge.visui.widget.VisTextButton.VisTextButtonStyle]))
    this.init()
  }
  def this(text: java.lang.String)(using sge.Sge) = {
    this(lowlevel.Nullable(text), sge.visui.VisUI.getSkin().get(classOf[sge.visui.widget.VisTextButton.VisTextButtonStyle]))
    this.init()
  }
  def this(text: java.lang.String, listener: sge.scenes.scene2d.utils.ChangeListener)(using sge.Sge) = {
    this(lowlevel.Nullable(text), sge.visui.VisUI.getSkin().get(classOf[sge.visui.widget.VisTextButton.VisTextButtonStyle]))
    this.init()
    this.addListener(listener)
  }
  def this(text: java.lang.String, styleName: java.lang.String, listener: sge.scenes.scene2d.utils.ChangeListener)(using sge.Sge) = {
    this(lowlevel.Nullable(text), sge.visui.VisUI.getSkin().get(styleName, classOf[sge.visui.widget.VisTextButton.VisTextButtonStyle]))
    this.init()
    this.addListener(listener)
  }
  def this(text: java.lang.String, buttonStyle: sge.visui.widget.VisTextButton.VisTextButtonStyle)(using sge.Sge) = {
    this(lowlevel.Nullable(text), buttonStyle)
    this.init()
  }
  private def init(): scala.Unit = {
    this.visStyle$field = this.style.asInstanceOf[sge.visui.widget.VisTextButton.VisTextButtonStyle]
    this.addListener(new sge.scenes.scene2d.InputListener() {
      /* porter: suppressed-warning reason=universal rule=suppressed-warning(orNull) annotation=@nowarn("msg=deprecated")
         — this member's body calls `.orNull` (the null-preserving unwrap at a slot that accepts null); lls deprecates `orNull` as a lint so every usage needs `@nowarn` — the same pattern sge uses at every Java interop boundary */
      @java.lang.Override
      @scala.annotation.nowarn("msg=deprecated")
      override def touchDown(event: sge.scenes.scene2d.InputEvent, x: scala.Float, y: scala.Float, pointer: scala.Int, button: scala.Int): scala.Boolean = {
        if (VisTextButton.this.disabled == false) {
          sge.visui.FocusManager.switchFocus(VisTextButton.this.stage.orNull, VisTextButton.this)
        } else ()
        return false
      }
    })
  }
  @java.lang.Override
  override def draw(batch: sge.graphics.g2d.Batch, parentAlpha: scala.Float): scala.Unit = {
    super.draw(batch, parentAlpha)
    if ((this.focusBorderEnabled$field && this.drawBorder) && (this.visStyle$field.focusBorder != null)) {
      this.visStyle$field.focusBorder.draw(batch, this.x, this.y, this.getWidth, this.getHeight)
    } else ()
  }
  /* porter: renamed-member reason=universal rule=bean-detect accessors=isFocusBorderEnabled/setFocusBorderEnabled property=focusBorderEnabled source=auto-detect */
  /* porter: renamed-member reason=universal rule=bean-detect component=6 from=isFocusBorderEnabled owner=com.kotcrab.vis.ui.widget.VisTextButton to=focusBorderEnabled
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  /* porter: renamed-member reason=universal rule=bean-detect component=6 from=isFocusBorderEnabled owner=com.kotcrab.vis.ui.widget.VisTextButton to=focusBorderEnabled
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  /* porter: renamed-member reason=universal rule=bean-detect component=6 from=isFocusBorderEnabled owner=com.kotcrab.vis.ui.widget.VisTextButton to=focusBorderEnabled
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  /* porter: renamed-member reason=universal rule=bean-detect component=6 from=isFocusBorderEnabled owner=com.kotcrab.vis.ui.widget.VisTextButton to=focusBorderEnabled
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  /* porter: renamed-member reason=universal rule=bean-detect component=6 from=isFocusBorderEnabled owner=com.kotcrab.vis.ui.widget.VisTextButton to=focusBorderEnabled
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  /* porter: renamed-member reason=universal rule=bean-detect component=6 from=isFocusBorderEnabled owner=com.kotcrab.vis.ui.widget.VisTextButton to=focusBorderEnabled
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  @java.lang.Override
  override def focusBorderEnabled: scala.Boolean = {
    return this.focusBorderEnabled$field
  }
  /* porter: renamed-member reason=universal rule=bean-detect component=6 from=setFocusBorderEnabled owner=com.kotcrab.vis.ui.widget.VisTextButton to=focusBorderEnabled_=
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  /* porter: renamed-member reason=universal rule=bean-detect component=6 from=setFocusBorderEnabled owner=com.kotcrab.vis.ui.widget.VisTextButton to=focusBorderEnabled_=
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  /* porter: renamed-member reason=universal rule=bean-detect component=6 from=setFocusBorderEnabled owner=com.kotcrab.vis.ui.widget.VisTextButton to=focusBorderEnabled_=
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  /* porter: renamed-member reason=universal rule=bean-detect component=6 from=setFocusBorderEnabled owner=com.kotcrab.vis.ui.widget.VisTextButton to=focusBorderEnabled_=
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  /* porter: renamed-member reason=universal rule=bean-detect component=6 from=setFocusBorderEnabled owner=com.kotcrab.vis.ui.widget.VisTextButton to=focusBorderEnabled_=
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  /* porter: renamed-member reason=universal rule=bean-detect component=6 from=setFocusBorderEnabled owner=com.kotcrab.vis.ui.widget.VisTextButton to=focusBorderEnabled_=
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  @java.lang.Override
  override def focusBorderEnabled_=(focusBorderEnabled: scala.Boolean): scala.Unit = {
    this.focusBorderEnabled$field = focusBorderEnabled
  }
  @java.lang.Override
  override def focusLost(): scala.Unit = {
    this.drawBorder = false
  }
  @java.lang.Override
  override def focusGained(): scala.Unit = {
    this.drawBorder = true
  }
}
object VisTextButton {
  /* porter: forced-class-init reason=universal rule=class-init-trigger(§4.4) forces=sge.scenes.scene2d.ui.Table trigger=subclass-init
     — initialising this type initialises `sge.scenes.scene2d.ui.Table` first (JLS 12.4.1 item 7), which runs that type's class initialiser; a scala object's initialisation reaches no other object */
  val _ = sge.scenes.scene2d.ui.Table
  export sge.scenes.scene2d.ui.TextButton.{VisTextButtonStyle => _, cellPool => _, cellPool$set => _, cellPool$value => _, columnWeightedWidth => _, rowWeightedHeight => _, tmp => _, *}
  /* porter: funnelled-ctor reason=universal rule=ctor-funnel constructors=3 disambiguator=none escapes=0 notSlot=- primary=() primaryVis=as-declared shape=no-arg-root slots=- superArgs=0
     — java lets every constructor pick its own `super(...)`; scala lets only the PRIMARY reach super, so one is nominated, its super arguments become the `extends` clause and its body becomes the class body — which runs on every construction path, `escapes` of which java did not run it on */
  class VisTextButtonStyle extends sge.scenes.scene2d.ui.TextButton.TextButtonStyle {
    var focusBorder: sge.scenes.scene2d.utils.Drawable = scala.compiletime.uninitialized
    /* porter: suppressed-warning reason=universal rule=ctor-replay-orNull-suppression annotation=@nowarn("msg=deprecated")
       — this constructor's rendered statements (delegation arguments, replayed parent statements, own body) call `.orNull` (the null-preserving unwrap at a slot that accepts null); lls deprecates `orNull` as a lint */
    @scala.annotation.nowarn("msg=deprecated")
    def this(up: sge.scenes.scene2d.utils.Drawable, down: sge.scenes.scene2d.utils.Drawable, checked: sge.scenes.scene2d.utils.Drawable, font: sge.graphics.g2d.BitmapFont) = {
      this()
      this.up = lowlevel.Nullable(up)
      this.down = lowlevel.Nullable(down)
      this.checked = lowlevel.Nullable(checked)
      this.font = lowlevel.Nullable(font).orNull
    }
    /* porter: suppressed-warning reason=universal rule=ctor-replay-orNull-suppression annotation=@nowarn("msg=deprecated")
       — this constructor's rendered statements (delegation arguments, replayed parent statements, own body) call `.orNull` (the null-preserving unwrap at a slot that accepts null); lls deprecates `orNull` as a lint */
    @scala.annotation.nowarn("msg=deprecated")
    def this(style: sge.visui.widget.VisTextButton.VisTextButtonStyle) = {
      this()
      this.up = style.up
      this.down = style.down
      this.over = style.over
      this.focused = style.focused
      this.disabled = style.disabled
      this.checked = style.checked
      this.checkedOver = style.checkedOver
      this.checkedDown = style.checkedDown
      this.checkedFocused = style.checkedFocused
      this.pressedOffsetX = style.pressedOffsetX
      this.pressedOffsetY = style.pressedOffsetY
      this.unpressedOffsetX = style.unpressedOffsetX
      this.unpressedOffsetY = style.unpressedOffsetY
      this.checkedOffsetX = style.checkedOffsetX
      this.checkedOffsetY = style.checkedOffsetY
      this.font = style.font
      if (!style.fontColor.isEmpty) {
        this.fontColor = lowlevel.Nullable(new sge.graphics.Color(style.fontColor.orNull))
      } else ()
      if (!style.downFontColor.isEmpty) {
        this.downFontColor = lowlevel.Nullable(new sge.graphics.Color(style.downFontColor.orNull))
      } else ()
      if (!style.overFontColor.isEmpty) {
        this.overFontColor = lowlevel.Nullable(new sge.graphics.Color(style.overFontColor.orNull))
      } else ()
      if (!style.focusedFontColor.isEmpty) {
        this.focusedFontColor = lowlevel.Nullable(new sge.graphics.Color(style.focusedFontColor.orNull))
      } else ()
      if (!style.disabledFontColor.isEmpty) {
        this.disabledFontColor = lowlevel.Nullable(new sge.graphics.Color(style.disabledFontColor.orNull))
      } else ()
      if (!style.checkedFontColor.isEmpty) {
        this.checkedFontColor = lowlevel.Nullable(new sge.graphics.Color(style.checkedFontColor.orNull))
      } else ()
      if (!style.checkedDownFontColor.isEmpty) {
        this.checkedDownFontColor = lowlevel.Nullable(new sge.graphics.Color(style.checkedDownFontColor.orNull))
      } else ()
      if (!style.checkedOverFontColor.isEmpty) {
        this.checkedOverFontColor = lowlevel.Nullable(new sge.graphics.Color(style.checkedOverFontColor.orNull))
      } else ()
      if (!style.checkedFocusedFontColor.isEmpty) {
        this.checkedFocusedFontColor = lowlevel.Nullable(new sge.graphics.Color(style.checkedFocusedFontColor.orNull))
      } else ()
      this.focusBorder = style.focusBorder
    }
  }
}