/*
 * Generated by Baltic Porter 0.1.0-SNAPSHOT — DO NOT EDIT; regenerate instead.
 *
 * Ported from: vis-ui/ui/src/main/java/com/kotcrab/vis/ui/widget/VisTextField.java
 * Original license: Apache-2.0 (see VisUI upstream)
 * upstream-commit: vis-ui@820300c86a1bd907404217195a9987e5c66d2220 (last change to ui/src/main/java; origin https://github.com/kotcrab/vis-ui.git)
 */
/*
 * Copyright 2014-2017 See AUTHORS file.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
/* porter: funnelled-ctor reason=universal rule=ctor-funnel constructors=4 disambiguator=none escapes=3 notSlot=- primary=() primaryVis=as-declared shape=unique-root slots=- superArgs=0
   — java lets every constructor pick its own `super(...)`; scala lets only the PRIMARY reach super, so one is nominated, its super arguments become the `extends` clause and its body becomes the class body — which runs on every construction path, `escapes` of which java did not run it on */
/* porter: renamed-package reason=configured phase=package-rename key="com.kotcrab.vis.ui -> sge.visui" from=com.kotcrab.vis.ui.widget.VisTextField to=sge.visui.widget.VisTextField */
package sge.visui.widget

/**
 * Extends functionality of standard {@link TextField}. Style supports over, and focus border. Improved text input.
 * Due to scope of changes made this widget is not compatible with {@link TextField}.
 * @author mzechner
 * @author Nathan Sweet
 * @author Kotcrab
 * @see TextField
 */
class VisTextField(using sge.Sge) extends sge.scenes.scene2d.ui.Widget with sge.scenes.scene2d.utils.Disableable with sge.visui.Focusable with sge.visui.util.BorderOwner {
  /* porter: forced-class-init reason=universal rule=class-init-trigger(§4.4) forces=sge.visui.widget.VisTextField trigger=instantiation
     — java runs this class's initialiser — its `static { }` blocks and its static field initialisers, one sequence, JLS 12.4.2 step 9 — at class initialisation, and a scala companion initialises on first access to the OBJECT, which `new` is not */
  val _ = sge.visui.widget.VisTextField
  /* porter: renamed-member reason=universal rule=member-rename(§4.55) clash=field-vs-method from=text owner=sge.visui.widget.VisTextField to=text$field
     — java keeps fields and methods in SEPARATE namespaces, so a field may share a name with a method of this class or of a SUBCLASS; scala has one namespace and forbids it */
  /* porter: widened-visibility reason=universal rule=member-rename(§4.55) cause=member-rename clash=field-vs-method from=protected to=public
     — java lets this name be reused where scala cannot, so the field is renamed (§4.55) — and a renamed field must stay reachable from every place java read it, which scala's own access rules do not grant at the new name; widening can only remove access errors, never introduce one, and never changes behaviour */
  var text$field: java.lang.String = scala.compiletime.uninitialized
  protected[widget] var cursor: scala.Int = 0
  /* porter: renamed-member reason=universal rule=member-rename(§4.55) clash=field-vs-method from=selectionStart owner=sge.visui.widget.VisTextField to=selectionStart$field
     — java keeps fields and methods in SEPARATE namespaces, so a field may share a name with a method of this class or of a SUBCLASS; scala has one namespace and forbids it */
  /* porter: widened-visibility reason=universal rule=member-rename(§4.55) cause=member-rename clash=field-vs-method from=protected to=public
     — java lets this name be reused where scala cannot, so the field is renamed (§4.55) — and a renamed field must stay reachable from every place java read it, which scala's own access rules do not grant at the new name; widening can only remove access errors, never introduce one, and never changes behaviour */
  var selectionStart$field: scala.Int = 0
  protected[widget] var hasSelection: scala.Boolean = false
  protected[widget] var writeEnters: scala.Boolean = false
  /* porter: renamed-member reason=universal rule=member-rename(§4.55) clash=shadows-inherited from=layout owner=sge.visui.widget.VisTextField to=layout$shadow
     — java fields SHADOW rather than override and are resolved by the static type of the receiver, so both storages exist; scala has no such thing and a var cannot be overridden at all. Every reference already points at the symbol java chose, so renaming the symbol re-points exactly those and no others */
  /* porter: widened-visibility reason=universal rule=member-rename(§4.55) cause=member-rename clash=shadows-inherited from=protected to=public
     — java lets this name be reused where scala cannot, so the field is renamed (§4.55) — and a renamed field must stay reachable from every place java read it, which scala's own access rules do not grant at the new name; widening can only remove access errors, never introduce one, and never changes behaviour */
  final val layout$shadow: sge.graphics.g2d.GlyphLayout = new sge.graphics.g2d.GlyphLayout()
  protected[widget] final val glyphPositions: lowlevel.util.DynamicArray[scala.Float] = lowlevel.util.DynamicArray.apply[scala.Float]()
  /* porter: renamed-member reason=universal rule=member-rename(§4.55) clash=field-vs-method from=messageText owner=sge.visui.widget.VisTextField to=messageText$field
     — java keeps fields and methods in SEPARATE namespaces, so a field may share a name with a method of this class or of a SUBCLASS; scala has one namespace and forbids it */
  /* porter: widened-visibility reason=universal rule=member-rename(§4.55) cause=member-rename clash=field-vs-method from=private to=public
     — java lets this name be reused where scala cannot, so the field is renamed (§4.55) — and a renamed field must stay reachable from every place java read it, which scala's own access rules do not grant at the new name; widening can only remove access errors, never introduce one, and never changes behaviour */
  var messageText$field: java.lang.String = scala.compiletime.uninitialized
  protected[widget] var displayText: java.lang.CharSequence = scala.compiletime.uninitialized
  /* porter: widened-visibility reason=universal rule=ctor-replay-widening cause=ctor-replay-widening from=package-private scope=dependent-modules to=public
     — a paramful constructor of this class writes this member, and a SUBCLASS IN ANOTHER MODULE can only express its `super(args)` as a replay one level down (scala lets only the primary reach super) — where `private` does not reach and where nothing but this run can widen it (ENGINE-LIMITS.md C15); widening can only remove access errors */
  var clipboard: sge.utils.Clipboard = scala.compiletime.uninitialized
  private[widget] var inputListener: sge.scenes.scene2d.InputListener = scala.compiletime.uninitialized
  private[widget] var listener: sge.visui.widget.VisTextField.TextFieldListener = scala.compiletime.uninitialized
  private[widget] var filter: sge.visui.widget.VisTextField.TextFieldFilter = scala.compiletime.uninitialized
  private[widget] var keyboard: sge.scenes.scene2d.ui.TextField.OnscreenKeyboard = new sge.scenes.scene2d.ui.TextField.DefaultOnscreenKeyboard()
  private[widget] var focusTraversal: scala.Boolean = true
  private[widget] var onlyFontChars: scala.Boolean = true
  /* porter: renamed-member reason=universal rule=member-rename(§4.55) clash=field-vs-method from=disabled owner=sge.visui.widget.VisTextField to=disabled$field
     — java keeps fields and methods in SEPARATE namespaces, so a field may share a name with a method of this class or of a SUBCLASS; scala has one namespace and forbids it */
  private[widget] var disabled$field: scala.Boolean = false
  private[widget] var enterKeyFocusTraversal: scala.Boolean = false
  private var textHAlign: sge.utils.Align = sge.utils.Align.left
  private var selectionX: scala.Float = 0.0f
  private var selectionWidth: scala.Float = 0.0f
  private[widget] var undoText: java.lang.String = ""
  private[widget] var undoCursorPos: scala.Int = 0
  private[widget] var lastChangeTime: scala.Long = 0L
  /* porter: renamed-member reason=universal rule=member-rename(§4.55) clash=field-vs-method from=passwordMode owner=sge.visui.widget.VisTextField to=passwordMode$field
     — java keeps fields and methods in SEPARATE namespaces, so a field may share a name with a method of this class or of a SUBCLASS; scala has one namespace and forbids it */
  private[widget] var passwordMode$field: scala.Boolean = false
  private var passwordBuffer: java.lang.StringBuilder = scala.compiletime.uninitialized
  private var passwordCharacter: scala.Char = VisTextField.BULLET
  protected[widget] var fontOffset: scala.Float = 0.0f
  protected[widget] var textHeight: scala.Float = 0.0f
  protected[widget] var textOffset: scala.Float = 0.0f
  private[widget] var renderOffset: scala.Float = 0.0f
  private var visibleTextStart: scala.Int = 0
  private var visibleTextEnd: scala.Int = 0
  /* porter: renamed-member reason=universal rule=member-rename(§4.55) clash=field-vs-method from=maxLength owner=sge.visui.widget.VisTextField to=maxLength$field
     — java keeps fields and methods in SEPARATE namespaces, so a field may share a name with a method of this class or of a SUBCLASS; scala has one namespace and forbids it */
  /* porter: widened-visibility reason=universal rule=member-rename(§4.55) cause=member-rename clash=field-vs-method from=private to=public
     — java lets this name be reused where scala cannot, so the field is renamed (§4.55) — and a renamed field must stay reachable from every place java read it, which scala's own access rules do not grant at the new name; widening can only remove access errors, never introduce one, and never changes behaviour */
  var maxLength$field: scala.Int = 0
  private var blinkTime: scala.Float = 0.45f
  private[widget] var cursorOn: scala.Boolean = true
  private[widget] var lastBlink: scala.Long = 0L
  private[widget] var keyRepeatTask: sge.visui.widget.VisTextField#KeyRepeatTask = new KeyRepeatTask()
  /* porter: renamed-member reason=universal rule=member-rename(§4.55) clash=field-vs-method from=programmaticChangeEvents owner=sge.visui.widget.VisTextField to=programmaticChangeEvents$field
     — java keeps fields and methods in SEPARATE namespaces, so a field may share a name with a method of this class or of a SUBCLASS; scala has one namespace and forbids it */
  private[widget] var programmaticChangeEvents$field: scala.Boolean = false
  // vis fields
  /* porter: renamed-member reason=universal rule=member-rename(§4.55) clash=field-vs-method from=style owner=sge.visui.widget.VisTextField to=style$field
     — java keeps fields and methods in SEPARATE namespaces, so a field may share a name with a method of this class or of a SUBCLASS; scala has one namespace and forbids it */
  private[widget] var style$field: sge.visui.widget.VisTextField.VisTextFieldStyle = scala.compiletime.uninitialized
  private var clickListener: sge.scenes.scene2d.utils.ClickListener = scala.compiletime.uninitialized
  private var drawBorder: scala.Boolean = false
  /* porter: renamed-member reason=universal rule=member-rename(§4.55) clash=field-vs-method from=focusBorderEnabled owner=sge.visui.widget.VisTextField to=focusBorderEnabled$field
     — java keeps fields and methods in SEPARATE namespaces, so a field may share a name with a method of this class or of a SUBCLASS; scala has one namespace and forbids it */
  /* porter: widened-visibility reason=universal rule=member-rename(§4.55) cause=member-rename clash=field-vs-method from=private to=public
     — java lets this name be reused where scala cannot, so the field is renamed (§4.55) — and a renamed field must stay reachable from every place java read it, which scala's own access rules do not grant at the new name; widening can only remove access errors, never introduce one, and never changes behaviour */
  var focusBorderEnabled$field: scala.Boolean = true
  /* porter: renamed-member reason=universal rule=member-rename(§4.55) clash=field-vs-method from=inputValid owner=sge.visui.widget.VisTextField to=inputValid$field
     — java keeps fields and methods in SEPARATE namespaces, so a field may share a name with a method of this class or of a SUBCLASS; scala has one namespace and forbids it */
  /* porter: widened-visibility reason=universal rule=member-rename(§4.55) cause=member-rename clash=field-vs-method from=private to=public
     — java lets this name be reused where scala cannot, so the field is renamed (§4.55) — and a renamed field must stay reachable from every place java read it, which scala's own access rules do not grant at the new name; widening can only remove access errors, never introduce one, and never changes behaviour */
  var inputValid$field: scala.Boolean = true
  /* porter: renamed-member reason=universal rule=member-rename(§4.55) clash=field-vs-method from=ignoreEqualsTextChange owner=sge.visui.widget.VisTextField to=ignoreEqualsTextChange$field
     — java keeps fields and methods in SEPARATE namespaces, so a field may share a name with a method of this class or of a SUBCLASS; scala has one namespace and forbids it */
  /* porter: widened-visibility reason=universal rule=member-rename(§4.55) cause=member-rename clash=field-vs-method from=private to=public
     — java lets this name be reused where scala cannot, so the field is renamed (§4.55) — and a renamed field must stay reachable from every place java read it, which scala's own access rules do not grant at the new name; widening can only remove access errors, never introduce one, and never changes behaviour */
  var ignoreEqualsTextChange$field: scala.Boolean = true
  /* porter: renamed-member reason=universal rule=member-rename(§4.55) clash=field-vs-method from=readOnly owner=sge.visui.widget.VisTextField to=readOnly$field
     — java keeps fields and methods in SEPARATE namespaces, so a field may share a name with a method of this class or of a SUBCLASS; scala has one namespace and forbids it */
  /* porter: widened-visibility reason=universal rule=member-rename(§4.55) cause=member-rename clash=field-vs-method from=private to=public
     — java lets this name be reused where scala cannot, so the field is renamed (§4.55) — and a renamed field must stay reachable from every place java read it, which scala's own access rules do not grant at the new name; widening can only remove access errors, never introduce one, and never changes behaviour */
  var readOnly$field: scala.Boolean = false
  private var cursorPercentHeight: scala.Float = 0.8f
  def this(text: java.lang.String, style: sge.visui.widget.VisTextField.VisTextFieldStyle)(using sge.Sge) = {
    this()
    this.style = style
    this.clipboard = scala.Predef.summon[sge.Sge].application.clipboard
    this.initialize()
    this.text = text
    this.setSize(this.getPrefWidth(), this.getPrefHeight())
  }
  def this(text: java.lang.String)(using sge.Sge) = {
    this(text, sge.visui.VisUI.getSkin().get(classOf[sge.visui.widget.VisTextField.VisTextFieldStyle]))
  }
  def this(text: java.lang.String, styleName: java.lang.String)(using sge.Sge) = {
    this(text, sge.visui.VisUI.getSkin().get(styleName, classOf[sge.visui.widget.VisTextField.VisTextFieldStyle]))
  }
  this.style = sge.visui.VisUI.getSkin().get(classOf[sge.visui.widget.VisTextField.VisTextFieldStyle])
  this.clipboard = scala.Predef.summon[sge.Sge].application.clipboard
  this.initialize()
  this.text = ""
  this.setSize(this.getPrefWidth(), this.getPrefHeight())
  protected[widget] def initialize(): scala.Unit = {
    this.addListener({
      this.inputListener = this.createInputListener
      this.inputListener
    })
    this.addListener({
      this.clickListener = new sge.scenes.scene2d.utils.ClickListener() {
        @java.lang.Override
        override def enter(event: sge.scenes.scene2d.InputEvent, x: scala.Float, y: scala.Float, pointer: scala.Int, fromActor: lowlevel.Nullable[sge.scenes.scene2d.Actor]): scala.Unit = {
          super.enter(event, x, y, pointer, fromActor)
          if ((pointer == (-1)) && (VisTextField.this.disabled == false)) {
            scala.Predef.summon[sge.Sge].graphics.setSystemCursor(sge.graphics.Cursor.SystemCursor.Ibeam)
          } else ()
        }
        @java.lang.Override
        override def exit(event: sge.scenes.scene2d.InputEvent, x: scala.Float, y: scala.Float, pointer: scala.Int, toActor: lowlevel.Nullable[sge.scenes.scene2d.Actor]): scala.Unit = {
          super.exit(event, x, y, pointer, toActor)
          if (pointer == (-1)) {
            sge.visui.util.CursorManager.restoreDefaultCursor()
          } else ()
        }
      }
      this.clickListener
    })
  }
  /* porter: parenless-conversion reason=universal rule=nullary-arity from=createInputListener() to=createInputListener */
  protected[widget] def createInputListener: sge.scenes.scene2d.InputListener = {
    return new TextFieldClickListener()
  }
  protected[widget] def letterUnderCursor(x$arg: scala.Float): scala.Int = {
    var x: scala.Float = x$arg
    x = x - (((this.textOffset + this.fontOffset) - this.style$field.font.data.cursorX) - this.glyphPositions.apply(this.visibleTextStart))
    val n: scala.Int = this.glyphPositions.size
    val glyphPositions: scala.Array[scala.Float] = this.glyphPositions.items;
    { var i: scala.Int = 1; while (i < n) { {
      if (glyphPositions(i) > x) {
        if ((glyphPositions(i) - x) <= (x - glyphPositions(i - 1))) {
          return i
        } else ()
        return i - 1
      } else ()
    }; i = i + 1 } }
    return n - 1
  }
  protected[widget] def isWordCharacter(c: scala.Char): scala.Boolean = {
    return java.lang.Character.isLetterOrDigit(c)
  }
  protected[widget] def wordUnderCursor(at: scala.Int): scala.Array[scala.Int] = {
    val text: java.lang.String = this.text$field
    val start: scala.Int = java.lang.Math.min(text.length(), at)
    var right: scala.Int = text.length()
    var left: scala.Int = 0
    var index: scala.Int = start
    scala.util.boundary { { ; while (index < right) { {
      if (!this.isWordCharacter(text.charAt(index))) {
        right = index
        scala.util.boundary.break(())
      } else ()
    }; index = index + 1 } } }
    scala.util.boundary { { index = start - 1; while (index > (-1)) { {
      if (!this.isWordCharacter(text.charAt(index))) {
        left = index + 1
        scala.util.boundary.break(())
      } else ()
    }; index = index - 1 } } }
    return scala.Array[scala.Int](left, right)
  }
  private[widget] def wordUnderCursor(x: scala.Float): scala.Array[scala.Int] = {
    return (this.wordUnderCursor: (scala.Int) => scala.Array[scala.Int])(this.letterUnderCursor(x))
  }
  private[widget] def withinMaxLength(size: scala.Int): scala.Boolean = {
    return (this.maxLength$field <= 0) || (size < this.maxLength$field)
  }
  /* porter: renamed-member reason=universal rule=bean-detect component=1 from=getMaxLength owner=com.kotcrab.vis.ui.widget.VisTextField to=maxLength
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  /* porter: renamed-member reason=universal rule=bean-detect accessors=getMaxLength/setMaxLength property=maxLength source=auto-detect */
  def maxLength: scala.Int = {
    return this.maxLength$field
  }
  /* porter: renamed-member reason=universal rule=bean-detect component=1 from=setMaxLength owner=com.kotcrab.vis.ui.widget.VisTextField to=maxLength_=
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  def maxLength_=(maxLength: scala.Int): scala.Unit = {
    this.maxLength$field = maxLength
  }
  /**
   * When false, text set by {@link #setText(String)} may contain characters not in the font, a space will be displayed instead.
   * When true (the default), characters not in the font are stripped by setText. Characters not in the font are always stripped
   * when typed or pasted.
   */
  def setOnlyFontChars(onlyFontChars: scala.Boolean): scala.Unit = {
    this.onlyFontChars = onlyFontChars
  }
  /**
   * Returns the text field's style. Modifying the returned style may not have an effect until
   * {@link #setStyle(VisTextFieldStyle)} is called.
   */
  /* porter: renamed-member reason=universal rule=bean-detect component=1 from=getStyle owner=com.kotcrab.vis.ui.widget.VisTextField to=style
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  /* porter: renamed-member reason=universal rule=bean-detect accessors=getStyle/setStyle property=style source=auto-detect */
  def style: sge.visui.widget.VisTextField.VisTextFieldStyle = {
    return this.style$field
  }
  /* porter: renamed-member reason=universal rule=bean-detect component=1 from=setStyle owner=com.kotcrab.vis.ui.widget.VisTextField to=style_=
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  def style_=(style: sge.visui.widget.VisTextField.VisTextFieldStyle): scala.Unit = {
    if (style == null) {
      throw new java.lang.IllegalArgumentException("style cannot be null.")
    } else ()
    this.style$field = style
    this.textHeight = style.font.capHeight - (style.font.descent * 2)
    this.invalidateHierarchy()
  }
  @java.lang.Override
  override def toString(): java.lang.String = {
    return this.text
  }
  protected[widget] def calculateOffsets(): scala.Unit = {
    var visibleWidth: scala.Float = this.getWidth
    if (!this.style$field.background.isEmpty) {
      visibleWidth = visibleWidth - (this.style$field.background.get.leftWidth + this.style$field.background.get.rightWidth)
    } else ()
    val glyphCount: scala.Int = this.glyphPositions.size
    val glyphPositions: scala.Array[scala.Float] = this.glyphPositions.items
    // Check if the cursor has gone out the left or right side of the visible area and adjust renderOffset.
    val distance: scala.Float = glyphPositions(java.lang.Math.max(0, this.cursor - 1)) + this.renderOffset
    if (distance <= 0) {
      this.renderOffset = this.renderOffset - distance
    } else {
      val index: scala.Int = java.lang.Math.min(glyphCount - 1, this.cursor + 1)
      val minX: scala.Float = glyphPositions(index) - visibleWidth
      if ((-this.renderOffset) < minX) {
        this.renderOffset = -minX
      } else ()
    }
    // Prevent renderOffset from starting too close to the end, eg after text was deleted.
    var maxOffset: scala.Float = 0.toFloat
    val width: scala.Float = glyphPositions(glyphCount - 1)
    scala.util.boundary { { var i: scala.Int = glyphCount - 2; while (i >= 0) { {
      val x: scala.Float = glyphPositions(i)
      if ((width - x) > visibleWidth) {
        scala.util.boundary.break(())
      } else ()
      maxOffset = x
    }; i = i - 1 } } }
    if ((-this.renderOffset) > maxOffset) {
      this.renderOffset = -maxOffset
    } else ()
    // calculate first visible char based on render offset
    this.visibleTextStart = 0
    var startX: scala.Float = 0.toFloat
    scala.util.boundary { { var i: scala.Int = 0; while (i < glyphCount) { {
      if (glyphPositions(i) >= (-this.renderOffset)) {
        this.visibleTextStart = java.lang.Math.max(0, i)
        startX = glyphPositions(i)
        scala.util.boundary.break(())
      } else ()
    }; i = i + 1 } } }
    // calculate last visible char based on visible width and render offset
    val length: scala.Int = java.lang.Math.min(this.displayText.length(), glyphPositions.length - 1)
    this.visibleTextEnd = java.lang.Math.min(length, this.cursor + 1)
    scala.util.boundary { { ; while (this.visibleTextEnd <= length) { {
      if (glyphPositions(this.visibleTextEnd) > (startX + visibleWidth)) {
        scala.util.boundary.break(())
      } else ()
    }; this.visibleTextEnd = this.visibleTextEnd + 1 } } }
    this.visibleTextEnd = java.lang.Math.max(0, this.visibleTextEnd - 1)
    if ((sge.utils.Align.toInt(this.textHAlign) & sge.utils.Align.toInt(sge.utils.Align.left)) == 0) {
      this.textOffset = visibleWidth - (glyphPositions(this.visibleTextEnd) - startX)
      if ((sge.utils.Align.toInt(this.textHAlign) & sge.utils.Align.toInt(sge.utils.Align.center)) != 0) {
        this.textOffset = java.lang.Math.round(this.textOffset * 0.5f).toFloat
      } else ()
    } else {
      this.textOffset = startX + this.renderOffset
    }
    // calculate selection x position and width
    if (this.hasSelection) {
      val minIndex: scala.Int = java.lang.Math.min(this.cursor, this.selectionStart$field)
      val maxIndex: scala.Int = java.lang.Math.max(this.cursor, this.selectionStart$field)
      val minX: scala.Float = java.lang.Math.max(glyphPositions(minIndex) - glyphPositions(this.visibleTextStart), -this.textOffset)
      val maxX: scala.Float = java.lang.Math.min(glyphPositions(maxIndex) - glyphPositions(this.visibleTextStart), visibleWidth - this.textOffset)
      this.selectionX = minX
      this.selectionWidth = (maxX - minX) - this.style$field.font.data.cursorX
    } else ()
  }
  /* porter: suppressed-warning reason=universal rule=suppressed-warning(orNull) annotation=@nowarn("msg=deprecated")
     — this member's body calls `.orNull` (the null-preserving unwrap at a slot that accepts null); lls deprecates `orNull` as a lint so every usage needs `@nowarn` — the same pattern sge uses at every Java interop boundary */
  @java.lang.Override
  @scala.annotation.nowarn("msg=deprecated")
  override def draw(batch: sge.graphics.g2d.Batch, parentAlpha: scala.Float): scala.Unit = {
    val stage: sge.scenes.scene2d.Stage = this.stage.orNull
    val focused: scala.Boolean = (stage != null) && (stage.getKeyboardFocus.get eq this)
    if (!focused) {
      this.keyRepeatTask.cancel()
    } else ()
    val font: sge.graphics.g2d.BitmapFont = this.style$field.font
    val fontColor: sge.graphics.Color = if (this.disabled$field && (!this.style$field.disabledFontColor.isEmpty)) this.style$field.disabledFontColor.orNull else if (focused && (!this.style$field.focusedFontColor.isEmpty)) this.style$field.focusedFontColor.orNull else this.style$field.fontColor
    val selection: sge.scenes.scene2d.utils.Drawable = this.style$field.selection.orNull
    val cursorPatch: sge.scenes.scene2d.utils.Drawable = this.style$field.cursor.orNull
    var background: sge.scenes.scene2d.utils.Drawable = if (this.disabled$field && (!this.style$field.disabledBackground.isEmpty)) this.style$field.disabledBackground.orNull else if (focused && (!this.style$field.focusedBackground.isEmpty)) this.style$field.focusedBackground.orNull else this.style$field.background.orNull
    // vis
    if (((!this.disabled$field) && (this.style$field.backgroundOver != null)) && (this.clickListener.over || focused)) {
      background = this.style$field.backgroundOver
    } else ()
    val color: sge.graphics.Color = this.color
    val x: scala.Float = this.x
    val y: scala.Float = this.y
    val width: scala.Float = this.getWidth
    val height: scala.Float = this.getHeight
    batch.setColor(color.r, color.g, color.b, color.a * parentAlpha)
    var bgLeftWidth: scala.Float = 0.toFloat
    var bgRightWidth: scala.Float = 0.toFloat
    if (background != null) {
      background.draw(batch, x, y, width, height)
      bgLeftWidth = background.leftWidth
      bgRightWidth = background.rightWidth
    } else ()
    val textY: scala.Float = this.getTextY(font, background)
    this.calculateOffsets()
    if ((focused && this.hasSelection) && (selection != null)) {
      this.drawSelection(selection, batch, font, x + bgLeftWidth, y + textY)
    } else ()
    val yOffset: scala.Float = if (font.flipped) -this.textHeight else 0.asInstanceOf[scala.Float].toFloat
    if (this.displayText.length() == 0) {
      if ((!focused) && (this.messageText$field != null)) {
        if (!this.style$field.messageFontColor.isEmpty) {
          font.setColor(this.style$field.messageFontColor.get.r, this.style$field.messageFontColor.get.g, this.style$field.messageFontColor.get.b, (this.style$field.messageFontColor.get.a * color.a) * parentAlpha)
        } else {
          font.setColor(0.7f, 0.7f, 0.7f, color.a * parentAlpha)
        }
        val messageFont: sge.graphics.g2d.BitmapFont = if (!this.style$field.messageFont.isEmpty) this.style$field.messageFont.orNull else font
        messageFont.draw(batch, this.messageText$field, x + bgLeftWidth, (y + textY) + yOffset, 0, this.messageText$field.length(), (width - bgLeftWidth) - bgRightWidth, this.textHAlign, false, "...")
      } else ()
    } else {
      val data: sge.graphics.g2d.BitmapFont.BitmapFontData = font.data
      val markupEnabled: scala.Boolean = data.markupEnabled
      data.markupEnabled = false
      font.setColor(fontColor.r, fontColor.g, fontColor.b, (fontColor.a * color.a) * parentAlpha)
      this.drawText(batch, font, x + bgLeftWidth, (y + textY) + yOffset)
      data.markupEnabled = markupEnabled
    }
    if ((this.drawBorder && focused) && (!this.disabled$field)) {
      this.blink()
      if (this.cursorOn && (cursorPatch != null)) {
        this.drawCursor(cursorPatch, batch, font, x + bgLeftWidth, y + textY)
      } else ()
    } else ()
    // vis
    if (((this.disabled == false) && (this.inputValid$field == false)) && (this.style$field.errorBorder != null)) {
      this.style$field.errorBorder.draw(batch, this.x, this.y, this.getWidth, this.getHeight)
    } else {
      if ((this.focusBorderEnabled$field && this.drawBorder) && (this.style$field.focusBorder != null)) {
        this.style$field.focusBorder.draw(batch, this.x, this.y, this.getWidth, this.getHeight)
      } else ()
    }
  }
  protected[widget] def getTextY(font: sge.graphics.g2d.BitmapFont, background: sge.scenes.scene2d.utils.Drawable): scala.Float = {
    val height: scala.Float = this.getHeight
    var textY: scala.Float = (this.textHeight / 2) + font.descent
    if (background != null) {
      val bottom: scala.Float = background.bottomHeight
      textY = (textY + (((height - background.topHeight) - bottom) / 2)) + bottom
    } else {
      textY = textY + (height / 2)
    }
    if (font.usesIntegerPositions) {
      textY = textY.asInstanceOf[scala.Int].toFloat
    } else ()
    return textY
  }
  /** Draws selection rectangle **/
  protected[widget] def drawSelection(selection: sge.scenes.scene2d.utils.Drawable, batch: sge.graphics.g2d.Batch, font: sge.graphics.g2d.BitmapFont, x: scala.Float, y: scala.Float): scala.Unit = {
    selection.draw(batch, ((x + this.selectionX) + this.textOffset) + this.fontOffset, (y - this.textHeight) - font.descent, this.selectionWidth, this.textHeight)
  }
  protected[widget] def drawText(batch: sge.graphics.g2d.Batch, font: sge.graphics.g2d.BitmapFont, x: scala.Float, y: scala.Float): scala.Unit = {
    font.draw(batch, this.displayText, x + this.textOffset, y, this.visibleTextStart, this.visibleTextEnd, 0.toFloat, sge.utils.Align.left, false)
  }
  protected[widget] def drawCursor(cursorPatch: sge.scenes.scene2d.utils.Drawable, batch: sge.graphics.g2d.Batch, font: sge.graphics.g2d.BitmapFont, x: scala.Float, y: scala.Float): scala.Unit = {
    val cursorHeight: scala.Float = this.textHeight * this.cursorPercentHeight
    val cursorYPadding: scala.Float = (this.textHeight - cursorHeight) / 2
    cursorPatch.draw(batch, ((((x + this.textOffset) + this.glyphPositions.apply(this.cursor)) - this.glyphPositions.apply(this.visibleTextStart)) + this.fontOffset) + font.data.cursorX, ((y - this.textHeight) - font.descent) + cursorYPadding, cursorPatch.minWidth, cursorHeight)
  }
  private[widget] def updateDisplayText(): scala.Unit = {
    val font: sge.graphics.g2d.BitmapFont = this.style$field.font
    val data: sge.graphics.g2d.BitmapFont.BitmapFontData = font.data
    val text: java.lang.String = this.text$field
    val textLength: scala.Int = text.length()
    val buffer: java.lang.StringBuilder = new java.lang.StringBuilder();
    { var i: scala.Int = 0; while (i < textLength) { {
      val c: scala.Char = text.charAt(i)
      buffer.append(if (data.hasGlyph(c)) c else ' ')
    }; i = i + 1 } }
    val newDisplayText: java.lang.String = buffer.toString()
    if (this.passwordMode$field && data.hasGlyph(this.passwordCharacter)) {
      if (this.passwordBuffer == null) {
        this.passwordBuffer = new java.lang.StringBuilder(newDisplayText.length())
      } else ()
      if (this.passwordBuffer.length() > textLength) {
        this.passwordBuffer.setLength(textLength)
      } else {
        { var i: scala.Int = this.passwordBuffer.length(); while (i < textLength) { {
          this.passwordBuffer.append(this.passwordCharacter)
        }; i = i + 1 } }
      }
      this.displayText = this.passwordBuffer
    } else {
      this.displayText = newDisplayText
    }
    val markupEnabled: scala.Boolean = data.markupEnabled
    data.markupEnabled = false
    this.layout$shadow.setText(font, this.displayText.toString().replace('\r', ' ').replace('\n', ' '))
    data.markupEnabled = markupEnabled
    this.glyphPositions.clear()
    var x: scala.Float = 0.toFloat
    if (this.layout$shadow.runs.size > 0) {
      val run: sge.graphics.g2d.GlyphLayout.GlyphRun = {
        val bp$tpl202 = this.layout$shadow.runs;
        { if (bp$tpl202.isEmpty) throw new java.lang.IllegalStateException("Array is empty."); bp$tpl202.first }
      }
      this.fontOffset = {
        val bp$tpl203 = run.xAdvances;
        { if (bp$tpl203.isEmpty) throw new java.lang.IllegalStateException("Array is empty."); bp$tpl203.first }
      }
      for (glyphRun <- this.layout$shadow.runs) {
        val xAdvances: lowlevel.util.DynamicArray[scala.Float] = glyphRun.xAdvances;
        { var i: scala.Int = 1; val n: scala.Int = xAdvances.size; while (i < n) { {
          this.glyphPositions.add(x)
          x = x + xAdvances.apply(i)
        }; i = i + 1 } }
        this.glyphPositions.add(x)
      }
    } else {
      this.fontOffset = 0.toFloat
    }
    this.glyphPositions.add(x)
    this.visibleTextStart = java.lang.Math.min(this.visibleTextStart, this.glyphPositions.size)
    this.visibleTextEnd = (sge.math.MathUtils.clamp: (scala.Int, scala.Int, scala.Int) => scala.Int)(this.visibleTextEnd, this.visibleTextStart, this.glyphPositions.size)
    if (this.selectionStart$field > newDisplayText.length()) {
      this.selectionStart$field = textLength
    } else ()
  }
  private def blink(): scala.Unit = {
    if (!scala.Predef.summon[sge.Sge].graphics.continuousRendering) {
      this.cursorOn = true
      return
    } else ()
    val time: scala.Long = sge.utils.TimeUtils.nanoTime()
    if (((time - this.lastBlink) / 1.0E9f) > this.blinkTime) {
      this.cursorOn = !this.cursorOn
      this.lastBlink = time
    } else ()
  }
  /** Copies the contents of this TextField to the {@link Clipboard} implementation set on this TextField. */
  def copy(): scala.Unit = {
    if (this.hasSelection && (!this.passwordMode$field)) {
      val beginIndex: scala.Int = java.lang.Math.min(this.cursor, this.selectionStart$field)
      val endIndex: scala.Int = java.lang.Math.max(this.cursor, this.selectionStart$field)
      this.clipboard.contents = this.text$field.substring(java.lang.Math.max(0, beginIndex), java.lang.Math.min(this.text$field.length(), endIndex))
    } else ()
  }
  /**
   * Copies the selected contents of this TextField to the {@link Clipboard} implementation set on this TextField, then removes
   * it.
   */
  def cut(): scala.Unit = {
    this.cut(this.programmaticChangeEvents$field)
  }
  private[widget] def cut(fireChangeEvent: scala.Boolean): scala.Unit = {
    if (this.hasSelection && (!this.passwordMode$field)) {
      this.copy()
      this.cursor = this.delete(fireChangeEvent)
      this.updateDisplayText()
    } else ()
  }
  private[widget] def paste(content$arg: java.lang.String, fireChangeEvent: scala.Boolean): scala.Unit = {
    var content: java.lang.String = content$arg
    if (content == null) {
      return
    } else ()
    val buffer: java.lang.StringBuilder = new java.lang.StringBuilder()
    var textLength: scala.Int = this.text$field.length()
    if (this.hasSelection) {
      textLength = textLength - java.lang.Math.abs(this.cursor - this.selectionStart$field)
    } else ()
    val data: sge.graphics.g2d.BitmapFont.BitmapFontData = this.style$field.font.data
    scala.util.boundary { (brk$16: scala.util.boundary.Label[scala.Unit]) ?=> { var i: scala.Int = 0; val n: scala.Int = content.length(); while (i < n) { scala.util.boundary { {
      if (!this.withinMaxLength(textLength + buffer.length())) {
        scala.util.boundary.break(())(using brk$16)
      } else ()
      val c: scala.Char = content.charAt(i)
      if (!(this.writeEnters && ((c == VisTextField.ENTER_ANDROID) || (c == VisTextField.ENTER_DESKTOP)))) {
        if ((c == '\r') || (c == '\n')) {
          scala.util.boundary.break(())
        } else ()
        if (this.onlyFontChars && (!data.hasGlyph(c))) {
          scala.util.boundary.break(())
        } else ()
        if ((this.filter != null) && (!this.filter.acceptChar(this, c))) {
          scala.util.boundary.break(())
        } else ()
      } else ()
      buffer.append(c)
    } }; i = i + 1 } } }
    content = buffer.toString()
    if (this.hasSelection) {
      this.cursor = this.delete(fireChangeEvent)
    } else ()
    if (fireChangeEvent) {
      this.changeText(this.text$field, this.insert(this.cursor, content, this.text$field))
    } else {
      this.text$field = this.insert(this.cursor, content, this.text$field)
    }
    this.updateDisplayText()
    this.cursor = this.cursor + content.length()
  }
  private[widget] def insert(position: scala.Int, text: java.lang.CharSequence, to: java.lang.String): java.lang.String = {
    if (to.length() == 0) {
      return text.toString()
    } else ()
    return (to.substring(0, position) + text) + to.substring(position, to.length())
  }
  private[widget] def delete(fireChangeEvent: scala.Boolean): scala.Int = {
    val from: scala.Int = this.selectionStart$field
    val to: scala.Int = this.cursor
    val minIndex: scala.Int = java.lang.Math.min(from, to)
    val maxIndex: scala.Int = java.lang.Math.max(from, to)
    val newText: java.lang.String = (if (minIndex > 0) this.text$field.substring(0, minIndex) else "") + (if (maxIndex < this.text$field.length()) this.text$field.substring(maxIndex, this.text$field.length()) else "")
    if (fireChangeEvent) {
      this.changeText(this.text$field, newText)
    } else {
      this.text$field = newText
    }
    this.clearSelection()
    return minIndex
  }
  /**
   * Focuses the next TextField. If none is found, the keyboard is hidden. Does nothing if the text field is not in a stage.
   * @param up If true, the TextField with the same or next smallest y coordinate is found, else the next highest.
   */
  /* porter: suppressed-warning reason=universal rule=suppressed-warning(orNull) annotation=@nowarn("msg=deprecated")
     — this member's body calls `.orNull` (the null-preserving unwrap at a slot that accepts null); lls deprecates `orNull` as a lint so every usage needs `@nowarn` — the same pattern sge uses at every Java interop boundary */
  @scala.annotation.nowarn("msg=deprecated")
  def next(up: scala.Boolean): scala.Unit = {
    val stage: sge.scenes.scene2d.Stage = this.stage.orNull
    if (stage == null) {
      return
    } else ()
    this.parent.get.localToStageCoordinates(VisTextField.tmp1.set(this.x, this.y))
    var textField: VisTextField = this.findNextTextField(stage.actors, null, VisTextField.tmp2, VisTextField.tmp1, up)
    if (textField == null) {
      // Try to wrap around.
      if (up) {
        VisTextField.tmp1.set(java.lang.Float.MIN_VALUE, java.lang.Float.MIN_VALUE)
      } else {
        VisTextField.tmp1.set(java.lang.Float.MAX_VALUE, java.lang.Float.MAX_VALUE)
      }
      textField = this.findNextTextField(this.stage.get.actors, null, VisTextField.tmp2, VisTextField.tmp1, up)
    } else ()
    if (textField != null) {
      textField.focusField()
      textField.cursorPosition = textField.text.length()
    } else {
      this.keyboard.close()
    }
  }
  private def findNextTextField(actors: lowlevel.util.DynamicArray[sge.scenes.scene2d.Actor], best$arg: VisTextField, bestCoords: sge.math.Vector2, currentCoords: sge.math.Vector2, up: scala.Boolean): VisTextField = {
    var best: VisTextField = best$arg
    val modalWindow: sge.scenes.scene2d.ui.Window = this.findModalWindow(this);
    { var i: scala.Int = 0; val n: scala.Int = actors.size; while (i < n) { scala.util.boundary { {
      val actor: sge.scenes.scene2d.Actor = actors.apply(i)
      if (actor eq this) {
        scala.util.boundary.break(())
      } else ()
      if (actor.isInstanceOf[VisTextField]) {
        val textField: VisTextField = actor.asInstanceOf[VisTextField]
        if (modalWindow != null) {
          val nextFieldModalWindow: sge.scenes.scene2d.ui.Window = this.findModalWindow(textField)
          if (nextFieldModalWindow ne modalWindow) {
            scala.util.boundary.break(())
          } else ()
        } else ()
        if ((textField.disabled || (!textField.focusTraversal)) || (this.isActorVisibleInStage(textField) == false)) {
          scala.util.boundary.break(())
        } else ()
        val actorCoords: sge.math.Vector2 = actor.parent.get.localToStageCoordinates(VisTextField.tmp3.set(actor.x, actor.y))
        if (((actorCoords.y < currentCoords.y) || ((actorCoords.y == currentCoords.y) && (actorCoords.x > currentCoords.x))) ^ up) {
          if ((best == null) || (((actorCoords.y > bestCoords.y) || ((actorCoords.y == bestCoords.y) && (actorCoords.x < bestCoords.x))) ^ up)) {
            best = actor.asInstanceOf[VisTextField]
            bestCoords.set(actorCoords)
          } else ()
        } else ()
      } else {
        if (actor.isInstanceOf[sge.scenes.scene2d.Group]) {
          best = this.findNextTextField(actor.asInstanceOf[sge.scenes.scene2d.Group].children, best, bestCoords, currentCoords, up)
        } else ()
      }
    } }; i = i + 1 } }
    return best
  }
  /**
   * Checks if actor is visible in stage acknowledging parent visibility.
   * If any parent returns false from isVisible then this method return false.
   * True is returned when this actor and all its parent are visible.
   */
  /* porter: suppressed-warning reason=universal rule=suppressed-warning(orNull) annotation=@nowarn("msg=deprecated")
     — this member's body calls `.orNull` (the null-preserving unwrap at a slot that accepts null); lls deprecates `orNull` as a lint so every usage needs `@nowarn` — the same pattern sge uses at every Java interop boundary */
  @scala.annotation.nowarn("msg=deprecated")
  private def isActorVisibleInStage(actor: sge.scenes.scene2d.Actor): scala.Boolean = {
    if (actor == null) {
      return true
    } else ()
    if (actor.visible == false) {
      return false
    } else ()
    return this.isActorVisibleInStage(actor.parent.orNull)
  }
  /* porter: suppressed-warning reason=universal rule=suppressed-warning(orNull) annotation=@nowarn("msg=deprecated")
     — this member's body calls `.orNull` (the null-preserving unwrap at a slot that accepts null); lls deprecates `orNull` as a lint so every usage needs `@nowarn` — the same pattern sge uses at every Java interop boundary */
  @scala.annotation.nowarn("msg=deprecated")
  private def findModalWindow(actor: sge.scenes.scene2d.Actor): sge.scenes.scene2d.ui.Window = {
    if (actor == null) {
      return null
    } else ()
    if (actor.isInstanceOf[sge.scenes.scene2d.ui.Window] && actor.asInstanceOf[sge.scenes.scene2d.ui.Window].modal) {
      return actor.asInstanceOf[sge.scenes.scene2d.ui.Window]
    } else ()
    return this.findModalWindow(actor.parent.orNull)
  }
  /* porter: renamed-member reason=universal rule=bean-detect accessors=getDefaultInputListener property=defaultInputListener source=auto-detect */
  /* porter: renamed-member reason=universal rule=bean-detect component=1 from=getDefaultInputListener owner=com.kotcrab.vis.ui.widget.VisTextField to=defaultInputListener
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  def defaultInputListener: sge.scenes.scene2d.InputListener = {
    return this.inputListener
  }
  /** @param listener May be null. */
  def setTextFieldListener(listener: sge.visui.widget.VisTextField.TextFieldListener): scala.Unit = {
    this.listener = listener
  }
  /** @param filter May be null. */
  /* porter: renamed-member reason=universal rule=bean-detect component=1 from=setTextFieldFilter owner=com.kotcrab.vis.ui.widget.VisTextField to=textFieldFilter_=
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  def textFieldFilter_=(filter: sge.visui.widget.VisTextField.TextFieldFilter): scala.Unit = {
    this.filter = filter
  }
  /* porter: renamed-member reason=universal rule=bean-detect component=1 from=getTextFieldFilter owner=com.kotcrab.vis.ui.widget.VisTextField to=textFieldFilter
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  /* porter: renamed-member reason=universal rule=bean-detect accessors=getTextFieldFilter/setTextFieldFilter property=textFieldFilter source=auto-detect */
  def textFieldFilter: sge.visui.widget.VisTextField.TextFieldFilter = {
    return this.filter
  }
  /** If true (the default), tab/shift+tab will move to the next text field. */
  def setFocusTraversal(focusTraversal: scala.Boolean): scala.Unit = {
    this.focusTraversal = focusTraversal
  }
  /**
   * If true, enter will move to the next text field with has focus traversal enabled.
   * False by default. Note that to enable or disable focus traversal completely you must
   * use {@link #setFocusTraversal(boolean)}
   */
  def setEnterKeyFocusTraversal(enterKeyFocusTraversal: scala.Boolean): scala.Unit = {
    this.enterKeyFocusTraversal = enterKeyFocusTraversal
  }
  /** @return May be null. */
  /* porter: renamed-member reason=universal rule=bean-detect component=1 from=getMessageText owner=com.kotcrab.vis.ui.widget.VisTextField to=messageText
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  /* porter: renamed-member reason=universal rule=bean-detect accessors=getMessageText/setMessageText property=messageText source=auto-detect */
  def messageText: java.lang.String = {
    return this.messageText$field
  }
  /**
   * Sets the text that will be drawn in the text field if no text has been entered.
   * @param messageText may be null.
   */
  /* porter: renamed-member reason=universal rule=bean-detect component=1 from=setMessageText owner=com.kotcrab.vis.ui.widget.VisTextField to=messageText_=
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  def messageText_=(messageText: java.lang.String): scala.Unit = {
    this.messageText$field = messageText
  }
  /** @param str If null, "" is used. */
  def appendText(str$arg: java.lang.String): scala.Unit = {
    var str: java.lang.String = str$arg
    if (str == null) {
      str = ""
    } else ()
    this.clearSelection()
    this.cursor = this.text$field.length()
    this.paste(str, this.programmaticChangeEvents$field)
  }
  /** @param str If null, "" is used. */
  /* porter: renamed-member reason=universal rule=bean-detect component=3 from=setText owner=com.kotcrab.vis.ui.widget.VisTextField to=text_=
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  def text_=(str$arg: java.lang.String): scala.Unit = {
    var str: java.lang.String = str$arg
    if (str == null) {
      str = ""
    } else ()
    if (this.ignoreEqualsTextChange$field && str.equals(this.text$field)) {
      return
    } else ()
    this.clearSelection()
    val oldText: java.lang.String = this.text$field
    this.text$field = ""
    this.paste(str, false)
    if (this.programmaticChangeEvents$field) {
      this.changeText(oldText, this.text$field)
    } else ()
    this.cursor = 0
  }
  /** @return Never null, might be an empty string. */
  /* porter: renamed-member reason=universal rule=bean-detect component=1 from=getText owner=com.kotcrab.vis.ui.widget.VisTextField to=text
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  /* porter: renamed-member reason=universal rule=bean-detect accessors=getText/setText property=text source=auto-detect */
  def text: java.lang.String = {
    return this.text$field
  }
  /**
   * @param oldText May be null.
   * @return True if the text was changed.
   */
  private[widget] def changeText(oldText: java.lang.String, newText: java.lang.String): scala.Boolean = {
    if (this.ignoreEqualsTextChange$field && newText.equals(oldText)) {
      return false
    } else ()
    this.text$field = newText
    this.beforeChangeEventFired()
    val changeEvent: sge.scenes.scene2d.utils.ChangeListener.ChangeEvent = sge.utils.Pools.obtain(classOf[sge.scenes.scene2d.utils.ChangeListener.ChangeEvent])
    val cancelled: scala.Boolean = this.fire(changeEvent)
    this.text$field = if (cancelled) oldText else newText
    sge.utils.Pools.free(changeEvent)
    return !cancelled
  }
  private[widget] def beforeChangeEventFired(): scala.Unit = {
    ()
  }
  /* porter: renamed-member reason=universal rule=bean-detect component=1 from=getProgrammaticChangeEvents owner=com.kotcrab.vis.ui.widget.VisTextField to=programmaticChangeEvents
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  /* porter: renamed-member reason=universal rule=bean-detect accessors=getProgrammaticChangeEvents/setProgrammaticChangeEvents property=programmaticChangeEvents source=auto-detect */
  def programmaticChangeEvents: scala.Boolean = {
    return this.programmaticChangeEvents$field
  }
  /**
   * If false, methods that change the text will not fire {@link ChangeEvent}, the event will be fired only when user changes
   * the text.
   */
  /* porter: renamed-member reason=universal rule=bean-detect component=1 from=setProgrammaticChangeEvents owner=com.kotcrab.vis.ui.widget.VisTextField to=programmaticChangeEvents_=
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  def programmaticChangeEvents_=(programmaticChangeEvents: scala.Boolean): scala.Unit = {
    this.programmaticChangeEvents$field = programmaticChangeEvents
  }
  /* porter: renamed-member reason=universal rule=bean-detect component=1 from=getSelectionStart owner=com.kotcrab.vis.ui.widget.VisTextField to=selectionStart
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  /* porter: renamed-member reason=universal rule=bean-detect accessors=getSelectionStart property=selectionStart source=auto-detect */
  def selectionStart: scala.Int = {
    return this.selectionStart$field
  }
  /* porter: renamed-member reason=universal rule=bean-detect component=1 from=getSelection owner=com.kotcrab.vis.ui.widget.VisTextField to=selection
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  /* porter: renamed-member reason=universal rule=bean-detect accessors=getSelection property=selection source=auto-detect */
  def selection: java.lang.String = {
    return if (this.hasSelection) this.text$field.substring(java.lang.Math.min(this.selectionStart$field, this.cursor), java.lang.Math.max(this.selectionStart$field, this.cursor)) else ""
  }
  /* porter: renamed-member reason=universal rule=bean-detect component=1 from=isTextSelected owner=com.kotcrab.vis.ui.widget.VisTextField to=textSelected
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  /* porter: renamed-member reason=universal rule=bean-detect accessors=isTextSelected property=textSelected source=auto-detect */
  def textSelected: scala.Boolean = {
    return this.hasSelection
  }
  /** Sets the selected text. */
  def setSelection(selectionStart$arg: scala.Int, selectionEnd$arg: scala.Int): scala.Unit = {
    var selectionStart: scala.Int = selectionStart$arg
    var selectionEnd: scala.Int = selectionEnd$arg
    if (selectionStart < 0) {
      throw new java.lang.IllegalArgumentException("selectionStart must be >= 0")
    } else ()
    if (selectionEnd < 0) {
      throw new java.lang.IllegalArgumentException("selectionEnd must be >= 0")
    } else ()
    selectionStart = java.lang.Math.min(this.text$field.length(), selectionStart)
    selectionEnd = java.lang.Math.min(this.text$field.length(), selectionEnd)
    if (selectionEnd == selectionStart) {
      this.clearSelection()
      return
    } else ()
    if (selectionEnd < selectionStart) {
      val temp: scala.Int = selectionEnd
      selectionEnd = selectionStart
      selectionStart = temp
    } else ()
    this.hasSelection = true
    this.selectionStart$field = selectionStart
    this.cursor = selectionEnd
  }
  def selectAll(): scala.Unit = {
    this.setSelection(0, this.text$field.length())
  }
  def clearSelection(): scala.Unit = {
    this.hasSelection = false
  }
  /** Clears VisTextField text. If programmatic change events are disabled then this will not fire change event. */
  def clearText(): scala.Unit = {
    this.text = ""
  }
  /** Sets the cursor position and clears any selection. */
  /* porter: renamed-member reason=universal rule=bean-detect component=1 from=setCursorPosition owner=com.kotcrab.vis.ui.widget.VisTextField to=cursorPosition_=
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  def cursorPosition_=(cursorPosition: scala.Int): scala.Unit = {
    if (cursorPosition < 0) {
      throw new java.lang.IllegalArgumentException("cursorPosition must be >= 0")
    } else ()
    this.clearSelection()
    this.cursor = java.lang.Math.min(cursorPosition, this.text$field.length())
  }
  /* porter: renamed-member reason=universal rule=bean-detect accessors=getCursorPosition/setCursorPosition property=cursorPosition source=auto-detect */
  /* porter: renamed-member reason=universal rule=bean-detect component=1 from=getCursorPosition owner=com.kotcrab.vis.ui.widget.VisTextField to=cursorPosition
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  def cursorPosition: scala.Int = {
    return this.cursor
  }
  def setCursorAtTextEnd(): scala.Unit = {
    this.cursorPosition = 0
    this.calculateOffsets()
    this.cursorPosition = this.text.length()
  }
  /** @param cursorPercentHeight cursor size, value from 0..1 range */
  def setCursorPercentHeight(cursorPercentHeight: scala.Float): scala.Unit = {
    if ((cursorPercentHeight < 0) || (cursorPercentHeight > 1)) {
      throw new java.lang.IllegalArgumentException("cursorPercentHeight must be >= 0 and <= 1")
    } else ()
    this.cursorPercentHeight = cursorPercentHeight
  }
  /** Default is an instance of {@link DefaultOnscreenKeyboard}. */
  /* porter: renamed-member reason=universal rule=bean-detect component=1 from=getOnscreenKeyboard owner=com.kotcrab.vis.ui.widget.VisTextField to=onscreenKeyboard
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  /* porter: renamed-member reason=universal rule=bean-detect accessors=getOnscreenKeyboard/setOnscreenKeyboard property=onscreenKeyboard source=auto-detect */
  def onscreenKeyboard: sge.scenes.scene2d.ui.TextField.OnscreenKeyboard = {
    return this.keyboard
  }
  /* porter: renamed-member reason=universal rule=bean-detect component=1 from=setOnscreenKeyboard owner=com.kotcrab.vis.ui.widget.VisTextField to=onscreenKeyboard_=
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  def onscreenKeyboard_=(keyboard: sge.scenes.scene2d.ui.TextField.OnscreenKeyboard): scala.Unit = {
    this.keyboard = keyboard
  }
  def setClipboard(clipboard: sge.utils.Clipboard): scala.Unit = {
    this.clipboard = clipboard
  }
  /* porter: renamed-member reason=universal rule=bean-detect accessors=getPrefWidth property=prefWidth source=auto-detect */
  @java.lang.Override
  override def getPrefWidth(): scala.Float = {
    return 150.toFloat
  }
  /* porter: renamed-member reason=universal rule=bean-detect accessors=getPrefHeight property=prefHeight source=auto-detect */
  @java.lang.Override
  override def getPrefHeight(): scala.Float = {
    var prefHeight: scala.Float = this.textHeight
    if (!this.style$field.background.isEmpty) {
      prefHeight = java.lang.Math.max((prefHeight + this.style$field.background.get.bottomHeight) + this.style$field.background.get.topHeight, this.style$field.background.get.minHeight)
    } else ()
    return prefHeight
  }
  /**
   * Sets text horizontal alignment (left, center or right).
   * @see Align
   */
  def setAlignment(alignment: sge.utils.Align): scala.Unit = {
    this.textHAlign = alignment
  }
  /**
   * If true, the text in this text field will be shown as bullet characters.
   * @see #setPasswordCharacter(char)
   */
  /* porter: renamed-member reason=universal rule=bean-detect component=1 from=setPasswordMode owner=com.kotcrab.vis.ui.widget.VisTextField to=passwordMode_=
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  def passwordMode_=(passwordMode: scala.Boolean): scala.Unit = {
    this.passwordMode$field = passwordMode
    this.updateDisplayText()
  }
  /* porter: renamed-member reason=universal rule=bean-detect component=1 from=isPasswordMode owner=com.kotcrab.vis.ui.widget.VisTextField to=passwordMode
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  /* porter: renamed-member reason=universal rule=bean-detect accessors=isPasswordMode/setPasswordMode property=passwordMode source=auto-detect */
  def passwordMode: scala.Boolean = {
    return this.passwordMode$field
  }
  /**
   * Sets the password character for the text field. The character must be present in the {@link BitmapFont}. Default is 149
   * (bullet).
   */
  def setPasswordCharacter(passwordCharacter: scala.Char): scala.Unit = {
    this.passwordCharacter = passwordCharacter
    if (this.passwordMode$field) {
      this.updateDisplayText()
    } else ()
  }
  def setBlinkTime(blinkTime: scala.Float): scala.Unit = {
    this.blinkTime = blinkTime
  }
  /* porter: renamed-member reason=universal rule=bean-detect accessors=isDisabled/setDisabled property=disabled source=auto-detect */
  /* porter: renamed-member reason=universal rule=bean-detect component=8 from=isDisabled owner=com.kotcrab.vis.ui.widget.VisTextField to=disabled
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  /* porter: renamed-member reason=universal rule=bean-detect component=8 from=isDisabled owner=com.kotcrab.vis.ui.widget.VisTextField to=disabled
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  /* porter: renamed-member reason=universal rule=bean-detect component=8 from=isDisabled owner=com.kotcrab.vis.ui.widget.VisTextField to=disabled
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  /* porter: renamed-member reason=universal rule=bean-detect component=8 from=isDisabled owner=com.kotcrab.vis.ui.widget.VisTextField to=disabled
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  /* porter: renamed-member reason=universal rule=bean-detect component=8 from=isDisabled owner=com.kotcrab.vis.ui.widget.VisTextField to=disabled
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  /* porter: renamed-member reason=universal rule=bean-detect component=8 from=isDisabled owner=com.kotcrab.vis.ui.widget.VisTextField to=disabled
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  /* porter: renamed-member reason=universal rule=bean-detect component=8 from=isDisabled owner=com.kotcrab.vis.ui.widget.VisTextField to=disabled
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  override def disabled: scala.Boolean = {
    return this.disabled$field
  }
  /* porter: renamed-member reason=universal rule=bean-detect component=11 from=setDisabled owner=com.kotcrab.vis.ui.widget.VisTextField to=disabled_=
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  /* porter: renamed-member reason=universal rule=bean-detect component=11 from=setDisabled owner=com.kotcrab.vis.ui.widget.VisTextField to=disabled_=
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  /* porter: renamed-member reason=universal rule=bean-detect component=11 from=setDisabled owner=com.kotcrab.vis.ui.widget.VisTextField to=disabled_=
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  /* porter: renamed-member reason=universal rule=bean-detect component=11 from=setDisabled owner=com.kotcrab.vis.ui.widget.VisTextField to=disabled_=
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  /* porter: renamed-member reason=universal rule=bean-detect component=11 from=setDisabled owner=com.kotcrab.vis.ui.widget.VisTextField to=disabled_=
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  /* porter: renamed-member reason=universal rule=bean-detect component=11 from=setDisabled owner=com.kotcrab.vis.ui.widget.VisTextField to=disabled_=
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  /* porter: renamed-member reason=universal rule=bean-detect component=11 from=setDisabled owner=com.kotcrab.vis.ui.widget.VisTextField to=disabled_=
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  /* porter: suppressed-warning reason=universal rule=suppressed-warning(orNull) annotation=@nowarn("msg=deprecated")
     — this member's body calls `.orNull` (the null-preserving unwrap at a slot that accepts null); lls deprecates `orNull` as a lint so every usage needs `@nowarn` — the same pattern sge uses at every Java interop boundary */
  @java.lang.Override
  @scala.annotation.nowarn("msg=deprecated")
  override def disabled_=(disabled: scala.Boolean): scala.Unit = {
    this.disabled$field = disabled
    if (disabled) {
      sge.visui.FocusManager.resetFocus(this.stage.orNull, this)
      this.keyRepeatTask.cancel()
    } else ()
  }
  /* porter: renamed-member reason=universal rule=bean-detect component=1 from=isReadOnly owner=com.kotcrab.vis.ui.widget.VisTextField to=readOnly
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  /* porter: renamed-member reason=universal rule=bean-detect accessors=isReadOnly/setReadOnly property=readOnly source=auto-detect */
  def readOnly: scala.Boolean = {
    return this.readOnly$field
  }
  /* porter: renamed-member reason=universal rule=bean-detect component=1 from=setReadOnly owner=com.kotcrab.vis.ui.widget.VisTextField to=readOnly_=
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  def readOnly_=(readOnly: scala.Boolean): scala.Unit = {
    this.readOnly$field = readOnly
  }
  protected[widget] def moveCursor(forward: scala.Boolean, jump: scala.Boolean): scala.Unit = {
    val limit: scala.Int = if (forward) this.text$field.length() else 0
    val charOffset: scala.Int = if (forward) 0 else -1
    scala.util.boundary { while ((if (forward) { this.cursor += 1; this.cursor } < limit else { this.cursor -= 1; this.cursor } > limit) && jump) {
      if (!this.continueCursor(this.cursor, charOffset)) {
        scala.util.boundary.break(())
      } else ()
    } }
  }
  protected[widget] def continueCursor(index: scala.Int, offset: scala.Int): scala.Boolean = {
    val c: scala.Char = this.text$field.charAt(index + offset)
    return this.isWordCharacter(c)
  }
  /** Focuses this field, field must be added to stage before this method can be called */
  /* porter: suppressed-warning reason=universal rule=suppressed-warning(orNull) annotation=@nowarn("msg=deprecated")
     — this member's body calls `.orNull` (the null-preserving unwrap at a slot that accepts null); lls deprecates `orNull` as a lint so every usage needs `@nowarn` — the same pattern sge uses at every Java interop boundary */
  @scala.annotation.nowarn("msg=deprecated")
  def focusField(): scala.Unit = {
    if (this.disabled$field) {
      return
    } else ()
    val stage: sge.scenes.scene2d.Stage = this.stage.orNull
    sge.visui.FocusManager.switchFocus(stage, this)
    this.cursorPosition = 0
    this.selectionStart$field = 0
    //make sure textOffset was updated, prevent issue when there was long text selected and it was changed to short text
    //and field was focused. Without it textOffset would stay at max value and only one last letter will be visible in field
    this.calculateOffsets()
    if (stage != null) {
      stage.setKeyboardFocus(lowlevel.Nullable(this))
    } else ()
    this.keyboard.show(null.asInstanceOf[sge.scenes.scene2d.ui.TextField])
    this.hasSelection = true
  }
  @java.lang.Override
  override def focusLost(): scala.Unit = {
    this.drawBorder = false
  }
  @java.lang.Override
  override def focusGained(): scala.Unit = {
    this.drawBorder = true
  }
  /* porter: renamed-member reason=universal rule=bean-detect accessors=isEmpty property=empty source=auto-detect */
  /* porter: renamed-member reason=universal rule=bean-detect component=1 from=isEmpty owner=com.kotcrab.vis.ui.widget.VisTextField to=empty
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  def empty: scala.Boolean = {
    return this.text$field.length() == 0
  }
  /* porter: renamed-member reason=universal rule=bean-detect accessors=isInputValid/setInputValid property=inputValid source=auto-detect */
  /* porter: renamed-member reason=universal rule=bean-detect component=1 from=isInputValid owner=com.kotcrab.vis.ui.widget.VisTextField to=inputValid
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  def inputValid: scala.Boolean = {
    return this.inputValid$field
  }
  /* porter: renamed-member reason=universal rule=bean-detect component=1 from=setInputValid owner=com.kotcrab.vis.ui.widget.VisTextField to=inputValid_=
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  def inputValid_=(inputValid: scala.Boolean): scala.Unit = {
    this.inputValid$field = inputValid
  }
  /* porter: renamed-member reason=universal rule=bean-detect accessors=isFocusBorderEnabled/setFocusBorderEnabled property=focusBorderEnabled source=auto-detect */
  /* porter: renamed-member reason=universal rule=bean-detect component=6 from=isFocusBorderEnabled owner=com.kotcrab.vis.ui.widget.VisTextField to=focusBorderEnabled
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  /* porter: renamed-member reason=universal rule=bean-detect component=6 from=isFocusBorderEnabled owner=com.kotcrab.vis.ui.widget.VisTextField to=focusBorderEnabled
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  /* porter: renamed-member reason=universal rule=bean-detect component=6 from=isFocusBorderEnabled owner=com.kotcrab.vis.ui.widget.VisTextField to=focusBorderEnabled
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  /* porter: renamed-member reason=universal rule=bean-detect component=6 from=isFocusBorderEnabled owner=com.kotcrab.vis.ui.widget.VisTextField to=focusBorderEnabled
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  /* porter: renamed-member reason=universal rule=bean-detect component=6 from=isFocusBorderEnabled owner=com.kotcrab.vis.ui.widget.VisTextField to=focusBorderEnabled
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  /* porter: renamed-member reason=universal rule=bean-detect component=6 from=isFocusBorderEnabled owner=com.kotcrab.vis.ui.widget.VisTextField to=focusBorderEnabled
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  @java.lang.Override
  override def focusBorderEnabled: scala.Boolean = {
    return this.focusBorderEnabled$field
  }
  /* porter: renamed-member reason=universal rule=bean-detect component=6 from=setFocusBorderEnabled owner=com.kotcrab.vis.ui.widget.VisTextField to=focusBorderEnabled_=
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  /* porter: renamed-member reason=universal rule=bean-detect component=6 from=setFocusBorderEnabled owner=com.kotcrab.vis.ui.widget.VisTextField to=focusBorderEnabled_=
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  /* porter: renamed-member reason=universal rule=bean-detect component=6 from=setFocusBorderEnabled owner=com.kotcrab.vis.ui.widget.VisTextField to=focusBorderEnabled_=
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  /* porter: renamed-member reason=universal rule=bean-detect component=6 from=setFocusBorderEnabled owner=com.kotcrab.vis.ui.widget.VisTextField to=focusBorderEnabled_=
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  /* porter: renamed-member reason=universal rule=bean-detect component=6 from=setFocusBorderEnabled owner=com.kotcrab.vis.ui.widget.VisTextField to=focusBorderEnabled_=
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  /* porter: renamed-member reason=universal rule=bean-detect component=6 from=setFocusBorderEnabled owner=com.kotcrab.vis.ui.widget.VisTextField to=focusBorderEnabled_=
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  @java.lang.Override
  override def focusBorderEnabled_=(focusBorderEnabled: scala.Boolean): scala.Unit = {
    this.focusBorderEnabled$field = focusBorderEnabled
  }
  /** @see #setIgnoreEqualsTextChange(boolean) */
  /* porter: renamed-member reason=universal rule=bean-detect accessors=isIgnoreEqualsTextChange/setIgnoreEqualsTextChange property=ignoreEqualsTextChange source=auto-detect */
  /* porter: renamed-member reason=universal rule=bean-detect component=1 from=isIgnoreEqualsTextChange owner=com.kotcrab.vis.ui.widget.VisTextField to=ignoreEqualsTextChange
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  def ignoreEqualsTextChange: scala.Boolean = {
    return this.ignoreEqualsTextChange$field
  }
  /**
   * Allows to control whether change event is sent when text field's text is changed to same same as was it before.
   * Eg. current text field is 'abc' and {@link #setText(String)} is called it with 'abc' again.
   * @param ignoreEqualsTextChange if true then setting text to the same as it was before will NOT fire change event.
   * Default is true however it is false default {@link VisValidatableTextField} to prevent form refreshment issues -
   * see issue VisEditor#165
   */
  /* porter: renamed-member reason=universal rule=bean-detect component=1 from=setIgnoreEqualsTextChange owner=com.kotcrab.vis.ui.widget.VisTextField to=ignoreEqualsTextChange_=
     — the port renames this member by policy, and every declaration of the override component moves with it — java resolved each reference statically, so re-pointing the symbol re-points exactly the references java meant */
  def ignoreEqualsTextChange_=(ignoreEqualsTextChange: scala.Boolean): scala.Unit = {
    this.ignoreEqualsTextChange$field = ignoreEqualsTextChange
  }
  private[widget] class KeyRepeatTask private[widget] (using sge.Sge) extends sge.utils.Timer.Task {
    private[widget] var keycode: scala.Int = 0
    @java.lang.Override
    override def run(): scala.Unit = {
      VisTextField.this.inputListener.keyDown(null, this.keycode)
    }
  }
  /** Basic input listener for the text field */
  class TextFieldClickListener(using sge.Sge) extends sge.scenes.scene2d.utils.ClickListener {
    @java.lang.Override
    override def clicked(event: sge.scenes.scene2d.InputEvent, x: scala.Float, y: scala.Float): scala.Unit = {
      val count: scala.Int = this.tapCount % 4
      if (count == 0) {
        VisTextField.this.clearSelection()
      } else ()
      if (count == 2) {
        val array: scala.Array[scala.Int] = VisTextField.this.wordUnderCursor(x)
        VisTextField.this.setSelection(array(0), array(1))
      } else ()
      if (count == 3) {
        VisTextField.this.selectAll()
      } else ()
    }
    /* porter: suppressed-warning reason=universal rule=suppressed-warning(orNull) annotation=@nowarn("msg=deprecated")
       — this member's body calls `.orNull` (the null-preserving unwrap at a slot that accepts null); lls deprecates `orNull` as a lint so every usage needs `@nowarn` — the same pattern sge uses at every Java interop boundary */
    @java.lang.Override
    @scala.annotation.nowarn("msg=deprecated")
    override def touchDown(event: sge.scenes.scene2d.InputEvent, x: scala.Float, y: scala.Float, pointer: scala.Int, button: scala.Int): scala.Boolean = {
      if (!super.touchDown(event, x, y, pointer, button)) {
        return false
      } else ()
      if ((pointer == 0) && (button != 0)) {
        return false
      } else ()
      if (VisTextField.this.disabled$field) {
        return true
      } else ()
      val stage: sge.scenes.scene2d.Stage = VisTextField.this.stage.orNull
      sge.visui.FocusManager.switchFocus(stage, VisTextField.this)
      this.setCursorPosition(x, y)
      VisTextField.this.selectionStart$field = VisTextField.this.cursor
      if (stage != null) {
        stage.setKeyboardFocus(lowlevel.Nullable(VisTextField.this))
      } else ()
      if (VisTextField.this.readOnly$field == false) {
        VisTextField.this.keyboard.show(null.asInstanceOf[sge.scenes.scene2d.ui.TextField])
      } else ()
      VisTextField.this.hasSelection = true
      return true
    }
    @java.lang.Override
    override def touchDragged(event: sge.scenes.scene2d.InputEvent, x: scala.Float, y: scala.Float, pointer: scala.Int): scala.Unit = {
      super.touchDragged(event, x, y, pointer)
      this.setCursorPosition(x, y)
    }
    @java.lang.Override
    override def touchUp(event: sge.scenes.scene2d.InputEvent, x: scala.Float, y: scala.Float, pointer: scala.Int, button: scala.Int): scala.Unit = {
      if (VisTextField.this.selectionStart$field == VisTextField.this.cursor) {
        VisTextField.this.hasSelection = false
      } else ()
      super.touchUp(event, x, y, pointer, button)
    }
    protected[widget] def setCursorPosition(x: scala.Float, y: scala.Float): scala.Unit = {
      VisTextField.this.lastBlink = 0
      VisTextField.this.cursorOn = false
      VisTextField.this.cursor = java.lang.Math.min(VisTextField.this.letterUnderCursor(x), VisTextField.this.text$field.length())
    }
    protected[widget] def goHome(jump: scala.Boolean): scala.Unit = {
      VisTextField.this.cursor = 0
    }
    protected[widget] def goEnd(jump: scala.Boolean): scala.Unit = {
      VisTextField.this.cursor = VisTextField.this.text$field.length()
    }
    /* porter: suppressed-warning reason=universal rule=suppressed-warning(orNull) annotation=@nowarn("msg=deprecated")
       — this member's body calls `.orNull` (the null-preserving unwrap at a slot that accepts null); lls deprecates `orNull` as a lint so every usage needs `@nowarn` — the same pattern sge uses at every Java interop boundary */
    @java.lang.Override
    @scala.annotation.nowarn("msg=deprecated")
    override def keyDown(event: sge.scenes.scene2d.InputEvent, keycode: scala.Int): scala.Boolean = {
      if (VisTextField.this.disabled$field) {
        return false
      } else ()
      VisTextField.this.lastBlink = 0
      VisTextField.this.cursorOn = false
      val stage: sge.scenes.scene2d.Stage = VisTextField.this.stage.orNull
      if ((stage == null) || (stage.getKeyboardFocus.get ne VisTextField.this)) {
        return false
      } else ()
      if (VisTextField.this.drawBorder == false) {
        return false
      } else ()
      var repeat: scala.Boolean = false
      val ctrl: scala.Boolean = sge.scenes.scene2d.utils.UIUtils.ctrl()
      val jump: scala.Boolean = ctrl && (!VisTextField.this.passwordMode$field)
      if (ctrl) {
        if ((keycode == sge.Input.Keys.V) && (VisTextField.this.readOnly$field == false)) {
          VisTextField.this.paste(VisTextField.this.clipboard.contents, true)
          repeat = true
        } else ()
        if ((keycode == sge.Input.Keys.C) || (keycode == sge.Input.Keys.INSERT)) {
          VisTextField.this.copy()
          return true
        } else ()
        if ((keycode == sge.Input.Keys.X) && (VisTextField.this.readOnly$field == false)) {
          VisTextField.this.cut(true)
          return true
        } else ()
        if (keycode == sge.Input.Keys.A) {
          VisTextField.this.selectAll()
          return true
        } else ()
        if ((keycode == sge.Input.Keys.Z) && (VisTextField.this.readOnly$field == false)) {
          val oldText: java.lang.String = VisTextField.this.text$field
          val oldCursorPos: scala.Int = VisTextField.this.cursorPosition
          VisTextField.this.text = VisTextField.this.undoText
          VisTextField.this.cursorPosition = (sge.math.MathUtils.clamp: (scala.Int, scala.Int, scala.Int) => scala.Int)(VisTextField.this.cursor, 0, VisTextField.this.undoText.length())
          VisTextField.this.undoText = oldText
          VisTextField.this.undoCursorPos = oldCursorPos
          VisTextField.this.updateDisplayText()
          return true
        } else ()
      } else ()
      if (sge.scenes.scene2d.utils.UIUtils.shift()) {
        if ((keycode == sge.Input.Keys.INSERT) && (VisTextField.this.readOnly$field == false)) {
          VisTextField.this.paste(VisTextField.this.clipboard.contents, true)
        } else ()
        if ((keycode == sge.Input.Keys.FORWARD_DEL) && (VisTextField.this.readOnly$field == false)) {
          VisTextField.this.cut(true)
        } else ()
        scala.util.boundary { (lbl$19: scala.util.boundary.Label[scala.Unit]) ?=> {
          val temp: scala.Int = VisTextField.this.cursor
          scala.util.boundary { (lbl$20: scala.util.boundary.Label[scala.Unit]) ?=> {
            if (keycode == sge.Input.Keys.LEFT) {
              VisTextField.this.moveCursor(false, jump)
              repeat = true
              scala.util.boundary.break(())(using lbl$20)
            } else ()
            if (keycode == sge.Input.Keys.RIGHT) {
              VisTextField.this.moveCursor(true, jump)
              repeat = true
              scala.util.boundary.break(())(using lbl$20)
            } else ()
            if (keycode == sge.Input.Keys.HOME) {
              this.goHome(jump)
              scala.util.boundary.break(())(using lbl$20)
            } else ()
            if (keycode == sge.Input.Keys.END) {
              this.goEnd(jump)
              scala.util.boundary.break(())(using lbl$20)
            } else ()
            scala.util.boundary.break(())(using lbl$19)
          } }
          if (!VisTextField.this.hasSelection) {
            VisTextField.this.selectionStart$field = temp
            VisTextField.this.hasSelection = true
          } else ()
        } }
      } else {
        // Cursor movement or other keys (kills selection).
        if (keycode == sge.Input.Keys.LEFT) {
          VisTextField.this.moveCursor(false, jump)
          VisTextField.this.clearSelection()
          repeat = true
        } else ()
        if (keycode == sge.Input.Keys.RIGHT) {
          VisTextField.this.moveCursor(true, jump)
          VisTextField.this.clearSelection()
          repeat = true
        } else ()
        if (keycode == sge.Input.Keys.HOME) {
          this.goHome(jump)
          VisTextField.this.clearSelection()
        } else ()
        if (keycode == sge.Input.Keys.END) {
          this.goEnd(jump)
          VisTextField.this.clearSelection()
        } else ()
      }
      VisTextField.this.cursor = (sge.math.MathUtils.clamp: (scala.Int, scala.Int, scala.Int) => scala.Int)(VisTextField.this.cursor, 0, VisTextField.this.text$field.length())
      if (repeat) {
        this.scheduleKeyRepeatTask(keycode)
      } else ()
      return true
    }
    protected[widget] def scheduleKeyRepeatTask(keycode: scala.Int): scala.Unit = {
      if ((!VisTextField.this.keyRepeatTask.scheduled) || (VisTextField.this.keyRepeatTask.keycode != keycode)) {
        VisTextField.this.keyRepeatTask.keycode = keycode
        VisTextField.this.keyRepeatTask.cancel()
        if (scala.Predef.summon[sge.Sge].input.isKeyPressed(VisTextField.this.keyRepeatTask.keycode)) {
          //issue #179
          sge.utils.Timer.schedule(VisTextField.this.keyRepeatTask, VisTextField.keyRepeatInitialTime, VisTextField.keyRepeatTime)
        } else ()
      } else ()
    }
    @java.lang.Override
    override def keyUp(event: sge.scenes.scene2d.InputEvent, keycode: scala.Int): scala.Boolean = {
      if (VisTextField.this.disabled$field) {
        return false
      } else ()
      VisTextField.this.keyRepeatTask.cancel()
      return true
    }
    /* porter: suppressed-warning reason=universal rule=suppressed-warning(orNull) annotation=@nowarn("msg=deprecated")
       — this member's body calls `.orNull` (the null-preserving unwrap at a slot that accepts null); lls deprecates `orNull` as a lint so every usage needs `@nowarn` — the same pattern sge uses at every Java interop boundary */
    @java.lang.Override
    @scala.annotation.nowarn("msg=deprecated")
    override def keyTyped(event: sge.scenes.scene2d.InputEvent, character: scala.Char): scala.Boolean = {
      if (VisTextField.this.disabled$field || VisTextField.this.readOnly$field) {
        return false
      } else ()
      // Disallow "typing" most ASCII control characters, which would show up as a space when onlyFontChars is true.
      character match {
        case VisTextField.BACKSPACE | VisTextField.TAB | VisTextField.ENTER_ANDROID | VisTextField.ENTER_DESKTOP => {
          ()
        }
        case _ => {
          if (character < 32) {
            return false
          } else ()
        }
      }
      val stage: sge.scenes.scene2d.Stage = VisTextField.this.stage.orNull
      if ((stage == null) || (stage.getKeyboardFocus.get ne VisTextField.this)) {
        return false
      } else ()
      if (sge.scenes.scene2d.utils.UIUtils.isMac && scala.Predef.summon[sge.Sge].input.isKeyPressed(sge.Input.Keys.SYM)) {
        return true
      } else ()
      if (VisTextField.this.focusTraversal && ((character == VisTextField.TAB) || ((character == VisTextField.ENTER_ANDROID) && VisTextField.this.enterKeyFocusTraversal))) {
        VisTextField.this.next(sge.scenes.scene2d.utils.UIUtils.shift())
      } else {
        val delete: scala.Boolean = character == VisTextField.DELETE
        val backspace: scala.Boolean = character == VisTextField.BACKSPACE
        val enter: scala.Boolean = (character == VisTextField.ENTER_DESKTOP) || (character == VisTextField.ENTER_ANDROID)
        val add: scala.Boolean = if (enter) VisTextField.this.writeEnters else (!VisTextField.this.onlyFontChars) || VisTextField.this.style$field.font.data.hasGlyph(character)
        val remove: scala.Boolean = backspace || delete
        if (add || remove) {
          val oldText: java.lang.String = VisTextField.this.text$field
          val oldCursor: scala.Int = VisTextField.this.cursor
          if (VisTextField.this.hasSelection) {
            VisTextField.this.cursor = VisTextField.this.delete(false)
          } else {
            if (backspace && (VisTextField.this.cursor > 0)) {
              VisTextField.this.text$field = VisTextField.this.text$field.substring(0, VisTextField.this.cursor - 1) + VisTextField.this.text$field.substring({ val $prev = VisTextField.this.cursor; VisTextField.this.cursor -= 1; $prev })
              VisTextField.this.renderOffset = 0.toFloat
            } else ()
            if (delete && (VisTextField.this.cursor < VisTextField.this.text$field.length())) {
              VisTextField.this.text$field = VisTextField.this.text$field.substring(0, VisTextField.this.cursor) + VisTextField.this.text$field.substring(VisTextField.this.cursor + 1)
            } else ()
          }
          if (add && (!remove)) {
            // Character may be added to the text.
            if (((!enter) && (VisTextField.this.filter != null)) && (!VisTextField.this.filter.acceptChar(VisTextField.this, character))) {
              return true
            } else ()
            if (!VisTextField.this.withinMaxLength(VisTextField.this.text$field.length())) {
              return true
            } else ()
            val insertion: java.lang.String = if (enter) "\n" else java.lang.String.valueOf(character)
            VisTextField.this.text$field = VisTextField.this.insert({ val $prev = VisTextField.this.cursor; VisTextField.this.cursor += 1; $prev }, insertion, VisTextField.this.text$field)
          } else ()
          if (VisTextField.this.changeText(oldText, VisTextField.this.text$field)) {
            val time: scala.Long = java.lang.System.currentTimeMillis()
            if ((time - 750) > VisTextField.this.lastChangeTime) {
              VisTextField.this.undoText = oldText
              VisTextField.this.undoCursorPos = VisTextField.this.cursorPosition - 1
            } else ()
            VisTextField.this.lastChangeTime = time
          } else {
            VisTextField.this.cursor = oldCursor
          }
          VisTextField.this.updateDisplayText()
        } else ()
      }
      if (VisTextField.this.listener != null) {
        VisTextField.this.listener.keyTyped(VisTextField.this, character)
      } else ()
      return true
    }
  }
  object TextFieldClickListener {
    /* porter: forced-class-init reason=universal rule=class-init-trigger(§4.4) forces=sge.scenes.scene2d.utils.ClickListener trigger=subclass-init
       — initialising this type initialises `sge.scenes.scene2d.utils.ClickListener` first (JLS 12.4.1 item 7), which runs that type's class initialiser; a scala object's initialisation reaches no other object */
    val _ = sge.scenes.scene2d.utils.ClickListener
    export sge.scenes.scene2d.utils.ClickListener.{tmpCoords => _, *}
  }
}
object VisTextField {
  /* porter: forced-class-init reason=universal rule=class-init-trigger(§4.4) forces=sge.scenes.scene2d.Actor trigger=subclass-init
     — initialising this type initialises `sge.scenes.scene2d.Actor` first (JLS 12.4.1 item 7), which runs that type's class initialiser; a scala object's initialisation reaches no other object */
  val _ = sge.scenes.scene2d.Actor
  export sge.scenes.scene2d.ui.Widget.{BACKSPACE => _, BULLET => _, DELETE => _, ENTER_ANDROID => _, ENTER_DESKTOP => _, TAB => _, TextFieldFilter => _, TextFieldListener => _, VisTextFieldStyle => _, keyRepeatInitialTime => _, keyRepeatTime => _, tmp1 => _, tmp2 => _, tmp3 => _, *}
  private final val BACKSPACE: scala.Char = 8.asInstanceOf[scala.Char]
  /* porter: widened-visibility reason=universal rule=visibility(§8.7) cause=protected-static from=protected to=public
     — java grants a cross-package subclass access to this static; scala's companion object is not a supertype of anything, so no qualified form can express it and the port widens instead */
  inline val ENTER_DESKTOP = '\r'
  /* porter: widened-visibility reason=universal rule=visibility(§8.7) cause=protected-static from=protected to=public
     — java grants a cross-package subclass access to this static; scala's companion object is not a supertype of anything, so no qualified form can express it and the port widens instead */
  inline val ENTER_ANDROID = '\n'
  private inline val TAB = '\t'
  private final val DELETE: scala.Char = 127.asInstanceOf[scala.Char]
  private final val BULLET: scala.Char = 8226.asInstanceOf[scala.Char]
  private final val tmp1: sge.math.Vector2 = new sge.math.Vector2()
  private final val tmp2: sge.math.Vector2 = new sge.math.Vector2()
  private final val tmp3: sge.math.Vector2 = new sge.math.Vector2()
  var keyRepeatInitialTime: scala.Float = 0.4f
  /** Repeat times for keys handled by {@link InputListener#keyDown(InputEvent, int)} such as navigation arrows */
  var keyRepeatTime: scala.Float = 0.04f
  /* porter: funnelled-ctor reason=universal rule=ctor-funnel constructors=3 disambiguator=none escapes=0 notSlot=- primary=() primaryVis=as-declared shape=no-arg-root slots=- superArgs=0
     — java lets every constructor pick its own `super(...)`; scala lets only the PRIMARY reach super, so one is nominated, its super arguments become the `extends` clause and its body becomes the class body — which runs on every construction path, `escapes` of which java did not run it on */
  class VisTextFieldStyle extends sge.scenes.scene2d.ui.TextField.TextFieldStyle {
    var focusBorder: sge.scenes.scene2d.utils.Drawable = scala.compiletime.uninitialized
    var errorBorder: sge.scenes.scene2d.utils.Drawable = scala.compiletime.uninitialized
    var backgroundOver: sge.scenes.scene2d.utils.Drawable = scala.compiletime.uninitialized
    def this(font: sge.graphics.g2d.BitmapFont, fontColor: sge.graphics.Color, cursor: sge.scenes.scene2d.utils.Drawable, selection: sge.scenes.scene2d.utils.Drawable, background: sge.scenes.scene2d.utils.Drawable) = {
      this()
      this.font = font
      this.fontColor = fontColor
      this.cursor = lowlevel.Nullable(cursor)
      this.selection = lowlevel.Nullable(selection)
      this.background = lowlevel.Nullable(background)
    }
    /* porter: suppressed-warning reason=universal rule=ctor-replay-orNull-suppression annotation=@nowarn("msg=deprecated")
       — this constructor's rendered statements (delegation arguments, replayed parent statements, own body) call `.orNull` (the null-preserving unwrap at a slot that accepts null); lls deprecates `orNull` as a lint */
    @scala.annotation.nowarn("msg=deprecated")
    def this(style: sge.visui.widget.VisTextField.VisTextFieldStyle) = {
      this()
      this.font = style.font
      if (style.fontColor != null) {
        this.fontColor = new sge.graphics.Color(style.fontColor)
      } else ()
      if (!style.focusedFontColor.isEmpty) {
        this.focusedFontColor = lowlevel.Nullable(new sge.graphics.Color(style.focusedFontColor.orNull))
      } else ()
      if (!style.disabledFontColor.isEmpty) {
        this.disabledFontColor = lowlevel.Nullable(new sge.graphics.Color(style.disabledFontColor.orNull))
      } else ()
      this.background = style.background
      this.focusedBackground = style.focusedBackground
      this.disabledBackground = style.disabledBackground
      this.cursor = style.cursor
      this.selection = style.selection
      this.messageFont = style.messageFont
      if (!style.messageFontColor.isEmpty) {
        this.messageFontColor = lowlevel.Nullable(new sge.graphics.Color(style.messageFontColor.orNull))
      } else ()
      this.focusBorder = style.focusBorder
      this.errorBorder = style.errorBorder
      this.backgroundOver = style.backgroundOver
    }
  }
  /**
   * Interface for listening to typed characters.
   * @author mzechner
   */
  trait TextFieldListener {
    def keyTyped(textField: VisTextField, c: scala.Char): scala.Unit
  }
  /**
   * Interface for filtering characters entered into the text field.
   * @author mzechner
   */
  trait TextFieldFilter {
    def acceptChar(textField: VisTextField, c: scala.Char): scala.Boolean
  }
  object TextFieldFilter {
    class DigitsOnlyFilter extends sge.visui.widget.VisTextField.TextFieldFilter {
      @java.lang.Override
      override def acceptChar(textField: VisTextField, c: scala.Char): scala.Boolean = {
        return java.lang.Character.isDigit(c)
      }
    }
    object DigitsOnlyFilter {
      export sge.visui.widget.VisTextField.TextFieldFilter.*
    }
  }
}