package balticporter.sbtgen

import java.nio.file.{Files, Path}

/** Emits the sbt 2.0 project skeleton for a translated module (PLAN.md §10).
  * Byte-deterministic; everything generated carries the do-not-edit header.
  */
object SbtGen:

  final case class Dep(org: String, artifact: String, version: String):
    def sbtString: String = s""""$org" % "$artifact" % "$version""""

  final case class ProjectSpec(
      moduleName: String,
      organization: String,
      scalaVersion: String,
      sbtVersion: String,
      deps: List[Dep],
      testDeps: List[Dep] = Nil,
      testFramework: Option[String] = None, // e.g. com.novocode.junit.JUnitFramework fingerprint line
      engineFingerprint: String,
  )

  /** Where a port's GENERATED Scala goes: `src_managed/{main,test}/scala`, never `src/`.
    *
    * `src/` is for the human-written part of a port — the hand-written shims and overrides a
    * library needs and the engine cannot derive. Everything the engine emits is a build product:
    * reproducible from the Java sources plus the manifest, invalidated by every engine change, and
    * therefore not something to commit or to diff by hand. Keeping the two in one tree makes it
    * impossible to tell, from a `git status`, whether a change is a decision or an artefact.
    *
    * `src_managed` is sbt's own name for exactly this (its default lives under `target/`); we lift
    * it to the project root only so a porter can read the output without digging through
    * `target/scala-3.x/`. [[emit]] wires it into `Compile/Test sourceGenerators` and into
    * `cleanFiles`, and writes the `.gitignore` — so `clean` removes it and git never sees it. */
  def managedDir(root: Path, config: String): Path =
    root.resolve("src_managed").resolve(config).resolve("scala")
  def managedMain(root: Path): Path = managedDir(root, "main")
  def managedTest(root: Path): Path = managedDir(root, "test")

  def emit(root: Path, spec: ProjectSpec): Unit =
    Files.createDirectories(root.resolve("project"))
    Files.createDirectories(managedMain(root))
    Files.writeString(
      root.resolve("project/build.properties"),
      s"sbt.version=${spec.sbtVersion}\n",
    )
    Files.writeString(root.resolve(".gitignore"), gitignore)
    if spec.testDeps.nonEmpty then Files.createDirectories(managedTest(root))
    val deps =
      if spec.deps.isEmpty then ""
      else
        spec.deps
          .map(d => s"  ${d.sbtString},")
          .mkString("\nlibraryDependencies ++= Seq(\n", "\n", "\n)\n")
    val testDeps =
      if spec.testDeps.isEmpty then ""
      else
        spec.testDeps
          .map(d => s"  ${d.sbtString} % Test,")
          .mkString("\nlibraryDependencies ++= Seq(\n", "\n", "\n)\n")
    Files.writeString(
      root.resolve("build.sbt"),
      s"""// Generated by Baltic Porter (${spec.engineFingerprint}) — DO NOT EDIT; regenerate instead.
         |
         |name := "${spec.moduleName}"
         |organization := "${spec.organization}"
         |scalaVersion := "${spec.scalaVersion}"
         |
         |// upstream suites mutate shared registries — run serially, like Maven did
         |Test / parallelExecution := false
         |
         |// upstream code (DecimalFormat/SimpleDateFormat) is locale-sensitive and its
         |// CI runs English — the faithful translation inherits that assumption
         |Test / fork := true
         |Test / javaOptions ++= Seq("-Duser.language=en", "-Duser.country=US")
         |$managedSources
         |$deps$testDeps""".stripMargin,
    )

  /** `.gitignore` for a port: the emitted Scala is a build product, not source. */
  val gitignore: String =
    """# Generated by Baltic Porter — DO NOT EDIT; regenerate instead.
      |# Emitted Scala is a build product: reproducible from the Java sources plus the
      |# manifest, and invalidated by every engine change. Only src/ is committed.
      |src_managed/
      |target/
      |""".stripMargin

  /** The sbt settings that make `src_managed/` a real managed-source root.
    *
    * A `sourceGenerator` that merely LISTS the directory is the idiomatic way to register sources
    * some other process wrote: sbt re-globs on every compile, so re-running the migration is picked
    * up without a reload, and the files still count as *managed* (excluded from `package-src`,
    * skipped by source formatters). `cleanFiles` is what makes `clean` delete them — sbt only
    * cleans `target/` by default, and the whole point of lifting `src_managed` to the project root
    * is that it is NOT under `target/`. */
  val managedSources: String =
    """
      |// Emitted Scala lives in src_managed/, is gitignored, and `clean` deletes it.
      |Compile / sourceGenerators += Def.task {
      |  ((baseDirectory.value / "src_managed" / "main" / "scala") ** "*.scala").get()
      |}.taskValue
      |Test / sourceGenerators += Def.task {
      |  ((baseDirectory.value / "src_managed" / "test" / "scala") ** "*.scala").get()
      |}.taskValue
      |cleanFiles += baseDirectory.value / "src_managed"
      |""".stripMargin
