package balticporter.sbtgen

import java.nio.file.{Files, Path}

/** Emits the sbt 2.0 project skeleton for a translated module (PLAN.md §10).
  * Byte-deterministic; everything generated carries the do-not-edit header.
  */
object SbtGen:

  final case class Dep(org: String, artifact: String, version: String):
    def sbtString: String = s""""$org" % "$artifact" % "$version""""

  final case class ProjectSpec(
      moduleName: String,
      organization: String,
      scalaVersion: String,
      sbtVersion: String,
      deps: List[Dep],
      testDeps: List[Dep] = Nil,
      testFramework: Option[String] = None, // e.g. com.novocode.junit.JUnitFramework fingerprint line
      engineFingerprint: String,
  )

  def emit(root: Path, spec: ProjectSpec): Unit =
    Files.createDirectories(root.resolve("project"))
    Files.createDirectories(root.resolve("src/main/scala"))
    Files.writeString(
      root.resolve("project/build.properties"),
      s"sbt.version=${spec.sbtVersion}\n",
    )
    if spec.testDeps.nonEmpty then Files.createDirectories(root.resolve("src/test/scala"))
    val deps =
      if spec.deps.isEmpty then ""
      else
        spec.deps
          .map(d => s"  ${d.sbtString},")
          .mkString("\nlibraryDependencies ++= Seq(\n", "\n", "\n)\n")
    val testDeps =
      if spec.testDeps.isEmpty then ""
      else
        spec.testDeps
          .map(d => s"  ${d.sbtString} % Test,")
          .mkString("\nlibraryDependencies ++= Seq(\n", "\n", "\n)\n")
    Files.writeString(
      root.resolve("build.sbt"),
      s"""// Generated by Baltic Porter (${spec.engineFingerprint}) — DO NOT EDIT; regenerate instead.
         |
         |name := "${spec.moduleName}"
         |organization := "${spec.organization}"
         |scalaVersion := "${spec.scalaVersion}"
         |
         |// upstream suites mutate shared registries — run serially, like Maven did
         |Test / parallelExecution := false
         |$deps$testDeps""".stripMargin,
    )
