package com.badlogic.gdx.utils

class BitsTest extends balticporter.runtime.PortedSuite {
  testCase("testHashcodeAndEquals", {
    val b1: com.badlogic.gdx.utils.Bits = new com.badlogic.gdx.utils.Bits()
    val b2: com.badlogic.gdx.utils.Bits = new com.badlogic.gdx.utils.Bits()
    b1.set(1)
    b2.set(1)
    balticporter.runtime.Asserts.assertEquals(b1.hashCode(), b2.hashCode())
    balticporter.runtime.Asserts.assertTrue(b1.equals(b2))
    b2.set(420)
    b2.clear(420)
    balticporter.runtime.Asserts.assertEquals(b1.hashCode(), b2.hashCode())
    balticporter.runtime.Asserts.assertTrue(b1.equals(b2))
    b1.set(810)
    b1.clear(810)
    balticporter.runtime.Asserts.assertEquals(b1.hashCode(), b2.hashCode())
    balticporter.runtime.Asserts.assertTrue(b1.equals(b2))
  })
  testCase("testXor", {
    val b1: com.badlogic.gdx.utils.Bits = new com.badlogic.gdx.utils.Bits()
    val b2: com.badlogic.gdx.utils.Bits = new com.badlogic.gdx.utils.Bits()
    b2.set(200)
    b1.xor(b2)
    balticporter.runtime.Asserts.assertTrue(b1.get(200))
    b1.set(1024)
    b2.xor(b1)
    balticporter.runtime.Asserts.assertTrue(b2.get(1024))
  })
  testCase("testOr", {
    val b1: com.badlogic.gdx.utils.Bits = new com.badlogic.gdx.utils.Bits()
    val b2: com.badlogic.gdx.utils.Bits = new com.badlogic.gdx.utils.Bits()
    b2.set(200)
    b1.or(b2)
    balticporter.runtime.Asserts.assertTrue(b1.get(200))
    b1.set(1024)
    b2.or(b1)
    balticporter.runtime.Asserts.assertTrue(b2.get(1024))
  })
  testCase("testAnd", {
    val b1: com.badlogic.gdx.utils.Bits = new com.badlogic.gdx.utils.Bits()
    val b2: com.badlogic.gdx.utils.Bits = new com.badlogic.gdx.utils.Bits()
    b2.set(200)
    b2.and(b1)
    balticporter.runtime.Asserts.assertFalse(b2.get(200))
    b1.set(400)
    b1.and(b2)
    balticporter.runtime.Asserts.assertFalse(b1.get(400))
  })
  testCase("testCopyConstructor", {
    val b1: com.badlogic.gdx.utils.Bits = new com.badlogic.gdx.utils.Bits()
    b1.set(50)
    b1.set(100)
    b1.set(150)
    val b2: com.badlogic.gdx.utils.Bits = new com.badlogic.gdx.utils.Bits(b1)
    balticporter.runtime.Asserts.assertTrue(b1 != b2)
    balticporter.runtime.Asserts.assertTrue(b1.containsAll(b2))
    balticporter.runtime.Asserts.assertTrue(b2.containsAll(b1))
    balticporter.runtime.Asserts.assertTrue(b1.equals(b2))
  })
}