package com.badlogic.gdx.utils

class CharArrayTest extends balticporter.runtime.PortedSuite {
  testCase("constructorTest", {
    val array1: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    balticporter.runtime.Asserts.assertEquals(0, array1.size)
    balticporter.runtime.Asserts.assertTrue(array1.ordered)
    val array2: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray(100)
    balticporter.runtime.Asserts.assertEquals(0, array2.size)
    balticporter.runtime.Asserts.assertEquals(100, array2.capacity())
    balticporter.runtime.Asserts.assertTrue(array2.ordered)
    val array3: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray(false, 50)
    balticporter.runtime.Asserts.assertEquals(0, array3.size)
    balticporter.runtime.Asserts.assertEquals(50, array3.capacity())
    balticporter.runtime.Asserts.assertFalse(array3.ordered)
    val array4: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    array4.add('a')
    array4.add('b')
    val array5: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray(array4)
    balticporter.runtime.Asserts.assertEquals(2, array5.size)
    balticporter.runtime.Asserts.assertEquals('a', array5.get(0))
    balticporter.runtime.Asserts.assertEquals('b', array5.get(1))
    val chars: scala.Array[scala.Char] = scala.Array[scala.Char]('x', 'y', 'z')
    val array6: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray(chars)
    balticporter.runtime.Asserts.assertEquals(3, array6.size)
    balticporter.runtime.Asserts.assertEquals('x', array6.get(0))
    balticporter.runtime.Asserts.assertEquals('z', array6.get(2))
    val array7: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray(true, chars, 1, 2)
    balticporter.runtime.Asserts.assertEquals(2, array7.size)
    balticporter.runtime.Asserts.assertEquals('y', array7.get(0))
    balticporter.runtime.Asserts.assertEquals('z', array7.get(1))
    val array8: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray("hello")
    balticporter.runtime.Asserts.assertEquals(5, array8.size)
    balticporter.runtime.Asserts.assertEquals("hello", array8.toString())
    val sb: java.lang.StringBuilder = new java.lang.StringBuilder("world")
    val array9: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray(sb)
    balticporter.runtime.Asserts.assertEquals(5, array9.size)
    balticporter.runtime.Asserts.assertEquals("world", array9.toString())
  })
  testCase("addTest", {
    val array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    array.add('a')
    balticporter.runtime.Asserts.assertEquals(1, array.size)
    balticporter.runtime.Asserts.assertEquals('a', array.get(0))
    array.add('b', 'c')
    balticporter.runtime.Asserts.assertEquals(3, array.size)
    balticporter.runtime.Asserts.assertEquals('b', array.get(1))
    balticporter.runtime.Asserts.assertEquals('c', array.get(2))
    array.add('d', 'e', 'f')
    balticporter.runtime.Asserts.assertEquals(6, array.size)
    balticporter.runtime.Asserts.assertEquals('f', array.get(5))
    array.add('g', 'h', 'i', 'j')
    balticporter.runtime.Asserts.assertEquals(10, array.size)
    balticporter.runtime.Asserts.assertEquals('j', array.get(9))
    val array2: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    array2.add('k')
    array2.add('l')
    array.addAll(array2)
    balticporter.runtime.Asserts.assertEquals(12, array.size)
    balticporter.runtime.Asserts.assertEquals('k', array.get(10))
    balticporter.runtime.Asserts.assertEquals('l', array.get(11))
    array.addAll(scala.Array[scala.Char]('m', 'n', 'o'))
    balticporter.runtime.Asserts.assertEquals(15, array.size)
    balticporter.runtime.Asserts.assertEquals('o', array.get(14))
    val chars: scala.Array[scala.Char] = scala.Array[scala.Char]('p', 'q', 'r', 's', 't')
    array.addAll(chars, 1, 3)
    balticporter.runtime.Asserts.assertEquals(18, array.size)
    balticporter.runtime.Asserts.assertEquals('q', array.get(15))
    balticporter.runtime.Asserts.assertEquals('r', array.get(16))
    balticporter.runtime.Asserts.assertEquals('s', array.get(17))
  })
  testCase("getSetTest", {
    val array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    array.addAll(scala.Array[scala.Char]('a', 'b', 'c', 'd', 'e'))
    balticporter.runtime.Asserts.assertEquals('a', array.get(0))
    balticporter.runtime.Asserts.assertEquals('e', array.get(4))
    array.set(2, 'Z')
    balticporter.runtime.Asserts.assertEquals('Z', array.get(2))
    array.set(0, 65.asInstanceOf[scala.Char].asInstanceOf[scala.Char])
    array.incr(0, 1.asInstanceOf[scala.Char].asInstanceOf[scala.Char])
    balticporter.runtime.Asserts.assertEquals(66.asInstanceOf[scala.Char], array.get(0))
    val array2: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    array2.addAll(scala.Array[scala.Char](1.asInstanceOf[scala.Char].asInstanceOf[scala.Char], 2.asInstanceOf[scala.Char].asInstanceOf[scala.Char], 3.asInstanceOf[scala.Char].asInstanceOf[scala.Char]))
    array2.incr(10.asInstanceOf[scala.Char].asInstanceOf[scala.Char])
    balticporter.runtime.Asserts.assertEquals(11.asInstanceOf[scala.Char], array2.get(0))
    balticporter.runtime.Asserts.assertEquals(12.asInstanceOf[scala.Char], array2.get(1))
    balticporter.runtime.Asserts.assertEquals(13.asInstanceOf[scala.Char], array2.get(2))
    array2.set(0, 5.asInstanceOf[scala.Char].asInstanceOf[scala.Char])
    array2.mul(0, 3.asInstanceOf[scala.Char].asInstanceOf[scala.Char])
    balticporter.runtime.Asserts.assertEquals(15.asInstanceOf[scala.Char], array2.get(0))
    val array3: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    array3.addAll(scala.Array[scala.Char](2.asInstanceOf[scala.Char].asInstanceOf[scala.Char], 3.asInstanceOf[scala.Char].asInstanceOf[scala.Char], 4.asInstanceOf[scala.Char].asInstanceOf[scala.Char]))
    array3.mul(2.asInstanceOf[scala.Char].asInstanceOf[scala.Char])
    balticporter.runtime.Asserts.assertEquals(4.asInstanceOf[scala.Char], array3.get(0))
    balticporter.runtime.Asserts.assertEquals(6.asInstanceOf[scala.Char], array3.get(1))
    balticporter.runtime.Asserts.assertEquals(8.asInstanceOf[scala.Char], array3.get(2))
  })
  testCase("removeTest", {
    val array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray(true, 10)
    array.addAll(scala.Array[scala.Char]('a', 'b', 'c', 'd', 'e'))
    balticporter.runtime.Asserts.assertTrue(array.removeValue('c'))
    balticporter.runtime.Asserts.assertEquals(4, array.size)
    balticporter.runtime.Asserts.assertEquals('a', array.get(0))
    balticporter.runtime.Asserts.assertEquals('b', array.get(1))
    balticporter.runtime.Asserts.assertEquals('d', array.get(2))
    balticporter.runtime.Asserts.assertEquals('e', array.get(3))
    balticporter.runtime.Asserts.assertFalse(array.removeValue('z'))
    val removed: scala.Char = array.removeIndex(1)
    balticporter.runtime.Asserts.assertEquals('b', removed)
    balticporter.runtime.Asserts.assertEquals(3, array.size)
    balticporter.runtime.Asserts.assertEquals('a', array.get(0))
    balticporter.runtime.Asserts.assertEquals('d', array.get(1))
    balticporter.runtime.Asserts.assertEquals('e', array.get(2))
    array.addAll(scala.Array[scala.Char]('f', 'g', 'h', 'i'))
    array.removeRange(1, 4)
    balticporter.runtime.Asserts.assertEquals(3, array.size)
    balticporter.runtime.Asserts.assertEquals('a', array.get(0))
    balticporter.runtime.Asserts.assertEquals('h', array.get(1))
    balticporter.runtime.Asserts.assertEquals('i', array.get(2))
    val unordered: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray(false, 10)
    unordered.addAll(scala.Array[scala.Char]('a', 'b', 'c', 'd', 'e'))
    balticporter.runtime.Asserts.assertTrue(unordered.removeValue('b'))
    balticporter.runtime.Asserts.assertEquals(4, unordered.size)
    balticporter.runtime.Asserts.assertEquals('a', unordered.get(0))
    balticporter.runtime.Asserts.assertEquals('e', unordered.get(1))
    balticporter.runtime.Asserts.assertEquals('c', unordered.get(2))
    balticporter.runtime.Asserts.assertEquals('d', unordered.get(3))
    val toRemove: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    toRemove.addAll(scala.Array[scala.Char]('a', 'd'))
    balticporter.runtime.Asserts.assertTrue(unordered.removeAll(toRemove))
    balticporter.runtime.Asserts.assertEquals(2, unordered.size)
    balticporter.runtime.Asserts.assertEquals('c', unordered.get(0))
    balticporter.runtime.Asserts.assertEquals('e', unordered.get(1))
  })
  testCase("searchTest", {
    val array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    array.addAll(scala.Array[scala.Char]('h', 'e', 'l', 'l', 'o', ' ', 'w', 'o', 'r', 'l', 'd'))
    balticporter.runtime.Asserts.assertTrue(array.contains('l'))
    balticporter.runtime.Asserts.assertFalse(array.contains('z'))
    balticporter.runtime.Asserts.assertEquals(0, array.indexOf('h'))
    balticporter.runtime.Asserts.assertEquals(2, array.indexOf('l'))
    balticporter.runtime.Asserts.assertEquals(-1, array.indexOf('z'))
    balticporter.runtime.Asserts.assertEquals(9, array.lastIndexOf('l'))
    balticporter.runtime.Asserts.assertEquals(7, array.lastIndexOf('o'))
    balticporter.runtime.Asserts.assertEquals(-1, array.lastIndexOf('z'))
    balticporter.runtime.Asserts.assertTrue(array.contains("hello"))
    balticporter.runtime.Asserts.assertTrue(array.contains("world"))
    balticporter.runtime.Asserts.assertFalse(array.contains("xyz"))
    balticporter.runtime.Asserts.assertEquals(0, array.indexOf("hello"))
    balticporter.runtime.Asserts.assertEquals(6, array.indexOf("world"))
    balticporter.runtime.Asserts.assertEquals(-1, array.indexOf("xyz"))
    balticporter.runtime.Asserts.assertEquals(0, array.lastIndexOf("hello"))
    balticporter.runtime.Asserts.assertEquals(2, array.lastIndexOf("ll"))
  })
  testCase("stackTest", {
    val array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    array.add('a')
    array.add('b')
    array.add('c')
    balticporter.runtime.Asserts.assertEquals('c', array.pop())
    balticporter.runtime.Asserts.assertEquals(2, array.size)
    balticporter.runtime.Asserts.assertEquals('b', array.peek())
    balticporter.runtime.Asserts.assertEquals(2, array.size)
    balticporter.runtime.Asserts.assertEquals('a', array.first())
    balticporter.runtime.Asserts.assertTrue(array.notEmpty())
    balticporter.runtime.Asserts.assertFalse(array.isEmpty())
    array.clear()
    balticporter.runtime.Asserts.assertFalse(array.notEmpty())
    balticporter.runtime.Asserts.assertTrue(array.isEmpty())
  })
  testCase("arrayOperationsTest", {
    val array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    array.addAll(scala.Array[scala.Char]('d', 'b', 'e', 'a', 'c'))
    array.sort()
    balticporter.runtime.Asserts.assertEquals('a', array.get(0))
    balticporter.runtime.Asserts.assertEquals('b', array.get(1))
    balticporter.runtime.Asserts.assertEquals('c', array.get(2))
    balticporter.runtime.Asserts.assertEquals('d', array.get(3))
    balticporter.runtime.Asserts.assertEquals('e', array.get(4))
    array.swap(0, 4)
    balticporter.runtime.Asserts.assertEquals('e', array.get(0))
    balticporter.runtime.Asserts.assertEquals('a', array.get(4))
    val array2: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    array2.addAll(scala.Array[scala.Char]('1', '2', '3', '4', '5'))
    array2.reverse()
    balticporter.runtime.Asserts.assertEquals('5', array2.get(0))
    balticporter.runtime.Asserts.assertEquals('4', array2.get(1))
    balticporter.runtime.Asserts.assertEquals('3', array2.get(2))
    balticporter.runtime.Asserts.assertEquals('2', array2.get(3))
    balticporter.runtime.Asserts.assertEquals('1', array2.get(4))
    array2.truncate(3)
    balticporter.runtime.Asserts.assertEquals(3, array2.size)
    balticporter.runtime.Asserts.assertEquals('5', array2.get(0))
    balticporter.runtime.Asserts.assertEquals('4', array2.get(1))
    balticporter.runtime.Asserts.assertEquals('3', array2.get(2))
    array2.clear()
    balticporter.runtime.Asserts.assertEquals(0, array2.size)
  })
  testCase("appendTest", {
    val array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    array.append(true)
    balticporter.runtime.Asserts.assertEquals("true", array.toString())
    array.clear()
    array.append(false)
    balticporter.runtime.Asserts.assertEquals("false", array.toString())
    array.clear()
    (array.append: (scala.Char) => com.badlogic.gdx.utils.CharArray)('X')
    balticporter.runtime.Asserts.assertEquals("X", array.toString())
    array.clear()
    (array.append: (scala.Int) => com.badlogic.gdx.utils.CharArray)(123)
    balticporter.runtime.Asserts.assertEquals("123", array.toString())
    array.clear()
    (array.append: (scala.Int, scala.Int, scala.Char) => com.badlogic.gdx.utils.CharArray)(42, 5, '0')
    balticporter.runtime.Asserts.assertEquals("00042", array.toString())
    array.clear()
    (array.append: (scala.Long) => com.badlogic.gdx.utils.CharArray)(9876543210L)
    balticporter.runtime.Asserts.assertEquals("9876543210", array.toString())
    array.clear()
    (array.append: (scala.Float) => com.badlogic.gdx.utils.CharArray)(3.14f)
    balticporter.runtime.Asserts.assertEquals("3.14", array.toString())
    array.clear()
    array.append(2.71828)
    balticporter.runtime.Asserts.assertEquals("2.71828", array.toString())
    array.clear()
    array.append("Hello")
    balticporter.runtime.Asserts.assertEquals("Hello", array.toString())
    array.append(" World")
    balticporter.runtime.Asserts.assertEquals("Hello World", array.toString())
    array.clear()
    array.append(null.asInstanceOf[java.lang.String])
    balticporter.runtime.Asserts.assertEquals("null", array.toString())
    array.clear()
    array.append("one")
    array.appendSeparator(',')
    array.append("two")
    array.appendSeparator(',')
    array.append("three")
    balticporter.runtime.Asserts.assertEquals("one,two,three", array.toString())
    array.clear()
    val other: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray("test")
    array.append(other)
    balticporter.runtime.Asserts.assertEquals("test", array.toString())
    array.clear()
    val sb: java.lang.StringBuilder = new java.lang.StringBuilder("builder")
    array.append(sb)
    balticporter.runtime.Asserts.assertEquals("builder", array.toString())
    array.clear()
    val sbuf: java.lang.StringBuffer = new java.lang.StringBuffer("buffer")
    array.append(sbuf)
    balticporter.runtime.Asserts.assertEquals("buffer", array.toString())
  })
  testCase("appendlnTest", {
    val array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    array.appendln("Line 1")
    array.appendln("Line 2")
    array.append("Line 3")
    val result: java.lang.String = array.toString()
    balticporter.runtime.Asserts.assertEquals("Line 1\nLine 2\nLine 3", result)
    array.clear()
    array.appendln()
    balticporter.runtime.Asserts.assertEquals("\n", array.toString())
  })
  testCase("paddingTest", {
    val array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    array.append("Hello")
    array.appendPadding(5, '*')
    balticporter.runtime.Asserts.assertEquals("Hello*****", array.toString())
    array.clear()
    array.appendFixedWidthPadLeft("42", 5, '0')
    balticporter.runtime.Asserts.assertEquals("00042", array.toString())
    array.clear()
    array.appendFixedWidthPadLeft("12345", 3, '0')
    balticporter.runtime.Asserts.assertEquals("345", array.toString())
    array.clear()
    array.appendFixedWidthPadRight("Hi", 5, ' ')
    balticporter.runtime.Asserts.assertEquals("Hi   ", array.toString())
    array.clear()
  })
  testCase("deleteTest", {
    var array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray("Hello World!")
    array.delete(5, 11)
    balticporter.runtime.Asserts.assertEquals("Hello!", array.toString())
    array.deleteCharAt(5)
    balticporter.runtime.Asserts.assertEquals("Hello", array.toString())
    array = new com.badlogic.gdx.utils.CharArray("Hello World!")
    array.deleteAll('l')
    balticporter.runtime.Asserts.assertEquals("Heo Word!", array.toString())
    array = new com.badlogic.gdx.utils.CharArray("Hello World!")
    array.deleteFirst('l')
    balticporter.runtime.Asserts.assertEquals("Helo World!", array.toString())
    array = new com.badlogic.gdx.utils.CharArray("Hello World! Hello!")
    array.deleteAll("Hello")
    balticporter.runtime.Asserts.assertEquals(" World! !", array.toString())
    array = new com.badlogic.gdx.utils.CharArray("Hello World! Hello!")
    array.deleteFirst("Hello")
    balticporter.runtime.Asserts.assertEquals(" World! Hello!", array.toString())
  })
  testCase("replaceTest", {
    var array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray("Hello World!")
    balticporter.runtime.Asserts.assertTrue(array.replaceFirst('l', 'L'))
    balticporter.runtime.Asserts.assertEquals("HeLlo World!", array.toString())
    balticporter.runtime.Asserts.assertFalse(array.replaceFirst('z', 'Z'))
    array = new com.badlogic.gdx.utils.CharArray("Hello World!")
    val count: scala.Int = array.replaceAll('l', 'L')
    balticporter.runtime.Asserts.assertEquals(3, count)
    balticporter.runtime.Asserts.assertEquals("HeLLo WorLd!", array.toString())
    array = new com.badlogic.gdx.utils.CharArray("Hello World!")
    array.replace(0, 5, "Hi")
    balticporter.runtime.Asserts.assertEquals("Hi World!", array.toString())
    array = new com.badlogic.gdx.utils.CharArray("Hello World! Hello!")
    array.replaceAll("Hello", "Hi")
    balticporter.runtime.Asserts.assertEquals("Hi World! Hi!", array.toString())
    array = new com.badlogic.gdx.utils.CharArray("Hello World! Hello!")
    array.replaceFirst("Hello", "Hi")
    balticporter.runtime.Asserts.assertEquals("Hi World! Hello!", array.toString())
    array = new com.badlogic.gdx.utils.CharArray("a-b-c")
    array.replace('-', " to ")
    balticporter.runtime.Asserts.assertEquals("a to b to c", array.toString())
  })
  testCase("insertTest", {
    var array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray("Hello!")
    (array.insert: (scala.Int, scala.Char) => scala.Unit)(5, ' ')
    balticporter.runtime.Asserts.assertEquals("Hello !", array.toString())
    array.insert(6, "World")
    balticporter.runtime.Asserts.assertEquals("Hello World!", array.toString())
    array.insert(0, "Say ")
    balticporter.runtime.Asserts.assertEquals("Say Hello World!", array.toString())
    array = new com.badlogic.gdx.utils.CharArray("Value: ")
    array.insert(7, true)
    balticporter.runtime.Asserts.assertEquals("Value: true", array.toString())
    array = new com.badlogic.gdx.utils.CharArray("Number: ")
    (array.insert: (scala.Int, scala.Int) => com.badlogic.gdx.utils.CharArray)(8, 42)
    balticporter.runtime.Asserts.assertEquals("Number: 42", array.toString())
    array = new com.badlogic.gdx.utils.CharArray("AB")
    val chars: scala.Array[scala.Char] = scala.Array[scala.Char]('C', 'D', 'E')
    array.insert(1, chars)
    balticporter.runtime.Asserts.assertEquals("ACDEB", array.toString())
    array = new com.badlogic.gdx.utils.CharArray("AC")
    array.insertRange(1, 2)
    array.set(1, 'B')
    array.set(2, 'B')
    balticporter.runtime.Asserts.assertEquals("ABBC", array.toString())
  })
  testCase("substringTest", {
    val array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray("Hello World!")
    balticporter.runtime.Asserts.assertEquals("Hello", array.substring(0, 5))
    balticporter.runtime.Asserts.assertEquals("World!", array.substring(6))
    balticporter.runtime.Asserts.assertEquals("World", array.substring(6, 11))
    balticporter.runtime.Asserts.assertEquals("Hello", array.leftString(5))
    balticporter.runtime.Asserts.assertEquals("", array.leftString(0))
    balticporter.runtime.Asserts.assertEquals("Hello World!", array.leftString(20))
    balticporter.runtime.Asserts.assertEquals("World!", array.rightString(6))
    balticporter.runtime.Asserts.assertEquals("", array.rightString(0))
    balticporter.runtime.Asserts.assertEquals("Hello World!", array.rightString(20))
    balticporter.runtime.Asserts.assertEquals("World", array.midString(6, 5))
    balticporter.runtime.Asserts.assertEquals("", array.midString(6, 0))
    balticporter.runtime.Asserts.assertEquals("World!", array.midString(6, 10))
  })
  testCase("stringComparisonTest", {
    val array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray("Hello World")
    balticporter.runtime.Asserts.assertTrue(array.startsWith("Hello"))
    balticporter.runtime.Asserts.assertFalse(array.startsWith("World"))
    balticporter.runtime.Asserts.assertTrue(array.startsWith(""))
    balticporter.runtime.Asserts.assertTrue(array.endsWith("World"))
    balticporter.runtime.Asserts.assertFalse(array.endsWith("Hello"))
    balticporter.runtime.Asserts.assertTrue(array.endsWith(""))
    balticporter.runtime.Asserts.assertTrue(array.contains("Hello"))
    balticporter.runtime.Asserts.assertTrue(array.contains("World"))
    balticporter.runtime.Asserts.assertTrue(array.contains(" "))
    balticporter.runtime.Asserts.assertFalse(array.contains("xyz"))
    balticporter.runtime.Asserts.assertTrue(array.containsIgnoreCase("hello"))
    balticporter.runtime.Asserts.assertTrue(array.containsIgnoreCase("WORLD"))
    balticporter.runtime.Asserts.assertFalse(array.containsIgnoreCase("xyz"))
    val other: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray("Hello World")
    balticporter.runtime.Asserts.assertTrue(array.equals(other))
    balticporter.runtime.Asserts.assertTrue(array.equalsString("Hello World"))
    other.append("!")
    balticporter.runtime.Asserts.assertFalse(array.equals(other))
    val upper: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray("HELLO WORLD")
    balticporter.runtime.Asserts.assertTrue(array.equalsIgnoreCase(upper))
    balticporter.runtime.Asserts.assertTrue(array.equalsIgnoreCase("hello world"))
  })
  testCase("charSequenceTest", {
    val array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray("Hello World!")
    balticporter.runtime.Asserts.assertEquals(12, array.length())
    balticporter.runtime.Asserts.assertEquals('H', array.charAt(0))
    balticporter.runtime.Asserts.assertEquals('!', array.charAt(11))
    val sub: java.lang.CharSequence = array.subSequence(0, 5)
    balticporter.runtime.Asserts.assertEquals("Hello", sub.toString())
  })
  testCase("trimCapacityTest", {
    var array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray(100)
    array.append("Hello")
    balticporter.runtime.Asserts.assertEquals(100, array.capacity())
    balticporter.runtime.Asserts.assertEquals(5, array.size)
    array.trim()
    balticporter.runtime.Asserts.assertEquals("Hello", array.toString())
    balticporter.runtime.Asserts.assertEquals(5, array.size)
    array = new com.badlogic.gdx.utils.CharArray(100)
    array.append("Test")
    array.trimToSize()
    balticporter.runtime.Asserts.assertEquals(4, array.capacity())
    array = new com.badlogic.gdx.utils.CharArray("Hello")
    array.setLength(3)
    balticporter.runtime.Asserts.assertEquals("Hel", array.toString())
    array.setLength(5)
    balticporter.runtime.Asserts.assertEquals(5, array.length())
  })
  testCase("hashCodeEqualsTest", {
    val array1: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray("Hello")
    val array2: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray("Hello")
    val array3: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray("World")
    balticporter.runtime.Asserts.assertTrue(array1.equals(array2))
    balticporter.runtime.Asserts.assertFalse(array1.equals(array3))
    balticporter.runtime.Asserts.assertFalse(array1.equals(null))
    balticporter.runtime.Asserts.assertFalse(array1.equals("Hello"))
    balticporter.runtime.Asserts.assertEquals(array1.hashCode(), array2.hashCode())
    balticporter.runtime.Asserts.assertNotEquals(array1.hashCode(), array3.hashCode())
  })
  testCase("readerWriterTest", {
    val array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray("Hello World!")
    val reader: java.io.Reader = array.reader()
    val buffer: scala.Array[scala.Char] = new scala.Array[scala.Char](5)
    val read: scala.Int = reader.read(buffer)
    balticporter.runtime.Asserts.assertEquals(5, read)
    balticporter.runtime.Asserts.assertArrayEquals(scala.Array[scala.Char]('H', 'e', 'l', 'l', 'o'), buffer)
    balticporter.runtime.Asserts.assertEquals(' ', reader.read())
    balticporter.runtime.Asserts.assertEquals('W', reader.read())
    reader.skip(2)
    balticporter.runtime.Asserts.assertEquals('l', reader.read())
    val array2: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    val writer: java.io.Writer = array2.writer()
    writer.write("Test")
    balticporter.runtime.Asserts.assertEquals("Test", array2.toString())
    writer.write(' ')
    writer.write(scala.Array[scala.Char]('1', '2', '3'))
    balticporter.runtime.Asserts.assertEquals("Test 123", array2.toString())
  })
  testCase("unicodeTest", {
    val array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    val smiley: scala.Int = 128512
    array.appendCodePoint(smiley)
    balticporter.runtime.Asserts.assertEquals(2, array.size)
    val cp: scala.Int = array.codePointAt(0)
    balticporter.runtime.Asserts.assertEquals(smiley, cp)
    array.append("Hello")
    val count: scala.Int = array.codePointCount(0, array.size)
    balticporter.runtime.Asserts.assertEquals(6, count)
    val array2: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    array2.appendCodePoint(128512)
    array2.append("Hi")
    array2.reverseCodePoints()
    balticporter.runtime.Asserts.assertEquals("iH", array2.substring(0, 2))
  })
  testCase("iteratorTest", {
    val array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    val list: scala.collection.mutable.ArrayBuffer[java.lang.String] = new scala.collection.mutable.ArrayBuffer[java.lang.String]()
    list += "One"
    list += "Two"
    list += "Three"
    array.appendAll(balticporter.runtime.JavaIterable.from(list))
    balticporter.runtime.Asserts.assertEquals("OneTwoThree", array.toString())
    array.clear()
    array.appendWithSeparators(balticporter.runtime.JavaIterable.from(list), ", ")
    balticporter.runtime.Asserts.assertEquals("One, Two, Three", array.toString())
    array.clear()
    val iter: balticporter.runtime.JavaIterator[java.lang.String] = balticporter.runtime.JavaIterator.from(list.iterator)
    array.appendAll(iter)
    balticporter.runtime.Asserts.assertEquals("OneTwoThree", array.toString())
    array.clear()
    val strArray: scala.Array[java.lang.String] = scala.Array[java.lang.String]("A", "B", "C")
    array.appendWithSeparators(strArray.asInstanceOf[scala.Array[java.lang.Object]], "-")
    balticporter.runtime.Asserts.assertEquals("A-B-C", array.toString())
  })
  testCase("edgeCasesTest", {
    val array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    balticporter.runtime.Asserts.assertEquals(-1, array.indexOf('a'))
    balticporter.runtime.Asserts.assertEquals(-1, array.lastIndexOf('a'))
    balticporter.runtime.Asserts.assertFalse(array.contains('a'))
    balticporter.runtime.Asserts.assertFalse(array.removeValue('a'))
    array.append("")
    balticporter.runtime.Asserts.assertEquals(0, array.size)
    array.append(null.asInstanceOf[java.lang.String])
    balticporter.runtime.Asserts.assertEquals("null", array.toString())
    val large: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray(10000);
    { var i: scala.Int = 0; while (i < 10000) { {
      large.add(('A' + (i % 26)).asInstanceOf[scala.Char].asInstanceOf[scala.Char])
    }; i = i + 1 } }
    balticporter.runtime.Asserts.assertEquals(10000, large.size)
    try {
      array.get(100)
      balticporter.runtime.Asserts.fail("Should throw exception")
    } catch {
      case e: java.lang.IndexOutOfBoundsException => {
        ()
      }
    }
    try {
      array.set(100, 'x')
      balticporter.runtime.Asserts.fail("Should throw exception")
    } catch {
      case e: java.lang.IndexOutOfBoundsException => {
        ()
      }
    }
  })
  testCase("toArrayTest", {
    val array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    array.addAll(scala.Array[scala.Char]('a', 'b', 'c', 'd', 'e'))
    val chars: scala.Array[scala.Char] = array.toCharArray()
    balticporter.runtime.Asserts.assertArrayEquals(scala.Array[scala.Char]('a', 'b', 'c', 'd', 'e'), chars)
    val target: scala.Array[scala.Char] = new scala.Array[scala.Char](10)
    array.getChars(1, 4, target, 2)
    balticporter.runtime.Asserts.assertEquals('b', target(2))
    balticporter.runtime.Asserts.assertEquals('c', target(3))
    balticporter.runtime.Asserts.assertEquals('d', target(4))
  })
  testCase("drainTest", {
    val array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray("Hello World!")
    val drained: scala.Char = array.drainChar(6)
    balticporter.runtime.Asserts.assertEquals('W', drained)
    balticporter.runtime.Asserts.assertEquals("Hello orld!", array.toString())
    val target: scala.Array[scala.Char] = new scala.Array[scala.Char](5)
    val count: scala.Int = array.drainChars(0, 5, target, 0)
    balticporter.runtime.Asserts.assertEquals(5, count)
    balticporter.runtime.Asserts.assertArrayEquals(scala.Array[scala.Char]('H', 'e', 'l', 'l', 'o'), target)
    balticporter.runtime.Asserts.assertEquals(" orld!", array.toString())
  })
  testCase("appendSeparatorTest", {
    val array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    array.appendSeparator(',')
    array.append("first")
    balticporter.runtime.Asserts.assertEquals("first", array.toString())
    array.appendSeparator(',')
    array.append("second")
    balticporter.runtime.Asserts.assertEquals("first,second", array.toString())
    val array2: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    (array2.appendSeparator: (scala.Char, scala.Char) => com.badlogic.gdx.utils.CharArray)(',', ';')
    balticporter.runtime.Asserts.assertEquals(";", array2.toString())
    val array3: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray();
    { var i: scala.Int = 0; while (i < 3) { {
      array3.appendSeparator(',', i)
      array3.append("item" + i)
    }; i = i + 1 } }
    balticporter.runtime.Asserts.assertEquals("item0,item1,item2", array3.toString())
    val array4: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    array4.append("A")
    array4.appendSeparator(" | ")
    array4.append("B")
    array4.appendSeparator(" | ")
    array4.append("C")
    balticporter.runtime.Asserts.assertEquals("A | B | C", array4.toString())
  })
  testCase("randomTest", {
    val array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    array.addAll(scala.Array[scala.Char]('a', 'b', 'c', 'd', 'e'))
    val random: scala.Char = array.random()
    balticporter.runtime.Asserts.assertTrue(array.contains(random))
    array.shuffle()
    balticporter.runtime.Asserts.assertEquals(5, array.size)
    balticporter.runtime.Asserts.assertTrue(array.contains('a'))
    balticporter.runtime.Asserts.assertTrue(array.contains('b'))
    balticporter.runtime.Asserts.assertTrue(array.contains('c'))
    balticporter.runtime.Asserts.assertTrue(array.contains('d'))
    balticporter.runtime.Asserts.assertTrue(array.contains('e'))
  })
  testCase("appendToTest", {
    val array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray("Hello World")
    val sb: java.lang.StringBuilder = new java.lang.StringBuilder("Start: ")
    array.appendTo(sb)
    balticporter.runtime.Asserts.assertEquals("Start: Hello World", sb.toString())
    val sbuf: java.lang.StringBuffer = new java.lang.StringBuffer("Start: ")
    array.appendTo(sbuf)
    balticporter.runtime.Asserts.assertEquals("Start: Hello World", sbuf.toString())
  })
  testCase("setCharAtTest", {
    val array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray("Hello")
    array.setCharAt(1, 'a')
    balticporter.runtime.Asserts.assertEquals("Hallo", array.toString())
    array.setCharAt(2, 'p').setCharAt(3, 'p').setCharAt(4, 'y')
    balticporter.runtime.Asserts.assertEquals("Happy", array.toString())
  })
  testCase("toStringAndClearTest", {
    val array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray("Test String")
    val result: java.lang.String = array.toStringAndClear()
    balticporter.runtime.Asserts.assertEquals("Test String", result)
    balticporter.runtime.Asserts.assertEquals(0, array.size)
    balticporter.runtime.Asserts.assertTrue(array.isEmpty())
  })
  testCase("toStringWithSeparatorTest", {
    val array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    array.addAll(scala.Array[scala.Char]('a', 'b', 'c', 'd', 'e'))
    val result: java.lang.String = array.toString(",")
    balticporter.runtime.Asserts.assertEquals("a,b,c,d,e", result)
    val empty: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    balticporter.runtime.Asserts.assertEquals("", empty.toString(","))
    val single: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    single.add('x')
    balticporter.runtime.Asserts.assertEquals("x", single.toString(","))
  })
}