package com.badlogic.gdx.utils

class CharArrayTest extends munit.FunSuite {
  test("constructorTest")({
    val array1: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    assertEquals(array1.size, 0)
    assert(array1.ordered)
    val array2: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray(100)
    assertEquals(array2.size, 0)
    assertEquals(array2.capacity(), 100)
    assert(array2.ordered)
    val array3: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray(false, 50)
    assertEquals(array3.size, 0)
    assertEquals(array3.capacity(), 50)
    assertEquals(array3.ordered, false)
    val array4: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    array4.add('a')
    array4.add('b')
    val array5: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray(array4)
    assertEquals(array5.size, 2)
    assertEquals(array5.get(0), 'a')
    assertEquals(array5.get(1), 'b')
    val chars: scala.Array[scala.Char] = scala.Array[scala.Char]('x', 'y', 'z')
    val array6: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray(chars)
    assertEquals(array6.size, 3)
    assertEquals(array6.get(0), 'x')
    assertEquals(array6.get(2), 'z')
    val array7: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray(true, chars, 1, 2)
    assertEquals(array7.size, 2)
    assertEquals(array7.get(0), 'y')
    assertEquals(array7.get(1), 'z')
    val array8: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray("hello")
    assertEquals(array8.size, 5)
    assertEquals(array8.toString(), "hello")
    val sb: java.lang.StringBuilder = new java.lang.StringBuilder("world")
    val array9: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray(sb)
    assertEquals(array9.size, 5)
    assertEquals(array9.toString(), "world")
  })
  test("addTest")({
    val array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    array.add('a')
    assertEquals(array.size, 1)
    assertEquals(array.get(0), 'a')
    array.add('b', 'c')
    assertEquals(array.size, 3)
    assertEquals(array.get(1), 'b')
    assertEquals(array.get(2), 'c')
    array.add('d', 'e', 'f')
    assertEquals(array.size, 6)
    assertEquals(array.get(5), 'f')
    array.add('g', 'h', 'i', 'j')
    assertEquals(array.size, 10)
    assertEquals(array.get(9), 'j')
    val array2: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    array2.add('k')
    array2.add('l')
    array.addAll(array2)
    assertEquals(array.size, 12)
    assertEquals(array.get(10), 'k')
    assertEquals(array.get(11), 'l')
    array.addAll(scala.Array[scala.Char]('m', 'n', 'o'))
    assertEquals(array.size, 15)
    assertEquals(array.get(14), 'o')
    val chars: scala.Array[scala.Char] = scala.Array[scala.Char]('p', 'q', 'r', 's', 't')
    array.addAll(chars, 1, 3)
    assertEquals(array.size, 18)
    assertEquals(array.get(15), 'q')
    assertEquals(array.get(16), 'r')
    assertEquals(array.get(17), 's')
  })
  test("getSetTest")({
    val array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    array.addAll(scala.Array[scala.Char]('a', 'b', 'c', 'd', 'e'))
    assertEquals(array.get(0), 'a')
    assertEquals(array.get(4), 'e')
    array.set(2, 'Z')
    assertEquals(array.get(2), 'Z')
    array.set(0, 65.asInstanceOf[scala.Char].asInstanceOf[scala.Char])
    array.incr(0, 1.asInstanceOf[scala.Char].asInstanceOf[scala.Char])
    assertEquals(array.get(0), 66.asInstanceOf[scala.Char])
    val array2: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    array2.addAll(scala.Array[scala.Char](1.asInstanceOf[scala.Char].asInstanceOf[scala.Char], 2.asInstanceOf[scala.Char].asInstanceOf[scala.Char], 3.asInstanceOf[scala.Char].asInstanceOf[scala.Char]))
    array2.incr(10.asInstanceOf[scala.Char].asInstanceOf[scala.Char])
    assertEquals(array2.get(0), 11.asInstanceOf[scala.Char])
    assertEquals(array2.get(1), 12.asInstanceOf[scala.Char])
    assertEquals(array2.get(2), 13.asInstanceOf[scala.Char])
    array2.set(0, 5.asInstanceOf[scala.Char].asInstanceOf[scala.Char])
    array2.mul(0, 3.asInstanceOf[scala.Char].asInstanceOf[scala.Char])
    assertEquals(array2.get(0), 15.asInstanceOf[scala.Char])
    val array3: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    array3.addAll(scala.Array[scala.Char](2.asInstanceOf[scala.Char].asInstanceOf[scala.Char], 3.asInstanceOf[scala.Char].asInstanceOf[scala.Char], 4.asInstanceOf[scala.Char].asInstanceOf[scala.Char]))
    array3.mul(2.asInstanceOf[scala.Char].asInstanceOf[scala.Char])
    assertEquals(array3.get(0), 4.asInstanceOf[scala.Char])
    assertEquals(array3.get(1), 6.asInstanceOf[scala.Char])
    assertEquals(array3.get(2), 8.asInstanceOf[scala.Char])
  })
  test("removeTest")({
    val array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray(true, 10)
    array.addAll(scala.Array[scala.Char]('a', 'b', 'c', 'd', 'e'))
    assert(array.removeValue('c'))
    assertEquals(array.size, 4)
    assertEquals(array.get(0), 'a')
    assertEquals(array.get(1), 'b')
    assertEquals(array.get(2), 'd')
    assertEquals(array.get(3), 'e')
    assertEquals(array.removeValue('z'), false)
    val removed: scala.Char = array.removeIndex(1)
    assertEquals(removed, 'b')
    assertEquals(array.size, 3)
    assertEquals(array.get(0), 'a')
    assertEquals(array.get(1), 'd')
    assertEquals(array.get(2), 'e')
    array.addAll(scala.Array[scala.Char]('f', 'g', 'h', 'i'))
    array.removeRange(1, 4)
    assertEquals(array.size, 3)
    assertEquals(array.get(0), 'a')
    assertEquals(array.get(1), 'h')
    assertEquals(array.get(2), 'i')
    val unordered: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray(false, 10)
    unordered.addAll(scala.Array[scala.Char]('a', 'b', 'c', 'd', 'e'))
    assert(unordered.removeValue('b'))
    assertEquals(unordered.size, 4)
    assertEquals(unordered.get(0), 'a')
    assertEquals(unordered.get(1), 'e')
    assertEquals(unordered.get(2), 'c')
    assertEquals(unordered.get(3), 'd')
    val toRemove: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    toRemove.addAll(scala.Array[scala.Char]('a', 'd'))
    assert(unordered.removeAll(toRemove))
    assertEquals(unordered.size, 2)
    assertEquals(unordered.get(0), 'c')
    assertEquals(unordered.get(1), 'e')
  })
  test("searchTest")({
    val array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    array.addAll(scala.Array[scala.Char]('h', 'e', 'l', 'l', 'o', ' ', 'w', 'o', 'r', 'l', 'd'))
    assert(array.contains('l'))
    assertEquals(array.contains('z'), false)
    assertEquals(array.indexOf('h'), 0)
    assertEquals(array.indexOf('l'), 2)
    assertEquals(array.indexOf('z'), -1)
    assertEquals(array.lastIndexOf('l'), 9)
    assertEquals(array.lastIndexOf('o'), 7)
    assertEquals(array.lastIndexOf('z'), -1)
    assert(array.contains("hello"))
    assert(array.contains("world"))
    assertEquals(array.contains("xyz"), false)
    assertEquals(array.indexOf("hello"), 0)
    assertEquals(array.indexOf("world"), 6)
    assertEquals(array.indexOf("xyz"), -1)
    assertEquals(array.lastIndexOf("hello"), 0)
    assertEquals(array.lastIndexOf("ll"), 2)
  })
  test("stackTest")({
    val array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    array.add('a')
    array.add('b')
    array.add('c')
    assertEquals(array.pop(), 'c')
    assertEquals(array.size, 2)
    assertEquals(array.peek(), 'b')
    assertEquals(array.size, 2)
    assertEquals(array.first(), 'a')
    assert(array.notEmpty())
    assertEquals(array.isEmpty(), false)
    array.clear()
    assertEquals(array.notEmpty(), false)
    assert(array.isEmpty())
  })
  test("arrayOperationsTest")({
    val array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    array.addAll(scala.Array[scala.Char]('d', 'b', 'e', 'a', 'c'))
    array.sort()
    assertEquals(array.get(0), 'a')
    assertEquals(array.get(1), 'b')
    assertEquals(array.get(2), 'c')
    assertEquals(array.get(3), 'd')
    assertEquals(array.get(4), 'e')
    array.swap(0, 4)
    assertEquals(array.get(0), 'e')
    assertEquals(array.get(4), 'a')
    val array2: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    array2.addAll(scala.Array[scala.Char]('1', '2', '3', '4', '5'))
    array2.reverse()
    assertEquals(array2.get(0), '5')
    assertEquals(array2.get(1), '4')
    assertEquals(array2.get(2), '3')
    assertEquals(array2.get(3), '2')
    assertEquals(array2.get(4), '1')
    array2.truncate(3)
    assertEquals(array2.size, 3)
    assertEquals(array2.get(0), '5')
    assertEquals(array2.get(1), '4')
    assertEquals(array2.get(2), '3')
    array2.clear()
    assertEquals(array2.size, 0)
  })
  test("appendTest")({
    val array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    array.append(true)
    assertEquals(array.toString(), "true")
    array.clear()
    array.append(false)
    assertEquals(array.toString(), "false")
    array.clear()
    (array.append: (scala.Char) => com.badlogic.gdx.utils.CharArray)('X')
    assertEquals(array.toString(), "X")
    array.clear()
    (array.append: (scala.Int) => com.badlogic.gdx.utils.CharArray)(123)
    assertEquals(array.toString(), "123")
    array.clear()
    (array.append: (scala.Int, scala.Int, scala.Char) => com.badlogic.gdx.utils.CharArray)(42, 5, '0')
    assertEquals(array.toString(), "00042")
    array.clear()
    (array.append: (scala.Long) => com.badlogic.gdx.utils.CharArray)(9876543210L)
    assertEquals(array.toString(), "9876543210")
    array.clear()
    (array.append: (scala.Float) => com.badlogic.gdx.utils.CharArray)(3.14f)
    assertEquals(array.toString(), "3.14")
    array.clear()
    array.append(2.71828)
    assertEquals(array.toString(), "2.71828")
    array.clear()
    array.append("Hello")
    assertEquals(array.toString(), "Hello")
    array.append(" World")
    assertEquals(array.toString(), "Hello World")
    array.clear()
    array.append(null.asInstanceOf[java.lang.String])
    assertEquals(array.toString(), "null")
    array.clear()
    array.append("one")
    array.appendSeparator(',')
    array.append("two")
    array.appendSeparator(',')
    array.append("three")
    assertEquals(array.toString(), "one,two,three")
    array.clear()
    val other: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray("test")
    array.append(other)
    assertEquals(array.toString(), "test")
    array.clear()
    val sb: java.lang.StringBuilder = new java.lang.StringBuilder("builder")
    array.append(sb)
    assertEquals(array.toString(), "builder")
    array.clear()
    val sbuf: java.lang.StringBuffer = new java.lang.StringBuffer("buffer")
    array.append(sbuf)
    assertEquals(array.toString(), "buffer")
  })
  test("appendlnTest")({
    val array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    array.appendln("Line 1")
    array.appendln("Line 2")
    array.append("Line 3")
    val result: java.lang.String = array.toString()
    assertEquals(result, "Line 1\nLine 2\nLine 3")
    array.clear()
    array.appendln()
    assertEquals(array.toString(), "\n")
  })
  test("paddingTest")({
    val array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    array.append("Hello")
    array.appendPadding(5, '*')
    assertEquals(array.toString(), "Hello*****")
    array.clear()
    array.appendFixedWidthPadLeft("42", 5, '0')
    assertEquals(array.toString(), "00042")
    array.clear()
    array.appendFixedWidthPadLeft("12345", 3, '0')
    assertEquals(array.toString(), "345")
    array.clear()
    array.appendFixedWidthPadRight("Hi", 5, ' ')
    assertEquals(array.toString(), "Hi   ")
    array.clear()
  })
  test("deleteTest")({
    var array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray("Hello World!")
    array.delete(5, 11)
    assertEquals(array.toString(), "Hello!")
    array.deleteCharAt(5)
    assertEquals(array.toString(), "Hello")
    array = new com.badlogic.gdx.utils.CharArray("Hello World!")
    array.deleteAll('l')
    assertEquals(array.toString(), "Heo Word!")
    array = new com.badlogic.gdx.utils.CharArray("Hello World!")
    array.deleteFirst('l')
    assertEquals(array.toString(), "Helo World!")
    array = new com.badlogic.gdx.utils.CharArray("Hello World! Hello!")
    array.deleteAll("Hello")
    assertEquals(array.toString(), " World! !")
    array = new com.badlogic.gdx.utils.CharArray("Hello World! Hello!")
    array.deleteFirst("Hello")
    assertEquals(array.toString(), " World! Hello!")
  })
  test("replaceTest")({
    var array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray("Hello World!")
    assert(array.replaceFirst('l', 'L'))
    assertEquals(array.toString(), "HeLlo World!")
    assertEquals(array.replaceFirst('z', 'Z'), false)
    array = new com.badlogic.gdx.utils.CharArray("Hello World!")
    val count: scala.Int = array.replaceAll('l', 'L')
    assertEquals(count, 3)
    assertEquals(array.toString(), "HeLLo WorLd!")
    array = new com.badlogic.gdx.utils.CharArray("Hello World!")
    array.replace(0, 5, "Hi")
    assertEquals(array.toString(), "Hi World!")
    array = new com.badlogic.gdx.utils.CharArray("Hello World! Hello!")
    array.replaceAll("Hello", "Hi")
    assertEquals(array.toString(), "Hi World! Hi!")
    array = new com.badlogic.gdx.utils.CharArray("Hello World! Hello!")
    array.replaceFirst("Hello", "Hi")
    assertEquals(array.toString(), "Hi World! Hello!")
    array = new com.badlogic.gdx.utils.CharArray("a-b-c")
    array.replace('-', " to ")
    assertEquals(array.toString(), "a to b to c")
  })
  test("insertTest")({
    var array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray("Hello!")
    (array.insert: (scala.Int, scala.Char) => scala.Unit)(5, ' ')
    assertEquals(array.toString(), "Hello !")
    array.insert(6, "World")
    assertEquals(array.toString(), "Hello World!")
    array.insert(0, "Say ")
    assertEquals(array.toString(), "Say Hello World!")
    array = new com.badlogic.gdx.utils.CharArray("Value: ")
    array.insert(7, true)
    assertEquals(array.toString(), "Value: true")
    array = new com.badlogic.gdx.utils.CharArray("Number: ")
    (array.insert: (scala.Int, scala.Int) => com.badlogic.gdx.utils.CharArray)(8, 42)
    assertEquals(array.toString(), "Number: 42")
    array = new com.badlogic.gdx.utils.CharArray("AB")
    val chars: scala.Array[scala.Char] = scala.Array[scala.Char]('C', 'D', 'E')
    array.insert(1, chars)
    assertEquals(array.toString(), "ACDEB")
    array = new com.badlogic.gdx.utils.CharArray("AC")
    array.insertRange(1, 2)
    array.set(1, 'B')
    array.set(2, 'B')
    assertEquals(array.toString(), "ABBC")
  })
  test("substringTest")({
    val array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray("Hello World!")
    assertEquals(array.substring(0, 5), "Hello")
    assertEquals(array.substring(6), "World!")
    assertEquals(array.substring(6, 11), "World")
    assertEquals(array.leftString(5), "Hello")
    assertEquals(array.leftString(0), "")
    assertEquals(array.leftString(20), "Hello World!")
    assertEquals(array.rightString(6), "World!")
    assertEquals(array.rightString(0), "")
    assertEquals(array.rightString(20), "Hello World!")
    assertEquals(array.midString(6, 5), "World")
    assertEquals(array.midString(6, 0), "")
    assertEquals(array.midString(6, 10), "World!")
  })
  test("stringComparisonTest")({
    val array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray("Hello World")
    assert(array.startsWith("Hello"))
    assertEquals(array.startsWith("World"), false)
    assert(array.startsWith(""))
    assert(array.endsWith("World"))
    assertEquals(array.endsWith("Hello"), false)
    assert(array.endsWith(""))
    assert(array.contains("Hello"))
    assert(array.contains("World"))
    assert(array.contains(" "))
    assertEquals(array.contains("xyz"), false)
    assert(array.containsIgnoreCase("hello"))
    assert(array.containsIgnoreCase("WORLD"))
    assertEquals(array.containsIgnoreCase("xyz"), false)
    val other: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray("Hello World")
    assert(array.equals(other))
    assert(array.equalsString("Hello World"))
    other.append("!")
    assertEquals(array.equals(other), false)
    val upper: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray("HELLO WORLD")
    assert(array.equalsIgnoreCase(upper))
    assert(array.equalsIgnoreCase("hello world"))
  })
  test("charSequenceTest")({
    val array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray("Hello World!")
    assertEquals(array.length(), 12)
    assertEquals(array.charAt(0), 'H')
    assertEquals(array.charAt(11), '!')
    val sub: java.lang.CharSequence = array.subSequence(0, 5)
    assertEquals(sub.toString(), "Hello")
  })
  test("trimCapacityTest")({
    var array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray(100)
    array.append("Hello")
    assertEquals(array.capacity(), 100)
    assertEquals(array.size, 5)
    array.trim()
    assertEquals(array.toString(), "Hello")
    assertEquals(array.size, 5)
    array = new com.badlogic.gdx.utils.CharArray(100)
    array.append("Test")
    array.trimToSize()
    assertEquals(array.capacity(), 4)
    array = new com.badlogic.gdx.utils.CharArray("Hello")
    array.setLength(3)
    assertEquals(array.toString(), "Hel")
    array.setLength(5)
    assertEquals(array.length(), 5)
  })
  test("hashCodeEqualsTest")({
    val array1: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray("Hello")
    val array2: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray("Hello")
    val array3: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray("World")
    assert(array1.equals(array2))
    assertEquals(array1.equals(array3), false)
    assertEquals(array1.equals(null), false)
    assertEquals(array1.equals("Hello"), false)
    assertEquals(array2.hashCode(), array1.hashCode())
    assertNotEquals(array3.hashCode(), array1.hashCode())
  })
  test("readerWriterTest")({
    val array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray("Hello World!")
    val reader: java.io.Reader = array.reader()
    val buffer: scala.Array[scala.Char] = new scala.Array[scala.Char](5)
    val read: scala.Int = reader.read(buffer)
    assertEquals(read, 5)
    balticporter.runtime.Asserts.assertArrayEquals(scala.Array[scala.Char]('H', 'e', 'l', 'l', 'o'), buffer)
    assertEquals(reader.read(), ' ')
    assertEquals(reader.read(), 'W')
    reader.skip(2)
    assertEquals(reader.read(), 'l')
    val array2: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    val writer: java.io.Writer = array2.writer()
    writer.write("Test")
    assertEquals(array2.toString(), "Test")
    writer.write(' ')
    writer.write(scala.Array[scala.Char]('1', '2', '3'))
    assertEquals(array2.toString(), "Test 123")
  })
  test("unicodeTest")({
    val array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    val smiley: scala.Int = 128512
    array.appendCodePoint(smiley)
    assertEquals(array.size, 2)
    val cp: scala.Int = array.codePointAt(0)
    assertEquals(cp, smiley)
    array.append("Hello")
    val count: scala.Int = array.codePointCount(0, array.size)
    assertEquals(count, 6)
    val array2: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    array2.appendCodePoint(128512)
    array2.append("Hi")
    array2.reverseCodePoints()
    assertEquals(array2.substring(0, 2), "iH")
  })
  test("iteratorTest")({
    val array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    val list: scala.collection.mutable.ArrayBuffer[java.lang.String] = new scala.collection.mutable.ArrayBuffer[java.lang.String]()
    list += "One"
    list += "Two"
    list += "Three"
    array.appendAll(balticporter.runtime.JavaIterable.from(list))
    assertEquals(array.toString(), "OneTwoThree")
    array.clear()
    array.appendWithSeparators(balticporter.runtime.JavaIterable.from(list), ", ")
    assertEquals(array.toString(), "One, Two, Three")
    array.clear()
    val iter: balticporter.runtime.JavaIterator[java.lang.String] = balticporter.runtime.JavaIterator.from(list.iterator)
    array.appendAll(iter)
    assertEquals(array.toString(), "OneTwoThree")
    array.clear()
    val strArray: scala.Array[java.lang.String] = scala.Array[java.lang.String]("A", "B", "C")
    array.appendWithSeparators(strArray.asInstanceOf[scala.Array[java.lang.Object]], "-")
    assertEquals(array.toString(), "A-B-C")
  })
  test("edgeCasesTest")({
    val array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    assertEquals(array.indexOf('a'), -1)
    assertEquals(array.lastIndexOf('a'), -1)
    assertEquals(array.contains('a'), false)
    assertEquals(array.removeValue('a'), false)
    array.append("")
    assertEquals(array.size, 0)
    array.append(null.asInstanceOf[java.lang.String])
    assertEquals(array.toString(), "null")
    val large: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray(10000);
    { var i: scala.Int = 0; while (i < 10000) { {
      large.add(('A' + (i % 26)).asInstanceOf[scala.Char].asInstanceOf[scala.Char])
    }; i = i + 1 } }
    assertEquals(large.size, 10000)
    try {
      array.get(100)
      fail("Should throw exception")
    } catch {
      case e: java.lang.IndexOutOfBoundsException => {
        ()
      }
    }
    try {
      array.set(100, 'x')
      fail("Should throw exception")
    } catch {
      case e: java.lang.IndexOutOfBoundsException => {
        ()
      }
    }
  })
  test("toArrayTest")({
    val array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    array.addAll(scala.Array[scala.Char]('a', 'b', 'c', 'd', 'e'))
    val chars: scala.Array[scala.Char] = array.toCharArray()
    balticporter.runtime.Asserts.assertArrayEquals(scala.Array[scala.Char]('a', 'b', 'c', 'd', 'e'), chars)
    val target: scala.Array[scala.Char] = new scala.Array[scala.Char](10)
    array.getChars(1, 4, target, 2)
    assertEquals(target(2), 'b')
    assertEquals(target(3), 'c')
    assertEquals(target(4), 'd')
  })
  test("drainTest")({
    val array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray("Hello World!")
    val drained: scala.Char = array.drainChar(6)
    assertEquals(drained, 'W')
    assertEquals(array.toString(), "Hello orld!")
    val target: scala.Array[scala.Char] = new scala.Array[scala.Char](5)
    val count: scala.Int = array.drainChars(0, 5, target, 0)
    assertEquals(count, 5)
    balticporter.runtime.Asserts.assertArrayEquals(scala.Array[scala.Char]('H', 'e', 'l', 'l', 'o'), target)
    assertEquals(array.toString(), " orld!")
  })
  test("appendSeparatorTest")({
    val array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    array.appendSeparator(',')
    array.append("first")
    assertEquals(array.toString(), "first")
    array.appendSeparator(',')
    array.append("second")
    assertEquals(array.toString(), "first,second")
    val array2: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    (array2.appendSeparator: (scala.Char, scala.Char) => com.badlogic.gdx.utils.CharArray)(',', ';')
    assertEquals(array2.toString(), ";")
    val array3: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray();
    { var i: scala.Int = 0; while (i < 3) { {
      array3.appendSeparator(',', i)
      array3.append("item" + i)
    }; i = i + 1 } }
    assertEquals(array3.toString(), "item0,item1,item2")
    val array4: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    array4.append("A")
    array4.appendSeparator(" | ")
    array4.append("B")
    array4.appendSeparator(" | ")
    array4.append("C")
    assertEquals(array4.toString(), "A | B | C")
  })
  test("randomTest")({
    val array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    array.addAll(scala.Array[scala.Char]('a', 'b', 'c', 'd', 'e'))
    val random: scala.Char = array.random()
    assert(array.contains(random))
    array.shuffle()
    assertEquals(array.size, 5)
    assert(array.contains('a'))
    assert(array.contains('b'))
    assert(array.contains('c'))
    assert(array.contains('d'))
    assert(array.contains('e'))
  })
  test("appendToTest")({
    val array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray("Hello World")
    val sb: java.lang.StringBuilder = new java.lang.StringBuilder("Start: ")
    array.appendTo(sb)
    assertEquals(sb.toString(), "Start: Hello World")
    val sbuf: java.lang.StringBuffer = new java.lang.StringBuffer("Start: ")
    array.appendTo(sbuf)
    assertEquals(sbuf.toString(), "Start: Hello World")
  })
  test("setCharAtTest")({
    val array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray("Hello")
    array.setCharAt(1, 'a')
    assertEquals(array.toString(), "Hallo")
    array.setCharAt(2, 'p').setCharAt(3, 'p').setCharAt(4, 'y')
    assertEquals(array.toString(), "Happy")
  })
  test("toStringAndClearTest")({
    val array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray("Test String")
    val result: java.lang.String = array.toStringAndClear()
    assertEquals(result, "Test String")
    assertEquals(array.size, 0)
    assert(array.isEmpty())
  })
  test("toStringWithSeparatorTest")({
    val array: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    array.addAll(scala.Array[scala.Char]('a', 'b', 'c', 'd', 'e'))
    val result: java.lang.String = array.toString(",")
    assertEquals(result, "a,b,c,d,e")
    val empty: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    assertEquals(empty.toString(","), "")
    val single: com.badlogic.gdx.utils.CharArray = new com.badlogic.gdx.utils.CharArray()
    single.add('x')
    assertEquals(single.toString(","), "x")
  })
}