package com.badlogic.gdx.utils

class JsonValueTest {
  def testAddingRemovedValue(): scala.Unit = {
    val firstObject: com.badlogic.gdx.utils.JsonValue = new com.badlogic.gdx.utils.JsonValue(com.badlogic.gdx.utils.JsonValue.ValueType.`object`)
    val secondObject: com.badlogic.gdx.utils.JsonValue = new com.badlogic.gdx.utils.JsonValue(com.badlogic.gdx.utils.JsonValue.ValueType.`object`)
    firstObject.addChild("a", new com.badlogic.gdx.utils.JsonValue("A"))
    secondObject.addChild("b", new com.badlogic.gdx.utils.JsonValue("B"))
    secondObject.addChild("c", new com.badlogic.gdx.utils.JsonValue("C"))
    val b: com.badlogic.gdx.utils.JsonValue = secondObject.remove("b")
    firstObject.addChild(b)
    org.junit.Assert.assertNotNull(firstObject.get("a"))
    org.junit.Assert.assertNotNull(firstObject.get("b"))
    org.junit.Assert.assertNull(firstObject.get("c"))
    org.junit.Assert.assertNull(secondObject.get("a"))
    org.junit.Assert.assertNull(secondObject.get("b"))
    org.junit.Assert.assertNotNull(secondObject.get("c"))
  }
  def testReplaceValue(): scala.Unit = {
    val `object`: com.badlogic.gdx.utils.JsonValue = new com.badlogic.gdx.utils.JsonValue(com.badlogic.gdx.utils.JsonValue.ValueType.`object`)
    `object`.addChild("a", new com.badlogic.gdx.utils.JsonValue("A"))
    `object`.addChild("b", new com.badlogic.gdx.utils.JsonValue("B"))
    `object`.addChild("c", new com.badlogic.gdx.utils.JsonValue("C"))
    `object`.addChild("d", new com.badlogic.gdx.utils.JsonValue("D"))
    `object`.setChild("b", new com.badlogic.gdx.utils.JsonValue("X"))
    `object`.setChild("c", new com.badlogic.gdx.utils.JsonValue("Y"))
    org.junit.Assert.assertEquals(`object`.get("a").asString(), "A")
    org.junit.Assert.assertEquals(`object`.get("b").asString(), "X")
    org.junit.Assert.assertEquals(`object`.get("c").asString(), "Y")
    org.junit.Assert.assertEquals(`object`.get("d").asString(), "D")
    `object`.setChild("a", new com.badlogic.gdx.utils.JsonValue("W"))
    val z: com.badlogic.gdx.utils.JsonValue = new com.badlogic.gdx.utils.JsonValue("Z")
    z.name$field = "d"
    `object`.setChild(z)
    org.junit.Assert.assertEquals(`object`.get("a").parent(), `object`)
    org.junit.Assert.assertEquals(`object`.get("a").asString(), "W")
    org.junit.Assert.assertEquals(`object`.get("b").asString(), "X")
    org.junit.Assert.assertEquals(`object`.get("c").asString(), "Y")
    org.junit.Assert.assertEquals(`object`.get("d").asString(), "Z")
  }
  def testCopyConstructor(): scala.Unit = {
    val b: com.badlogic.gdx.utils.JsonValue = new com.badlogic.gdx.utils.JsonValue(com.badlogic.gdx.utils.JsonValue.ValueType.`object`)
    b.addChild("c", new com.badlogic.gdx.utils.JsonValue("C"))
    b.addChild("d", new com.badlogic.gdx.utils.JsonValue("D"))
    val `object`: com.badlogic.gdx.utils.JsonValue = new com.badlogic.gdx.utils.JsonValue(com.badlogic.gdx.utils.JsonValue.ValueType.`object`)
    `object`.addChild("a", new com.badlogic.gdx.utils.JsonValue("A"))
    `object`.addChild("b", b)
    `object`.addChild("e", new com.badlogic.gdx.utils.JsonValue(123))
    val copy: com.badlogic.gdx.utils.JsonValue = new com.badlogic.gdx.utils.JsonValue(`object`)
    org.junit.Assert.assertEquals(`object`.get("a").asString(), "A")
    org.junit.Assert.assertEquals(`object`.get("b"), b)
    org.junit.Assert.assertEquals(`object`.get("b").get("c").asString(), "C")
    org.junit.Assert.assertEquals(`object`.get("b").get("d").asString(), "D")
    org.junit.Assert.assertEquals(`object`.get("b").parent(), `object`)
    org.junit.Assert.assertEquals(`object`.get("e").asInt(), 123)
    org.junit.Assert.assertNull(`object`.get("E"))
    org.junit.Assert.assertEquals(`object`.getIgnoreCase("E").asInt(), 123)
    org.junit.Assert.assertEquals(copy.get("a").asString(), "A")
    org.junit.Assert.assertNotEquals(copy.get("b"), b)
    org.junit.Assert.assertEquals(copy.get("b").get("c").asString(), "C")
    org.junit.Assert.assertEquals(copy.get("b").get("d").asString(), "D")
    org.junit.Assert.assertEquals(copy.get("b").parent(), copy)
    org.junit.Assert.assertEquals(copy.get("e").asInt(), 123)
    org.junit.Assert.assertNull(copy.get("E"))
    org.junit.Assert.assertEquals(copy.getIgnoreCase("E").asInt(), 123)
    val bCopy: com.badlogic.gdx.utils.JsonValue = new com.badlogic.gdx.utils.JsonValue(copy.get("b"))
    org.junit.Assert.assertNotEquals(b, bCopy)
    org.junit.Assert.assertNotEquals(copy.get("b"), bCopy)
    org.junit.Assert.assertEquals(bCopy.get("c").asString(), "C")
    org.junit.Assert.assertEquals(bCopy.get("d").asString(), "D")
    org.junit.Assert.assertEquals(bCopy.get("d").parent(), bCopy)
  }
}