package com.badlogic.gdx.utils

class JsonValueTest extends munit.FunSuite {
  test("testAddingRemovedValue")({
    val firstObject: com.badlogic.gdx.utils.JsonValue = new com.badlogic.gdx.utils.JsonValue(com.badlogic.gdx.utils.JsonValue.ValueType.`object`)
    val secondObject: com.badlogic.gdx.utils.JsonValue = new com.badlogic.gdx.utils.JsonValue(com.badlogic.gdx.utils.JsonValue.ValueType.`object`)
    firstObject.addChild("a", new com.badlogic.gdx.utils.JsonValue("A"))
    secondObject.addChild("b", new com.badlogic.gdx.utils.JsonValue("B"))
    secondObject.addChild("c", new com.badlogic.gdx.utils.JsonValue("C"))
    val b: com.badlogic.gdx.utils.JsonValue = secondObject.remove("b")
    firstObject.addChild(b)
    assertNotEquals(firstObject.get("a"), null)
    assertNotEquals(firstObject.get("b"), null)
    assertEquals(firstObject.get("c"), null)
    assertEquals(secondObject.get("a"), null)
    assertEquals(secondObject.get("b"), null)
    assertNotEquals(secondObject.get("c"), null)
  })
  test("testReplaceValue")({
    val `object`: com.badlogic.gdx.utils.JsonValue = new com.badlogic.gdx.utils.JsonValue(com.badlogic.gdx.utils.JsonValue.ValueType.`object`)
    `object`.addChild("a", new com.badlogic.gdx.utils.JsonValue("A"))
    `object`.addChild("b", new com.badlogic.gdx.utils.JsonValue("B"))
    `object`.addChild("c", new com.badlogic.gdx.utils.JsonValue("C"))
    `object`.addChild("d", new com.badlogic.gdx.utils.JsonValue("D"))
    `object`.setChild("b", new com.badlogic.gdx.utils.JsonValue("X"))
    `object`.setChild("c", new com.badlogic.gdx.utils.JsonValue("Y"))
    assertEquals("A", `object`.get("a").asString())
    assertEquals("X", `object`.get("b").asString())
    assertEquals("Y", `object`.get("c").asString())
    assertEquals("D", `object`.get("d").asString())
    `object`.setChild("a", new com.badlogic.gdx.utils.JsonValue("W"))
    val z: com.badlogic.gdx.utils.JsonValue = new com.badlogic.gdx.utils.JsonValue("Z")
    z.name$field = "d"
    `object`.setChild(z)
    assertEquals(`object`, `object`.get("a").parent())
    assertEquals("W", `object`.get("a").asString())
    assertEquals("X", `object`.get("b").asString())
    assertEquals("Y", `object`.get("c").asString())
    assertEquals("Z", `object`.get("d").asString())
  })
  test("testCopyConstructor")({
    val b: com.badlogic.gdx.utils.JsonValue = new com.badlogic.gdx.utils.JsonValue(com.badlogic.gdx.utils.JsonValue.ValueType.`object`)
    b.addChild("c", new com.badlogic.gdx.utils.JsonValue("C"))
    b.addChild("d", new com.badlogic.gdx.utils.JsonValue("D"))
    val `object`: com.badlogic.gdx.utils.JsonValue = new com.badlogic.gdx.utils.JsonValue(com.badlogic.gdx.utils.JsonValue.ValueType.`object`)
    `object`.addChild("a", new com.badlogic.gdx.utils.JsonValue("A"))
    `object`.addChild("b", b)
    `object`.addChild("e", new com.badlogic.gdx.utils.JsonValue(123))
    val copy: com.badlogic.gdx.utils.JsonValue = new com.badlogic.gdx.utils.JsonValue(`object`)
    assertEquals("A", `object`.get("a").asString())
    assertEquals(b, `object`.get("b"))
    assertEquals("C", `object`.get("b").get("c").asString())
    assertEquals("D", `object`.get("b").get("d").asString())
    assertEquals(`object`, `object`.get("b").parent())
    assertEquals(123, `object`.get("e").asInt())
    assertEquals(`object`.get("E"), null)
    assertEquals(123, `object`.getIgnoreCase("E").asInt())
    assertEquals("A", copy.get("a").asString())
    assertNotEquals(b, copy.get("b"))
    assertEquals("C", copy.get("b").get("c").asString())
    assertEquals("D", copy.get("b").get("d").asString())
    assertEquals(copy, copy.get("b").parent())
    assertEquals(123, copy.get("e").asInt())
    assertEquals(copy.get("E"), null)
    assertEquals(123, copy.getIgnoreCase("E").asInt())
    val bCopy: com.badlogic.gdx.utils.JsonValue = new com.badlogic.gdx.utils.JsonValue(copy.get("b"))
    assertNotEquals(bCopy, b)
    assertNotEquals(bCopy, copy.get("b"))
    assertEquals("C", bCopy.get("c").asString())
    assertEquals("D", bCopy.get("d").asString())
    assertEquals(bCopy, bCopy.get("d").parent())
  })
}