package com.badlogic.gdx.utils

class JsonValueTest extends balticporter.runtime.PortedSuite {
  testCase("testAddingRemovedValue", {
    val firstObject: com.badlogic.gdx.utils.JsonValue = new com.badlogic.gdx.utils.JsonValue(com.badlogic.gdx.utils.JsonValue.ValueType.`object`)
    val secondObject: com.badlogic.gdx.utils.JsonValue = new com.badlogic.gdx.utils.JsonValue(com.badlogic.gdx.utils.JsonValue.ValueType.`object`)
    firstObject.addChild("a", new com.badlogic.gdx.utils.JsonValue("A"))
    secondObject.addChild("b", new com.badlogic.gdx.utils.JsonValue("B"))
    secondObject.addChild("c", new com.badlogic.gdx.utils.JsonValue("C"))
    val b: com.badlogic.gdx.utils.JsonValue = secondObject.remove("b")
    firstObject.addChild(b)
    assertNotNull(firstObject.get("a"))
    assertNotNull(firstObject.get("b"))
    assertNull(firstObject.get("c"))
    assertNull(secondObject.get("a"))
    assertNull(secondObject.get("b"))
    assertNotNull(secondObject.get("c"))
  })
  testCase("testReplaceValue", {
    val `object`: com.badlogic.gdx.utils.JsonValue = new com.badlogic.gdx.utils.JsonValue(com.badlogic.gdx.utils.JsonValue.ValueType.`object`)
    `object`.addChild("a", new com.badlogic.gdx.utils.JsonValue("A"))
    `object`.addChild("b", new com.badlogic.gdx.utils.JsonValue("B"))
    `object`.addChild("c", new com.badlogic.gdx.utils.JsonValue("C"))
    `object`.addChild("d", new com.badlogic.gdx.utils.JsonValue("D"))
    `object`.setChild("b", new com.badlogic.gdx.utils.JsonValue("X"))
    `object`.setChild("c", new com.badlogic.gdx.utils.JsonValue("Y"))
    assertEquals(`object`.get("a").asString(), "A")
    assertEquals(`object`.get("b").asString(), "X")
    assertEquals(`object`.get("c").asString(), "Y")
    assertEquals(`object`.get("d").asString(), "D")
    `object`.setChild("a", new com.badlogic.gdx.utils.JsonValue("W"))
    val z: com.badlogic.gdx.utils.JsonValue = new com.badlogic.gdx.utils.JsonValue("Z")
    z.name$field = "d"
    `object`.setChild(z)
    assertEquals(`object`.get("a").parent(), `object`)
    assertEquals(`object`.get("a").asString(), "W")
    assertEquals(`object`.get("b").asString(), "X")
    assertEquals(`object`.get("c").asString(), "Y")
    assertEquals(`object`.get("d").asString(), "Z")
  })
  testCase("testCopyConstructor", {
    val b: com.badlogic.gdx.utils.JsonValue = new com.badlogic.gdx.utils.JsonValue(com.badlogic.gdx.utils.JsonValue.ValueType.`object`)
    b.addChild("c", new com.badlogic.gdx.utils.JsonValue("C"))
    b.addChild("d", new com.badlogic.gdx.utils.JsonValue("D"))
    val `object`: com.badlogic.gdx.utils.JsonValue = new com.badlogic.gdx.utils.JsonValue(com.badlogic.gdx.utils.JsonValue.ValueType.`object`)
    `object`.addChild("a", new com.badlogic.gdx.utils.JsonValue("A"))
    `object`.addChild("b", b)
    `object`.addChild("e", new com.badlogic.gdx.utils.JsonValue(123))
    val copy: com.badlogic.gdx.utils.JsonValue = new com.badlogic.gdx.utils.JsonValue(`object`)
    assertEquals(`object`.get("a").asString(), "A")
    assertEquals(`object`.get("b"), b)
    assertEquals(`object`.get("b").get("c").asString(), "C")
    assertEquals(`object`.get("b").get("d").asString(), "D")
    assertEquals(`object`.get("b").parent(), `object`)
    assertEquals(`object`.get("e").asInt(), 123)
    assertNull(`object`.get("E"))
    assertEquals(`object`.getIgnoreCase("E").asInt(), 123)
    assertEquals(copy.get("a").asString(), "A")
    assertNotEquals(copy.get("b"), b)
    assertEquals(copy.get("b").get("c").asString(), "C")
    assertEquals(copy.get("b").get("d").asString(), "D")
    assertEquals(copy.get("b").parent(), copy)
    assertEquals(copy.get("e").asInt(), 123)
    assertNull(copy.get("E"))
    assertEquals(copy.getIgnoreCase("E").asInt(), 123)
    val bCopy: com.badlogic.gdx.utils.JsonValue = new com.badlogic.gdx.utils.JsonValue(copy.get("b"))
    assertNotEquals(b, bCopy)
    assertNotEquals(copy.get("b"), bCopy)
    assertEquals(bCopy.get("c").asString(), "C")
    assertEquals(bCopy.get("d").asString(), "D")
    assertEquals(bCopy.get("d").parent(), bCopy)
  })
}