package balticporter.emit

import balticporter.core.*
import balticporter.core.BExpr.*

/** Deterministic BIR → Scala 3 printer. Pure function of (unit, provenance):
  * same input + same engine version = byte-identical output.
  *
  * M0 conventions (M1 will refine): fully-qualified type references except
  * java.lang and same-package types; every binary expression parenthesized;
  * no import synthesis. Constructor translation follows PLAN.md's funnel
  * strategies; the two-ctor sentinel merge mirrors the idiom used across the
  * hand-ported corpus (see ssg Filter.scala).
  */
object ScalaPrinter:

  def print(unit: BUnit, prov: Provenance): String =
    new Printer(unit, prov).result()

private final class Printer(unit: BUnit, prov: Provenance):
  private val sb = new StringBuilder
  private var indent = 0

  private def line(s: String = ""): Unit =
    if s.isEmpty then sb.append('\n')
    else sb.append("  " * indent).append(s).append('\n')

  /** Renders `body`'s line() output into a string instead of the document —
    * the mechanism for multi-line expressions (anonymous class bodies).
    */
  private def captured(body: => Unit): String =
    val mark = sb.length
    body
    val s = sb.substring(mark)
    sb.setLength(mark)
    s

  private def unsupported(what: String): Nothing =
    throw Unsupported(unit.sourcePath, "-", what)

  def result(): String =
    header()
    if unit.pkg.nonEmpty then
      line(s"package ${unit.pkg.split('.').map(id).mkString(".")}")
      line()
    unit.types.foreach(typeDecl)
    sb.toString

  private def header(): Unit =
    line("/*")
    line(s" * Generated by Baltic Porter ${EngineInfo.version} — DO NOT EDIT; regenerate instead.")
    line(" *")
    line(s" * Ported from: ${prov.sourcePathPrefix}/${unit.sourcePath}")
    line(s" * Original license: ${prov.originalLicense} (see ${prov.upstreamName} upstream)")
    line(s" * upstream-commit: ${prov.upstreamCommit}")
    line(" */")

  // ---- names & types ---------------------------------------------------------

  private val keywords = Set(
    "abstract", "case", "catch", "class", "def", "do", "else", "enum", "export", "extends",
    "false", "final", "finally", "for", "given", "if", "implicit", "import", "lazy", "match",
    "new", "null", "object", "override", "package", "private", "protected", "return", "sealed",
    "super", "then", "throw", "trait", "true", "try", "type", "val", "var", "while", "with", "yield",
  )

  private def id(name: String): String =
    if keywords.contains(name) then s"`$name`" else name

  private def pkgOfQ(q: String): String = q.lastIndexOf('.') match
    case -1 => ""
    case i  => q.substring(0, i)

  private def refName(q0: String): String =
    // Spoon qualifies nested types as Outer$Inner; the companion encoding makes that Outer.Inner
    val q = q0.replace('$', '.')
    val name =
      if q == BType.ObjectQ then "Any"
      else if q == "java.lang.String" then "String"
      else if pkgOfQ(q) == "java.lang" then q.substring("java.lang.".length)
      else if q.startsWith(unit.pkg + ".") && pkgOfQ(q0).length <= unit.pkg.length then
        q.substring(unit.pkg.length + 1)
      else q
    // Scala keywords can appear as Java package segments (e.g. jackson.core.type)
    name.split('.').map(id).mkString(".")

  private val primMap = Map(
    "void" -> "Unit", "int" -> "Int", "long" -> "Long", "double" -> "Double", "float" -> "Float",
    "boolean" -> "Boolean", "char" -> "Char", "byte" -> "Byte", "short" -> "Short",
  )

  private def tpe(t: BType): String = t match
    case BType.Prim(n)       => primMap.getOrElse(n, unsupported(s"primitive $n"))
    case BType.Ref(q, Nil)   => refName(q)
    case BType.Ref(q, args)  => s"${refName(q)}[${args.map(tpe).mkString(", ")}]"
    case BType.Arr(e)        => s"Array[${tpe(e)}]"
    case BType.TVar(n)       => n
    case BType.Wild(up, lo) =>
      (up, lo) match
        case (Some(u), None) => s"? <: ${tpe(u)}"
        case (None, Some(l)) => s"? >: ${tpe(l)}"
        case _               => "?"

  private def innermostPkg: String = unit.pkg.lastIndexOf('.') match
    case -1 => unit.pkg
    case i  => unit.pkg.substring(i + 1)

  private def visPrefix(m: Mods): String = m.vis match
    case Vis.Public         => ""
    case Vis.Private        => "private "
    case Vis.Protected      => if unit.pkg.isEmpty then "protected " else s"protected[$innermostPkg] "
    case Vis.PackagePrivate => if unit.pkg.isEmpty then "private " else s"private[$innermostPkg] "

  // ---- trivia ----------------------------------------------------------------

  private def trivia(ts: List[Trivia]): Unit =
    ts.foreach { t =>
      t.text.linesIterator.zipWithIndex.foreach { case (l, i) =>
        // continuation lines of block comments keep a leading space so `*` aligns under `/*`
        if i == 0 then line(l.trim) else line(" " + l.trim)
      }
    }

  // ---- declarations ----------------------------------------------------------

  private def typeDecl(t: BTypeDecl): Unit = t.kind match
    case BTypeKind.Interface => traitDecl(t)
    case BTypeKind.Class     => classDecl(t)
    case BTypeKind.Enum      => enumDecl(t)

  /** Java enum → `enum E(val params) extends java.lang.Enum[E]` (the conversion rule
    * both target repos mandate; parameterized cases per the corpus encoding).
    */
  private def enumDecl(t: BTypeDecl): Unit =
    trivia(t.leading)
    val plan = CtorPlan.of(t, unit)
    trivia(plan.primaryLeading)
    t.serialVersionUID.foreach(v => line(s"@SerialVersionUID(${v}L)"))
    // enum ctors are implicitly private in Java; the Scala enum primary stays unmodified
    val primary = plan.primaryParams match
      case Nil => ""
      case ps  => "(" + ps.map(paramStr).mkString(", ") + ")"
    val ext = (s"java.lang.Enum[${id(t.name)}]" :: t.interfaces.map(tpe)).mkString(" extends ", " with ", "")
    line(s"${visPrefix(t.mods)}enum ${id(t.name)}$primary$ext {")
    indent += 1
    t.enumCases.foreach { c =>
      trivia(c.leading)
      if c.args.isEmpty && plan.primaryParams.isEmpty then line(s"case ${id(c.name)}")
      else line(s"case ${id(c.name)} extends ${id(t.name)}(${c.args.map(expr).mkString(", ")})")
    }
    line()
    plan.fieldLines.foreach {
      case FieldLine.FromField(f, init) =>
        trivia(f.leading)
        val kw = if f.mods.isFinal then "val" else "var"
        line(s"${visPrefix(f.mods)}$kw ${id(f.name)}: ${tpe(f.tpe)} = ${expr(init)}")
        line()
      case FieldLine.SentinelVal(f, pname, default) =>
        trivia(f.leading)
        line(s"${visPrefix(f.mods)}val ${id(f.name)}: ${tpe(f.tpe)} = if (${id(pname)} != null) ${id(pname)} else ${expr(default)}")
        line()
      case FieldLine.DefaultInit(f) =>
        trivia(f.leading)
        line(s"${visPrefix(f.mods)}var ${id(f.name)}: ${tpe(f.tpe)} = ${defaultOf(f.tpe)}")
        line()
    }
    if plan.primaryBody.nonEmpty then
      plan.primaryBody.foreach(stmt)
      line()
    t.methods.foreach(methodDecl)
    indent -= 1
    line("}")
    companion(t)

  private def traitDecl(t: BTypeDecl): Unit =
    trivia(t.leading)
    val ext =
      if t.interfaces.isEmpty then ""
      else " extends " + t.interfaces.map(tpe).mkString(" with ")
    line(s"${visPrefix(t.mods)}trait ${id(t.name)}${tparamsStr(t.tparams)}$ext {")
    indent += 1
    t.methods.foreach(methodDecl)
    indent -= 1
    line("}")
    companion(t)

  /** Java statics + static nested types → companion object (RESEARCH.md §4.2;
    * init-order caveats documented there).
    */
  private def companion(t: BTypeDecl): Unit =
    if t.staticFields.nonEmpty || t.staticMethods.nonEmpty || t.nested.nonEmpty then
      line()
      line(s"object ${id(t.name)} {")
      indent += 1
      t.staticFields.foreach { f =>
        trivia(f.leading)
        val kw = if f.mods.isFinal then "val" else "var"
        val rhs = f.init.map(expr).getOrElse(defaultOf(f.tpe))
        line(s"${visPrefix(f.mods)}$kw ${id(f.name)}: ${tpe(f.tpe)} = $rhs")
        line()
      }
      t.staticMethods.foreach(methodDecl)
      t.nested.foreach { n =>
        typeDecl(n)
        line()
      }
      indent -= 1
      line("}")

  private def tparamsStr(tps: List[BTypeParam]): String =
    if tps.isEmpty then ""
    else "[" + tps.map(tp => tp.name + tp.upper.map(u => s" <: ${tpe(u)}").getOrElse("")).mkString(", ") + "]"

  private def classDecl(t: BTypeDecl): Unit =
    trivia(t.leading)
    val plan = CtorPlan.of(t, unit)
    trivia(plan.primaryLeading)
    t.serialVersionUID.foreach(v => line(s"@SerialVersionUID(${v}L)"))
    val mods = StringBuilder(visPrefix(t.mods))
    if t.mods.isAbstract then mods.append("abstract ")
    if t.mods.isFinal then mods.append("final ")

    val primaryVis = plan.primaryMods
      .map(m => visPrefix(m).trim)
      .filter(_.nonEmpty)
      .map(v => s" $v ")
      .getOrElse("")
    val primary = plan.primaryParams match
      case Nil => ""
      case ps  => primaryVis + "(" + ps.map(paramStr).mkString(", ") + ")"
    val ext = (t.superClass, plan.superArgs) match
      case (None, _) if t.interfaces.isEmpty => ""
      case (None, _)         => " extends " + t.interfaces.map(tpe).mkString(" with ")
      case (Some(s), args)   =>
        val sup = tpe(s) + (if args.isEmpty then "" else "(" + args.map(expr).mkString(", ") + ")")
        " extends " + (sup :: t.interfaces.map(tpe)).mkString(" with ")

    line(s"${mods.result()}class ${id(t.name)}${tparamsStr(t.tparams)}$primary$ext {")
    indent += 1

    plan.fieldLines.foreach {
      case FieldLine.FromField(f, init) =>
        trivia(f.leading)
        val kw = if f.mods.isFinal then "val" else "var"
        line(s"${visPrefix(f.mods)}$kw ${id(f.name)}: ${tpe(f.tpe)} = ${expr(init)}")
        line()
      case FieldLine.SentinelVal(f, pname, default) =>
        trivia(f.leading)
        line(s"${visPrefix(f.mods)}val ${id(f.name)}: ${tpe(f.tpe)} = if (${id(pname)} != null) ${id(pname)} else ${expr(default)}")
        line()
      case FieldLine.DefaultInit(f) =>
        trivia(f.leading)
        line(s"${visPrefix(f.mods)}var ${id(f.name)}: ${tpe(f.tpe)} = ${defaultOf(f.tpe)}")
        line()
    }
    plan.secondaryCtors.foreach { sc =>
      trivia(sc.leading)
      val sig = s"${visPrefix(sc.mods)}def this(${sc.params.map(paramOf).mkString(", ")}) ="
      if sc.body.isEmpty then
        line(sig)
        indent += 1
        line(s"this(${sc.delegateArgs.map(expr).mkString(", ")})")
        indent -= 1
      else
        line(sig + " {")
        indent += 1
        line(s"this(${sc.delegateArgs.map(expr).mkString(", ")})")
        sc.body.foreach(stmt)
        indent -= 1
        line("}")
      line()
    }
    if plan.primaryBody.nonEmpty then
      plan.primaryBody.foreach(stmt)
      line()
    t.methods.foreach(methodDecl)

    indent -= 1
    line("}")
    companion(t)

  private def paramStr(p: CtorPlan.Param): String =
    p.promoted match
      case Some(f) => s"${visPrefix(f.mods)}val ${id(p.p.name)}: ${tpe(p.p.tpe)}"
      case None    => paramOf(p.p)

  private def paramOf(p: BParam): String =
    val t = if p.varargs then
      p.tpe match
        case BType.Arr(e) => tpe(e) + "*"
        case other        => tpe(other) + "*"
    else tpe(p.tpe)
    s"${id(p.name)}: $t"

  private def methodDecl(m: BMethod): Unit =
    trivia(m.leading)
    val mods = StringBuilder(visPrefix(m.mods))
    if m.mods.isOverride then mods.append("override ")
    if m.mods.isFinal then mods.append("final ")

    // Java parameters are mutable; reassigned ones become `_p` + `var p = _p`.
    val paramStrs = m.params.map { p =>
      if m.assignedParams.contains(p.name) then paramOf(p.copy(name = "_" + p.name)) else paramOf(p)
    }
    val sig = s"${mods.result()}def ${id(m.name)}${tparamsStr(m.tparams)}(${paramStrs.mkString(", ")}): ${tpe(m.ret)}"
    m.body match
      case None => line(sig)
      case Some(body) =>
        line(sig + " = {")
        indent += 1
        m.params.filter(p => m.assignedParams.contains(p.name)).foreach { p =>
          val t = if p.varargs then unsupported(s"reassigned varargs parameter ${p.name}") else tpe(p.tpe)
          line(s"var ${id(p.name)}: $t = ${id("_" + p.name)}")
        }
        printBody(body)
        indent -= 1
        line("}")
    line()

  // ---- statements ------------------------------------------------------------

  /** Prints a method body; a trailing `return e` prints as `e`. */
  private def printBody(body: List[BStmt]): Unit =
    body.zipWithIndex.foreach { case (s, i) =>
      val isLast = i == body.length - 1
      s.k match
        case BStmtK.Return(Some(e)) if isLast => trivia(s.leading); line(expr(e))
        case _                                => stmt(s)
    }

  private def stmt(s: BStmt): Unit =
    trivia(s.leading)
    s.k match
      case BStmtK.LocalVar(name, t, init, effFinal) =>
        val kw = if effFinal then "val" else "var"
        val rhs = init.map(expr).getOrElse(defaultOf(t))
        line(s"$kw ${id(name)}: ${tpe(t)} = $rhs")
      case BStmtK.ExprStmt(e) => line(expr(e))
      case BStmtK.Assign(lhs, rhs, op) =>
        line(s"${expr(lhs)} ${op.getOrElse("")}= ${expr(rhs)}")
      case BStmtK.If(c, t, e) =>
        line(s"if (${expr(c)}) {")
        indent += 1; t.foreach(stmt); indent -= 1
        e match
          case None => line("}")
          case Some(els) =>
            line("} else {")
            indent += 1; els.foreach(stmt); indent -= 1
            line("}")
      case BStmtK.Return(None)    => line("return")
      case BStmtK.Return(Some(e)) => line(s"return ${expr(e)}")
      case BStmtK.Throw(e)        => line(s"throw ${expr(e)}")
      case BStmtK.While(c, b) =>
        line(s"while (${expr(c)}) {")
        indent += 1; b.foreach(stmt); indent -= 1
        line("}")
      case BStmtK.Block(b) =>
        line("{")
        indent += 1; b.foreach(stmt); indent -= 1
        line("}")
      case BStmtK.Try(b, catches, fin) =>
        line("try {")
        indent += 1; b.foreach(stmt); indent -= 1
        if catches.nonEmpty then
          line("} catch {")
          indent += 1
          catches.foreach { c =>
            val pat = c.types match
              case List(t1) => s"${id(c.param)}: ${tpe(t1)}"
              case ts       => s"${id(c.param)} @ (${ts.map(t1 => s"_: ${tpe(t1)}").mkString(" | ")})"
            line(s"case $pat =>")
            indent += 1; c.body.foreach(stmt); indent -= 1
          }
          indent -= 1
        fin match
          case Some(f) =>
            line("} finally {")
            indent += 1; f.foreach(stmt); indent -= 1
            line("}")
          case None => line("}")
      case BStmtK.Boundary(b) =>
        line("scala.util.boundary {")
        indent += 1; b.foreach(stmt); indent -= 1
        line("}")
      case BStmtK.LoopBreak => line("scala.util.boundary.break()")
      case BStmtK.Match(scrutinee, cases) =>
        line(s"${expr(scrutinee)} match {")
        indent += 1
        cases.foreach { c =>
          val pat = if c.isDefault then "_" else c.exprs.map(expr).mkString(" | ")
          line(s"case $pat =>")
          indent += 1
          if c.body.isEmpty then line("()") else c.body.foreach(stmt)
          indent -= 1
        }
        indent -= 1
        line("}")
      case BStmtK.Empty => ()

  private def defaultOf(t: BType): String = t match
    case BType.Prim("boolean")                          => "false"
    case BType.Prim("float")                            => "0.0f"
    case BType.Prim("double")                           => "0.0d"
    case BType.Prim("long")                             => "0L"
    case BType.Prim("char")                             => "'\\u0000'"
    case BType.Prim(_)                                  => "0"
    case _                                              => "null"

  // ---- expressions -----------------------------------------------------------

  private def expr(e: BExpr): String = e match
    case Lit(_, raw)   => raw
    case Ident(n, RefKind.StaticField(owner)) => s"${refName(owner)}.${id(n)}"
    case Ident(n, _)   => id(n)
    case This          => "this"
    case Select(r, n)  => s"${expr(r)}.${id(n)}"
    case ArrayLength(a) => s"${expr(a)}.length"
    case ArrayAccess(a, i) => s"${expr(a)}(${expr(i)})"
    case Typed(inner, _) => expr(inner)

    case Call(recv, name, args, formals, ownerQ) =>
      val target = recv match
        case Recv.OnThis        => ""
        case Recv.OnSuper       => "super."
        case Recv.Static(owner) => refName(owner) + "."
        case Recv.On(r)         => expr(r) + "."
      s"$target${id(name)}(${adaptedArgs(args, formals, ownerQ).mkString(", ")})"

    case New(t, args, anon) =>
      val argsStr = if args.isEmpty && anon.isDefined then "" else s"(${args.map(expr).mkString(", ")})"
      val base = s"new ${tpe(t)}$argsStr"
      anon match
        case None => base
        case Some(BAnonBody(Nil, Nil)) => base + " {}"
        case Some(BAnonBody(fields, methods)) =>
          val body = captured {
            indent += 1
            fields.foreach { f =>
              trivia(f.leading)
              val kw = if f.mods.isFinal then "val" else "var"
              val rhs = f.init.map(expr).getOrElse(defaultOf(f.tpe))
              line(s"${visPrefix(f.mods)}$kw ${id(f.name)}: ${tpe(f.tpe)} = $rhs")
            }
            methods.foreach(methodDecl)
            indent -= 1
          }
          base + " {\n" + body + ("  " * indent) + "}"
    case NewArray(el, _, Some(inits)) => s"Array[${tpe(el)}](${inits.map(expr).mkString(", ")})"
    case NewArray(el, List(dim), None) => s"new Array[${tpe(el)}](${expr(dim)})"
    case NewArray(_, dims, None) => unsupported(s"multi-dimensional array (${dims.length} dims)")

    case Binary(op, l, r, _) => s"(${expr(l)} $op ${expr(r)})"
    case Unary(op, e1, true) => s"($op${expr(e1)})"
    case Unary(op, _, false) => unsupported(s"postfix operator $op")
    case Ternary(c, t, e1)    => s"(if (${expr(c)}) ${expr(t)} else ${expr(e1)})"

    case MethodRef(prefix, name) =>
      prefix match
        case Left(owner) => s"${refName(owner)}.${id(name)}"
        case Right(r)    => s"${expr(r)}.${id(name)}"

    case Lambda(ps, body) =>
      val plist = ps match
        case List(p1) => id(p1)
        case _        => "(" + ps.map(id).mkString(", ") + ")"
      body match
        case Right(e)                                     => s"($plist => ${expr(e)})"
        case Left(List(BStmt(_, BStmtK.Return(Some(e))))) => s"($plist => ${expr(e)})"
        case Left(List(BStmt(_, BStmtK.ExprStmt(e))))     => s"($plist => ${expr(e)})"
        case Left(_)                                      => unsupported("multi-statement lambda body")

    case Cast(BType.Prim(p), e1) =>
      val conv = primMap.getOrElse(p, unsupported(s"cast to $p"))
      s"${expr(e1)}.to$conv"
    case Cast(t, e1)       => s"${expr(e1)}.asInstanceOf[${tpe(t)}]"
    case InstanceOf(e1, t) => s"${expr(e1)}.isInstanceOf[${tpe(t)}]"
    case ClassLit(t)       => s"classOf[${tpe(t)}]"

  /** Call-site adaptation of Java varargs/array boundaries (RESEARCH.md §4.2):
    *   - varargs param forwarded into a varargs slot        → spread `p*`
    *   - varargs param passed where an array is expected    → `p.toArray`
    *     (`.asInstanceOf[Array[AnyRef]]` when the callee is a JDK Object[] slot,
    *     since translated code maps Object → Any but the JDK keeps AnyRef)
    */
  private def adaptedArgs(args: List[BExpr], formals: Option[List[Formal]], ownerQ: Option[String]): List[String] =
    val jdkOwner = ownerQ.exists(q => q.startsWith("java.") || q.startsWith("javax."))
    formals match
      case Some(fs) if fs.length == args.length =>
        args.zip(fs).map {
          case (a @ Ident(_, RefKind.Param(true)), Formal(_, true)) => expr(a) + "*"
          case (a @ Ident(_, RefKind.Param(true)), Formal(BType.Arr(el), false)) =>
            val conv = expr(a) + ".toArray"
            if jdkOwner && BType.isObject(el) then conv + ".asInstanceOf[Array[AnyRef]]" else conv
          case (a, _) => expr(a)
        }
      case _ => args.map(expr)
