package com.badlogic.gdx.net

trait HttpRequestHeader
object HttpRequestHeader {
  final val Accept: java.lang.String = "Accept"
  final val AcceptCharset: java.lang.String = "Accept-Charset"
  final val AcceptEncoding: java.lang.String = "Accept-Encoding"
  final val AcceptLanguage: java.lang.String = "Accept-Language"
  final val AcceptDatetime: java.lang.String = "Accept-Datetime"
  final val Authorization: java.lang.String = "Authorization"
  final val CacheControl: java.lang.String = "Cache-Control"
  final val Connection: java.lang.String = "Connection"
  final val Cookie: java.lang.String = "Cookie"
  final val ContentLength: java.lang.String = "Content-Length"
  final val ContentMD5: java.lang.String = "Content-MD5"
  final val ContentType: java.lang.String = "Content-Type"
  final val Date: java.lang.String = "Date"
  final val Expect: java.lang.String = "Expect"
  final val From: java.lang.String = "From"
  final val Host: java.lang.String = "Host"
  final val IfMatch: java.lang.String = "If-Match"
  final val IfModifiedSince: java.lang.String = "If-Modified-Since"
  final val IfNoneMatch: java.lang.String = "If-None-Match"
  final val IfRange: java.lang.String = "If-Range"
  final val IfUnmodifiedSince: java.lang.String = "If-Unmodified-Since"
  final val MaxForwards: java.lang.String = "Max-Forwards"
  final val Origin: java.lang.String = "Origin"
  final val Pragma: java.lang.String = "Pragma"
  final val ProxyAuthorization: java.lang.String = "Proxy-Authorization"
  final val Range: java.lang.String = "Range"
  final val Referer: java.lang.String = "Referer"
  final val TE: java.lang.String = "TE"
  final val UserAgent: java.lang.String = "User-Agent"
  final val Upgrade: java.lang.String = "Upgrade"
  final val Via: java.lang.String = "Via"
  final val Warning: java.lang.String = "Warning"
}