package com.badlogic.gdx.net

trait HttpResponseHeader
object HttpResponseHeader {
  final val AccessControlAllowOrigin: java.lang.String = "Access-Control-Allow-Origin"
  final val AcceptRanges: java.lang.String = "Accept-Ranges"
  final val Age: java.lang.String = "Age"
  final val Allow: java.lang.String = "Allow"
  final val CacheControl: java.lang.String = "Cache-Control"
  final val Connection: java.lang.String = "Connection"
  final val ContentEncoding: java.lang.String = "Content-Encoding"
  final val ContentLanguage: java.lang.String = "Content-Language"
  final val ContentLength: java.lang.String = "Content-Length"
  final val ContentLocation: java.lang.String = "Content-Location"
  final val ContentMD5: java.lang.String = "Content-MD5"
  final val ContentDisposition: java.lang.String = "Content-Disposition"
  final val ContentRange: java.lang.String = "Content-Range"
  final val ContentType: java.lang.String = "Content-Type"
  final val Date: java.lang.String = "Date"
  final val ETag: java.lang.String = "ETag"
  final val Expires: java.lang.String = "Expires"
  final val LastModified: java.lang.String = "Last-Modified"
  final val Link: java.lang.String = "Link"
  final val Location: java.lang.String = "Location"
  final val P3P: java.lang.String = "P3P"
  final val Pragma: java.lang.String = "Pragma"
  final val ProxyAuthenticate: java.lang.String = "Proxy-Authenticate"
  final val Refresh: java.lang.String = "Refresh"
  final val RetryAfter: java.lang.String = "Retry-After"
  final val Server: java.lang.String = "Server"
  final val SetCookie: java.lang.String = "Set-Cookie"
  final val Status: java.lang.String = "Status"
  final val StrictTransportSecurity: java.lang.String = "Strict-Transport-Security"
  final val Trailer: java.lang.String = "Trailer"
  final val TransferEncoding: java.lang.String = "Transfer-Encoding"
  final val Upgrade: java.lang.String = "Upgrade"
  final val Vary: java.lang.String = "Vary"
  final val Via: java.lang.String = "Via"
  final val Warning: java.lang.String = "Warning"
  final val WWWAuthenticate: java.lang.String = "WWW-Authenticate"
}