package balticporter.emit

// FROZEN: BIR emission backend. New work goes on TirEmitter. Fix what liqp/flexmark need; add nothing.

import balticporter.core.*
import balticporter.core.BExpr.*

/** Deterministic BIR -> Scala 3 printer. Pure function of (unit, provenance). */
object ScalaPrinter:

  def print(
      unit: BUnit,
      prov: Provenance,
      sentinels: Set[String] = Set.empty,
      registry: Option[CtorRegistry] = None,
      ctorOverrides: Map[String, CtorOverride] = Map.empty,
  ): String =
    new Printer(MemberClashPass(widenFields(unit, registry), registry), prov, sentinels, registry, ctorOverrides).result()

  /** Widen private non-final fields assigned by subclass effect-replay to `protected`. */
  private def widenFields(unit: BUnit, registry: Option[CtorRegistry]): BUnit =
    registry match
      case None => unit
      case Some(reg) =>
        val w = reg.widenedFields
        if w.isEmpty then unit
        else
          unit.copy(types = unit.types.map { t =>
            val fqcn = if unit.pkg.isEmpty then t.name else s"${unit.pkg}.${t.name}"
            t.copy(fields = t.fields.map { f =>
              if w((fqcn, f.name)) then f.copy(mods = f.mods.copy(vis = Vis.Protected)) else f
            })
          })

/** Classes whose no-arg path equals the null sentinel (transitive). */
object SentinelRegistry:
  def compute(units: List[BUnit]): Set[String] =
    var acc = Set.empty[String]
    var changed = true
    while changed do
      changed = false
      units.foreach { u =>
        u.types.foreach { t =>
          val fqcn = if u.pkg.isEmpty then t.name else s"${u.pkg}.${t.name}"
          if !acc.contains(fqcn) then
            val sentinelish =
              try CtorPlan.of(t, u, acc).sentinelLike
              catch case _: Unsupported => false
            if sentinelish then
              acc += fqcn
              changed = true
        }
      }
    acc

/** Declaration-level ctor override: `headerSuffix` after `class Name[tparams]`,
  * `body` lines at the top of the class body. Engine emits the rest as usual. */
final case class CtorOverride(headerSuffix: String, body: List[String])

private final class Printer(
    unit: BUnit,
    prov: Provenance,
    sentinels: Set[String],
    registry: Option[CtorRegistry],
    ctorOverrides: Map[String, CtorOverride] = Map.empty,
):
  private val sb = new StringBuilder
  private var indent = 0

  private def line(s: String = ""): Unit =
    if s.isEmpty then sb.append('\n')
    else sb.append("  " * indent).append(s).append('\n')

  /** Capture line() output into a string (for multi-line expressions). */
  private def captured(body: => Unit): String =
    val mark = sb.length
    body
    val s = sb.substring(mark)
    sb.setLength(mark)
    s

  private def unsupported(what: String): Nothing =
    throw Unsupported(unit.sourcePath, "-", what)

  def result(): String =
    header()
    if unit.pkg.nonEmpty then
      line(s"package ${unit.pkg.split('.').map(id).mkString(".")}")
      line()
    unit.types.foreach(typeDecl)
    sb.toString

  private def header(): Unit =
    line("/*")
    line(s" * Generated by Baltic Porter ${EngineInfo.version} — DO NOT EDIT; regenerate instead.")
    line(" *")
    line(s" * Ported from: ${prov.sourcePathPrefix}/${unit.sourcePath}")
    line(s" * Original license: ${prov.originalLicense} (see ${prov.upstreamName} upstream)")
    line(s" * upstream-commit: ${prov.upstreamCommit}")
    line(" */")

  // ---- names & types ---------------------------------------------------------

  private val keywords = Set(
    "abstract", "case", "catch", "class", "def", "do", "else", "enum", "export", "extends",
    "false", "final", "finally", "for", "given", "if", "implicit", "import", "lazy", "match",
    "new", "null", "object", "override", "package", "private", "protected", "return", "sealed",
    "super", "then", "throw", "trait", "true", "try", "type", "val", "var", "while", "with", "yield",
    "macro", "forSome",
    // soft keywords: always safe to backtick
    "using", "extension", "inline", "opaque", "transparent", "derives", "end", "infix",
  )

  private def id(name: String): String =
    if keywords.contains(name) then s"`$name`" else name

  private def pkgOfQ(q: String): String = q.lastIndexOf('.') match
    case -1 => ""
    case i  => q.substring(0, i)

  /** Boxed types whose simple names collide with Scala primitives; never shortened. */
  private val collidingJavaLang = Set(
    "java.lang.Long", "java.lang.Double", "java.lang.Float", "java.lang.Boolean",
    "java.lang.Byte", "java.lang.Short", "java.lang.Character",
    "java.lang.StringBuilder", "java.lang.Iterable", "java.lang.Cloneable",
  )

  /** Inner (non-static) class qnames in this unit; referable only by simple name. */
  private lazy val innerQNames: Set[String] =
    def walk(prefix: String, t: BTypeDecl): List[String] =
      val q = s"$prefix${t.name}"
      t.inner.map(n => s"$q$$${n.name}") ++
        (t.nested ++ t.inner).flatMap(n => walk(s"$q$$", n))
    val pkgPrefix = if unit.pkg.isEmpty then "" else unit.pkg + "."
    unit.types.flatMap(t => walk(pkgPrefix, t)).toSet

  private def refName(q0: String): String =
    if innerQNames.contains(q0) then return id(q0.substring(q0.lastIndexOf('$') + 1))
    // local classes: strip block-counter prefix (Outer$1MyParams -> MyParams)
    val lastSeg0 = q0.substring(q0.lastIndexOf('$') + 1)
    val localStripped = lastSeg0.dropWhile(_.isDigit)
    if q0.contains('$') && lastSeg0.headOption.exists(_.isDigit) && localStripped.nonEmpty then
      return id(localStripped)
    // Spoon qualifies nested types as Outer$Inner; the companion encoding makes that Outer.Inner
    val q = q0.replace('$', '.')
    val name =
      if q == BType.ObjectQ then "Any"
      else if q == "java.lang.String" then "String"
      else if collidingJavaLang.contains(q) then q
      else if pkgOfQ(q) == "java.lang" then q.substring("java.lang.".length)
      else if q.startsWith(unit.pkg + ".") && pkgOfQ(q0).length <= unit.pkg.length then
        q.substring(unit.pkg.length + 1)
      else q
    // Scala keywords can appear as Java package segments (e.g. jackson.core.type)
    name.split('.').map(id).mkString(".")

  private val primMap = Map(
    "void" -> "Unit", "int" -> "Int", "long" -> "Long", "double" -> "Double", "float" -> "Float",
    "boolean" -> "Boolean", "char" -> "Char", "byte" -> "Byte", "short" -> "Short",
  )

  private def tpe(t: BType): String = t match
    case BType.Prim(n)       => primMap.getOrElse(n, unsupported(s"primitive $n"))
    case BType.Ref(q, Nil)   => refName(q)
    case BType.Ref(q, args)  => s"${refName(q)}[${args.map(tpe).mkString(", ")}]"
    case BType.Arr(e)        => s"Array[${arrElem(e)}]"
    case BType.TVar(n)       => n
    case BType.Wild(up, lo) =>
      (up, lo) match
        case (Some(u), None) => s"? <: ${tpe(u)}"
        case (None, Some(l)) => s"? >: ${tpe(l)}"
        case _               => "?"

  /** Object[] -> Array[AnyRef] (arrays are invariant; JDK requires reference types). */
  private def arrElem(e: BType): String =
    if BType.isObject(e) then "AnyRef" else tpe(e)

  private def innermostPkg: String = unit.pkg.lastIndexOf('.') match
    case -1 => unit.pkg
    case i  => unit.pkg.substring(i + 1)

  /** >0 inside a companion: nested private members widen to package scope. */
  private var nestedDepth = 0

  private def visPrefix(m: Mods): String = m.vis match
    case Vis.Public => ""
    case Vis.Private =>
      if nestedDepth > 0 && unit.pkg.nonEmpty then s"private[$innermostPkg] " else "private "
    case Vis.Protected      => if unit.pkg.isEmpty then "protected " else s"protected[$innermostPkg] "
    case Vis.PackagePrivate => if unit.pkg.isEmpty then "private " else s"private[$innermostPkg] "

  // ---- trivia ----------------------------------------------------------------

  private def trivia(ts: List[Trivia]): Unit =
    ts.foreach { t =>
      t.text.linesIterator.zipWithIndex.foreach { case (l, i) =>
        // leading space on continuation lines to align `*` under `/*`
        if i == 0 then line(l.trim) else line(" " + l.trim)
      }
    }

  // ---- declarations ----------------------------------------------------------

  private def typeDecl(t: BTypeDecl): Unit = t.kind match
    case BTypeKind.Interface => traitDecl(t)
    case BTypeKind.Class     => classDecl(t)
    case BTypeKind.Enum      => enumDecl(t)

  /** Java enum -> Scala 3 `enum E(val params) extends java.lang.Enum[E]`. */
  private def enumDecl(t: BTypeDecl): Unit =
    trivia(t.leading)
    val plan = CtorPlan.of(t, unit, sentinels, registry)
    trivia(plan.primaryLeading)
    t.serialVersionUID.foreach(v => line(s"@SerialVersionUID(${v}L)"))
    // enum ctors are implicitly private in Java; the Scala enum primary stays unmodified
    val primary = plan.primaryParams match
      case Nil => ""
      case ps  => "(" + ps.map(paramStr).mkString(", ") + ")"
    val ext = (s"java.lang.Enum[${id(t.name)}]" :: t.interfaces.map(tpe)).mkString(" extends ", " with ", "")
    line(s"${visPrefix(t.mods)}enum ${id(t.name)}$primary$ext {")
    indent += 1
    t.enumCases.foreach { c =>
      trivia(c.leading)
      if c.args.isEmpty && plan.primaryParams.isEmpty then line(s"case ${id(c.name)}")
      else line(s"case ${id(c.name)} extends ${id(t.name)}(${c.args.map(expr).mkString(", ")})")
    }
    line()
    // enum auxiliary constructors
    plan.secondaryCtors.foreach { sc =>
      trivia(sc.leading)
      val dArgs =
        if sc.targetTypes.length == sc.delegateArgs.length then
          sc.delegateArgs.zip(sc.targetTypes).map((a, tt) => delegateArg(a, Some(tt))).mkString(", ")
        else sc.delegateArgs.map(delegateArg).mkString(", ")
      if sc.body.isEmpty then
        line(s"${visPrefix(sc.mods)}def this(${sc.params.map(paramOf).mkString(", ")}) = this($dArgs)")
      else
        line(s"${visPrefix(sc.mods)}def this(${sc.params.map(paramOf).mkString(", ")}) = {")
        indent += 1; line(s"this($dArgs)"); sc.body.foreach(stmt); indent -= 1; line("}")
      line()
    }
    plan.fieldLines.foreach {
      case FieldLine.FromField(f, init) =>
        trivia(f.leading)
        annotationLines(f.mods)
        val kw = if f.mods.isFinal then "val" else "var"
        line(s"${beanPrefix(f, t.methods)}${visPrefix(f.mods)}$kw ${id(f.name)}: ${tpe(f.tpe)} = ${expr(init)}")
        line()
      case FieldLine.SentinelVal(f, pname, default) =>
        trivia(f.leading)
        line(s"${beanPrefix(f, t.methods)}${visPrefix(f.mods)}val ${id(f.name)}: ${tpe(f.tpe)} = if (${id(pname)} != null) ${id(pname)} else ${expr(default)}")
        line()
      case FieldLine.CondInit(f, pname, whenSome, whenNull) =>
        trivia(f.leading)
        val kw = if f.mods.isFinal then "val" else "var"
        line(s"${beanPrefix(f, t.methods)}${visPrefix(f.mods)}$kw ${id(f.name)}: ${tpe(f.tpe)} = if (${id(pname)} != null) ${expr(whenSome)} else ${expr(whenNull)}")
        line()
      case FieldLine.DefaultInit(f) =>
        trivia(f.leading)
        line(s"${beanPrefix(f, t.methods)}${visPrefix(f.mods)}var ${id(f.name)}: ${tpe(f.tpe)} = ${defaultOf(f.tpe)}")
        line()
    }
    if plan.primaryBody.nonEmpty then
      plan.primaryBody.foreach(stmt)
      line()
    t.methods.foreach(methodDecl)
    indent -= 1
    line("}")
    companion(t)

  private def traitDecl(t: BTypeDecl): Unit =
    trivia(t.leading)
    annotationLines(t.mods)
    val ext =
      if t.interfaces.isEmpty then ""
      else " extends " + t.interfaces.map(tpe).mkString(" with ")
    line(s"${visPrefix(t.mods)}trait ${id(t.name)}${tparamsStr(t.tparams)}$ext {")
    indent += 1
    t.methods.foreach(methodDecl)
    indent -= 1
    line("}")
    companion(t)

  /** Java statics + static nested types -> companion object. */
  private def companion(t: BTypeDecl): Unit =
    if t.staticFields.nonEmpty || t.staticMethods.nonEmpty || t.nested.nonEmpty || t.staticInit.nonEmpty then
      line()
      line(s"object ${id(t.name)} {")
      indent += 1
      // blank-final statics assigned in static-init must be var (no deferred val in Scala)
      val reassignedStatics = assignedFieldNames(t.staticInit)
      t.staticFields.foreach { f =>
        trivia(f.leading)
        val kw = if f.mods.isFinal && !reassignedStatics(f.name) then "val" else "var"
        val rhs = f.init.map(expr).getOrElse(defaultOf(f.tpe))
        line(s"${visPrefix(f.mods)}$kw ${id(f.name)}: ${tpe(f.tpe)} = $rhs")
        line()
      }
      if t.staticInit.nonEmpty then
        t.staticInit.foreach(stmt)
        line()
      t.staticMethods.foreach(methodDecl)
      t.nested.foreach { n =>
        nestedDepth += 1
        typeDecl(n)
        nestedDepth -= 1
        line()
      }
      indent -= 1
      line("}")

  /** Field names assigned anywhere in `stmts` (recursing through control flow). */
  private def assignedFieldNames(stmts: List[BStmt]): Set[String] =
    val out = collection.mutable.Set[String]()
    def fieldName(e: BExpr): Option[String] = e match
      case Ident(n, RefKind.StaticField(_)) => Some(n)
      case Ident(n, RefKind.OwnField)       => Some(n)
      case Select(_, n)                     => Some(n)
      case _                                => None
    def walk(ss: List[BStmt]): Unit = ss.foreach(s => walkK(s.k))
    def walkK(k: BStmtK): Unit = k match
      case BStmtK.Assign(lhs, _, _)  => fieldName(lhs).foreach(out += _)
      case BStmtK.If(_, tb, eb)      => walk(tb); eb.foreach(walk)
      case BStmtK.While(_, b)        => walk(b)
      case BStmtK.DoWhile(b, _)      => walk(b)
      case BStmtK.Block(b)           => walk(b)
      case BStmtK.Try(b, cs, f)      => walk(b); cs.foreach(c => walk(c.body)); f.foreach(walk)
      case BStmtK.Boundary(b, _)     => walk(b)
      case BStmtK.Match(_, cases)    => cases.foreach(c => walk(c.body))
      case BStmtK.Synchronized(_, b) => walk(b)
      case _                         => ()
    walk(stmts)
    out.toSet

  private def tparamsStr(tps: List[BTypeParam]): String =
    if tps.isEmpty then ""
    else "[" + tps.map(tp => tp.name + tp.upper.map(u => s" <: ${tpe(u)}").getOrElse("")).mkString(", ") + "]"

  private def classDecl(t: BTypeDecl): Unit =
    trivia(t.leading)
    annotationLines(t.mods)
    val fqcn = if unit.pkg.isEmpty then t.name else s"${unit.pkg}.${t.name}"
    ctorOverrides.get(fqcn).filter(_ => nestedDepth == 0) match
      case Some(ovr) => classDeclOverridden(t, ovr); return
      case None      => ()
    val plan = CtorPlan.of(t, unit, sentinels, registry)
    trivia(plan.primaryLeading)
    t.serialVersionUID.foreach(v => line(s"@SerialVersionUID(${v}L)"))
    val mods = StringBuilder(visPrefix(t.mods))
    if t.mods.isAbstract then mods.append("abstract ")
    if t.mods.isFinal then mods.append("final ")

    // private class: ctor cannot be less private
    val primaryVis =
      if t.mods.vis == Vis.Private then ""
      else
        plan.primaryMods
          .map(m => visPrefix(m).trim)
          .filter(_.nonEmpty)
          .map(v => s" $v ")
          .getOrElse("")
    val reParams = reassignedParams(plan.primaryBody, plan.primaryParams.map(_.p.name).toSet)
    val primary = plan.primaryParams match
      case Nil => ""
      case ps  => primaryVis + "(" + ps.map(paramStr(_, t.methods, reParams)).mkString(", ") + ")"
    val ext = (t.superClass, plan.superArgs) match
      case (None, _) if t.interfaces.isEmpty => ""
      case (None, _)         => " extends " + t.interfaces.map(tpe).mkString(" with ")
      case (Some(s), args)   =>
        val sup = tpe(s) + (if args.isEmpty then "" else "(" + args.map(delegateArg).mkString(", ") + ")")
        " extends " + (sup :: t.interfaces.map(tpe)).mkString(" with ")

    line(s"${mods.result()}class ${id(t.name)}${tparamsStr(t.tparams)}$primary$ext {")
    indent += 1

    if t.staticInit.nonEmpty then
      // force companion init to preserve Java's before-any-instance <clinit> timing
      line(s"locally(${id(t.name)})")
      line()

    plan.fieldLines.foreach {
      case FieldLine.FromField(f, init) =>
        trivia(f.leading)
        annotationLines(f.mods)
        val kw = if f.mods.isFinal then "val" else "var"
        line(s"${beanPrefix(f, t.methods)}${visPrefix(f.mods)}$kw ${id(f.name)}: ${tpe(f.tpe)} = ${expr(init)}")
        line()
      case FieldLine.SentinelVal(f, pname, default) =>
        trivia(f.leading)
        line(s"${beanPrefix(f, t.methods)}${visPrefix(f.mods)}val ${id(f.name)}: ${tpe(f.tpe)} = if (${id(pname)} != null) ${id(pname)} else ${expr(default)}")
        line()
      case FieldLine.CondInit(f, pname, whenSome, whenNull) =>
        trivia(f.leading)
        val kw = if f.mods.isFinal then "val" else "var"
        line(s"${beanPrefix(f, t.methods)}${visPrefix(f.mods)}$kw ${id(f.name)}: ${tpe(f.tpe)} = if (${id(pname)} != null) ${expr(whenSome)} else ${expr(whenNull)}")
        line()
      case FieldLine.DefaultInit(f) =>
        trivia(f.leading)
        line(s"${beanPrefix(f, t.methods)}${visPrefix(f.mods)}var ${id(f.name)}: ${tpe(f.tpe)} = ${defaultOf(f.tpe)}")
        line()
    }
    plan.secondaryCtors.foreach { sc =>
      trivia(sc.leading)
      // reassigned aux-ctor params: rename to `_p`, add `var p = _p` after delegation
      val reassigned = reassignedParams(sc.body, sc.params.map(_.name).toSet)
      val paramStrs = sc.params.map(p => if reassigned(p.name) then paramOf(p.copy(name = "_" + p.name)) else paramOf(p))
      val sig = s"${visPrefix(sc.mods)}def this(${paramStrs.mkString(", ")}) ="
      def fixArg(a: BExpr): BExpr =
        if reassigned.isEmpty then a
        else
          BirTransform.mapExpr(a) {
            case Ident(n, RefKind.Param(v)) if reassigned(n) => Ident("_" + n, RefKind.Param(v))
            case e                                           => e
          }
      val dArgs =
        if sc.targetTypes.length == sc.delegateArgs.length then
          sc.delegateArgs.zip(sc.targetTypes).map((a, tt) => delegateArg(fixArg(a), Some(tt))).mkString(", ")
        else sc.delegateArgs.map(a => delegateArg(fixArg(a))).mkString(", ")
      if sc.body.isEmpty then
        line(sig)
        indent += 1
        line(s"this($dArgs)")
        indent -= 1
      else
        line(sig + " {")
        indent += 1
        line(s"this($dArgs)")
        reassigned.toList.sorted.foreach { n =>
          val p = sc.params.find(_.name == n).get
          line(s"var ${id(n)}: ${tpe(p.tpe)} = ${id("_" + n)}")
        }
        sc.body.foreach(stmt)
        indent -= 1
        line("}")
      line()
    }
    if t.instanceInit.nonEmpty then
      t.instanceInit.foreach(stmt)
      line()
    if plan.primaryBody.nonEmpty then
      plan.primaryBody.foreach(stmt)
      line()
    t.methods.foreach(methodDecl)

    t.inner.foreach { n =>
      nestedDepth += 1
      typeDecl(n)
      nestedDepth -= 1
      line()
    }

    indent -= 1
    line("}")
    companion(t)

  /** Emit class with a handwritten CtorOverride; fields/methods/companion are engine-generated. */
  private def classDeclOverridden(t: BTypeDecl, ovr: CtorOverride): Unit =
    t.serialVersionUID.foreach(v => line(s"@SerialVersionUID(${v}L)"))
    val mods = StringBuilder(visPrefix(t.mods))
    if t.mods.isAbstract then mods.append("abstract ")
    if t.mods.isFinal then mods.append("final ")
    line(s"${mods.result()}class ${id(t.name)}${tparamsStr(t.tparams)}${ovr.headerSuffix} {")
    indent += 1
    if t.staticInit.nonEmpty then
      line(s"locally(${id(t.name)})")
      line()
    ovr.body.foreach(line)
    if ovr.body.nonEmpty then line()
    t.methods.foreach(methodDecl)
    t.inner.foreach { n =>
      nestedDepth += 1
      typeDecl(n)
      nestedDepth -= 1
      line()
    }
    indent -= 1
    line("}")
    companion(t)

  /** A type carrying a wildcard anywhere. */
  private def hasWildType(x: BType): Boolean = x match
    case _: BType.Wild    => true
    case BType.Ref(_, as) => as.exists(hasWildType)
    case BType.Arr(e2)    => hasWildType(e2)
    case _                => false

  private def delegateArg(e: BExpr): String = delegateArg(e, None)

  private def delegateArg(e: BExpr, target: Option[BType]): String =
    val stripped = e match
      case Typed(i, _) => i
      case other       => other
    (stripped, target) match
      case (Ident(_, RefKind.Param(true)), Some(BType.Arr(_))) => expr(stripped) + ".toArray"
      case (Ident(_, RefKind.Param(true)), _)                  => expr(stripped) + "*"
      // ascribe null to disambiguate overloaded targets; cast for type-variable targets
      case (Lit(LitKind.NullL, _), Some(t: BType.TVar))                    => s"null.asInstanceOf[${tpe(t)}]"
      case (Lit(LitKind.NullL, _), Some(t)) if !t.isInstanceOf[BType.Prim] => s"(null: ${tpe(t)})"
      case _                                                   => expr(stripped)

  private def paramStr(p: CtorPlan.Param): String = paramStr(p, Nil, Set.empty)

  private def paramStr(p: CtorPlan.Param, methods: List[BMethod], reassigned: Set[String] = Set.empty): String =
    p.promoted match
      // promoted field reassigned in ctor body: var, not val
      case Some(f)                               => s"${beanPrefix(f, methods)}${visPrefix(f.mods)}${if reassigned.contains(p.p.name) then "var" else "val"} ${id(p.p.name)}: ${tpe(p.p.tpe)}"
      // reassigned plain param: private var (Scala params are val)
      case None if reassigned.contains(p.p.name) => s"private var ${paramOf(p.p)}"
      case None                                  => paramOf(p.p)

  /** Primary-ctor parameters reassigned in the ctor body. */
  private def reassignedParams(stmts: List[BStmt], pnames: Set[String]): Set[String] =
    if pnames.isEmpty then Set.empty
    else
      val out = collection.mutable.Set[String]()
      // a param promoted to a field may appear as either Param or OwnField ref
      def isTarget(e: BExpr): Option[String] = e match
        case Ident(n, RefKind.Param(_)) if pnames(n) => Some(n)
        case Ident(n, RefKind.OwnField) if pnames(n) => Some(n)
        case _                                       => None
      def exprScan(e: BExpr): Unit =
        BirTransform.mapExpr(e) { x =>
          x match
            case AssignExpr(t, _) => isTarget(t).foreach(out += _)
            case IncDecExpr(t, _, _) => isTarget(t).foreach(out += _)
            case _                => ()
          x
        }
      def walk(ss: List[BStmt]): Unit = ss.foreach(s => walkK(s.k))
      def walkK(k: BStmtK): Unit = k match
        case BStmtK.Assign(lhs, rhs, _) =>
          isTarget(lhs) match
            case Some(n) => out += n
            case None    => exprScan(lhs)
          exprScan(rhs)
        case BStmtK.LocalVar(_, _, i, _) => i.foreach(exprScan)
        case BStmtK.ExprStmt(e)          => exprScan(e)
        case BStmtK.If(c, t, e)          => exprScan(c); walk(t); e.foreach(walk)
        case BStmtK.While(c, b)          => exprScan(c); walk(b)
        case BStmtK.DoWhile(b, c)        => walk(b); exprScan(c)
        case BStmtK.Return(e)            => e.foreach(exprScan)
        case BStmtK.Throw(e)             => exprScan(e)
        case BStmtK.Block(b)             => walk(b)
        case BStmtK.Try(b, cs, f)        => walk(b); cs.foreach(c => walk(c.body)); f.foreach(walk)
        case BStmtK.Boundary(b, _)       => walk(b)
        case BStmtK.Match(scr, cases)    => exprScan(scr); cases.foreach(c => walk(c.body))
        case BStmtK.Synchronized(l, b)   => exprScan(l); walk(b)
        case BStmtK.Assert(c, m)         => exprScan(c); m.foreach(exprScan)
        case _                           => ()
      walk(stmts)
      out.toSet

  private def paramOf(p: BParam): String =
    val t = if p.varargs then
      p.tpe match
        case BType.Arr(e) => tpe(e) + "*"
        case other        => tpe(other) + "*"
    else tpe(p.tpe)
    s"${id(p.name)}: $t"

  /** @BeanProperty for public fields (restores JVM-visible getters).
    * Skipped when the class already declares the bean method. */
  private def beanPrefix(f: BField, methods: List[BMethod]): String =
    if f.mods.vis != Vis.Public then ""
    else
      val cap = f.name.capitalize
      val clash = methods.exists(m => m.name == s"get$cap" || m.name == s"is$cap" || m.name == s"set$cap")
      if clash then "" else "@scala.beans.BeanProperty "

  private def annotationLines(m: Mods): Unit =
    m.annotations.foreach { a =>
      val args =
        if a.args.isEmpty then ""
        else "(" + a.args.map((k, v) => s"${id(k)} = ${expr(v)}").mkString(", ") + ")"
      line(s"@${refName(a.qname)}$args")
    }

  private def methodDecl(m: BMethod): Unit =
    trivia(m.leading)
    annotationLines(m.mods)
    val mods = StringBuilder(visPrefix(m.mods))
    if m.mods.isOverride then mods.append("override ")
    if m.mods.isFinal then mods.append("final ")

    // reassigned params: `_p` + `var p = _p`
    val paramStrs = m.params.map { p =>
      if m.assignedParams.contains(p.name) then paramOf(p.copy(name = "_" + p.name)) else paramOf(p)
    }
    val sig = s"${mods.result()}def ${id(m.name)}${tparamsStr(m.tparams)}(${paramStrs.mkString(", ")}): ${tpe(m.ret)}"
    m.body match
      case None => line(sig)
      case Some(body) =>
        line(sig + " = {")
        indent += 1
        m.params.filter(p => m.assignedParams.contains(p.name)).foreach { p =>
          val t = if p.varargs then unsupported(s"reassigned varargs parameter ${p.name}") else tpe(p.tpe)
          line(s"var ${id(p.name)}: $t = ${id("_" + p.name)}")
        }
        // ascribe `return null` for type-variable returns (Null is not <: T)
        printBody(if m.ret.isInstanceOf[BType.TVar] then body.map(ascribeReturnNulls(_, m.ret)) else body)
        indent -= 1
        line("}")
    line()

  // ---- statements ------------------------------------------------------------

  /** Ascribe `return null` to T-typed return, recursing into control-flow. */
  private def ascribeReturnNulls(s: BStmt, ret: BType): BStmt =
    def r(x: BStmt) = ascribeReturnNulls(x, ret)
    val k = s.k match
      case BStmtK.Return(Some(Lit(LitKind.NullL, _))) => BStmtK.Return(Some(Cast(ret, Lit(LitKind.NullL, "null"))))
      case BStmtK.If(c, t, e)        => BStmtK.If(c, t.map(r), e.map(_.map(r)))
      case BStmtK.While(c, b)        => BStmtK.While(c, b.map(r))
      case BStmtK.DoWhile(b, c)      => BStmtK.DoWhile(b.map(r), c)
      case BStmtK.Block(b)           => BStmtK.Block(b.map(r))
      case BStmtK.Try(b, cs, f)      => BStmtK.Try(b.map(r), cs.map(c => c.copy(body = c.body.map(r))), f.map(_.map(r)))
      case BStmtK.Boundary(b, l)     => BStmtK.Boundary(b.map(r), l)
      case BStmtK.Synchronized(l, b) => BStmtK.Synchronized(l, b.map(r))
      case BStmtK.Match(scr, cases)  => BStmtK.Match(scr, cases.map(c => c.copy(body = c.body.map(r))))
      case other                     => other
    s.copy(k = k)

  /** True inside a lambda boundary: `return e` prints as `boundary.break(e)`. */
  private var lambdaBoundaryActive = false

  /** Strip tail-position returns; non-tail returns are left for boundary fallback. */
  private def stripTailReturns(stmts: List[BStmt]): List[BStmt] =
    if stmts.isEmpty then stmts
    else
      val last = stmts.last
      val newK = last.k match
        case BStmtK.Return(Some(e)) => BStmtK.ExprStmt(e)
        case BStmtK.Return(None)    => BStmtK.Empty
        case BStmtK.If(c, t, e)     => BStmtK.If(c, stripTailReturns(t), e.map(stripTailReturns))
        case BStmtK.Match(s, cs)    => BStmtK.Match(s, cs.map(cc => cc.copy(body = stripTailReturns(cc.body))))
        case BStmtK.Block(b)        => BStmtK.Block(stripTailReturns(b))
        case BStmtK.Try(b, cs, f)   => BStmtK.Try(stripTailReturns(b), cs.map(cc => cc.copy(body = stripTailReturns(cc.body))), f)
        case k                      => k
      stmts.init :+ last.copy(k = newK)

  private def hasReturn(stmts: List[BStmt]): Boolean =
    stmts.exists { s =>
      s.k match
        case BStmtK.Return(_)       => true
        case BStmtK.If(_, t, e)     => hasReturn(t) || e.exists(hasReturn)
        case BStmtK.While(_, b)     => hasReturn(b)
        case BStmtK.DoWhile(b, _)   => hasReturn(b)
        case BStmtK.Block(b)        => hasReturn(b)
        case BStmtK.Boundary(b, _)  => hasReturn(b)
        case BStmtK.Match(_, cs)    => cs.exists(cc => hasReturn(cc.body))
        case BStmtK.Try(b, cs, f)   => hasReturn(b) || cs.exists(cc => hasReturn(cc.body)) || f.exists(hasReturn)
        case BStmtK.Synchronized(_, b) => hasReturn(b)
        case _                      => false
    }

  /** Prints a method body; a trailing `return e` prints as `e`. */
  private def printBody(body: List[BStmt]): Unit =
    body.zipWithIndex.foreach { case (s, i) =>
      val isLast = i == body.length - 1
      s.k match
        case BStmtK.Return(Some(e)) if isLast => trivia(s.leading); line(expr(e))
        case _                                => stmt(s)
    }

  private def stmt(s: BStmt): Unit =
    trivia(s.leading)
    s.k match
      case BStmtK.LocalVar(name, t, init, effFinal) =>
        val kw = if effFinal then "val" else "var"
        // wildcard-typed locals: skip annotation, let inference handle it
        def wildIn(x: BType): Boolean = x match
          case _: BType.Wild    => true
          case BType.Ref(_, as) => as.exists(wildIn)
          case BType.Arr(e2)    => wildIn(e2)
          case _                => false
        // synthesized loop locals ($it/$arr) always infer correctly
        val synthetic = name.endsWith("$it") || name.endsWith("$arr")
        // keep annotation when a method type-var return needs inference context
        def topWild(x: BType): Boolean = x.isInstanceOf[BType.Wild]
        // calls/constructors needing type inference context keep the annotation
        val ctorInit = init.exists(e => e.isInstanceOf[Call] || e.isInstanceOf[New] || e.isInstanceOf[NewArray])
        val skip = synthetic || (wildIn(t) && !(ctorInit && !topWild(t)))
        val ann = if skip && init.isDefined then "" else s": ${tpe(t)}"
        val rhs = init.map(expr).getOrElse(defaultOf(t))
        line(s"$kw ${id(name)}$ann = $rhs")
      case BStmtK.ExprStmt(e) => line(expr(e))
      case BStmtK.Assign(lhs, rhs, op) =>
        line(s"${expr(lhs)} ${op.getOrElse("")}= ${expr(rhs)}")
      case BStmtK.If(c, t, e) =>
        line(s"if (${expr(c)}) {")
        indent += 1; t.foreach(stmt); indent -= 1
        e match
          case None => line("}")
          case Some(els) =>
            line("} else {")
            indent += 1; els.foreach(stmt); indent -= 1
            line("}")
      case BStmtK.Return(None)    => line(if lambdaBoundaryActive then "scala.util.boundary.break()" else "return")
      case BStmtK.Return(Some(e)) => line(if lambdaBoundaryActive then s"scala.util.boundary.break(${expr(e)})" else s"return ${expr(e)}")
      case BStmtK.Throw(e)        => line(s"throw ${expr(e)}")
      case BStmtK.While(c, b) =>
        line(s"while (${expr(c)}) {")
        indent += 1; b.foreach(stmt); indent -= 1
        line("}")
      case BStmtK.DoWhile(b, c) =>
        line("while ({")
        indent += 1; b.foreach(stmt); line(expr(c)); indent -= 1
        line("}) ()")
      case BStmtK.Assert(c, m) =>
        m match
          case Some(msg) => line(s"assert(${expr(c)}, ${expr(msg)})")
          case None      => line(s"assert(${expr(c)})")
      case BStmtK.Block(b) =>
        // `locally` prevents parsing as an anonymous-class body
        line("locally {")
        indent += 1; b.foreach(stmt); indent -= 1
        line("}")
      case BStmtK.Try(b, catches, fin) =>
        line("try {")
        indent += 1; b.foreach(stmt); indent -= 1
        if catches.nonEmpty then
          line("} catch {")
          indent += 1
          catches.foreach { c =>
            val pat = c.types match
              case List(t1) => s"${id(c.param)}: ${tpe(t1)}"
              case ts       => s"${id(c.param)} @ (${ts.map(t1 => s"_: ${tpe(t1)}").mkString(" | ")})"
            line(s"case $pat =>")
            indent += 1; c.body.foreach(stmt); indent -= 1
          }
          indent -= 1
        fin match
          case Some(f) =>
            line("} finally {")
            indent += 1; f.foreach(stmt); indent -= 1
            line("}")
          case None => line("}")
      case BStmtK.Boundary(b, label) =>
        label match
          case None    => line("scala.util.boundary {")
          case Some(l) => line(s"scala.util.boundary { (${id(l)}: scala.util.boundary.Label[Unit]) ?=>")
        indent += 1; b.foreach(stmt); indent -= 1
        line("}")
      case BStmtK.LoopBreak(None)    => line("scala.util.boundary.break()")
      case BStmtK.LoopBreak(Some(l)) => line(s"scala.util.boundary.break()(using ${id(l)})")
      case BStmtK.Match(scrutinee, cases) =>
        line(s"${expr(scrutinee)} match {")
        indent += 1
        cases.foreach { c =>
          val pat = if c.isDefault then "_" else c.exprs.map(expr).mkString(" | ")
          line(s"case $pat =>")
          indent += 1
          if c.body.isEmpty then line("()") else c.body.foreach(stmt)
          indent -= 1
        }
        indent -= 1
        line("}")
      case BStmtK.Synchronized(l, b) =>
        line(s"${expr(l)}.synchronized {")
        indent += 1; b.foreach(stmt); indent -= 1
        line("}")
      case BStmtK.LocalType(t) =>
        // local definitions take no access modifiers in Scala
        typeDecl(t.copy(mods = t.mods.copy(vis = Vis.Public)))
      case BStmtK.Empty => ()

  private def defaultOf(t: BType): String = t match
    case BType.Prim("boolean")                          => "false"
    case BType.Prim("float")                            => "0.0f"
    case BType.Prim("double")                           => "0.0d"
    case BType.Prim("long")                             => "0L"
    case BType.Prim("char")                             => "'\\u0000'"
    case BType.Prim(_)                                  => "0"
    case _                                              => "null"

  // ---- expressions -----------------------------------------------------------

  private def expr(e: BExpr): String = e match
    case Lit(_, raw)   => raw
    case Ident(n, RefKind.StaticField(owner)) => s"${refName(owner)}.${id(n)}"
    // explicit `this.` to defeat Scala's block scoping of same-named locals
    case Ident(n, RefKind.OwnField) => s"this.${id(n)}"
    case Ident(n, RefKind.OuterField(outer)) => s"${id(outer)}.this.${id(n)}"
    case Ident(n, RefKind.EnclosingField) => id(n) // bare: resolved lexically from an anon/local class
    case Ident(n, _)                => id(n)
    case This          => "this"
    case Select(r, n)  => s"${expr(r)}.${id(n)}"
    case ArrayLength(a) => s"${expr(a)}.length"
    case ArrayAccess(a, i) => s"${expr(a)}(${expr(i)})"
    case Typed(inner, _) => expr(inner)
    case AssignExpr(l, r) => s"{ ${expr(l)} = ${expr(r)}; ${expr(l)} }"
    case IncDecExpr(t, op, post) =>
      if post then s"{ val tmp$$ = ${expr(t)}; ${expr(t)} $op= 1; tmp$$ }"
      else s"{ ${expr(t)} $op= 1; ${expr(t)} }"

    case Call(recv, name, args, formals, ownerQ) =>
      val target = recv match
        case Recv.OnThis        => ""
        case Recv.OnSuper       => "super."
        case Recv.Static(owner) => refName(owner) + "."
        case Recv.On(r)         => expr(r) + "."
      s"$target${id(name)}(${adaptedArgs(args, formals, ownerQ).mkString(", ")})"

    case New(t, args, anon, formals) =>
      // strip wildcards from instantiation type args (let inference handle them)
      val newT = if t.args.exists(hasWildType) then t.copy(args = Nil) else t
      val argsStr =
        if args.isEmpty && anon.isDefined then ""
        else s"(${adaptedArgs(args, formals, Some(t.qname)).mkString(", ")})"
      // `new Object()` -> `new Object()` (Any has no constructor)
      val typeStr = if BType.isObject(BType.Ref(t.qname, Nil)) then "Object" else tpe(newT)
      val base = s"new $typeStr$argsStr"
      anon match
        case None => base
        case Some(BAnonBody(Nil, Nil, Nil)) => base + " {}"
        case Some(BAnonBody(fields, methods, init)) =>
          val body = captured {
            indent += 1
            fields.foreach { f =>
              trivia(f.leading)
              val kw = if f.mods.isFinal then "val" else "var"
              val rhs = f.init.map(expr).getOrElse(defaultOf(f.tpe))
              line(s"${beanPrefix(f, methods)}${visPrefix(f.mods)}$kw ${id(f.name)}: ${tpe(f.tpe)} = $rhs")
            }
            init.foreach(stmt)
            methods.foreach(methodDecl)
            indent -= 1
          }
          base + " {\n" + body + ("  " * indent) + "}"
    case NewArray(el, _, Some(inits)) =>
      val items =
        if BType.isObject(el) then inits.map(i => s"${expr(i)}.asInstanceOf[AnyRef]")
        else inits.map(expr)
      s"Array[${arrElem(el)}](${items.mkString(", ")})"
    case NewArray(el, List(dim), None) => s"new Array[${arrElem(el)}](${expr(dim)})"
    case NewArray(_, dims, None) => unsupported(s"multi-dimensional array (${dims.length} dims)")

    case Binary(op, l, r, concat) =>
      // Scala needs a String left operand for concat; wrap non-obvious cases
      def obviouslyString(x: BExpr): Boolean = x match
        case Lit(LitKind.StringL, _)      => true
        case Binary(_, _, _, true)        => true
        case Typed(i, BType.Ref("java.lang.String", _)) => true
        case Typed(i, _)                  => obviouslyString(i)
        case _                            => false
      if concat && !obviouslyString(l) then s"(String.valueOf(${expr(l)}) $op ${expr(r)})"
      else s"(${expr(l)} $op ${expr(r)})"
    case Unary(op, e1, true) => s"($op${expr(e1)})"
    case Unary(op, _, false) => unsupported(s"postfix operator $op")
    case Ternary(c, t, e1)    => s"(if (${expr(c)}) ${expr(t)} else ${expr(e1)})"

    case CtorRef(t, formals) =>
      val ps = formals.zipWithIndex.map((ft, i) => s"p$i$$: ${tpe(ft)}")
      val args = formals.indices.map(i => s"p$i$$").mkString(", ")
      // strip wildcards from instantiation type args
      val ctorT = if t.args.exists(hasWildType) then t.copy(args = Nil) else t
      s"((${ps.mkString(", ")}) => new ${tpe(ctorT)}($args))"

    case MethodRef(prefix, name) =>
      prefix match
        case Left(owner) => s"${refName(owner)}.${id(name)}"
        case Right(r)    => s"${expr(r)}.${id(name)}"

    case UnboundMethodRef(recvT, name, formals) =>
      // annotate receiver only when precise (wildcards would widen SAM inference)
      def precise(x: BType): Boolean = x match
        case _: BType.Wild    => false
        case BType.Ref(_, as) => as.forall(precise)
        case BType.Arr(e2)    => precise(e2)
        case _                => true
      val recvP = if precise(recvT) then s"recv$$: ${tpe(recvT)}" else "recv$"
      val ps = recvP :: formals.indices.map(i => s"p$i$$").toList
      val args = formals.indices.map(i => s"p$i$$").mkString(", ")
      s"((${ps.mkString(", ")}) => recv$$.${id(name)}($args))"

    case Lambda(ps, body, pts) =>
      // annotate lambda params with SAM types when available and wildcard-free
      val useTypes = pts.length == ps.length && pts.nonEmpty && !pts.exists(hasWildType)
      val plist =
        if useTypes then "(" + ps.zip(pts).map((p, t) => s"${id(p)}: ${tpe(t)}").mkString(", ") + ")"
        else
          ps match
            case List(p1) => id(p1)
            case _        => "(" + ps.map(id).mkString(", ") + ")"
      body match
        case Right(e)                                     => s"($plist => ${expr(e)})"
        case Left(List(BStmt(_, BStmtK.Return(Some(e))))) => s"($plist => ${expr(e)})"
        case Left(List(BStmt(_, BStmtK.ExprStmt(e))))     => s"($plist => ${expr(e)})"
        case Left(stmts0) =>
          // strip tail returns; wrap non-tail returns in boundary.break
          val stmts = stripTailReturns(stmts0)
          val needsBoundary = hasReturn(stmts)
          val bodyStr = captured {
            indent += 1
            val saved = lambdaBoundaryActive
            lambdaBoundaryActive = needsBoundary
            printBody(stmts)
            lambdaBoundaryActive = saved
            indent -= 1
          }
          val pad = "  " * indent
          if needsBoundary then s"($plist => scala.util.boundary {\n" + bodyStr + pad + "})"
          else s"($plist => {\n" + bodyStr + pad + "})"

    case Cast(BType.Prim(p), e1) =>
      val conv = primMap.getOrElse(p, unsupported(s"cast to $p"))
      s"${expr(e1)}.to$conv"
    // SAM conversion: ascribe rather than cast so Scala resolves the target type
    case Cast(t, e1) if e1.isInstanceOf[Lambda] || e1.isInstanceOf[MethodRef] || e1.isInstanceOf[UnboundMethodRef] =>
      s"(${expr(e1)}: ${tpe(t)})"
    case Cast(t, e1)       => s"${expr(e1)}.asInstanceOf[${tpe(t)}]"
    case InstanceOf(e1, t) => s"${expr(e1)}.isInstanceOf[${tpe(t)}]"
    case ClassLit(t) =>
      t match
        case BType.Ref(_, args) if args.nonEmpty =>
          // generic class literal: cast to Class[AnyRef] (Java's raw Class is erased)
          s"classOf[${tpe(t)}].asInstanceOf[Class[AnyRef]]"
        case other => s"classOf[${tpe(other)}]"

  /** Call-site varargs/array adaptation: spread, toArray, or AnyRef cast as needed. */
  private def adaptedArgs(args: List[BExpr], formals: Option[List[Formal]], ownerQ: Option[String]): List[String] =
    formals match
      case Some(fs) if fs.length == args.length =>
        args.zip(fs).map { (a0, f) =>
          val (a, at) = a0 match
            case Typed(inner, t) => (inner, Some(t))
            case e               => (e, None)
          (a, at, f) match
            // varargs into varargs-of-arrays: materialize as one element, not spread
            case (Ident(_, RefKind.Param(true)), srcT, Formal(BType.Arr(el), true))
                if !srcT.exists(_.isInstanceOf[BType.Arr]) =>
              val conv = expr(a) + ".toArray"
              if BType.isObject(el) then conv + ".asInstanceOf[Array[AnyRef]]" else conv
            // varargs into varargs: spread
            case (Ident(_, RefKind.Param(true)), _, Formal(_, true)) => expr(a) + "*"
            // array into varargs: spread
            case (_, Some(BType.Arr(_)), Formal(_, true)) => expr(a) + "*"
            // varargs into array: materialize (Object[] needs AnyRef cast)
            case (Ident(_, RefKind.Param(true)), _, Formal(BType.Arr(el), false)) =>
              val conv = expr(a) + ".toArray"
              if BType.isObject(el) then conv + ".asInstanceOf[Array[AnyRef]]" else conv
            // varargs into Object slot: materialize to preserve isArray semantics
            case (Ident(_, RefKind.Param(true)), _, Formal(t, false)) if BType.isObject(t) =>
              expr(a) + ".toArray"
            case _ => expr(a)
        }
      case _ => args.map(expr)
