package balticporter.emit

// =============================================================================
// FROZEN — the BIR emission backend. New work goes on `TirEmitter`, beside this file.
//
// This prints `BUnit`s: the untyped Java IR described (and frozen) at the head of
// `core/Bir.scala`. `TirEmitter` prints the TIR, where every node carries a resolved
// `TypeRepr` and every reference a `SymId` — which is why it can decide diamonds,
// constructor funnels and member clashes that this printer can only guess at.
//
// Kept because liqp and xwiki/flexmark still port through it (the corpus
// programs are listed in `core/Bir.scala`). Fix what they need; add nothing.
// =============================================================================

import balticporter.core.*
import balticporter.core.BExpr.*

/** Deterministic BIR → Scala 3 printer. Pure function of (unit, provenance):
  * same input + same engine version = byte-identical output.
  *
  * M0 conventions (M1 will refine): fully-qualified type references except
  * java.lang and same-package types; every binary expression parenthesized;
  * no import synthesis. Constructor translation follows the constructor funnel
  * strategies (ENGINE-LIMITS.md §2); the two-ctor sentinel merge mirrors the idiom
  * used across the hand-ported corpus (see ssg Filter.scala).
  */
object ScalaPrinter:

  def print(
      unit: BUnit,
      prov: Provenance,
      sentinels: Set[String] = Set.empty,
      registry: Option[CtorRegistry] = None,
      ctorOverrides: Map[String, CtorOverride] = Map.empty,
  ): String =
    new Printer(MemberClashPass(widenFields(unit, registry), registry), prov, sentinels, registry, ctorOverrides).result()

  /** Private non-final fields that subclass effect-replay assigns (see
    * CtorRegistry.widenedFields) emit `protected` — the deterministic analog of
    * the hand-port corpus's accessor widening. */
  private def widenFields(unit: BUnit, registry: Option[CtorRegistry]): BUnit =
    registry match
      case None => unit
      case Some(reg) =>
        val w = reg.widenedFields
        if w.isEmpty then unit
        else
          unit.copy(types = unit.types.map { t =>
            val fqcn = if unit.pkg.isEmpty then t.name else s"${unit.pkg}.${t.name}"
            t.copy(fields = t.fields.map { f =>
              if w((fqcn, f.name)) then f.copy(mods = f.mods.copy(vis = Vis.Protected)) else f
            })
          })

/** Cross-unit knowledge: which classes' no-arg construction path equals the null
  * sentinel (needed for the super()-rewrite; transitive over subclass chains).
  */
object SentinelRegistry:
  def compute(units: List[BUnit]): Set[String] =
    var acc = Set.empty[String]
    var changed = true
    while changed do
      changed = false
      units.foreach { u =>
        u.types.foreach { t =>
          val fqcn = if u.pkg.isEmpty then t.name else s"${u.pkg}.${t.name}"
          if !acc.contains(fqcn) then
            val sentinelish =
              try CtorPlan.of(t, u, acc).sentinelLike
              catch case _: Unsupported => false
            if sentinelish then
              acc += fqcn
              changed = true
        }
      }
    acc

/** PLAN §7 declaration-level override: replace only a class's constructor block
  * (the irreducible cases the funnel refuses) while the engine still translates
  * every field, method, companion, and import. `headerSuffix` is spliced after
  * `class Name[tparams]` (primary params + `extends ...`); `body` lines open the
  * class body (field decls the ctors assign + the auxiliary `def this(...)`s).
  * The engine emits methods/inner types/companion below it as usual. */
final case class CtorOverride(headerSuffix: String, body: List[String])

private final class Printer(
    unit: BUnit,
    prov: Provenance,
    sentinels: Set[String],
    registry: Option[CtorRegistry],
    ctorOverrides: Map[String, CtorOverride] = Map.empty,
):
  private val sb = new StringBuilder
  private var indent = 0

  private def line(s: String = ""): Unit =
    if s.isEmpty then sb.append('\n')
    else sb.append("  " * indent).append(s).append('\n')

  /** Renders `body`'s line() output into a string instead of the document —
    * the mechanism for multi-line expressions (anonymous class bodies).
    */
  private def captured(body: => Unit): String =
    val mark = sb.length
    body
    val s = sb.substring(mark)
    sb.setLength(mark)
    s

  private def unsupported(what: String): Nothing =
    throw Unsupported(unit.sourcePath, "-", what)

  def result(): String =
    header()
    if unit.pkg.nonEmpty then
      line(s"package ${unit.pkg.split('.').map(id).mkString(".")}")
      line()
    unit.types.foreach(typeDecl)
    sb.toString

  private def header(): Unit =
    line("/*")
    line(s" * Generated by Baltic Porter ${EngineInfo.version} — DO NOT EDIT; regenerate instead.")
    line(" *")
    line(s" * Ported from: ${prov.sourcePathPrefix}/${unit.sourcePath}")
    line(s" * Original license: ${prov.originalLicense} (see ${prov.upstreamName} upstream)")
    line(s" * upstream-commit: ${prov.upstreamCommit}")
    line(" */")

  // ---- names & types ---------------------------------------------------------

  private val keywords = Set(
    "abstract", "case", "catch", "class", "def", "do", "else", "enum", "export", "extends",
    "false", "final", "finally", "for", "given", "if", "implicit", "import", "lazy", "match",
    "new", "null", "object", "override", "package", "private", "protected", "return", "sealed",
    "super", "then", "throw", "trait", "true", "try", "type", "val", "var", "while", "with", "yield",
    "macro", "forSome",
    // soft keywords — position-sensitive (e.g. `using = x` in annotation args); backticking
    // them unconditionally is always safe
    "using", "extension", "inline", "opaque", "transparent", "derives", "end", "infix",
  )

  private def id(name: String): String =
    if keywords.contains(name) then s"`$name`" else name

  private def pkgOfQ(q: String): String = q.lastIndexOf('.') match
    case -1 => ""
    case i  => q.substring(0, i)

  /** boxed types whose simple names collide with Scala primitives — never shortened
    * (java.lang.Long.MAX_VALUE must not become scala.Long.MAX_VALUE). */
  private val collidingJavaLang = Set(
    "java.lang.Long", "java.lang.Double", "java.lang.Float", "java.lang.Boolean",
    "java.lang.Byte", "java.lang.Short", "java.lang.Character",
    "java.lang.StringBuilder", "java.lang.Iterable", "java.lang.Cloneable",
  )

  /** Spoon qnames of inner (non-static) classes in this unit — referable only by
    * simple name inside their outer class (path-dependent from anywhere else). */
  private lazy val innerQNames: Set[String] =
    def walk(prefix: String, t: BTypeDecl): List[String] =
      val q = s"$prefix${t.name}"
      t.inner.map(n => s"$q$$${n.name}") ++
        (t.nested ++ t.inner).flatMap(n => walk(s"$q$$", n))
    val pkgPrefix = if unit.pkg.isEmpty then "" else unit.pkg + "."
    unit.types.flatMap(t => walk(pkgPrefix, t)).toSet

  private def refName(q0: String): String =
    if innerQNames.contains(q0) then return id(q0.substring(q0.lastIndexOf('$') + 1))
    // Spoon names LOCAL classes with a block-counter prefix (Outer$1MyParams) — they
    // are only referable by simple name inside their defining method
    val lastSeg0 = q0.substring(q0.lastIndexOf('$') + 1)
    val localStripped = lastSeg0.dropWhile(_.isDigit)
    if q0.contains('$') && lastSeg0.headOption.exists(_.isDigit) && localStripped.nonEmpty then
      return id(localStripped)
    // Spoon qualifies nested types as Outer$Inner; the companion encoding makes that Outer.Inner
    val q = q0.replace('$', '.')
    val name =
      if q == BType.ObjectQ then "Any"
      else if q == "java.lang.String" then "String"
      else if collidingJavaLang.contains(q) then q
      else if pkgOfQ(q) == "java.lang" then q.substring("java.lang.".length)
      else if q.startsWith(unit.pkg + ".") && pkgOfQ(q0).length <= unit.pkg.length then
        q.substring(unit.pkg.length + 1)
      else q
    // Scala keywords can appear as Java package segments (e.g. jackson.core.type)
    name.split('.').map(id).mkString(".")

  private val primMap = Map(
    "void" -> "Unit", "int" -> "Int", "long" -> "Long", "double" -> "Double", "float" -> "Float",
    "boolean" -> "Boolean", "char" -> "Char", "byte" -> "Byte", "short" -> "Short",
  )

  private def tpe(t: BType): String = t match
    case BType.Prim(n)       => primMap.getOrElse(n, unsupported(s"primitive $n"))
    case BType.Ref(q, Nil)   => refName(q)
    case BType.Ref(q, args)  => s"${refName(q)}[${args.map(tpe).mkString(", ")}]"
    case BType.Arr(e)        => s"Array[${arrElem(e)}]"
    case BType.TVar(n)       => n
    case BType.Wild(up, lo) =>
      (up, lo) match
        case (Some(u), None) => s"? <: ${tpe(u)}"
        case (None, Some(l)) => s"? >: ${tpe(l)}"
        case _               => "?"

  /** Java Object[] is Array[AnyRef], not Array[Any] — arrays are invariant and the
    * JDK's T[] overloads require reference element types. */
  private def arrElem(e: BType): String =
    if BType.isObject(e) then "AnyRef" else tpe(e)

  private def innermostPkg: String = unit.pkg.lastIndexOf('.') match
    case -1 => unit.pkg
    case i  => unit.pkg.substring(i + 1)

  /** >0 while printing types nested inside a companion — their `private` members are
    * outer-accessible in Java (synthetic accessors), so they widen to package scope. */
  private var nestedDepth = 0

  private def visPrefix(m: Mods): String = m.vis match
    case Vis.Public => ""
    case Vis.Private =>
      if nestedDepth > 0 && unit.pkg.nonEmpty then s"private[$innermostPkg] " else "private "
    case Vis.Protected      => if unit.pkg.isEmpty then "protected " else s"protected[$innermostPkg] "
    case Vis.PackagePrivate => if unit.pkg.isEmpty then "private " else s"private[$innermostPkg] "

  // ---- trivia ----------------------------------------------------------------

  private def trivia(ts: List[Trivia]): Unit =
    ts.foreach { t =>
      t.text.linesIterator.zipWithIndex.foreach { case (l, i) =>
        // continuation lines of block comments keep a leading space so `*` aligns under `/*`
        if i == 0 then line(l.trim) else line(" " + l.trim)
      }
    }

  // ---- declarations ----------------------------------------------------------

  private def typeDecl(t: BTypeDecl): Unit = t.kind match
    case BTypeKind.Interface => traitDecl(t)
    case BTypeKind.Class     => classDecl(t)
    case BTypeKind.Enum      => enumDecl(t)

  /** Java enum → `enum E(val params) extends java.lang.Enum[E]` (the conversion rule
    * both target repos mandate; parameterized cases per the corpus encoding).
    */
  private def enumDecl(t: BTypeDecl): Unit =
    trivia(t.leading)
    val plan = CtorPlan.of(t, unit, sentinels, registry)
    trivia(plan.primaryLeading)
    t.serialVersionUID.foreach(v => line(s"@SerialVersionUID(${v}L)"))
    // enum ctors are implicitly private in Java; the Scala enum primary stays unmodified
    val primary = plan.primaryParams match
      case Nil => ""
      case ps  => "(" + ps.map(paramStr).mkString(", ") + ")"
    val ext = (s"java.lang.Enum[${id(t.name)}]" :: t.interfaces.map(tpe)).mkString(" extends ", " with ", "")
    line(s"${visPrefix(t.mods)}enum ${id(t.name)}$primary$ext {")
    indent += 1
    t.enumCases.foreach { c =>
      trivia(c.leading)
      if c.args.isEmpty && plan.primaryParams.isEmpty then line(s"case ${id(c.name)}")
      else line(s"case ${id(c.name)} extends ${id(t.name)}(${c.args.map(expr).mkString(", ")})")
    }
    line()
    // enum auxiliary constructors (a no-arg Java enum ctor delegating this(default))
    // let no-arg cases `extends Flags()` resolve — Scala 3 enums allow `def this()`
    plan.secondaryCtors.foreach { sc =>
      trivia(sc.leading)
      val dArgs =
        if sc.targetTypes.length == sc.delegateArgs.length then
          sc.delegateArgs.zip(sc.targetTypes).map((a, tt) => delegateArg(a, Some(tt))).mkString(", ")
        else sc.delegateArgs.map(delegateArg).mkString(", ")
      if sc.body.isEmpty then
        line(s"${visPrefix(sc.mods)}def this(${sc.params.map(paramOf).mkString(", ")}) = this($dArgs)")
      else
        line(s"${visPrefix(sc.mods)}def this(${sc.params.map(paramOf).mkString(", ")}) = {")
        indent += 1; line(s"this($dArgs)"); sc.body.foreach(stmt); indent -= 1; line("}")
      line()
    }
    plan.fieldLines.foreach {
      case FieldLine.FromField(f, init) =>
        trivia(f.leading)
        annotationLines(f.mods)
        val kw = if f.mods.isFinal then "val" else "var"
        line(s"${beanPrefix(f, t.methods)}${visPrefix(f.mods)}$kw ${id(f.name)}: ${tpe(f.tpe)} = ${expr(init)}")
        line()
      case FieldLine.SentinelVal(f, pname, default) =>
        trivia(f.leading)
        line(s"${beanPrefix(f, t.methods)}${visPrefix(f.mods)}val ${id(f.name)}: ${tpe(f.tpe)} = if (${id(pname)} != null) ${id(pname)} else ${expr(default)}")
        line()
      case FieldLine.CondInit(f, pname, whenSome, whenNull) =>
        trivia(f.leading)
        val kw = if f.mods.isFinal then "val" else "var"
        line(s"${beanPrefix(f, t.methods)}${visPrefix(f.mods)}$kw ${id(f.name)}: ${tpe(f.tpe)} = if (${id(pname)} != null) ${expr(whenSome)} else ${expr(whenNull)}")
        line()
      case FieldLine.DefaultInit(f) =>
        trivia(f.leading)
        line(s"${beanPrefix(f, t.methods)}${visPrefix(f.mods)}var ${id(f.name)}: ${tpe(f.tpe)} = ${defaultOf(f.tpe)}")
        line()
    }
    if plan.primaryBody.nonEmpty then
      plan.primaryBody.foreach(stmt)
      line()
    t.methods.foreach(methodDecl)
    indent -= 1
    line("}")
    companion(t)

  private def traitDecl(t: BTypeDecl): Unit =
    trivia(t.leading)
    annotationLines(t.mods)
    val ext =
      if t.interfaces.isEmpty then ""
      else " extends " + t.interfaces.map(tpe).mkString(" with ")
    line(s"${visPrefix(t.mods)}trait ${id(t.name)}${tparamsStr(t.tparams)}$ext {")
    indent += 1
    t.methods.foreach(methodDecl)
    indent -= 1
    line("}")
    companion(t)

  /** Java statics + static nested types → companion object (DESIGN.md §4;
    * init-order caveats documented there).
    */
  private def companion(t: BTypeDecl): Unit =
    if t.staticFields.nonEmpty || t.staticMethods.nonEmpty || t.nested.nonEmpty || t.staticInit.nonEmpty then
      line()
      line(s"object ${id(t.name)} {")
      indent += 1
      // Java blank-final statics (`static final X F; static { F = ...; }`) are
      // assigned in the static-init block, not at declaration — Scala can't express
      // a val assigned later in the object body, so those must be `var`.
      val reassignedStatics = assignedFieldNames(t.staticInit)
      t.staticFields.foreach { f =>
        trivia(f.leading)
        val kw = if f.mods.isFinal && !reassignedStatics(f.name) then "val" else "var"
        val rhs = f.init.map(expr).getOrElse(defaultOf(f.tpe))
        line(s"${visPrefix(f.mods)}$kw ${id(f.name)}: ${tpe(f.tpe)} = $rhs")
        line()
      }
      if t.staticInit.nonEmpty then
        // Java `static { ... }` blocks — companion body statements (init-order caveat:
        // Scala companions initialize lazily on first access, DESIGN.md §4 trap 1)
        t.staticInit.foreach(stmt)
        line()
      t.staticMethods.foreach(methodDecl)
      t.nested.foreach { n =>
        nestedDepth += 1
        typeDecl(n)
        nestedDepth -= 1
        line()
      }
      indent -= 1
      line("}")

  /** Names of fields that appear as the LHS of an assignment anywhere in `stmts`
    * (recursing through control flow). A static blank-final assigned in a static
    * init block is detected here and rendered `var` rather than `val`. Method calls
    * on a field (`F.addAll(...)`) are not assignments and don't count. */
  private def assignedFieldNames(stmts: List[BStmt]): Set[String] =
    val out = collection.mutable.Set[String]()
    def fieldName(e: BExpr): Option[String] = e match
      case Ident(n, RefKind.StaticField(_)) => Some(n)
      case Ident(n, RefKind.OwnField)       => Some(n)
      case Select(_, n)                     => Some(n)
      case _                                => None
    def walk(ss: List[BStmt]): Unit = ss.foreach(s => walkK(s.k))
    def walkK(k: BStmtK): Unit = k match
      case BStmtK.Assign(lhs, _, _)  => fieldName(lhs).foreach(out += _)
      case BStmtK.If(_, tb, eb)      => walk(tb); eb.foreach(walk)
      case BStmtK.While(_, b)        => walk(b)
      case BStmtK.DoWhile(b, _)      => walk(b)
      case BStmtK.Block(b)           => walk(b)
      case BStmtK.Try(b, cs, f)      => walk(b); cs.foreach(c => walk(c.body)); f.foreach(walk)
      case BStmtK.Boundary(b, _)     => walk(b)
      case BStmtK.Match(_, cases)    => cases.foreach(c => walk(c.body))
      case BStmtK.Synchronized(_, b) => walk(b)
      case _                         => ()
    walk(stmts)
    out.toSet

  private def tparamsStr(tps: List[BTypeParam]): String =
    if tps.isEmpty then ""
    else "[" + tps.map(tp => tp.name + tp.upper.map(u => s" <: ${tpe(u)}").getOrElse("")).mkString(", ") + "]"

  private def classDecl(t: BTypeDecl): Unit =
    trivia(t.leading)
    annotationLines(t.mods)
    val fqcn = if unit.pkg.isEmpty then t.name else s"${unit.pkg}.${t.name}"
    ctorOverrides.get(fqcn).filter(_ => nestedDepth == 0) match
      case Some(ovr) => classDeclOverridden(t, ovr); return
      case None      => ()
    val plan = CtorPlan.of(t, unit, sentinels, registry)
    trivia(plan.primaryLeading)
    t.serialVersionUID.foreach(v => line(s"@SerialVersionUID(${v}L)"))
    val mods = StringBuilder(visPrefix(t.mods))
    if t.mods.isAbstract then mods.append("abstract ")
    if t.mods.isFinal then mods.append("final ")

    // a private class can't expose a less-private ctor; and ctor vis on a private
    // class trips "non-private constructor refers to private class"
    val primaryVis =
      if t.mods.vis == Vis.Private then ""
      else
        plan.primaryMods
          .map(m => visPrefix(m).trim)
          .filter(_.nonEmpty)
          .map(v => s" $v ")
          .getOrElse("")
    val reParams = reassignedParams(plan.primaryBody, plan.primaryParams.map(_.p.name).toSet)
    val primary = plan.primaryParams match
      case Nil => ""
      case ps  => primaryVis + "(" + ps.map(paramStr(_, t.methods, reParams)).mkString(", ") + ")"
    val ext = (t.superClass, plan.superArgs) match
      case (None, _) if t.interfaces.isEmpty => ""
      case (None, _)         => " extends " + t.interfaces.map(tpe).mkString(" with ")
      case (Some(s), args)   =>
        val sup = tpe(s) + (if args.isEmpty then "" else "(" + args.map(delegateArg).mkString(", ") + ")")
        " extends " + (sup :: t.interfaces.map(tpe)).mkString(" with ")

    line(s"${mods.result()}class ${id(t.name)}${tparamsStr(t.tparams)}$primary$ext {")
    indent += 1

    if t.staticInit.nonEmpty then
      // Java <clinit> runs before the first instance; Scala companions are lazy —
      // touch the companion so static{} blocks keep their before-any-instance timing
      // (DESIGN.md §4 trap 1, hit live by SPI registries)
      line(s"locally(${id(t.name)})")
      line()

    plan.fieldLines.foreach {
      case FieldLine.FromField(f, init) =>
        trivia(f.leading)
        annotationLines(f.mods)
        val kw = if f.mods.isFinal then "val" else "var"
        line(s"${beanPrefix(f, t.methods)}${visPrefix(f.mods)}$kw ${id(f.name)}: ${tpe(f.tpe)} = ${expr(init)}")
        line()
      case FieldLine.SentinelVal(f, pname, default) =>
        trivia(f.leading)
        line(s"${beanPrefix(f, t.methods)}${visPrefix(f.mods)}val ${id(f.name)}: ${tpe(f.tpe)} = if (${id(pname)} != null) ${id(pname)} else ${expr(default)}")
        line()
      case FieldLine.CondInit(f, pname, whenSome, whenNull) =>
        trivia(f.leading)
        val kw = if f.mods.isFinal then "val" else "var"
        line(s"${beanPrefix(f, t.methods)}${visPrefix(f.mods)}$kw ${id(f.name)}: ${tpe(f.tpe)} = if (${id(pname)} != null) ${expr(whenSome)} else ${expr(whenNull)}")
        line()
      case FieldLine.DefaultInit(f) =>
        trivia(f.leading)
        line(s"${beanPrefix(f, t.methods)}${visPrefix(f.mods)}var ${id(f.name)}: ${tpe(f.tpe)} = ${defaultOf(f.tpe)}")
        line()
    }
    plan.secondaryCtors.foreach { sc =>
      trivia(sc.leading)
      // an aux-ctor param reassigned in the body can't stay a val: rename it `_p`,
      // add `var p = _p` after the delegate, and read `_p` in the delegate args
      val reassigned = reassignedParams(sc.body, sc.params.map(_.name).toSet)
      val paramStrs = sc.params.map(p => if reassigned(p.name) then paramOf(p.copy(name = "_" + p.name)) else paramOf(p))
      val sig = s"${visPrefix(sc.mods)}def this(${paramStrs.mkString(", ")}) ="
      def fixArg(a: BExpr): BExpr =
        if reassigned.isEmpty then a
        else
          BirTransform.mapExpr(a) {
            case Ident(n, RefKind.Param(v)) if reassigned(n) => Ident("_" + n, RefKind.Param(v))
            case e                                           => e
          }
      val dArgs =
        if sc.targetTypes.length == sc.delegateArgs.length then
          sc.delegateArgs.zip(sc.targetTypes).map((a, tt) => delegateArg(fixArg(a), Some(tt))).mkString(", ")
        else sc.delegateArgs.map(a => delegateArg(fixArg(a))).mkString(", ")
      if sc.body.isEmpty then
        line(sig)
        indent += 1
        line(s"this($dArgs)")
        indent -= 1
      else
        line(sig + " {")
        indent += 1
        line(s"this($dArgs)")
        reassigned.toList.sorted.foreach { n =>
          val p = sc.params.find(_.name == n).get
          line(s"var ${id(n)}: ${tpe(p.tpe)} = ${id("_" + n)}")
        }
        sc.body.foreach(stmt)
        indent -= 1
        line("}")
      line()
    }
    if t.instanceInit.nonEmpty then
      t.instanceInit.foreach(stmt)
      line()
    if plan.primaryBody.nonEmpty then
      plan.primaryBody.foreach(stmt)
      line()
    t.methods.foreach(methodDecl)

    t.inner.foreach { n =>
      nestedDepth += 1
      typeDecl(n)
      nestedDepth -= 1
      line()
    }

    indent -= 1
    line("}")
    companion(t)

  /** Class emission with a handwritten constructor block (CtorOverride): the header
    * suffix and body come verbatim from the override; fields/methods/inner/companion
    * are still the engine's, so the class stays in sync with upstream on re-port. */
  private def classDeclOverridden(t: BTypeDecl, ovr: CtorOverride): Unit =
    t.serialVersionUID.foreach(v => line(s"@SerialVersionUID(${v}L)"))
    val mods = StringBuilder(visPrefix(t.mods))
    if t.mods.isAbstract then mods.append("abstract ")
    if t.mods.isFinal then mods.append("final ")
    line(s"${mods.result()}class ${id(t.name)}${tparamsStr(t.tparams)}${ovr.headerSuffix} {")
    indent += 1
    if t.staticInit.nonEmpty then
      line(s"locally(${id(t.name)})")
      line()
    ovr.body.foreach(line)
    if ovr.body.nonEmpty then line()
    t.methods.foreach(methodDecl)
    t.inner.foreach { n =>
      nestedDepth += 1
      typeDecl(n)
      nestedDepth -= 1
      line()
    }
    indent -= 1
    line("}")
    companion(t)

  /** Delegation/super-call argument: forwarding a varargs param needs a spread
    * (formals of this()/super() targets aren't tracked; forwarding-whole is the
    * overwhelmingly common Java shape, and scalac verifies).
    */
  /** a type carrying a wildcard anywhere — illegal in `new`/CtorRef instantiation args. */
  private def hasWildType(x: BType): Boolean = x match
    case _: BType.Wild    => true
    case BType.Ref(_, as) => as.exists(hasWildType)
    case BType.Arr(e2)    => hasWildType(e2)
    case _                => false

  private def delegateArg(e: BExpr): String = delegateArg(e, None)

  private def delegateArg(e: BExpr, target: Option[BType]): String =
    val stripped = e match
      case Typed(i, _) => i
      case other       => other
    (stripped, target) match
      case (Ident(_, RefKind.Param(true)), Some(BType.Arr(_))) => expr(stripped) + ".toArray"
      case (Ident(_, RefKind.Param(true)), _)                  => expr(stripped) + "*"
      // a bare `null` delegate arg is ambiguous when the target ctor is overloaded
      // (this(null) matching both (String) and (BasedSequence)) — ascribe its type
      // a type-variable target can't take the `(null: T)` ascription (Null isn't a
      // subtype of an unbounded T) — cast instead
      case (Lit(LitKind.NullL, _), Some(t: BType.TVar))                    => s"null.asInstanceOf[${tpe(t)}]"
      case (Lit(LitKind.NullL, _), Some(t)) if !t.isInstanceOf[BType.Prim] => s"(null: ${tpe(t)})"
      case _                                                   => expr(stripped)

  private def paramStr(p: CtorPlan.Param): String = paramStr(p, Nil, Set.empty)

  private def paramStr(p: CtorPlan.Param, methods: List[BMethod], reassigned: Set[String] = Set.empty): String =
    p.promoted match
      // a promoted field reassigned in the ctor body (Java mutates the param before
      // storing the final field) must be `var`, not `val`
      case Some(f)                               => s"${beanPrefix(f, methods)}${visPrefix(f.mods)}${if reassigned.contains(p.p.name) then "var" else "val"} ${id(p.p.name)}: ${tpe(p.p.tpe)}"
      // Java ctor params are mutable; a primary-ctor param reassigned in the ctor body
      // becomes a `private var` field (Scala params are val). The super call still reads
      // its value, and the body's `p += ...` / `p++` mutate the field.
      case None if reassigned.contains(p.p.name) => s"private var ${paramOf(p.p)}"
      case None                                  => paramOf(p.p)

  /** Primary-ctor parameters reassigned in the ctor body (statement `p = …`, or an
    * `AssignExpr`/`IncDecExpr` nested in an expression such as `p++`). */
  private def reassignedParams(stmts: List[BStmt], pnames: Set[String]): Set[String] =
    if pnames.isEmpty then Set.empty
    else
      val out = collection.mutable.Set[String]()
      // a primary-ctor param may be read back either as its parameter (Param) or, when
      // promoted to a field, as an own-field reference — both count as the same binding
      def isTarget(e: BExpr): Option[String] = e match
        case Ident(n, RefKind.Param(_)) if pnames(n) => Some(n)
        case Ident(n, RefKind.OwnField) if pnames(n) => Some(n)
        case _                                       => None
      def exprScan(e: BExpr): Unit =
        BirTransform.mapExpr(e) { x =>
          x match
            case AssignExpr(t, _) => isTarget(t).foreach(out += _)
            case IncDecExpr(t, _, _) => isTarget(t).foreach(out += _)
            case _                => ()
          x
        }
      def walk(ss: List[BStmt]): Unit = ss.foreach(s => walkK(s.k))
      def walkK(k: BStmtK): Unit = k match
        case BStmtK.Assign(lhs, rhs, _) =>
          isTarget(lhs) match
            case Some(n) => out += n
            case None    => exprScan(lhs)
          exprScan(rhs)
        case BStmtK.LocalVar(_, _, i, _) => i.foreach(exprScan)
        case BStmtK.ExprStmt(e)          => exprScan(e)
        case BStmtK.If(c, t, e)          => exprScan(c); walk(t); e.foreach(walk)
        case BStmtK.While(c, b)          => exprScan(c); walk(b)
        case BStmtK.DoWhile(b, c)        => walk(b); exprScan(c)
        case BStmtK.Return(e)            => e.foreach(exprScan)
        case BStmtK.Throw(e)             => exprScan(e)
        case BStmtK.Block(b)             => walk(b)
        case BStmtK.Try(b, cs, f)        => walk(b); cs.foreach(c => walk(c.body)); f.foreach(walk)
        case BStmtK.Boundary(b, _)       => walk(b)
        case BStmtK.Match(scr, cases)    => exprScan(scr); cases.foreach(c => walk(c.body))
        case BStmtK.Synchronized(l, b)   => exprScan(l); walk(b)
        case BStmtK.Assert(c, m)         => exprScan(c); m.foreach(exprScan)
        case _                           => ()
      walk(stmts)
      out.toSet

  private def paramOf(p: BParam): String =
    val t = if p.varargs then
      p.tpe match
        case BType.Arr(e) => tpe(e) + "*"
        case other        => tpe(other) + "*"
    else tpe(p.tpe)
    s"${id(p.name)}: $t"

  /** Java PUBLIC fields are reflectively visible (Jackson/beans introspection);
    * Scala fields compile to private+accessor — @BeanProperty restores getters.
    * Skipped when the class already declares the bean method. */
  private def beanPrefix(f: BField, methods: List[BMethod]): String =
    if f.mods.vis != Vis.Public then ""
    else
      val cap = f.name.capitalize
      val clash = methods.exists(m => m.name == s"get$cap" || m.name == s"is$cap" || m.name == s"set$cap")
      if clash then "" else "@scala.beans.BeanProperty "

  private def annotationLines(m: Mods): Unit =
    m.annotations.foreach { a =>
      val args =
        if a.args.isEmpty then ""
        else "(" + a.args.map((k, v) => s"${id(k)} = ${expr(v)}").mkString(", ") + ")"
      line(s"@${refName(a.qname)}$args")
    }

  private def methodDecl(m: BMethod): Unit =
    trivia(m.leading)
    annotationLines(m.mods)
    val mods = StringBuilder(visPrefix(m.mods))
    if m.mods.isOverride then mods.append("override ")
    if m.mods.isFinal then mods.append("final ")

    // Java parameters are mutable; reassigned ones become `_p` + `var p = _p`.
    val paramStrs = m.params.map { p =>
      if m.assignedParams.contains(p.name) then paramOf(p.copy(name = "_" + p.name)) else paramOf(p)
    }
    val sig = s"${mods.result()}def ${id(m.name)}${tparamsStr(m.tparams)}(${paramStrs.mkString(", ")}): ${tpe(m.ret)}"
    m.body match
      case None => line(sig)
      case Some(body) =>
        line(sig + " = {")
        indent += 1
        m.params.filter(p => m.assignedParams.contains(p.name)).foreach { p =>
          val t = if p.varargs then unsupported(s"reassigned varargs parameter ${p.name}") else tpe(p.tpe)
          line(s"var ${id(p.name)}: $t = ${id("_" + p.name)}")
        }
        // `return null` from a method whose return type is a type variable — Scala's
        // unbounded T rejects Null, so ascribe (Java allows null for any ref type)
        printBody(if m.ret.isInstanceOf[BType.TVar] then body.map(ascribeReturnNulls(_, m.ret)) else body)
        indent -= 1
        line("}")
    line()

  // ---- statements ------------------------------------------------------------

  /** ascribe a bare `return null` to the method's type-variable return type,
    * recursing into control-flow bodies (the null must carry the T type). */
  private def ascribeReturnNulls(s: BStmt, ret: BType): BStmt =
    def r(x: BStmt) = ascribeReturnNulls(x, ret)
    val k = s.k match
      case BStmtK.Return(Some(Lit(LitKind.NullL, _))) => BStmtK.Return(Some(Cast(ret, Lit(LitKind.NullL, "null"))))
      case BStmtK.If(c, t, e)        => BStmtK.If(c, t.map(r), e.map(_.map(r)))
      case BStmtK.While(c, b)        => BStmtK.While(c, b.map(r))
      case BStmtK.DoWhile(b, c)      => BStmtK.DoWhile(b.map(r), c)
      case BStmtK.Block(b)           => BStmtK.Block(b.map(r))
      case BStmtK.Try(b, cs, f)      => BStmtK.Try(b.map(r), cs.map(c => c.copy(body = c.body.map(r))), f.map(_.map(r)))
      case BStmtK.Boundary(b, l)     => BStmtK.Boundary(b.map(r), l)
      case BStmtK.Synchronized(l, b) => BStmtK.Synchronized(l, b.map(r))
      case BStmtK.Match(scr, cases)  => BStmtK.Match(scr, cases.map(c => c.copy(body = c.body.map(r))))
      case other                     => other
    s.copy(k = k)

  /** true while emitting a lambda body wrapped in scala.util.boundary — any
    * surviving `return e` prints as `boundary.break(e)`. */
  private var lambdaBoundaryActive = false

  /** Converts tail-position `return e` to a bare value `e` (recursing into the
    * tails of if/else, match, try, and nested blocks) so a Java lambda block reads
    * as a Scala expression. Non-tail returns are left for the boundary fallback. */
  private def stripTailReturns(stmts: List[BStmt]): List[BStmt] =
    if stmts.isEmpty then stmts
    else
      val last = stmts.last
      val newK = last.k match
        case BStmtK.Return(Some(e)) => BStmtK.ExprStmt(e)
        case BStmtK.Return(None)    => BStmtK.Empty
        case BStmtK.If(c, t, e)     => BStmtK.If(c, stripTailReturns(t), e.map(stripTailReturns))
        case BStmtK.Match(s, cs)    => BStmtK.Match(s, cs.map(cc => cc.copy(body = stripTailReturns(cc.body))))
        case BStmtK.Block(b)        => BStmtK.Block(stripTailReturns(b))
        case BStmtK.Try(b, cs, f)   => BStmtK.Try(stripTailReturns(b), cs.map(cc => cc.copy(body = stripTailReturns(cc.body))), f)
        case k                      => k
      stmts.init :+ last.copy(k = newK)

  private def hasReturn(stmts: List[BStmt]): Boolean =
    stmts.exists { s =>
      s.k match
        case BStmtK.Return(_)       => true
        case BStmtK.If(_, t, e)     => hasReturn(t) || e.exists(hasReturn)
        case BStmtK.While(_, b)     => hasReturn(b)
        case BStmtK.DoWhile(b, _)   => hasReturn(b)
        case BStmtK.Block(b)        => hasReturn(b)
        case BStmtK.Boundary(b, _)  => hasReturn(b)
        case BStmtK.Match(_, cs)    => cs.exists(cc => hasReturn(cc.body))
        case BStmtK.Try(b, cs, f)   => hasReturn(b) || cs.exists(cc => hasReturn(cc.body)) || f.exists(hasReturn)
        case BStmtK.Synchronized(_, b) => hasReturn(b)
        case _                      => false
    }

  /** Prints a method body; a trailing `return e` prints as `e`. */
  private def printBody(body: List[BStmt]): Unit =
    body.zipWithIndex.foreach { case (s, i) =>
      val isLast = i == body.length - 1
      s.k match
        case BStmtK.Return(Some(e)) if isLast => trivia(s.leading); line(expr(e))
        case _                                => stmt(s)
    }

  private def stmt(s: BStmt): Unit =
    trivia(s.leading)
    s.k match
      case BStmtK.LocalVar(name, t, init, effFinal) =>
        val kw = if effFinal then "val" else "var"
        // wildcard-typed locals: the annotation would demand invariant conformance the
        // rhs can't give (raw-type iterators etc.) — let inference take it
        def wildIn(x: BType): Boolean = x match
          case _: BType.Wild    => true
          case BType.Ref(_, as) => as.exists(wildIn)
          case BType.Arr(e2)    => wildIn(e2)
          case _                => false
        // engine-synthesized loop locals ($it/$arr) always infer correctly and their
        // declared types can be existential-hostile
        val synthetic = name.endsWith("$it") || name.endsWith("$arr")
        // a call whose return type is a bare method type variable (getBuilder():
        // <B extends ...> B) needs the declared type as inference context, even when
        // it carries a wildcard — otherwise B infers Nothing. Keep the skip only for
        // top-level-wildcard locals (raw iterators), which infer fine.
        def topWild(x: BType): Boolean = x.isInstanceOf[BType.Wild]
        // a call/constructor whose type args Scala must infer needs the declared type as
        // context: a method type-var return (getBuilder(): <B..> B) infers Nothing, and a
        // raw `new HashSet()` (Java diamond) infers Object without the annotation. Keep the
        // annotation for those (unless the local's own type is a top-level wildcard, which
        // can't be written and infers fine anyway).
        val ctorInit = init.exists(e => e.isInstanceOf[Call] || e.isInstanceOf[New] || e.isInstanceOf[NewArray])
        val skip = synthetic || (wildIn(t) && !(ctorInit && !topWild(t)))
        val ann = if skip && init.isDefined then "" else s": ${tpe(t)}"
        val rhs = init.map(expr).getOrElse(defaultOf(t))
        line(s"$kw ${id(name)}$ann = $rhs")
      case BStmtK.ExprStmt(e) => line(expr(e))
      case BStmtK.Assign(lhs, rhs, op) =>
        line(s"${expr(lhs)} ${op.getOrElse("")}= ${expr(rhs)}")
      case BStmtK.If(c, t, e) =>
        line(s"if (${expr(c)}) {")
        indent += 1; t.foreach(stmt); indent -= 1
        e match
          case None => line("}")
          case Some(els) =>
            line("} else {")
            indent += 1; els.foreach(stmt); indent -= 1
            line("}")
      case BStmtK.Return(None)    => line(if lambdaBoundaryActive then "scala.util.boundary.break()" else "return")
      case BStmtK.Return(Some(e)) => line(if lambdaBoundaryActive then s"scala.util.boundary.break(${expr(e)})" else s"return ${expr(e)}")
      case BStmtK.Throw(e)        => line(s"throw ${expr(e)}")
      case BStmtK.While(c, b) =>
        line(s"while (${expr(c)}) {")
        indent += 1; b.foreach(stmt); indent -= 1
        line("}")
      case BStmtK.DoWhile(b, c) =>
        line("while ({")
        indent += 1; b.foreach(stmt); line(expr(c)); indent -= 1
        line("}) ()")
      case BStmtK.Assert(c, m) =>
        m match
          case Some(msg) => line(s"assert(${expr(c)}, ${expr(msg)})")
          case None      => line(s"assert(${expr(c)})")
      case BStmtK.Block(b) =>
        // `locally` keeps a bare block from gluing onto the previous line as an
        // anonymous-class body or refinement
        line("locally {")
        indent += 1; b.foreach(stmt); indent -= 1
        line("}")
      case BStmtK.Try(b, catches, fin) =>
        line("try {")
        indent += 1; b.foreach(stmt); indent -= 1
        if catches.nonEmpty then
          line("} catch {")
          indent += 1
          catches.foreach { c =>
            val pat = c.types match
              case List(t1) => s"${id(c.param)}: ${tpe(t1)}"
              case ts       => s"${id(c.param)} @ (${ts.map(t1 => s"_: ${tpe(t1)}").mkString(" | ")})"
            line(s"case $pat =>")
            indent += 1; c.body.foreach(stmt); indent -= 1
          }
          indent -= 1
        fin match
          case Some(f) =>
            line("} finally {")
            indent += 1; f.foreach(stmt); indent -= 1
            line("}")
          case None => line("}")
      case BStmtK.Boundary(b, label) =>
        label match
          case None    => line("scala.util.boundary {")
          case Some(l) => line(s"scala.util.boundary { (${id(l)}: scala.util.boundary.Label[Unit]) ?=>")
        indent += 1; b.foreach(stmt); indent -= 1
        line("}")
      case BStmtK.LoopBreak(None)    => line("scala.util.boundary.break()")
      case BStmtK.LoopBreak(Some(l)) => line(s"scala.util.boundary.break()(using ${id(l)})")
      case BStmtK.Match(scrutinee, cases) =>
        line(s"${expr(scrutinee)} match {")
        indent += 1
        cases.foreach { c =>
          val pat = if c.isDefault then "_" else c.exprs.map(expr).mkString(" | ")
          line(s"case $pat =>")
          indent += 1
          if c.body.isEmpty then line("()") else c.body.foreach(stmt)
          indent -= 1
        }
        indent -= 1
        line("}")
      case BStmtK.Synchronized(l, b) =>
        line(s"${expr(l)}.synchronized {")
        indent += 1; b.foreach(stmt); indent -= 1
        line("}")
      case BStmtK.LocalType(t) =>
        // local definitions take no access modifiers in Scala
        typeDecl(t.copy(mods = t.mods.copy(vis = Vis.Public)))
      case BStmtK.Empty => ()

  private def defaultOf(t: BType): String = t match
    case BType.Prim("boolean")                          => "false"
    case BType.Prim("float")                            => "0.0f"
    case BType.Prim("double")                           => "0.0d"
    case BType.Prim("long")                             => "0L"
    case BType.Prim("char")                             => "'\\u0000'"
    case BType.Prim(_)                                  => "0"
    case _                                              => "null"

  // ---- expressions -----------------------------------------------------------

  private def expr(e: BExpr): String = e match
    case Lit(_, raw)   => raw
    case Ident(n, RefKind.StaticField(owner)) => s"${refName(owner)}.${id(n)}"
    // explicit `this.` — a Java local may shadow a same-named field, and Java resolves
    // the pre-declaration read to the field while Scala's block scoping would not
    case Ident(n, RefKind.OwnField) => s"this.${id(n)}"
    case Ident(n, RefKind.OuterField(outer)) => s"${id(outer)}.this.${id(n)}"
    case Ident(n, RefKind.EnclosingField) => id(n) // bare: resolved lexically from an anon/local class
    case Ident(n, _)                => id(n)
    case This          => "this"
    case Select(r, n)  => s"${expr(r)}.${id(n)}"
    case ArrayLength(a) => s"${expr(a)}.length"
    case ArrayAccess(a, i) => s"${expr(a)}(${expr(i)})"
    case Typed(inner, _) => expr(inner)
    case AssignExpr(l, r) => s"{ ${expr(l)} = ${expr(r)}; ${expr(l)} }"
    case IncDecExpr(t, op, post) =>
      if post then s"{ val tmp$$ = ${expr(t)}; ${expr(t)} $op= 1; tmp$$ }"
      else s"{ ${expr(t)} $op= 1; ${expr(t)} }"

    case Call(recv, name, args, formals, ownerQ) =>
      val target = recv match
        case Recv.OnThis        => ""
        case Recv.OnSuper       => "super."
        case Recv.Static(owner) => refName(owner) + "."
        case Recv.On(r)         => expr(r) + "."
      s"$target${id(name)}(${adaptedArgs(args, formals, ownerQ).mkString(", ")})"

    case New(t, args, anon, formals) =>
      // wildcards are illegal in instantiation type args (Java diamond/raw) — strip
      // and let inference do what javac did
      val newT = if t.args.exists(hasWildType) then t.copy(args = Nil) else t
      val argsStr =
        if args.isEmpty && anon.isDefined then ""
        else s"(${adaptedArgs(args, formals, Some(t.qname)).mkString(", ")})"
      // `new Object()` — Any has no constructor; Object aliases AnyRef in Scala
      val typeStr = if BType.isObject(BType.Ref(t.qname, Nil)) then "Object" else tpe(newT)
      val base = s"new $typeStr$argsStr"
      anon match
        case None => base
        case Some(BAnonBody(Nil, Nil, Nil)) => base + " {}"
        case Some(BAnonBody(fields, methods, init)) =>
          val body = captured {
            indent += 1
            fields.foreach { f =>
              trivia(f.leading)
              val kw = if f.mods.isFinal then "val" else "var"
              val rhs = f.init.map(expr).getOrElse(defaultOf(f.tpe))
              line(s"${beanPrefix(f, methods)}${visPrefix(f.mods)}$kw ${id(f.name)}: ${tpe(f.tpe)} = $rhs")
            }
            init.foreach(stmt)
            methods.foreach(methodDecl)
            indent -= 1
          }
          base + " {\n" + body + ("  " * indent) + "}"
    case NewArray(el, _, Some(inits)) =>
      // Object[] initializers box like Java autoboxing did
      val items =
        if BType.isObject(el) then inits.map(i => s"${expr(i)}.asInstanceOf[AnyRef]")
        else inits.map(expr)
      s"Array[${arrElem(el)}](${items.mkString(", ")})"
    case NewArray(el, List(dim), None) => s"new Array[${arrElem(el)}](${expr(dim)})"
    case NewArray(_, dims, None) => unsupported(s"multi-dimensional array (${dims.length} dims)")

    case Binary(op, l, r, concat) =>
      // Java string concat: any operand String makes the whole chain concat; Scala
      // needs a String LEFT operand — String.valueOf is identity on strings, so
      // wrapping when the left isn't obviously a string is semantics-preserving
      // (incl. null → "null", matching Java)
      def obviouslyString(x: BExpr): Boolean = x match
        case Lit(LitKind.StringL, _)      => true
        case Binary(_, _, _, true)        => true
        case Typed(i, BType.Ref("java.lang.String", _)) => true
        case Typed(i, _)                  => obviouslyString(i)
        case _                            => false
      if concat && !obviouslyString(l) then s"(String.valueOf(${expr(l)}) $op ${expr(r)})"
      else s"(${expr(l)} $op ${expr(r)})"
    case Unary(op, e1, true) => s"($op${expr(e1)})"
    case Unary(op, _, false) => unsupported(s"postfix operator $op")
    case Ternary(c, t, e1)    => s"(if (${expr(c)}) ${expr(t)} else ${expr(e1)})"

    case CtorRef(t, formals) =>
      val ps = formals.zipWithIndex.map((ft, i) => s"p$i$$: ${tpe(ft)}")
      val args = formals.indices.map(i => s"p$i$$").mkString(", ")
      // wildcards are illegal in instantiation type args (raw HashMap::new) — strip
      val ctorT = if t.args.exists(hasWildType) then t.copy(args = Nil) else t
      s"((${ps.mkString(", ")}) => new ${tpe(ctorT)}($args))"

    case MethodRef(prefix, name) =>
      prefix match
        case Left(owner) => s"${refName(owner)}.${id(name)}"
        case Right(r)    => s"${expr(r)}.${id(name)}"

    case UnboundMethodRef(recvT, name, formals) =>
      // annotate the receiver only when its type is precise (wildcards would WIDEN what
      // SAM inference could otherwise carry); other params always infer
      def precise(x: BType): Boolean = x match
        case _: BType.Wild    => false
        case BType.Ref(_, as) => as.forall(precise)
        case BType.Arr(e2)    => precise(e2)
        case _                => true
      val recvP = if precise(recvT) then s"recv$$: ${tpe(recvT)}" else "recv$"
      val ps = recvP :: formals.indices.map(i => s"p$i$$").toList
      val args = formals.indices.map(i => s"p$i$$").mkString(", ")
      s"((${ps.mkString(", ")}) => recv$$.${id(name)}($args))"

    case Lambda(ps, body, pts) =>
      // annotate params with their resolved SAM types when available and clean —
      // wildcards can't be written as lambda param types, so fall back to bare names
      val useTypes = pts.length == ps.length && pts.nonEmpty && !pts.exists(hasWildType)
      val plist =
        if useTypes then "(" + ps.zip(pts).map((p, t) => s"${id(p)}: ${tpe(t)}").mkString(", ") + ")"
        else
          ps match
            case List(p1) => id(p1)
            case _        => "(" + ps.map(id).mkString(", ") + ")"
      body match
        case Right(e)                                     => s"($plist => ${expr(e)})"
        case Left(List(BStmt(_, BStmtK.Return(Some(e))))) => s"($plist => ${expr(e)})"
        case Left(List(BStmt(_, BStmtK.ExprStmt(e))))     => s"($plist => ${expr(e)})"
        case Left(stmts0) =>
          // Java lambdas use `return` for their value; Scala lambdas can't. Strip
          // tail-position returns (recursing into if/else/match/try tails); if early
          // (non-tail) returns remain, wrap in scala.util.boundary and break instead.
          val stmts = stripTailReturns(stmts0)
          val needsBoundary = hasReturn(stmts)
          val bodyStr = captured {
            indent += 1
            val saved = lambdaBoundaryActive
            lambdaBoundaryActive = needsBoundary
            printBody(stmts)
            lambdaBoundaryActive = saved
            indent -= 1
          }
          val pad = "  " * indent
          if needsBoundary then s"($plist => scala.util.boundary {\n" + bodyStr + pad + "})"
          else s"($plist => {\n" + bodyStr + pad + "})"

    case Cast(BType.Prim(p), e1) =>
      val conv = primMap.getOrElse(p, unsupported(s"cast to $p"))
      s"${expr(e1)}.to$conv"
    // a Java cast of a lambda / method reference to a functional interface is a SAM
    // conversion, not a runtime cast — ascribe it (`(f: I)`) so Scala converts, and so
    // the target type resolves an overloaded method reference (`(this.matches: Predicate)`)
    case Cast(t, e1) if e1.isInstanceOf[Lambda] || e1.isInstanceOf[MethodRef] || e1.isInstanceOf[UnboundMethodRef] =>
      s"(${expr(e1)}: ${tpe(t)})"
    case Cast(t, e1)       => s"${expr(e1)}.asInstanceOf[${tpe(t)}]"
    case InstanceOf(e1, t) => s"${expr(e1)}.isInstanceOf[${tpe(t)}]"
    case ClassLit(t) =>
      // Java class literals are erased. For a GENERIC class the raw Class value flows
      // with an unchecked T in Java — Class[AnyRef] reproduces that for inference,
      // with result casts handled at the assignment (maybeUncheckedCast).
      t match
        case BType.Ref(_, args) if args.nonEmpty =>
          // generic class literal: Java's raw Class flows with unchecked T
          s"classOf[${tpe(t)}].asInstanceOf[Class[AnyRef]]"
        case other => s"classOf[${tpe(other)}]"

  /** Call-site adaptation of Java varargs/array boundaries (DESIGN.md §4):
    *   - varargs param forwarded into a varargs slot        → spread `p*`
    *   - varargs param passed where an array is expected    → `p.toArray`
    *     (`.asInstanceOf[Array[AnyRef]]` when the callee is a JDK Object[] slot,
    *     since translated code maps Object → Any but the JDK keeps AnyRef)
    */
  private def adaptedArgs(args: List[BExpr], formals: Option[List[Formal]], ownerQ: Option[String]): List[String] =
    formals match
      case Some(fs) if fs.length == args.length =>
        args.zip(fs).map { (a0, f) =>
          val (a, at) = a0 match
            case Typed(inner, t) => (inner, Some(t))
            case e               => (e, None)
          (a, at, f) match
            // flat varargs param (H...) forwarded into a varargs-OF-ARRAYS slot
            // (Java H[]... target = Scala Array[H]*): Java passes the whole array as
            // ONE element, so materialize the Seq to one array — don't spread it flat
            case (Ident(_, RefKind.Param(true)), srcT, Formal(BType.Arr(el), true))
                if !srcT.exists(_.isInstanceOf[BType.Arr]) =>
              val conv = expr(a) + ".toArray"
              if BType.isObject(el) then conv + ".asInstanceOf[Array[AnyRef]]" else conv
            // varargs param forwarded into a varargs slot → spread
            case (Ident(_, RefKind.Param(true)), _, Formal(_, true)) => expr(a) + "*"
            // array-typed value into a varargs slot (Java passes arrays directly) → spread
            case (_, Some(BType.Arr(_)), Formal(_, true)) => expr(a) + "*"
            // varargs param into an array slot → materialize (Object[] slots always
            // need the cast: the Seq is Seq[Any] but Object[] is Array[AnyRef])
            case (Ident(_, RefKind.Param(true)), _, Formal(BType.Arr(el), false)) =>
              val conv = expr(a) + ".toArray"
              if BType.isObject(el) then conv + ".asInstanceOf[Array[AnyRef]]" else conv
            // varargs param into a plain Object slot: Java's runtime value is an
            // Object[] (isArray-visible) — Scala's Seq must materialize
            case (Ident(_, RefKind.Param(true)), _, Formal(t, false)) if BType.isObject(t) =>
              expr(a) + ".toArray"
            case _ => expr(a)
        }
      case _ => args.map(expr)
