package balticporter.corpus.simplegraphs

import balticporter.runner.PortConfig

import java.nio.file.{Files, Path}

/** Port simple-graphs' own JUnit suite (`src/test/java`) through the same pipeline as `src/main/java`.
  *
  *   corpus/runMain balticporter.corpus.simplegraphs.SimpleGraphsTestMigrate [--determinism=full]
  *
  * The port is `corpus/ports/simplegraphs/test.conf`; this `main` names it, ensures the test
  * classpath the conf points at exists, and gives the run its report identity. See
  * [[SimpleGraphsMigrate]] for why that is all a migration program is.
  *
  * 7 files, 16 `@Test` (a 17th, `GraphBuilderTest.testExample`, is commented out upstream) — the only behavioural evidence this port can have. `PROGRESS.md`
  * §simple-graphs says "compiles" until this runs, and CLAUDE.md §3 is explicit about the difference:
  * four silent
  * correctness defects in libGDX core all compiled cleanly, and not one of the ten Java forms in §4.4
  * moves a compile-error count.
  *
  * ==What makes this suite worth running rather than merely counting==
  * It exercises precisely the translations this library forced into the engine, from the outside:
  *
  *   - `Collections.sort(list, cmp)` and `Comparator` — is the ORDER the one java produced? A
  *     comparator whose sense is inverted compiles perfectly (`PROGRESS.md` §simple-graphs).
  *   - `java.util.stream` (`Collectors`, `IntStream`) in the TEST sources too, so the chain collapse
  *     is checked on code the library's own authors wrote to be read rather than to be ported.
  *   - `BadHashInteger` — a deliberately colliding `hashCode`, which is how `NodeMap`'s open
  *     addressing gets tested. That is a behavioural property no signature check can see.
  *   - `Array`, `Path`, `NodeCollection` and `VertexCollection` through their COLLECTION surface,
  *     which is the whole subject of K5: `containsAll`, `removeAll`, `retainAll`, `removeIf`,
  *     `toArray(T[])` all now come from a shim whose abstract/concrete split had four defects in it,
  *     each invisible until RefChecks ran.
  *
  * A DEPENDENT of [[SimpleGraphsMigrate]]: it resolves against `src/main/java`, never against the
  * Scala that port emitted, so the conf's `base = "main.conf"` inherits the base's rename and
  * surface phases rather than restating them (CLAUDE.md §1.5).
  */
object SimpleGraphsTestMigrate:

  def main(args: Array[String]): Unit =
    SimpleGraphsClasspath.ensure(SimpleGraphsPort.repoRoot)
    PortConfig.load(SimpleGraphsPort.conf("test.conf"), args.toSeq).execute()

/** simple-graphs' TEST-scope dependency, for shadow-class resolution only.
  *
  * JUnit 4 and nothing else — `build.gradle` declares exactly `junit:junit:4.12`, and that is the
  * version used rather than a current one. The rule is recorded in `AshleyClasspath` with its
  * cost: Ashley's suite needs Mockito **1.10.19** because `ComponentClassFactory` uses
  * `org.mockito.asm`, removed in 2.x, and guessing a modern version cost a full cycle. A port
  * resolves what the library DECLARES.
  *
  * `TestFrameworkTransform` converts the JUnit surface to MUnit, so the jar is a frontend input only
  * and never reaches the emitted code.
  *
  * ==Why this is a FILE the conf points at, and not a list in the conf==
  * The realistic source of a classpath is a dependency resolver, and a conf that inlined `cs`'s
  * output would be regenerated by hand on every dependency bump. So this writes the one
  * path-separator-joined line `cs fetch --classpath` produces, and `input.classpathFile` reads it.
  * A config file that named a COMMAND to run would be the strings-that-are-secretly-code the
  * transform SPI exists to keep out (CLAUDE.md §1.5).
  */
object SimpleGraphsClasspath:

  def cache(repoRoot: Path): Path = repoRoot.resolve("out/simplegraphs-test-classpath.txt")

  /** Guarantee the cache file exists, fetching once if it does not. Returns its path.
    *
    * A failure here is FATAL rather than an empty classpath, and that is not strictness for its own
    * sake: an `import static org.junit.Assert.assertEquals` the frontend cannot resolve does not
    * fail — it resolves WRONGLY, to an unqualified call on the enclosing test class — so a port
    * built with no JUnit on the frontend classpath emits nonsense and reports success.
    */
  def ensure(repoRoot: Path): Path =
    val out = cache(repoRoot)
    if Files.exists(out) && Files.readString(out).trim.nonEmpty then out
    else
      val pb = new ProcessBuilder("cs", "fetch", "--classpath", "junit:junit:4.12")
        .redirectErrorStream(true)
      val proc = pb.start()
      // `cs` writes PROGRESS to stderr and the classpath to stdout; merged here so a failure is
      // reportable, then filtered to the one line holding a jar. Taking the whole output cached
      // "Downloading https…" as a classpath entry and the frontend refused the run with
      // "Downloading https does not exist".
      val raw  = new String(proc.getInputStream.readAllBytes()).trim
      val line = raw.linesIterator.filter(_.contains(".jar")).toList.lastOption.getOrElse("")
      if proc.waitFor() != 0 || line.isEmpty then
        throw new IllegalStateException(
          s"[simple-graphs-test] could not fetch the test classpath (is `cs` installed?):\n$raw")
      Files.createDirectories(out.getParent)
      Files.writeString(out, line)
      out
