package balticporter.frontend.ts

class MermaidDbEmitterSpec extends munit.FunSuite:

  private def loadRast(resource: String): RastFile =
    val stream = getClass.getResourceAsStream(resource)
    assert(stream != null, s"Resource not found: $resource")
    val json = new String(stream.readAllBytes(), java.nio.charset.StandardCharsets.UTF_8)
    stream.close()
    Rast.readFile(json)

  // -- InfoDb (simplest: 11 LOC TS, no mutable state except version) ----------

  test("infoDb.ts -> InfoDb class from RAST"):
    val rast = loadRast("/rast/mermaid/src/diagrams/info/infoDb.rast.json")
    val scala = dedicated.MermaidDbEmitter.emitDb(rast, "InfoDb", "info")
    println("=== InfoDb.scala (RAST-based) ===")
    println(scala)
    assert(scala.contains("final class InfoDb"), "should emit InfoDb class")
    assert(scala.contains("def clear()"), "should have clear method")
    assert(scala.contains("Auto-generated by MermaidDbEmitter from RAST v1"), "should have RAST header")
    assert(scala.contains("package info"), "should have correct package")

  // -- PacketDb (56 LOC TS, mutable data, pushWord, getPacket) ---------------

  test("packet/db.ts -> PacketDb class from RAST"):
    val rast = loadRast("/rast/mermaid/src/diagrams/packet/db.rast.json")
    val scala = dedicated.MermaidDbEmitter.emitDb(rast, "PacketDb", "packet")
    println("=== PacketDb.scala (RAST-based) ===")
    println(scala)
    assert(scala.contains("final class PacketDb"), "should emit PacketDb class")
    assert(scala.contains("def clear()"), "should have clear method")
    assert(scala.contains("pushWord") || scala.contains("def pushWord"), "should have pushWord method")
    assert(scala.contains("getPacket") || scala.contains("def getPacket"), "should have getPacket method")
    assert(scala.contains("Auto-generated by MermaidDbEmitter from RAST v1"), "should have RAST header")

  // -- PieDb (67 LOC TS, Map sections, addSection, showData) -----------------

  test("pieDb.ts -> PieDb class from RAST"):
    val rast = loadRast("/rast/mermaid/src/diagrams/pie/pieDb.rast.json")
    val scala = dedicated.MermaidDbEmitter.emitDb(rast, "PieDb", "pie")
    println("=== PieDb.scala (RAST-based) ===")
    println(scala)
    assert(scala.contains("final class PieDb"), "should emit PieDb class")
    assert(scala.contains("def clear()"), "should have clear method")
    assert(scala.contains("sections"), "should have sections field")
    assert(scala.contains("showData"), "should have showData field")

  // -- SankeyDb (88 LOC TS, classes, addLink, findOrCreateNode) --------------

  test("sankeyDB.ts -> SankeyDb class from RAST"):
    val rast = loadRast("/rast/mermaid/src/diagrams/sankey/sankeyDB.rast.json")
    val scala = dedicated.MermaidDbEmitter.emitDb(rast, "SankeyDb", "sankey")
    println("=== SankeyDb.scala (RAST-based) ===")
    println(scala)
    assert(scala.contains("final class SankeyDb"), "should emit SankeyDb class")
    assert(scala.contains("def clear()"), "should have clear method")
    assert(scala.contains("links") || scala.contains("var links"), "should have links field")
    assert(scala.contains("nodes") || scala.contains("var nodes"), "should have nodes field")
    // Should have inner classes for SankeyLink and SankeyNode
    assert(scala.contains("SankeyLink") || scala.contains("case class"), "should have inner class")

  // -- MindmapDb (159 LOC TS, complex: switch, functions, object) ------------

  test("mindmapDb.ts -> MindmapDb class from RAST"):
    val rast = loadRast("/rast/mermaid/src/diagrams/mindmap/mindmapDb.rast.json")
    val scala = dedicated.MermaidDbEmitter.emitDb(rast, "MindmapDb", "mindmap")
    println("=== MindmapDb.scala (RAST-based) ===")
    println(scala)
    assert(scala.contains("final class MindmapDb"), "should emit MindmapDb class")
    assert(scala.contains("def clear()"), "should have clear method")
    assert(scala.contains("nodes") || scala.contains("var nodes"), "should have nodes field")

  // -- Write all emitted files to target/emitted-mermaid for inspection ------

  test("write RAST-based Db files to target/emitted-mermaid"):
    val outDir = java.nio.file.Path.of(sys.props.getOrElse("user.dir", ".")).resolve("target/emitted-mermaid")
    java.nio.file.Files.createDirectories(outDir)

    val files = List(
      ("/rast/mermaid/src/diagrams/info/infoDb.rast.json", "InfoDb", "info"),
      ("/rast/mermaid/src/diagrams/packet/db.rast.json", "PacketDb", "packet"),
      ("/rast/mermaid/src/diagrams/pie/pieDb.rast.json", "PieDb", "pie"),
      ("/rast/mermaid/src/diagrams/sankey/sankeyDB.rast.json", "SankeyDb", "sankey"),
      ("/rast/mermaid/src/diagrams/mindmap/mindmapDb.rast.json", "MindmapDb", "mindmap"),
    )

    for ((rastPath, className, pkg) <- files) {
      val rast = loadRast(rastPath)
      val scala = dedicated.MermaidDbEmitter.emitDb(rast, className, pkg)
      val path = outDir.resolve(s"${className}_rast.scala")
      java.nio.file.Files.writeString(path, scala)
      println(s"[emit-rast] ${className}.scala: ${scala.linesIterator.size} lines -> $path")
    }
