package balticporter.frontend.ts

class MermaidDiagramEmitterSpec extends munit.FunSuite:

  private def loadRast(resource: String): RastFile =
    val stream = getClass.getResourceAsStream(resource)
    assert(stream != null, s"Resource not found: $resource")
    val json = new String(stream.readAllBytes(), java.nio.charset.StandardCharsets.UTF_8)
    stream.close()
    Rast.readFile(json)

  // -- B4: Diagram emitter tests -------------------------------------------

  test("infoDiagram.ts -> InfoDiagram from RAST"):
    val rast = loadRast("/rast/mermaid/src/diagrams/info/infoDiagram.rast.json")
    val scala = balticporter.corpus.mermaid.MermaidDiagramEmitter.emitDiagram(
      rast, "InfoDiagram", "info", "InfoDb",
      parserClass = Some("InfoParser"),
      rendererClass = Some("InfoRenderer"),
      detectorClass = Some("InfoDetector"),
    )
    assert(scala.contains("object InfoDiagram"), "should emit InfoDiagram object")
    assert(scala.contains("def detect(text: String): Boolean"), "should have detect method")
    assert(scala.contains("def parse(text: String): InfoDb"), "should have parse method")
    assert(scala.contains("def render(text: String"), "should have render method")
    assert(scala.contains("Auto-generated by MermaidDiagramEmitter"), "should have header")

  test("pieDiagram.ts -> PieDiagram from RAST"):
    val rast = loadRast("/rast/mermaid/src/diagrams/pie/pieDiagram.rast.json")
    val scala = balticporter.corpus.mermaid.MermaidDiagramEmitter.emitDiagram(
      rast, "PieDiagram", "pie", "PieDb",
      detectorClass = Some("PieDetector"),
    )
    assert(scala.contains("object PieDiagram"), "should emit PieDiagram object")
    assert(scala.contains("def detect"), "should have detect method")

  test("sankeyDiagram.ts -> SankeyDiagram from RAST"):
    val rast = loadRast("/rast/mermaid/src/diagrams/sankey/sankeyDiagram.rast.json")
    val scala = balticporter.corpus.mermaid.MermaidDiagramEmitter.emitDiagram(
      rast, "SankeyDiagram", "sankey", "SankeyDb",
      detectorClass = Some("SankeyDetector"),
    )
    assert(scala.contains("object SankeyDiagram"), "should emit SankeyDiagram object")

  test("packetDiagram.ts -> PacketDiagram from RAST"):
    val rast = loadRast("/rast/mermaid/src/diagrams/packet/diagram.rast.json")
    val scala = balticporter.corpus.mermaid.MermaidDiagramEmitter.emitDiagram(
      rast, "PacketDiagram", "packet", "PacketDb",
      detectorClass = Some("PacketDetector"),
    )
    assert(scala.contains("object PacketDiagram"), "should emit PacketDiagram object")

  // B2 diagrams

  test("mindmapDiagram.ts -> MindmapDiagram from RAST"):
    val rast = loadRast("/rast/mermaid/src/diagrams/mindmap/mindmap-definition.rast.json")
    val scala = balticporter.corpus.mermaid.MermaidDiagramEmitter.emitDiagram(
      rast, "MindmapDiagram", "mindmap", "MindmapDb",
      detectorClass = Some("MindmapDetector"),
    )
    assert(scala.contains("object MindmapDiagram"), "should emit MindmapDiagram object")

  test("quadrantDiagram.ts -> QuadrantDiagram from RAST"):
    val rast = loadRast("/rast/mermaid/src/diagrams/quadrant-chart/quadrantDiagram.rast.json")
    val scala = balticporter.corpus.mermaid.MermaidDiagramEmitter.emitDiagram(
      rast, "QuadrantDiagram", "quadrant", "QuadrantDb",
      detectorClass = Some("QuadrantDetector"),
    )
    assert(scala.contains("object QuadrantDiagram"), "should emit QuadrantDiagram object")

  test("blockDiagram.ts -> BlockDiagram from RAST"):
    val rast = loadRast("/rast/mermaid/src/diagrams/block/blockDiagram.rast.json")
    val scala = balticporter.corpus.mermaid.MermaidDiagramEmitter.emitDiagram(
      rast, "BlockDiagram", "block", "BlockDb",
      detectorClass = Some("BlockDetector"),
    )
    assert(scala.contains("object BlockDiagram"), "should emit BlockDiagram object")

  test("xychartDiagram.ts -> XyChartDiagram from RAST"):
    val rast = loadRast("/rast/mermaid/src/diagrams/xychart/xychartDiagram.rast.json")
    val scala = balticporter.corpus.mermaid.MermaidDiagramEmitter.emitDiagram(
      rast, "XyChartDiagram", "xychart", "XyChartDb",
      detectorClass = Some("XyChartDetector"),
    )
    assert(scala.contains("object XyChartDiagram"), "should emit XyChartDiagram object")

  // B5: JS-based diagrams

  test("erDiagram.ts -> ErDiagram from RAST"):
    val rast = loadRast("/rast/mermaid/src/diagrams/er/erDiagram.rast.json")
    val scala = balticporter.corpus.mermaid.MermaidDiagramEmitter.emitDiagram(
      rast, "ErDiagram", "er", "ErDb",
      detectorClass = Some("ErDetector"),
    )
    assert(scala.contains("object ErDiagram"), "should emit ErDiagram object")

  test("c4Diagram.ts -> C4Diagram from RAST"):
    val rast = loadRast("/rast/mermaid/src/diagrams/c4/c4Diagram.rast.json")
    val scala = balticporter.corpus.mermaid.MermaidDiagramEmitter.emitDiagram(
      rast, "C4Diagram", "c4", "C4Db",
      detectorClass = Some("C4Detector"),
    )
    assert(scala.contains("object C4Diagram"), "should emit C4Diagram object")

  test("stateDiagram.ts -> StateDiagram from RAST"):
    val rast = loadRast("/rast/mermaid/src/diagrams/state/stateDiagram.rast.json")
    val scala = balticporter.corpus.mermaid.MermaidDiagramEmitter.emitDiagram(
      rast, "StateDiagram", "state", "StateDb",
      detectorClass = Some("StateDetector"),
    )
    assert(scala.contains("object StateDiagram"), "should emit StateDiagram object")

  test("journeyDiagram.ts -> JourneyDiagram from RAST"):
    val rast = loadRast("/rast/mermaid/src/diagrams/user-journey/journeyDiagram.rast.json")
    val scala = balticporter.corpus.mermaid.MermaidDiagramEmitter.emitDiagram(
      rast, "JourneyDiagram", "journey", "JourneyDb",
      detectorClass = Some("JourneyDetector"),
    )
    assert(scala.contains("object JourneyDiagram"), "should emit JourneyDiagram object")

  test("timelineDiagram.ts -> TimelineDiagram from RAST"):
    val rast = loadRast("/rast/mermaid/src/diagrams/timeline/timeline-definition.rast.json")
    val scala = balticporter.corpus.mermaid.MermaidDiagramEmitter.emitDiagram(
      rast, "TimelineDiagram", "timeline", "TimelineDb",
      detectorClass = Some("TimelineDetector"),
    )
    assert(scala.contains("object TimelineDiagram"), "should emit TimelineDiagram object")

  test("requirementDiagram.ts -> RequirementDiagram from RAST"):
    val rast = loadRast("/rast/mermaid/src/diagrams/requirement/requirementDiagram.rast.json")
    val scala = balticporter.corpus.mermaid.MermaidDiagramEmitter.emitDiagram(
      rast, "RequirementDiagram", "requirement", "RequirementDb",
      detectorClass = Some("RequirementDetector"),
    )
    assert(scala.contains("object RequirementDiagram"), "should emit RequirementDiagram object")

  test("gitGraphDiagram.ts -> GitDiagram from RAST"):
    val rast = loadRast("/rast/mermaid/src/diagrams/git/gitGraphDiagram.rast.json")
    val scala = balticporter.corpus.mermaid.MermaidDiagramEmitter.emitDiagram(
      rast, "GitDiagram", "git", "GitDb",
      detectorClass = Some("GitDetector"),
    )
    assert(scala.contains("object GitDiagram"), "should emit GitDiagram object")

  // -- Write all to target/emitted-mermaid ----------------------------------

  test("write RAST-based Diagram files to target/emitted-mermaid"):
    val outDir = java.nio.file.Path.of(sys.props.getOrElse("user.dir", ".")).resolve("target/emitted-mermaid")
    java.nio.file.Files.createDirectories(outDir)

    val files = List(
      ("/rast/mermaid/src/diagrams/info/infoDiagram.rast.json", "InfoDiagram", "info", "InfoDb"),
      ("/rast/mermaid/src/diagrams/pie/pieDiagram.rast.json", "PieDiagram", "pie", "PieDb"),
      ("/rast/mermaid/src/diagrams/sankey/sankeyDiagram.rast.json", "SankeyDiagram", "sankey", "SankeyDb"),
      ("/rast/mermaid/src/diagrams/packet/diagram.rast.json", "PacketDiagram", "packet", "PacketDb"),
      ("/rast/mermaid/src/diagrams/block/blockDiagram.rast.json", "BlockDiagram", "block", "BlockDb"),
      ("/rast/mermaid/src/diagrams/xychart/xychartDiagram.rast.json", "XyChartDiagram", "xychart", "XyChartDb"),
      ("/rast/mermaid/src/diagrams/er/erDiagram.rast.json", "ErDiagram", "er", "ErDb"),
      ("/rast/mermaid/src/diagrams/c4/c4Diagram.rast.json", "C4Diagram", "c4", "C4Db"),
      ("/rast/mermaid/src/diagrams/state/stateDiagram.rast.json", "StateDiagram", "state", "StateDb"),
      ("/rast/mermaid/src/diagrams/user-journey/journeyDiagram.rast.json", "JourneyDiagram", "journey", "JourneyDb"),
      ("/rast/mermaid/src/diagrams/timeline/timeline-definition.rast.json", "TimelineDiagram", "timeline", "TimelineDb"),
      ("/rast/mermaid/src/diagrams/requirement/requirementDiagram.rast.json", "RequirementDiagram", "requirement", "RequirementDb"),
      ("/rast/mermaid/src/diagrams/git/gitGraphDiagram.rast.json", "GitDiagram", "git", "GitDb"),
    )

    for ((rastPath, className, pkg, dbClass) <- files) {
      val rast = loadRast(rastPath)
      val scala = balticporter.corpus.mermaid.MermaidDiagramEmitter.emitDiagram(
        rast, className, pkg, dbClass,
        detectorClass = Some(className.replace("Diagram", "Detector")),
      )
      val path = outDir.resolve(s"${className}_rast.scala")
      java.nio.file.Files.writeString(path, scala)
      println(s"[emit-rast] ${className}.scala: ${scala.linesIterator.size} lines -> $path")
    }
