package balticporter.frontend.ts

class MermaidDbEmitterSpec extends munit.FunSuite:

  private def loadRast(resource: String): RastFile =
    val stream = getClass.getResourceAsStream(resource)
    assert(stream != null, s"Resource not found: $resource")
    val json = new String(stream.readAllBytes(), java.nio.charset.StandardCharsets.UTF_8)
    stream.close()
    Rast.readFile(json)

  // -- InfoDb (simplest: 11 LOC TS, no mutable state except version) ----------

  test("infoDb.ts -> InfoDb class from RAST"):
    val rast = loadRast("/rast/mermaid/src/diagrams/info/infoDb.rast.json")
    val scala = dedicated.MermaidDbEmitter.emitDb(rast, "InfoDb", "info")
    println("=== InfoDb.scala (RAST-based) ===")
    println(scala)
    assert(scala.contains("final class InfoDb"), "should emit InfoDb class")
    assert(scala.contains("def clear()"), "should have clear method")
    assert(scala.contains("Auto-generated by MermaidDbEmitter from RAST v1"), "should have RAST header")
    assert(scala.contains("package info"), "should have correct package")

  // -- PacketDb (56 LOC TS, mutable data, pushWord, getPacket) ---------------

  test("packet/db.ts -> PacketDb class from RAST"):
    val rast = loadRast("/rast/mermaid/src/diagrams/packet/db.rast.json")
    val scala = dedicated.MermaidDbEmitter.emitDb(rast, "PacketDb", "packet")
    println("=== PacketDb.scala (RAST-based) ===")
    println(scala)
    assert(scala.contains("final class PacketDb"), "should emit PacketDb class")
    assert(scala.contains("def clear()"), "should have clear method")
    assert(scala.contains("pushWord") || scala.contains("def pushWord"), "should have pushWord method")
    assert(scala.contains("getPacket") || scala.contains("def getPacket"), "should have getPacket method")
    assert(scala.contains("Auto-generated by MermaidDbEmitter from RAST v1"), "should have RAST header")

  // -- PieDb (67 LOC TS, Map sections, addSection, showData) -----------------

  test("pieDb.ts -> PieDb class from RAST"):
    val rast = loadRast("/rast/mermaid/src/diagrams/pie/pieDb.rast.json")
    val scala = dedicated.MermaidDbEmitter.emitDb(rast, "PieDb", "pie")
    println("=== PieDb.scala (RAST-based) ===")
    println(scala)
    assert(scala.contains("final class PieDb"), "should emit PieDb class")
    assert(scala.contains("def clear()"), "should have clear method")
    assert(scala.contains("sections"), "should have sections field")
    assert(scala.contains("showData"), "should have showData field")

  // -- SankeyDb (88 LOC TS, classes, addLink, findOrCreateNode) --------------

  test("sankeyDB.ts -> SankeyDb class from RAST"):
    val rast = loadRast("/rast/mermaid/src/diagrams/sankey/sankeyDB.rast.json")
    val scala = dedicated.MermaidDbEmitter.emitDb(rast, "SankeyDb", "sankey")
    println("=== SankeyDb.scala (RAST-based) ===")
    println(scala)
    assert(scala.contains("final class SankeyDb"), "should emit SankeyDb class")
    assert(scala.contains("def clear()"), "should have clear method")
    assert(scala.contains("links") || scala.contains("var links"), "should have links field")
    assert(scala.contains("nodes") || scala.contains("var nodes"), "should have nodes field")
    // Should have inner classes for SankeyLink and SankeyNode
    assert(scala.contains("SankeyLink") || scala.contains("case class"), "should have inner class")

  // -- MindmapDb (159 LOC TS, complex: switch, functions, object) ------------

  test("mindmapDb.ts -> MindmapDb class from RAST"):
    val rast = loadRast("/rast/mermaid/src/diagrams/mindmap/mindmapDb.rast.json")
    val scala = dedicated.MermaidDbEmitter.emitDb(rast, "MindmapDb", "mindmap")
    assert(scala.contains("final class MindmapDb"), "should emit MindmapDb class")
    assert(scala.contains("def clear()"), "should have clear method")
    assert(scala.contains("nodes") || scala.contains("var nodes"), "should have nodes field")
    // B2: switch should be emitted as match, not TODO
    assert(!scala.contains("// TODO: switch"), "switch should be emitted as match")
    assert(scala.contains("match {"), "should emit match expression")
    // Reserved keyword `type` should be escaped
    assert(scala.contains("`type`"), "reserved keyword type should be backtick-escaped")

  // -- B2: QuadrantDb (complex with setters and axis labels) ----------------

  test("quadrantDb.ts -> QuadrantDb class from RAST"):
    val rast = loadRast("/rast/mermaid/src/diagrams/quadrant-chart/quadrantDb.rast.json")
    val scala = dedicated.MermaidDbEmitter.emitDb(rast, "QuadrantDb", "quadrant")
    assert(scala.contains("final class QuadrantDb"), "should emit QuadrantDb class")
    assert(scala.contains("def clear()"), "should have clear method")

  // -- B2: BlockDb (complex with arrays, for loops) -------------------------

  test("blockDB.ts -> BlockDb class from RAST"):
    val rast = loadRast("/rast/mermaid/src/diagrams/block/blockDB.rast.json")
    val scala = dedicated.MermaidDbEmitter.emitDb(rast, "BlockDb", "block")
    assert(scala.contains("final class BlockDb"), "should emit BlockDb class")
    assert(scala.contains("def clear()"), "should have clear method")
    // for-of should not be TODO anymore
    assert(!scala.contains("// TODO: ForOfStatement"), "for-of should be emitted")

  // -- B2: XyChartDb (axis labels, data series) ----------------------------

  test("xychartDb.ts -> XyChartDb class from RAST"):
    val rast = loadRast("/rast/mermaid/src/diagrams/xychart/xychartDb.rast.json")
    val scala = dedicated.MermaidDbEmitter.emitDb(rast, "XyChartDb", "xychart")
    assert(scala.contains("final class XyChartDb"), "should emit XyChartDb class")
    assert(scala.contains("def clear()"), "should have clear method")

  // -- B5: JS-based Dbs ---------------------------------------------------

  test("erDb.js -> ErDb class from RAST (JS source)"):
    val rast = loadRast("/rast/mermaid/src/diagrams/er/erDb.rast.json")
    val scala = dedicated.MermaidDbEmitter.emitDb(rast, "ErDb", "er")
    assert(scala.contains("final class ErDb"), "should emit ErDb class")
    assert(scala.contains("def clear()"), "should have clear method")

  test("c4Db.ts -> C4Db class from RAST"):
    val rast = loadRast("/rast/mermaid/src/diagrams/c4/c4Db.rast.json")
    val scala = dedicated.MermaidDbEmitter.emitDb(rast, "C4Db", "c4")
    assert(scala.contains("final class C4Db"), "should emit C4Db class")
    assert(scala.contains("def clear()"), "should have clear method")

  test("stateDb.ts -> StateDb class from RAST"):
    val rast = loadRast("/rast/mermaid/src/diagrams/state/stateDb.rast.json")
    val scala = dedicated.MermaidDbEmitter.emitDb(rast, "StateDb", "state")
    assert(scala.contains("final class StateDb"), "should emit StateDb class")
    assert(scala.contains("def clear()"), "should have clear method")

  test("journeyDb.ts -> JourneyDb class from RAST"):
    val rast = loadRast("/rast/mermaid/src/diagrams/user-journey/journeyDb.rast.json")
    val scala = dedicated.MermaidDbEmitter.emitDb(rast, "JourneyDb", "journey")
    assert(scala.contains("final class JourneyDb"), "should emit JourneyDb class")
    assert(scala.contains("def clear()"), "should have clear method")

  test("timelineDb.ts -> TimelineDb class from RAST"):
    val rast = loadRast("/rast/mermaid/src/diagrams/timeline/timelineDb.rast.json")
    val scala = dedicated.MermaidDbEmitter.emitDb(rast, "TimelineDb", "timeline")
    assert(scala.contains("final class TimelineDb"), "should emit TimelineDb class")
    assert(scala.contains("def clear()"), "should have clear method")

  test("requirementDb.ts -> RequirementDb class from RAST"):
    val rast = loadRast("/rast/mermaid/src/diagrams/requirement/requirementDb.rast.json")
    val scala = dedicated.MermaidDbEmitter.emitDb(rast, "RequirementDb", "requirement")
    assert(scala.contains("final class RequirementDb"), "should emit RequirementDb class")
    assert(scala.contains("def clear()"), "should have clear method")

  test("gitGraphAst.js -> GitDb class from RAST (JS source)"):
    val rast = loadRast("/rast/mermaid/src/diagrams/git/gitGraphAst.rast.json")
    val scala = dedicated.MermaidDbEmitter.emitDb(rast, "GitDb", "git")
    assert(scala.contains("final class GitDb"), "should emit GitDb class")
    assert(scala.contains("def clear()"), "should have clear method")

  // -- Write all emitted files to target/emitted-mermaid for inspection ------

  test("write RAST-based Db files to target/emitted-mermaid"):
    val outDir = java.nio.file.Path.of(sys.props.getOrElse("user.dir", ".")).resolve("target/emitted-mermaid")
    java.nio.file.Files.createDirectories(outDir)

    val files = List(
      // B1: T0 Dbs
      ("/rast/mermaid/src/diagrams/info/infoDb.rast.json", "InfoDb", "info"),
      ("/rast/mermaid/src/diagrams/packet/db.rast.json", "PacketDb", "packet"),
      ("/rast/mermaid/src/diagrams/pie/pieDb.rast.json", "PieDb", "pie"),
      ("/rast/mermaid/src/diagrams/sankey/sankeyDB.rast.json", "SankeyDb", "sankey"),
      // B2: T1 Dbs
      ("/rast/mermaid/src/diagrams/mindmap/mindmapDb.rast.json", "MindmapDb", "mindmap"),
      ("/rast/mermaid/src/diagrams/quadrant-chart/quadrantDb.rast.json", "QuadrantDb", "quadrant"),
      ("/rast/mermaid/src/diagrams/block/blockDB.rast.json", "BlockDb", "block"),
      ("/rast/mermaid/src/diagrams/xychart/xychartDb.rast.json", "XyChartDb", "xychart"),
      // B5: JS-based Dbs
      ("/rast/mermaid/src/diagrams/er/erDb.rast.json", "ErDb", "er"),
      ("/rast/mermaid/src/diagrams/c4/c4Db.rast.json", "C4Db", "c4"),
      ("/rast/mermaid/src/diagrams/state/stateDb.rast.json", "StateDb", "state"),
      ("/rast/mermaid/src/diagrams/user-journey/journeyDb.rast.json", "JourneyDb", "journey"),
      ("/rast/mermaid/src/diagrams/timeline/timelineDb.rast.json", "TimelineDb", "timeline"),
      ("/rast/mermaid/src/diagrams/requirement/requirementDb.rast.json", "RequirementDb", "requirement"),
      ("/rast/mermaid/src/diagrams/git/gitGraphAst.rast.json", "GitDb", "git"),
    )

    for ((rastPath, className, pkg) <- files) {
      val rast = loadRast(rastPath)
      val scala = dedicated.MermaidDbEmitter.emitDb(rast, className, pkg)
      val path = outDir.resolve(s"${className}_rast.scala")
      java.nio.file.Files.writeString(path, scala)
      println(s"[emit-rast] ${className}.scala: ${scala.linesIterator.size} lines -> $path")
    }
