package balticporter.frontend.ts

class MermaidTypeEmitterSpec extends munit.FunSuite:

  private def loadRast(resource: String): RastFile =
    val stream = getClass.getResourceAsStream(resource)
    assert(stream != null, s"Resource not found: $resource")
    val json = new String(stream.readAllBytes(), java.nio.charset.StandardCharsets.UTF_8)
    stream.close()
    Rast.readFile(json)

  // -- B3: Type emitter tests -----------------------------------------------

  test("pieTypes.ts -> case classes from RAST"):
    val rast = loadRast("/rast/mermaid/src/diagrams/pie/pieTypes.rast.json")
    val scala = balticporter.corpus.mermaid.MermaidTypeEmitter.emitTypes(rast, "", "pie")
    assert(scala.contains("package pie"), "should have correct package")
    // PieFields interface -> case class
    assert(scala.contains("case class PieFields") || scala.contains("PieFields"), "should emit PieFields")
    // PieStyleOptions interface -> case class
    assert(scala.contains("case class PieStyleOptions") || scala.contains("PieStyleOptions"),
      "should emit PieStyleOptions")
    // D3Section interface -> case class
    assert(scala.contains("case class D3Section") || scala.contains("D3Section"),
      "should emit D3Section")
    // Sections type alias
    assert(scala.contains("type Sections"), "should emit Sections type alias")
    // PieDB should be skipped (it's a method-only DB interface)
    assert(scala.contains("PieDB") && scala.contains("method declarations"),
      "should skip PieDB interface (all functions)")
    assert(scala.contains("Auto-generated by MermaidTypeEmitter"), "should have header")

  test("infoTypes.ts -> case classes from RAST"):
    val rast = loadRast("/rast/mermaid/src/diagrams/info/infoTypes.rast.json")
    val scala = balticporter.corpus.mermaid.MermaidTypeEmitter.emitTypes(rast, "", "info")
    assert(scala.contains("package info"), "should have correct package")

  test("blockTypes.ts -> case classes from RAST"):
    val rast = loadRast("/rast/mermaid/src/diagrams/block/blockTypes.rast.json")
    val scala = balticporter.corpus.mermaid.MermaidTypeEmitter.emitTypes(rast, "", "block")
    assert(scala.contains("package block"), "should have correct package")

  test("mindmapTypes.ts -> case classes from RAST"):
    val rast = loadRast("/rast/mermaid/src/diagrams/mindmap/mindmapTypes.rast.json")
    val scala = balticporter.corpus.mermaid.MermaidTypeEmitter.emitTypes(rast, "", "mindmap")
    assert(scala.contains("package mindmap"), "should have correct package")

  test("classTypes.ts -> case classes from RAST"):
    val rast = loadRast("/rast/mermaid/src/diagrams/class/classTypes.rast.json")
    val scala = balticporter.corpus.mermaid.MermaidTypeEmitter.emitTypes(rast, "", "class_")
    assert(scala.contains("package class_"), "should have correct package")

  test("commonTypes.ts -> case classes from RAST"):
    val rast = loadRast("/rast/mermaid/src/diagrams/common/commonTypes.rast.json")
    val scala = balticporter.corpus.mermaid.MermaidTypeEmitter.emitTypes(rast, "", "common")
    assert(scala.contains("package common"), "should have correct package")

  test("config.type.ts -> config types from RAST"):
    val rast = loadRast("/rast/mermaid/src/config.type.rast.json")
    val scala = balticporter.corpus.mermaid.MermaidTypeEmitter.emitTypes(rast, "", "")
    assert(scala.contains("package mermaid"), "should be in mermaid package")

  test("packet types.ts -> case classes from RAST"):
    val rast = loadRast("/rast/mermaid/src/diagrams/packet/types.rast.json")
    val scala = balticporter.corpus.mermaid.MermaidTypeEmitter.emitTypes(rast, "", "packet")
    assert(scala.contains("package packet"), "should have correct package")

  // -- Write all to target/emitted-mermaid ----------------------------------

  test("write RAST-based type files to target/emitted-mermaid"):
    val outDir = java.nio.file.Path.of(sys.props.getOrElse("user.dir", ".")).resolve("target/emitted-mermaid")
    java.nio.file.Files.createDirectories(outDir)

    val files = List(
      ("/rast/mermaid/src/diagrams/pie/pieTypes.rast.json", "PieTypes", "pie"),
      ("/rast/mermaid/src/diagrams/info/infoTypes.rast.json", "InfoTypes", "info"),
      ("/rast/mermaid/src/diagrams/block/blockTypes.rast.json", "BlockTypes", "block"),
      ("/rast/mermaid/src/diagrams/mindmap/mindmapTypes.rast.json", "MindmapTypes", "mindmap"),
      ("/rast/mermaid/src/diagrams/class/classTypes.rast.json", "ClassTypes", "class_"),
      ("/rast/mermaid/src/diagrams/common/commonTypes.rast.json", "CommonTypes", "common"),
      ("/rast/mermaid/src/config.type.rast.json", "ConfigTypes", ""),
      ("/rast/mermaid/src/diagrams/packet/types.rast.json", "PacketTypes", "packet"),
    )

    for ((rastPath, className, pkg) <- files) {
      val rast = loadRast(rastPath)
      val scala = balticporter.corpus.mermaid.MermaidTypeEmitter.emitTypes(rast, "", pkg)
      val path = outDir.resolve(s"${className}_rast.scala")
      java.nio.file.Files.writeString(path, scala)
      println(s"[emit-rast] ${className}.scala: ${scala.linesIterator.size} lines -> $path")
    }
