package com.badlogic.gdx.math

class BSplineTest extends munit.FunSuite {
  test("testCubicSplineNonContinuous")({
    val controlPoints: scala.Array[com.badlogic.gdx.math.Vector3] = scala.Array[com.badlogic.gdx.math.Vector3](new com.badlogic.gdx.math.Vector3(0, 0, 0), new com.badlogic.gdx.math.Vector3(1, 1, 0), new com.badlogic.gdx.math.Vector3(2, 0, 0), new com.badlogic.gdx.math.Vector3(3, -1, 0))
    val spline: com.badlogic.gdx.math.BSpline[com.badlogic.gdx.math.Vector3] = new com.badlogic.gdx.math.BSpline[com.badlogic.gdx.math.Vector3](controlPoints, 3, false)
    val result: com.badlogic.gdx.math.Vector3 = new com.badlogic.gdx.math.Vector3()
    spline.valueAt(result, 0.5f)
    val expected: com.badlogic.gdx.math.Vector3 = new com.badlogic.gdx.math.Vector3(1.5f, 0.5f, 0)
    assertEquals(0.1f, result.x, expected.x)
    assertEquals(0.1f, result.y, expected.y)
    assertEquals(0.1f, result.z, expected.z)
  })
  test("testCubicSplineContinuous")({
    val controlPoints: scala.Array[com.badlogic.gdx.math.Vector3] = scala.Array[com.badlogic.gdx.math.Vector3](new com.badlogic.gdx.math.Vector3(1, 0, 0), new com.badlogic.gdx.math.Vector3(0, 1, 0), new com.badlogic.gdx.math.Vector3(-1, 0, 0), new com.badlogic.gdx.math.Vector3(0, -1, 0))
    val spline: com.badlogic.gdx.math.BSpline[com.badlogic.gdx.math.Vector3] = new com.badlogic.gdx.math.BSpline[com.badlogic.gdx.math.Vector3](controlPoints, 3, true)
    val result: com.badlogic.gdx.math.Vector3 = new com.badlogic.gdx.math.Vector3()
    spline.valueAt(result, 0.875f)
    val expected: com.badlogic.gdx.math.Vector3 = new com.badlogic.gdx.math.Vector3(0.45f, -0.45f, 0)
    assertEquals(0.1f, result.x, expected.x)
    assertEquals(0.1f, result.y, expected.y)
    assertEquals(0.1f, result.z, expected.z)
  })
  test("testCubicDerivative")({
    val controlPoints: scala.Array[com.badlogic.gdx.math.Vector3] = scala.Array[com.badlogic.gdx.math.Vector3](new com.badlogic.gdx.math.Vector3(0, 0, 0), new com.badlogic.gdx.math.Vector3(1, 1, 0), new com.badlogic.gdx.math.Vector3(2, 0, 0), new com.badlogic.gdx.math.Vector3(3, -1, 0))
    val spline: com.badlogic.gdx.math.BSpline[com.badlogic.gdx.math.Vector3] = new com.badlogic.gdx.math.BSpline[com.badlogic.gdx.math.Vector3](controlPoints, 3, true)
    val derivative: com.badlogic.gdx.math.Vector3 = new com.badlogic.gdx.math.Vector3()
    spline.derivativeAt(derivative, 0.5f)
    val expectedDerivative: com.badlogic.gdx.math.Vector3 = new com.badlogic.gdx.math.Vector3(1, -1, 0)
    assertEquals(0.001f, derivative.x, expectedDerivative.x)
    assertEquals(0.001f, derivative.y, expectedDerivative.y)
    assertEquals(0.001f, derivative.z, expectedDerivative.z)
  })
  test("testContinuousApproximation")({
    val controlPoints: scala.Array[com.badlogic.gdx.math.Vector3] = scala.Array[com.badlogic.gdx.math.Vector3](new com.badlogic.gdx.math.Vector3(1, 0, 0), new com.badlogic.gdx.math.Vector3(0, 1, 0), new com.badlogic.gdx.math.Vector3(-1, 0, 0), new com.badlogic.gdx.math.Vector3(0, -1, 0))
    val spline: com.badlogic.gdx.math.BSpline[com.badlogic.gdx.math.Vector3] = new com.badlogic.gdx.math.BSpline[com.badlogic.gdx.math.Vector3](controlPoints, 3, true)
    val point: com.badlogic.gdx.math.Vector3 = new com.badlogic.gdx.math.Vector3(0.45f, -0.45f, 0.0f)
    val t: scala.Float = spline.approximate(point)
    assertEquals(0.1f, t, 0.875f)
  })
  test("testNonContinuousApproximation")({
    val controlPoints: scala.Array[com.badlogic.gdx.math.Vector3] = scala.Array[com.badlogic.gdx.math.Vector3](new com.badlogic.gdx.math.Vector3(1, 0, 0), new com.badlogic.gdx.math.Vector3(0, 1, 0), new com.badlogic.gdx.math.Vector3(-1, 0, 0), new com.badlogic.gdx.math.Vector3(0, -1, 0))
    val spline: com.badlogic.gdx.math.BSpline[com.badlogic.gdx.math.Vector3] = new com.badlogic.gdx.math.BSpline[com.badlogic.gdx.math.Vector3](controlPoints, 3, false)
    var point: com.badlogic.gdx.math.Vector3 = null.asInstanceOf[com.badlogic.gdx.math.Vector3]
    var t: scala.Float = 0.0f
    point = new com.badlogic.gdx.math.Vector3(0.0f, 0.666f, 0.0f)
    t = spline.approximate(point)
    assertEquals(0.1f, t, 0.0f)
    point = new com.badlogic.gdx.math.Vector3(-0.666f, 0.0f, 0.0f)
    t = spline.approximate(point)
    assertEquals(0.1f, t, 1.0f)
    point = new com.badlogic.gdx.math.Vector3(-0.45f, 0.45f, 0.0f)
    t = spline.approximate(point)
    assertEquals(0.1f, t, 0.5f)
  })
  test("testSplineContinuity")({
    val controlPoints: scala.Array[com.badlogic.gdx.math.Vector3] = scala.Array[com.badlogic.gdx.math.Vector3](new com.badlogic.gdx.math.Vector3(0, 0, 0), new com.badlogic.gdx.math.Vector3(1, 1, 0), new com.badlogic.gdx.math.Vector3(2, 0, 0), new com.badlogic.gdx.math.Vector3(3, -1, 0))
    val spline: com.badlogic.gdx.math.BSpline[com.badlogic.gdx.math.Vector3] = new com.badlogic.gdx.math.BSpline[com.badlogic.gdx.math.Vector3](controlPoints, 3, true)
    val start: com.badlogic.gdx.math.Vector3 = new com.badlogic.gdx.math.Vector3()
    val `end`: com.badlogic.gdx.math.Vector3 = new com.badlogic.gdx.math.Vector3()
    spline.valueAt(start, 0.0f)
    spline.valueAt(`end`, 1.0f)
    assertEquals(0.001f, `end`.x, start.x)
    assertEquals(0.001f, `end`.y, start.y)
    assertEquals(0.001f, `end`.z, start.z)
  })
  test("testEdgeCases")({
    val controlPoints: scala.Array[com.badlogic.gdx.math.Vector3] = scala.Array[com.badlogic.gdx.math.Vector3](new com.badlogic.gdx.math.Vector3(0, 0, 0), new com.badlogic.gdx.math.Vector3(1, 1, 0), new com.badlogic.gdx.math.Vector3(2, 0, 0), new com.badlogic.gdx.math.Vector3(3, -1, 0))
    val spline: com.badlogic.gdx.math.BSpline[com.badlogic.gdx.math.Vector3] = new com.badlogic.gdx.math.BSpline[com.badlogic.gdx.math.Vector3](controlPoints, 3, false)
    val start: com.badlogic.gdx.math.Vector3 = new com.badlogic.gdx.math.Vector3()
    val expectedStart: com.badlogic.gdx.math.Vector3 = new com.badlogic.gdx.math.Vector3(1.0f, 0.666f, 0.0f)
    val `end`: com.badlogic.gdx.math.Vector3 = new com.badlogic.gdx.math.Vector3()
    val expectedEnd: com.badlogic.gdx.math.Vector3 = new com.badlogic.gdx.math.Vector3(2.0f, 0.0f, 0.0f)
    spline.valueAt(start, 0.0f)
    assertEquals(0.001f, start.x, expectedStart.x)
    assertEquals(0.001f, start.y, expectedStart.y)
    assertEquals(0.001f, start.z, expectedStart.z)
    spline.valueAt(`end`, 1.0f)
    assertEquals(0.001f, `end`.x, expectedEnd.x)
    assertEquals(0.001f, `end`.y, expectedEnd.y)
    assertEquals(0.001f, `end`.z, expectedEnd.z)
  })
}