package balticporter.core

import java.nio.file.Path

/** Provenance stamped into every generated file's header. */
final case class Provenance(
    upstreamName: String,
    upstreamCommit: String,
    originalLicense: String,
    /** path prefix shown in headers before the unit's sourcePath, e.g. "liqp/src/main/java". */
    sourcePathPrefix: String,
)

/** M0 subset of the PortPlan from PLAN.md §3.1: one module, explicit file list. */
final case class UnitPlan(
    sourceRoot: Path,
    files: List[String],
    classpath: List[Path],
    outDir: Path,
    provenance: Provenance,
    /** source roots participating in resolution but not converted (see FrontendConfig). */
    resolutionRoots: List[Path] = Nil,
)

/** The engine's own coordinates, taken from the BUILD rather than restated here.
  *
  * `BuildVersion` is generated by build.sbt from `ThisBuild / version`, so the version stamped
  * into a generated project's header is the version of the artifact that produced it, and the
  * `balticporter-runtime` a port resolves is the one this engine was built with
  * ([[RuntimeArtifact.version]] reads the same field). A hand-maintained literal here was already
  * a lie: it said `0.1.0-M0` while the build published `0.1.0-SNAPSHOT`.
  */
object EngineInfo:
  val organization: String = BuildVersion.organization
  val version: String      = BuildVersion.version
  /** Bumped whenever any pass/printer behavior changes; part of the header + cache key. */
  val fingerprint = s"balticporter/$version"

/** The engine version a generated project was produced by, recorded IN that project.
  *
  * A port must be able to pin a known-good engine: emitted Scala is a build product (CLAUDE.md
  * §5.5), so "which engine wrote this" is not recoverable from the output, and a port regenerated
  * by a newer engine that changed an emitted construct is a silent behavioural change. The pin is
  * a plain, ordered, timestamp-free properties file — byte-deterministic like everything else
  * `SbtGen` writes — committed alongside `src/`, and checked by [[check]].
  *
  * It is a DECLARATION, not a lock file: nothing here downloads or switches engines. What it buys
  * is that an agent regenerating a port in another repository is told, by a check rather than by
  * a diff, that the engine changed under it.
  */
final case class EnginePin(
    engineVersion: String,
    engineFingerprint: String,
    runtimeArtifact: String,
    runtimeVersion: String,
    runtimeMode: String,
):
  def render: String =
    s"""# Generated by Baltic Porter — DO NOT EDIT; regenerate instead.
       |# The engine version this project was produced by. `EnginePin.check` compares it against
       |# the engine now on the classpath; a mismatch means the emitted sources are stale.
       |engine.organization=${EngineInfo.organization}
       |engine.version=$engineVersion
       |engine.fingerprint=$engineFingerprint
       |runtime.artifact=$runtimeArtifact
       |runtime.version=$runtimeVersion
       |runtime.mode=$runtimeMode
       |""".stripMargin

object EnginePin:
  val fileName = "balticporter-engine.properties"

  /** the pin describing the engine RUNNING NOW, delivering `plan`. */
  def current(plan: RuntimePlan): EnginePin =
    EnginePin(
      engineVersion = EngineInfo.version,
      engineFingerprint = EngineInfo.fingerprint,
      runtimeArtifact = RuntimeArtifact.artifact,
      runtimeVersion = if plan.isEmpty then "" else RuntimeArtifact.version,
      runtimeMode = if plan.isEmpty then "none" else plan.mode.toString.toLowerCase,
    )

  def parse(text: String): Option[EnginePin] =
    val kv = text.linesIterator
      .map(_.trim)
      .filter(l => l.nonEmpty && !l.startsWith("#") && l.contains('='))
      .map { l => val i = l.indexOf('='); l.substring(0, i) -> l.substring(i + 1) }
      .toMap
    for v <- kv.get("engine.version"); f <- kv.get("engine.fingerprint")
    yield EnginePin(v, f, kv.getOrElse("runtime.artifact", ""), kv.getOrElse("runtime.version", ""),
      kv.getOrElse("runtime.mode", "none"))

  def write(root: Path, pin: EnginePin): Unit =
    java.nio.file.Files.writeString(root.resolve(fileName), pin.render)

  def read(root: Path): Option[EnginePin] =
    val p = root.resolve(fileName)
    if java.nio.file.Files.exists(p) then parse(java.nio.file.Files.readString(p)) else None

  /** Compare a port's declared engine against the one on the classpath.
    *
    * `Left` is a message an agent in another repository can act on without this session's context:
    * it names the two versions and the only two ways out. Absence of a pin is NOT an error — an
    * older port simply never declared one — but it is reported as such by [[read]] returning
    * `None`, which a caller can treat as it likes. */
  def check(root: Path): Either[String, Option[EnginePin]] =
    read(root) match
      case None => Right(None)
      case Some(pin) if pin.engineVersion == EngineInfo.version => Right(Some(pin))
      case Some(pin) =>
        Left(
          s"$fileName pins engine ${pin.engineVersion}, but ${EngineInfo.version} is on the classpath. " +
            s"Either depend on ${EngineInfo.organization}:balticporter-core:${pin.engineVersion} to " +
            s"regenerate byte-identical output, or regenerate with ${EngineInfo.version} and update the pin."
        )
