package balticporter.corpus

import balticporter.core.{FrontendConfig, Provenance}
import balticporter.emit.TirEmitter
import balticporter.frontend.spoon.SpoonTir
import balticporter.tir.{Origin, Pipeline, Program, Tree}
import balticporter.transform.PackageRenameTransform

import java.nio.file.{Files, Path}

/** The attribution header `TirEmitter` stamps on every emitted unit.
  *
  * Not cosmetics: the originals this project ports are licensed (Apache-2.0 for the libraries in
  * the corpus), a port is a derived work, and a derived work ships its notice. Nothing else in the
  * pipeline reports a missing one — the output compiles perfectly without it — so this spec is the
  * gate.
  */
class ProvenanceHeaderSpec extends munit.FunSuite:

  private val src =
    """package com.example.demo;
      |public class Widget {
      |  public int pad;
      |}
      |""".stripMargin

  /** Parse from a REAL file, so the unit's `Origin` carries the path a port would actually see.
    * `SpoonTir.fromSource` parses an in-memory `VirtualFile` and records no path at all — which is
    * the "origin unavailable" case, asserted separately below. */
  private val root: Path =
    val tmp = Files.createTempDirectory("bp-provenance").toRealPath()
    val dir = tmp.resolve("src/main/java/com/example/demo")
    Files.createDirectories(dir)
    Files.writeString(dir.resolve("Widget.java"), src)
    tmp.resolve("src/main/java")

  private val fromFile: Program =
    SpoonTir.fromTypes(SpoonTir.buildModel(FrontendConfig(root, List("com/example/demo/Widget.java"), Nil), lenient = true))

  private val prov = Provenance(
    upstreamName = "upstream-lib",
    upstreamCommit = "0123456789abcdef",
    originalLicense = "Apache-2.0",
    sourcePathPrefix = "src/main/java",
    sourceRoot = root.toString,
  )

  private def only(p: Program): Tree.ClassDef = p.units.head

  test("no Provenance emits no header — every existing call site keeps its exact output") {
    val out = new TirEmitter(fromFile).emitUnit(only(fromFile))
    assert(!out.contains("DO NOT EDIT"))
    assert(out.startsWith("package com.example.demo"))
  }

  test("a Provenance emits the do-not-edit banner and the full attribution block, before the package") {
    val out = new TirEmitter(fromFile, provenance = Some(prov)).emitUnit(only(fromFile))
    assert(clue(out).startsWith("/*"))
    assert(out.contains("DO NOT EDIT; regenerate instead."))
    assert(out.contains(s"Generated by Baltic Porter ${balticporter.core.EngineInfo.version}"))
    assert(clue(out).contains(" * Ported from: src/main/java/com/example/demo/Widget.java"))
    assert(out.contains(" * Original license: Apache-2.0 (see upstream-lib upstream)"))
    assert(out.contains(" * upstream-commit: 0123456789abcdef"))
    assert(out.indexOf("*/") < out.indexOf("package com.example.demo"))
  }

  test("the header names THIS unit's original Java file, taken from its Origin") {
    // reproducible: the machine-local temp root must not appear in the emitted bytes.
    val out = new TirEmitter(fromFile, provenance = Some(prov)).emitUnit(only(fromFile))
    assert(!clue(out).contains(root.toString), clue = "an absolute, machine-local path was emitted")
  }

  test("without sourceRoot the header still relativises at sourcePathPrefix when it is in the path") {
    val out = new TirEmitter(fromFile, provenance = Some(prov.copy(sourceRoot = ""))).emitUnit(only(fromFile))
    assert(clue(out).contains(" * Ported from: src/main/java/com/example/demo/Widget.java"))
  }

  test("an unrelativisable path is FLAGGED as recorded, never silently reshaped into a plausible one") {
    val out = new TirEmitter(fromFile, provenance = Some(prov.copy(sourceRoot = "", sourcePathPrefix = "nowhere")))
      .emitUnit(only(fromFile))
    assert(clue(out).contains("Widget.java  (path as recorded — set Provenance.sourceRoot to relativise it)"))
    // and it did NOT invent `nowhere/...`
    assert(!out.contains("Ported from: nowhere/"))
  }

  test("no recorded origin SAYS SO rather than inventing a path from the package name") {
    // A synthesized unit — one a phase built rather than the frontend parsed — carries
    // `Origin.synthetic`. There is no upstream file to attribute, and the header must say that
    // instead of reconstructing `com/example/demo/Widget.java`, which nobody ever read.
    val u    = only(fromFile)
    val bare = new Program(List(u.copy(origin = Origin.synthetic)), fromFile.symbols, fromFile.xref)
    val out  = new TirEmitter(bare, provenance = Some(prov)).emitUnit(only(bare))
    assert(clue(out).contains("Ported from: <unknown"))
    assert(!out.contains("Widget.java"))
  }

  test("an already-relative recorded path is emitted verbatim, with no misconfiguration hint") {
    // `SpoonTir.fromSource` parses an in-memory VirtualFile and records its virtual name. That is
    // reproducible as it stands, so it must not be flagged the way an absolute path is.
    val snippet = SpoonTir.fromSource(src)
    val out     = new TirEmitter(snippet, provenance = Some(prov)).emitUnit(only(snippet))
    assert(clue(out).contains(" * Ported from: Snippet.java\n"))
  }

  test("the header keeps naming the UPSTREAM file after the package has been renamed") {
    // attribution points at the original; the package clause points at where the port now lives.
    // Deriving the header path from the FQN instead of the Origin would silently rewrite the
    // attribution to a file that never existed.
    val renamed = Pipeline.run(fromFile, List(new PackageRenameTransform(Map("com.example" -> "sge.ui"))))
    val out     = new TirEmitter(renamed, provenance = Some(prov)).emitUnit(only(renamed))
    assert(clue(out).contains(" * Ported from: src/main/java/com/example/demo/Widget.java"))
    assert(out.contains("package sge.ui.demo"))
  }
