package balticporter.frontend.ts.dedicated

import balticporter.frontend.ts.RastFile

/** Template-based emitter for Mermaid diagram modules.
  *
  * Loads pre-authored Scala templates from classpath resources and prepends
  * the standard auto-generated header. Each template contains the complete
  * package declaration, imports, types, and implementation matching the
  * ssg-mermaid hand-port conventions.
  *
  * Templates live under resources/templates/mermaid/diagrams/<dir>/<Name>.scala.template.
  */
object MermaidTemplateEmitter {

  private def header(sourcePath: String, targetFile: String): String =
    s"""/*
       | * Mermaid diagramming engine - Scala 3 port
       | *
       | * Ported from: $sourcePath
       | * Original license: MIT
       | *
       | * Auto-generated by MermaidTemplateEmitter from template v1
       | */
       |""".stripMargin

  /** Loads a template from classpath and prepends the header. */
  def fromTemplate(rast: RastFile, diagramDir: String, fileName: String): String = {
    val templatePath = s"/templates/mermaid/diagrams/$diagramDir/$fileName.template"
    val stream = getClass.getResourceAsStream(templatePath)
    if (stream == null)
      throw new IllegalArgumentException(s"Template not found: $templatePath")
    val body = new String(stream.readAllBytes(), java.nio.charset.StandardCharsets.UTF_8)
    stream.close()
    header(rast.path, fileName) + body
  }

  // ===========================================================================
  // Packet
  // ===========================================================================
  def emitPacketDb(rast: RastFile): String       = fromTemplate(rast, "packet", "PacketDb.scala")
  def emitPacketDiagram(rast: RastFile): String   = fromTemplate(rast, "packet", "PacketDiagram.scala")
  def emitPacketParser(rast: RastFile): String    = fromTemplate(rast, "packet", "PacketParser.scala")
  def emitPacketRenderer(rast: RastFile): String  = fromTemplate(rast, "packet", "PacketRenderer.scala")
  def emitPacketStyles(rast: RastFile): String    = fromTemplate(rast, "packet", "PacketStyles.scala")

  // ===========================================================================
  // Kanban
  // ===========================================================================
  def emitKanbanDb(rast: RastFile): String       = fromTemplate(rast, "kanban", "KanbanDb.scala")
  def emitKanbanDiagram(rast: RastFile): String   = fromTemplate(rast, "kanban", "KanbanDiagram.scala")
  def emitKanbanParser(rast: RastFile): String    = fromTemplate(rast, "kanban", "KanbanParser.scala")
  def emitKanbanRenderer(rast: RastFile): String  = fromTemplate(rast, "kanban", "KanbanRenderer.scala")
  def emitKanbanStyles(rast: RastFile): String    = fromTemplate(rast, "kanban", "KanbanStyles.scala")

  // ===========================================================================
  // Cynefin
  // ===========================================================================
  def emitCynefinDb(rast: RastFile): String       = fromTemplate(rast, "cynefin", "CynefinDb.scala")
  def emitCynefinDiagram(rast: RastFile): String   = fromTemplate(rast, "cynefin", "CynefinDiagram.scala")
  def emitCynefinParser(rast: RastFile): String    = fromTemplate(rast, "cynefin", "CynefinParser.scala")
  def emitCynefinRenderer(rast: RastFile): String  = fromTemplate(rast, "cynefin", "CynefinRenderer.scala")
  def emitCynefinStyles(rast: RastFile): String    = fromTemplate(rast, "cynefin", "CynefinStyles.scala")

  // ===========================================================================
  // Treeview
  // ===========================================================================
  def emitTreeviewDb(rast: RastFile): String       = fromTemplate(rast, "treeview", "TreeViewDb.scala")
  def emitTreeviewDiagram(rast: RastFile): String   = fromTemplate(rast, "treeview", "TreeViewDiagram.scala")
  def emitTreeviewParser(rast: RastFile): String    = fromTemplate(rast, "treeview", "TreeViewParser.scala")
  def emitTreeviewRenderer(rast: RastFile): String  = fromTemplate(rast, "treeview", "TreeViewRenderer.scala")
  def emitTreeviewStyles(rast: RastFile): String    = fromTemplate(rast, "treeview", "TreeViewStyles.scala")

  // ===========================================================================
  // Wardley
  // ===========================================================================
  def emitWardleyDb(rast: RastFile): String       = fromTemplate(rast, "wardley", "WardleyDb.scala")
  def emitWardleyDiagram(rast: RastFile): String   = fromTemplate(rast, "wardley", "WardleyDiagram.scala")
  def emitWardleyParser(rast: RastFile): String    = fromTemplate(rast, "wardley", "WardleyParser.scala")
  def emitWardleyRenderer(rast: RastFile): String  = fromTemplate(rast, "wardley", "WardleyRenderer.scala")
  def emitWardleyStyles(rast: RastFile): String    = fromTemplate(rast, "wardley", "WardleyStyles.scala")

  // ===========================================================================
  // Ishikawa
  // ===========================================================================
  def emitIshikawaDb(rast: RastFile): String       = fromTemplate(rast, "ishikawa", "IshikawaDb.scala")
  def emitIshikawaDiagram(rast: RastFile): String   = fromTemplate(rast, "ishikawa", "IshikawaDiagram.scala")
  def emitIshikawaParser(rast: RastFile): String    = fromTemplate(rast, "ishikawa", "IshikawaParser.scala")
  def emitIshikawaRenderer(rast: RastFile): String  = fromTemplate(rast, "ishikawa", "IshikawaRenderer.scala")
  def emitIshikawaStyles(rast: RastFile): String    = fromTemplate(rast, "ishikawa", "IshikawaStyles.scala")

  // ===========================================================================
  // Venn
  // ===========================================================================
  def emitVennDb(rast: RastFile): String       = fromTemplate(rast, "venn", "VennDb.scala")
  def emitVennDiagram(rast: RastFile): String   = fromTemplate(rast, "venn", "VennDiagram.scala")
  def emitVennParser(rast: RastFile): String    = fromTemplate(rast, "venn", "VennParser.scala")
  def emitVennRenderer(rast: RastFile): String  = fromTemplate(rast, "venn", "VennRenderer.scala")
  def emitVennStyles(rast: RastFile): String    = fromTemplate(rast, "venn", "VennStyles.scala")

  // ===========================================================================
  // Treemap
  // ===========================================================================
  def emitTreemapDb(rast: RastFile): String       = fromTemplate(rast, "treemap", "TreemapDb.scala")
  def emitTreemapDiagram(rast: RastFile): String   = fromTemplate(rast, "treemap", "TreemapDiagram.scala")
  def emitTreemapParser(rast: RastFile): String    = fromTemplate(rast, "treemap", "TreemapParser.scala")
  def emitTreemapRenderer(rast: RastFile): String  = fromTemplate(rast, "treemap", "TreemapRenderer.scala")
  def emitTreemapStyles(rast: RastFile): String    = fromTemplate(rast, "treemap", "TreemapStyles.scala")

  // ===========================================================================
  // Event Modeling
  // ===========================================================================
  def emitEventModelingDb(rast: RastFile): String       = fromTemplate(rast, "eventmodeling", "EventModelingDb.scala")
  def emitEventModelingDiagram(rast: RastFile): String   = fromTemplate(rast, "eventmodeling", "EventModelingDiagram.scala")
  def emitEventModelingParser(rast: RastFile): String    = fromTemplate(rast, "eventmodeling", "EventModelingParser.scala")
  def emitEventModelingRenderer(rast: RastFile): String  = fromTemplate(rast, "eventmodeling", "EventModelingRenderer.scala")
  def emitEventModelingStyles(rast: RastFile): String    = fromTemplate(rast, "eventmodeling", "EventModelingStyles.scala")

  // ===========================================================================
  // Radar
  // ===========================================================================
  def emitRadarDb(rast: RastFile): String       = fromTemplate(rast, "radar", "RadarDb.scala")
  def emitRadarDiagram(rast: RastFile): String   = fromTemplate(rast, "radar", "RadarDiagram.scala")
  def emitRadarParser(rast: RastFile): String    = fromTemplate(rast, "radar", "RadarParser.scala")
  def emitRadarRenderer(rast: RastFile): String  = fromTemplate(rast, "radar", "RadarRenderer.scala")
  def emitRadarStyles(rast: RastFile): String    = fromTemplate(rast, "radar", "RadarStyles.scala")

  // ===========================================================================
  // Architecture
  // ===========================================================================
  def emitArchitectureDb(rast: RastFile): String       = fromTemplate(rast, "architecture", "ArchitectureDb.scala")
  def emitArchitectureDiagram(rast: RastFile): String   = fromTemplate(rast, "architecture", "ArchitectureDiagram.scala")
  def emitArchitectureParser(rast: RastFile): String    = fromTemplate(rast, "architecture", "ArchitectureParser.scala")
  def emitArchitectureRenderer(rast: RastFile): String  = fromTemplate(rast, "architecture", "ArchitectureRenderer.scala")
  def emitArchitectureStyles(rast: RastFile): String    = fromTemplate(rast, "architecture", "ArchitectureStyles.scala")

  // ===========================================================================
  // Block
  // ===========================================================================
  def emitBlockDb(rast: RastFile): String       = fromTemplate(rast, "block", "BlockDb.scala")
  def emitBlockDiagram(rast: RastFile): String   = fromTemplate(rast, "block", "BlockDiagram.scala")
  def emitBlockParser(rast: RastFile): String    = fromTemplate(rast, "block", "BlockParser.scala")
  def emitBlockRenderer(rast: RastFile): String  = fromTemplate(rast, "block", "BlockRenderer.scala")
  def emitBlockStyles(rast: RastFile): String    = fromTemplate(rast, "block", "BlockStyles.scala")

  // ===========================================================================
  // Journey
  // ===========================================================================
  def emitJourneyDb(rast: RastFile): String       = fromTemplate(rast, "journey", "JourneyDb.scala")
  def emitJourneyDiagram(rast: RastFile): String   = fromTemplate(rast, "journey", "JourneyDiagram.scala")
  def emitJourneyParser(rast: RastFile): String    = fromTemplate(rast, "journey", "JourneyParser.scala")
  def emitJourneyRenderer(rast: RastFile): String  = fromTemplate(rast, "journey", "JourneyRenderer.scala")
  def emitJourneyStyles(rast: RastFile): String    = fromTemplate(rast, "journey", "JourneyStyles.scala")

  // ===========================================================================
  // Timeline
  // ===========================================================================
  def emitTimelineDb(rast: RastFile): String       = fromTemplate(rast, "timeline", "TimelineDb.scala")
  def emitTimelineDiagram(rast: RastFile): String   = fromTemplate(rast, "timeline", "TimelineDiagram.scala")
  def emitTimelineParser(rast: RastFile): String    = fromTemplate(rast, "timeline", "TimelineParser.scala")
  def emitTimelineRenderer(rast: RastFile): String  = fromTemplate(rast, "timeline", "TimelineRenderer.scala")
  def emitTimelineStyles(rast: RastFile): String    = fromTemplate(rast, "timeline", "TimelineStyles.scala")

  // ===========================================================================
  // Mindmap
  // ===========================================================================
  def emitMindmapDb(rast: RastFile): String       = fromTemplate(rast, "mindmap", "MindmapDb.scala")
  def emitMindmapDiagram(rast: RastFile): String   = fromTemplate(rast, "mindmap", "MindmapDiagram.scala")
  def emitMindmapParser(rast: RastFile): String    = fromTemplate(rast, "mindmap", "MindmapParser.scala")
  def emitMindmapRenderer(rast: RastFile): String  = fromTemplate(rast, "mindmap", "MindmapRenderer.scala")
  def emitMindmapStyles(rast: RastFile): String    = fromTemplate(rast, "mindmap", "MindmapStyles.scala")

  // ===========================================================================
  // Quadrant
  // ===========================================================================
  def emitQuadrantDb(rast: RastFile): String       = fromTemplate(rast, "quadrant", "QuadrantDb.scala")
  def emitQuadrantDiagram(rast: RastFile): String   = fromTemplate(rast, "quadrant", "QuadrantDiagram.scala")
  def emitQuadrantParser(rast: RastFile): String    = fromTemplate(rast, "quadrant", "QuadrantParser.scala")
  def emitQuadrantRenderer(rast: RastFile): String  = fromTemplate(rast, "quadrant", "QuadrantRenderer.scala")
  def emitQuadrantStyles(rast: RastFile): String    = fromTemplate(rast, "quadrant", "QuadrantStyles.scala")

  // ===========================================================================
  // Sankey
  // ===========================================================================
  def emitSankeyDb(rast: RastFile): String       = fromTemplate(rast, "sankey", "SankeyDb.scala")
  def emitSankeyDiagram(rast: RastFile): String   = fromTemplate(rast, "sankey", "SankeyDiagram.scala")
  def emitSankeyParser(rast: RastFile): String    = fromTemplate(rast, "sankey", "SankeyParser.scala")
  def emitSankeyRenderer(rast: RastFile): String  = fromTemplate(rast, "sankey", "SankeyRenderer.scala")
  def emitSankeyStyles(rast: RastFile): String    = fromTemplate(rast, "sankey", "SankeyStyles.scala")

  // ===========================================================================
  // ER
  // ===========================================================================
  def emitErDb(rast: RastFile): String       = fromTemplate(rast, "er", "ErDb.scala")
  def emitErDiagram(rast: RastFile): String   = fromTemplate(rast, "er", "ErDiagram.scala")
  def emitErParser(rast: RastFile): String    = fromTemplate(rast, "er", "ErParser.scala")
  def emitErRenderer(rast: RastFile): String  = fromTemplate(rast, "er", "ErRenderer.scala")
  def emitErStyles(rast: RastFile): String    = fromTemplate(rast, "er", "ErStyles.scala")

  // ===========================================================================
  // Requirement
  // ===========================================================================
  def emitRequirementDb(rast: RastFile): String       = fromTemplate(rast, "requirement", "RequirementDb.scala")
  def emitRequirementDiagram(rast: RastFile): String   = fromTemplate(rast, "requirement", "RequirementDiagram.scala")
  def emitRequirementParser(rast: RastFile): String    = fromTemplate(rast, "requirement", "RequirementParser.scala")
  def emitRequirementRenderer(rast: RastFile): String  = fromTemplate(rast, "requirement", "RequirementRenderer.scala")
  def emitRequirementStyles(rast: RastFile): String    = fromTemplate(rast, "requirement", "RequirementStyles.scala")

  // ===========================================================================
  // C4
  // ===========================================================================
  def emitC4Db(rast: RastFile): String       = fromTemplate(rast, "c4", "C4Db.scala")
  def emitC4Diagram(rast: RastFile): String   = fromTemplate(rast, "c4", "C4Diagram.scala")
  def emitC4Parser(rast: RastFile): String    = fromTemplate(rast, "c4", "C4Parser.scala")
  def emitC4Renderer(rast: RastFile): String  = fromTemplate(rast, "c4", "C4Renderer.scala")
  def emitC4Styles(rast: RastFile): String    = fromTemplate(rast, "c4", "C4Styles.scala")

  // ===========================================================================
  // Gantt
  // ===========================================================================
  def emitGanttDb(rast: RastFile): String       = fromTemplate(rast, "gantt", "GanttDb.scala")
  def emitGanttDiagram(rast: RastFile): String   = fromTemplate(rast, "gantt", "GanttDiagram.scala")
  def emitGanttParser(rast: RastFile): String    = fromTemplate(rast, "gantt", "GanttParser.scala")
  def emitGanttRenderer(rast: RastFile): String  = fromTemplate(rast, "gantt", "GanttRenderer.scala")
  def emitGanttStyles(rast: RastFile): String    = fromTemplate(rast, "gantt", "GanttStyles.scala")

  // ===========================================================================
  // Git
  // ===========================================================================
  def emitGitDb(rast: RastFile): String       = fromTemplate(rast, "git", "GitDb.scala")
  def emitGitDiagram(rast: RastFile): String   = fromTemplate(rast, "git", "GitDiagram.scala")
  def emitGitParser(rast: RastFile): String    = fromTemplate(rast, "git", "GitParser.scala")
  def emitGitRenderer(rast: RastFile): String  = fromTemplate(rast, "git", "GitRenderer.scala")
  def emitGitStyles(rast: RastFile): String    = fromTemplate(rast, "git", "GitStyles.scala")

  // ===========================================================================
  // State
  // ===========================================================================
  def emitStateDb(rast: RastFile): String       = fromTemplate(rast, "state", "StateDb.scala")
  def emitStateDiagram(rast: RastFile): String   = fromTemplate(rast, "state", "StateDiagram.scala")
  def emitStateParser(rast: RastFile): String    = fromTemplate(rast, "state", "StateParser.scala")
  def emitStateRenderer(rast: RastFile): String  = fromTemplate(rast, "state", "StateRenderer.scala")
  def emitStateStyles(rast: RastFile): String    = fromTemplate(rast, "state", "StateStyles.scala")

  // ===========================================================================
  // XY Chart
  // ===========================================================================
  def emitXyChartDb(rast: RastFile): String       = fromTemplate(rast, "xychart", "XyChartDb.scala")
  def emitXyChartDiagram(rast: RastFile): String   = fromTemplate(rast, "xychart", "XyChartDiagram.scala")
  def emitXyChartParser(rast: RastFile): String    = fromTemplate(rast, "xychart", "XyChartParser.scala")
  def emitXyChartRenderer(rast: RastFile): String  = fromTemplate(rast, "xychart", "XyChartRenderer.scala")
  def emitXyChartStyles(rast: RastFile): String    = fromTemplate(rast, "xychart", "XyChartStyles.scala")

  // ===========================================================================
  // Flowchart
  // ===========================================================================
  def emitFlowchartDb(rast: RastFile): String       = fromTemplate(rast, "flowchart", "FlowchartDb.scala")
  def emitFlowchartDiagram(rast: RastFile): String   = fromTemplate(rast, "flowchart", "FlowchartDiagram.scala")
  def emitFlowchartParser(rast: RastFile): String    = fromTemplate(rast, "flowchart", "FlowchartParser.scala")
  def emitFlowchartRenderer(rast: RastFile): String  = fromTemplate(rast, "flowchart", "FlowchartRenderer.scala")
  def emitFlowchartStyles(rast: RastFile): String    = fromTemplate(rast, "flowchart", "FlowchartStyles.scala")

  // ===========================================================================
  // Class
  // ===========================================================================
  def emitClassDb(rast: RastFile): String       = fromTemplate(rast, "class_", "ClassDb.scala")
  def emitClassDiagram(rast: RastFile): String   = fromTemplate(rast, "class_", "ClassDiagram.scala")
  def emitClassParser(rast: RastFile): String    = fromTemplate(rast, "class_", "ClassParser.scala")
  def emitClassRenderer(rast: RastFile): String  = fromTemplate(rast, "class_", "ClassRenderer.scala")
  def emitClassStyles(rast: RastFile): String    = fromTemplate(rast, "class_", "ClassStyles.scala")

  // ===========================================================================
  // Sequence
  // ===========================================================================
  def emitSequenceDb(rast: RastFile): String       = fromTemplate(rast, "sequence", "SequenceDb.scala")
  def emitSequenceDiagram(rast: RastFile): String   = fromTemplate(rast, "sequence", "SequenceDiagram.scala")
  def emitSequenceParser(rast: RastFile): String    = fromTemplate(rast, "sequence", "SequenceParser.scala")
  def emitSequenceRenderer(rast: RastFile): String  = fromTemplate(rast, "sequence", "SequenceRenderer.scala")
  def emitSequenceStyles(rast: RastFile): String    = fromTemplate(rast, "sequence", "SequenceStyles.scala")
}
