package balticporter.corpus.mermaid

import balticporter.frontend.ts.dedicated.{DefmethodBodyTranslator, DefmethodEntry, DefnodeClass, FreeFunction}

import balticporter.frontend.ts.{RastFile, RastNode, RastValue}
import scala.annotation.nowarn

/** RAST-based emitter for Mermaid diagram detector modules.
  *
  * Each detector module follows a fixed pattern:
  *   - `const id = "diagramName"`
  *   - `const detector: DiagramDetector = (txt) => /regex/.test(txt)`
  *   - `const loader: DiagramLoader = async () => { ... }`
  *   - `export const name: ExternalDiagramDefinition = { id, detector, loader }`
  *
  * The Scala translation drops the loader (dynamic import) and emits:
  *   - `object XxxDetector { def detect(text: String): Boolean = ... }`
  */
object MermaidDetectorEmitter {

  /** Emits a Scala detector object from a RAST file.
    *
    * @param rast        the parsed RAST file
    * @param objectName  e.g. "InfoDetector"
    * @param pkg         e.g. "info"
    * @return the complete Scala source
    */
  def emitDetector(
      rast: RastFile,
      objectName: String,
      pkg: String,
  ): String = {
    val sb = new StringBuilder
    sb.append(header(rast.path, s"$objectName.scala"))
    sb.append(s"package ssg\npackage mermaid\npackage diagrams\npackage $pkg\n\n")

    // Extract the detector regex pattern
    val regexPattern = findDetectorRegex(rast)
    val id = findDetectorId(rast)

    sb.append(s"/** Detector for the $pkg diagram type. */\n")
    sb.append(s"object $objectName {\n\n")

    id.foreach { idStr =>
      sb.append(s"  val id: String = \"$idStr\"\n\n")
    }

    regexPattern match {
      case Some(pattern) =>
        val scalaRegex = tsRegexToScalaPattern(pattern)
        sb.append(s"  def detect(text: String): Boolean =\n")
        sb.append(s"    $scalaRegex.findFirstIn(text.trim.split(\"[\\\\n\\\\r]\", 2)(0).trim.toLowerCase).isDefined\n")
      case None =>
        sb.append(s"  def detect(text: String): Boolean =\n")
        sb.append(s"    text.trim.toLowerCase.startsWith(\"${id.getOrElse(pkg)}\")\n")
    }

    sb.append("}\n")
    sb.toString
  }

  /** Finds the regex value from a detector's arrow function. */
  private def findDetectorRegex(rast: RastFile): Option[String] =
    rast.nodes.flatMap { node =>
      node.kind match {
        case "VariableStatement" =>
          extractVarDecls(node).flatMap { d =>
            val name = nameOf(d)
            if (name == "detector") {
              findRegexLiteral(d)
            } else Nil
          }
        case _ => Nil
      }
    }.headOption

  /** Finds the id string value. */
  private def findDetectorId(rast: RastFile): Option[String] =
    rast.nodes.flatMap { node =>
      node.kind match {
        case "VariableStatement" =>
          extractVarDecls(node).flatMap { d =>
            val name = nameOf(d)
            if (name == "id") {
              findStringLiteral(d)
            } else Nil
          }
        case _ => Nil
      }
    }.headOption

  /** Recursively finds RegularExpressionLiteral nodes. */
  private def findRegexLiteral(node: RastNode): List[String] = {
    if (node.kind == "RegularExpressionLiteral") {
      node.value match {
        case Some(RastValue.Str(s)) => List(s)
        case _ => Nil
      }
    } else {
      node.children.flatMap(findRegexLiteral)
    }
  }

  /** Recursively finds StringLiteral values. */
  private def findStringLiteral(node: RastNode): List[String] = {
    if (node.kind == "StringLiteral") {
      node.value match {
        case Some(RastValue.Str(s)) => List(s)
        case _ => Nil
      }
    } else {
      node.children.flatMap(findStringLiteral)
    }
  }

  /** Converts a TS regex pattern to a Scala regex string.
    * e.g. `/^\s*info/` -> `"^\\s*info".r`
    */
  private def tsRegexToScalaPattern(regex: String): String = {
    // Strip leading / and trailing /flags
    val body = if (regex.startsWith("/")) {
      val lastSlash = regex.lastIndexOf('/')
      if (lastSlash > 0) regex.substring(1, lastSlash) else regex.substring(1)
    } else regex
    val escaped = body.replace("\\", "\\\\").replace("\"", "\\\"")
    s"\"$escaped\".r"
  }

  private def nameOf(node: RastNode): String =
    node.children.find(_.kind == "Identifier").flatMap(_.text).getOrElse("$anon")

  private def extractVarDecls(stmt: RastNode): List[RastNode] = {
    val declLists = stmt.children.filter(_.kind == "VariableDeclarationList")
    if (declLists.nonEmpty) declLists.flatMap(_.children.filter(_.kind == "VariableDeclaration"))
    else stmt.children.filter(_.kind == "VariableDeclaration")
  }

  @nowarn("msg=unused")
  private def header(sourcePath: String, targetFile: String): String =
    s"""/*
       | * Mermaid diagramming engine - Scala 3 port
       | *
       | * Ported from: $sourcePath
       | * Original license: MIT
       | *
       | * Auto-generated by MermaidDetectorEmitter from RAST v1
       | */
       |""".stripMargin
}
