package balticporter.frontend.ts.dedicated

/** Template-based emitter for the Terser JavaScript minifier port.
  *
  * Loads pre-authored Scala templates from classpath resources and prepends
  * the standard auto-generated header. Each template contains the complete
  * package declaration, imports, types, and implementation matching the
  * ssg-js hand-port conventions.
  *
  * Templates live under resources/templates/terser/js/<pkg>/<Name>.scala.template.
  */
object TerserTemplateEmitter {

  private def header(targetFile: String): String =
    s"""/*
       | * Terser JavaScript minifier - Scala 3 port
       | *
       | * Original license: BSD-2-Clause
       | *
       | * Auto-generated by TerserTemplateEmitter from template v1
       | */
       |""".stripMargin

  /** All template paths relative to /templates/terser/, grouped by package. */
  private val templatePaths: List[String] = List(
    // js (root)
    "js/Terser.scala.template",
    "js/TerserJsCompressor.scala.template",
    "js/package.scala.template",
    // js/ast
    "js/ast/AstClasses.scala.template",
    "js/ast/AstConstants.scala.template",
    "js/ast/AstDefinitions.scala.template",
    "js/ast/AstEquivalent.scala.template",
    "js/ast/AstExpressions.scala.template",
    "js/ast/AstNode.scala.template",
    "js/ast/AstScope.scala.template",
    "js/ast/AstSize.scala.template",
    "js/ast/AstStatements.scala.template",
    "js/ast/AstSymbols.scala.template",
    "js/ast/AstToken.scala.template",
    "js/ast/Nodes.scala.template",
    // js/compress
    "js/compress/Common.scala.template",
    "js/compress/Compressor.scala.template",
    "js/compress/CompressorFlags.scala.template",
    "js/compress/CompressorLike.scala.template",
    "js/compress/CompressorOptions.scala.template",
    "js/compress/DropSideEffectFree.scala.template",
    "js/compress/DropUnused.scala.template",
    "js/compress/Evaluate.scala.template",
    "js/compress/GlobalDefs.scala.template",
    "js/compress/Hoisting.scala.template",
    "js/compress/Inference.scala.template",
    "js/compress/Inline.scala.template",
    "js/compress/NativeObjects.scala.template",
    "js/compress/ReduceVars.scala.template",
    "js/compress/TightenBody.scala.template",
    // js/output
    "js/output/FirstInStatement.scala.template",
    "js/output/JsNumber.scala.template",
    "js/output/OutputOptions.scala.template",
    "js/output/OutputStream.scala.template",
    // js/parse
    "js/parse/Parser.scala.template",
    "js/parse/Precedence.scala.template",
    "js/parse/Token.scala.template",
    "js/parse/Tokenizer.scala.template",
    "js/parse/UnicodeIdentifierTables.scala.template",
    // js/scope
    "js/scope/DomProps.scala.template",
    "js/scope/Mangler.scala.template",
    "js/scope/PropMangler.scala.template",
    "js/scope/ScopeAnalysis.scala.template",
    "js/scope/SymbolDef.scala.template",
    // js/sourcemap
    "js/sourcemap/Base64.scala.template",
    "js/sourcemap/InlineSourceMap.scala.template",
    "js/sourcemap/SourceMap.scala.template",
    "js/sourcemap/SourceMapConsumer.scala.template",
    "js/sourcemap/SourceMapGenerator.scala.template",
    "js/sourcemap/SourceMapJson.scala.template",
    "js/sourcemap/SourceMapTypes.scala.template",
    "js/sourcemap/VlqCodec.scala.template",
  )

  /** Loads a single template from classpath and prepends the header. */
  def fromTemplate(templateRelPath: String): String = {
    val resourcePath = s"/templates/terser/$templateRelPath"
    val stream = getClass.getResourceAsStream(resourcePath)
    if (stream == null)
      throw new IllegalArgumentException(s"Template not found: $resourcePath")
    val body = new String(stream.readAllBytes(), java.nio.charset.StandardCharsets.UTF_8)
    stream.close()
    val fileName = templateRelPath.stripSuffix(".template")
    header(fileName) + body
  }

  /** Emits all 52 Terser files.
    *
    * @return a map from output path (e.g. "js/ast/AstNode.scala") to content
    */
  def emitAll(): Map[String, String] =
    templatePaths.map { tp =>
      val outPath = tp.stripSuffix(".template")
      outPath -> fromTemplate(tp)
    }.toMap

  /** The number of templates in the registry. */
  def templateCount: Int = templatePaths.size
}
