package balticporter.testkit

import balticporter.core.CommentScanner

import scala.jdk.CollectionConverters.*

/** The FILE HEADER, harvested by POSITION — `ENGINE-LIMITS.md` V3, closed.
  *
  * Two consecutive block comments above `package` is the shape that lost one of them, and the loss
  * is a licence loss wherever the second block is the notice (a generated parser puts its
  * generator banner first). Nothing else in the pipeline can see it: the emitted file compiles, no
  * count moves, no test breaks — so the spec IS the gate, and it asserts the parser's own answer
  * too, because that answer is what the design turns on.
  */
class FileLeadingTriviaSpec extends munit.FunSuite:

  private val twoBlocks =
    """/* Generated by a tool — do not edit. */
      |/*
      | * Copyright 2011 Example Foundation
      | * Licensed under the Apache License, Version 2.0 (the "License").
      | */
      |package demo;
      |
      |public class Two {
      |    public int f() { return 1; }
      |}
      |""".stripMargin

  // ---- the probe: WHERE the parser puts them (the fact the design is built on) ----

  test("PROBE: of two leading blocks the parser gives the unit the FIRST and the PACKAGE the second") {
    val launcher = new spoon.Launcher
    launcher.getEnvironment.setComplianceLevel(21)
    launcher.getEnvironment.setCommentEnabled(true)
    launcher.getEnvironment.setNoClasspath(true)
    launcher.addInputResource(new spoon.support.compiler.VirtualFile(twoBlocks, "Two.java"))
    val model = launcher.buildModel()
    val top   = model.getAllTypes.asScala.toList.head
    val cu    = top.getPosition.getCompilationUnit

    val onUnit    = cu.getComments.asScala.toList
    val onPackage = Option(cu.getPackageDeclaration).map(_.getComments.asScala.toList).getOrElse(Nil)
    val onType    = top.getComments.asScala.toList

    // V3 recorded "the second is attached to nothing this walk reaches" and left WHERE open. It is
    // the PACKAGE DECLARATION — the one attachment site the harvest never read. The distinction
    // matters only for the docs: the fix is positional either way, because a rule that reads one
    // more of the parser's slots is a rule that the NEXT shape walks straight past, and because
    // only text can tell which of two blocks came first.
    assertEquals(onUnit.size, 1, s"unit comments: ${onUnit.map(_.getContent)}")
    assert(onUnit.head.getContent.contains("Generated by a tool"), onUnit.head.getContent)
    assertEquals(onPackage.size, 1, s"package-declaration comments: ${onPackage.map(_.getContent)}")
    assert(onPackage.head.getContent.contains("Copyright 2011"), onPackage.head.getContent)
    assertEquals(onType, Nil, s"type comments: ${onType.map(_.getContent)}")
  }

  // ---- what the port emits ----

  private lazy val out = PortFixture.port(twoBlocks).out

  private def occurrences(hay: String, needle: String): Int =
    var n = 0; var i = hay.indexOf(needle)
    while i >= 0 do { n += 1; i = hay.indexOf(needle, i + 1) }
    n

  test("BOTH leading blocks are emitted, in source order, above the package clause") {
    assert(out.contains("Generated by a tool — do not edit."), out)
    assert(out.contains("Copyright 2011 Example Foundation"), out)
    assert(out.indexOf("Generated by a tool") < out.indexOf("Copyright 2011"), out)
    assert(out.indexOf("Copyright 2011") < out.indexOf("package demo"), out)
  }

  test("neither block is emitted twice") {
    assertEquals(occurrences(out, "Generated by a tool"), 1, out)
    assertEquals(occurrences(out, "Copyright 2011 Example Foundation"), 1, out)
  }

  test("a file-leading block Spoon attaches to the TYPE is still emitted exactly once") {
    // one leading block and a class Javadoc: the header must take the first and leave the second,
    // which is the positional claim doing its job in the direction that could double-emit.
    val src =
      """/* The notice. */
        |package demo;
        |
        |/** The class doc. */
        |public class One { public int f() { return 1; } }
        |""".stripMargin
    val o = PortFixture.port(src).out
    assertEquals(occurrences(o, "The notice."), 1, o)
    assertEquals(occurrences(o, "The class doc."), 1, o)
    assert(o.indexOf("The notice.") < o.indexOf("package demo"), o)
    assert(o.indexOf("package demo") < o.indexOf("The class doc."), o)
  }

  test("EVERY top-level type in one file carries the whole header") {
    val src =
      """/* First banner. */
        |/* Second notice. */
        |package demo;
        |
        |public class A { public int f() { return 1; } }
        |class B { public int g() { return 2; } }
        |""".stripMargin
    val o = PortFixture.port(src).out
    // two units, each a derived work: the notice appears once per emitted file.
    assertEquals(occurrences(o, "First banner."), 2, o)
    assertEquals(occurrences(o, "Second notice."), 2, o)
  }

  // ---- the scanner's own contract, which the harvest and the check both read ----

  test("firstCodeOffset skips whitespace and comments and stops at code") {
    val src = "  /* a */\n// b\n\npackage p;\n"
    assertEquals(src.substring(CommentScanner.firstCodeOffset(src)).take(7), "package")
  }

  test("firstCodeOffset is not fooled by the word `package` inside a comment") {
    val src = "/* the package clause follows */\npackage p;\n"
    assertEquals(CommentScanner.firstCodeOffset(src), src.indexOf("package p"))
  }

  test("a comment repeated in one file is reported at ITS OWN line, not the first occurrence") {
    val src = "class C {\n  // TODO\n  int a;\n  // TODO\n  int b;\n}\n"
    assertEquals(CommentScanner.scanAt(src).map(_.line(src)), List(2, 4))
  }
